### ISSUE TITLE
Questions: "Failed to find DNS-record for resource at https://www.google.com"

### ISSUE THREAD

**Issue by vitvad** [DevExpress/testcafe#1135]
Hi,
I decide to try this test framework and got this error.
Same with you test page. I'm in corporate network with some firewall restrictions, but both pages are available if I try it in browser. Maybe you have any idea what could be wrong?
Sorry if this such silly report.

Test code

```js
import { Selector } from 'testcafe';
const articleHeader = Selector('#article-header');
fixture `Getting Started`
    .page `https://www.google.com/`;
test('My first test', async t => {
    await t
        .typeText('#lst-ib', 'Peter Parker')
        .click('[type="submit"]')
        .expect(true).eql(false);
});
```

### Specify your

* operating system:
Win 7
* testcafe version:
0.11.1
* node.js version:
6.9.1

**Comment by georgiy-abbasov** [comment]
Hello Vitaly !
Thank you for reply. Specify, please, has your browser special network settings like proxy or not ? Is TestCafe added to your firewall exceptions ?

At first we need to know, whether node.js has the access to the network. Run next steps, please:

1) Create a temporary directory:

``` cmd
mkdir test-request
cd test-request
```

2) Create the `request.js` file in the `test-request` directory:

``` js
var http = require("http");

http.get('http://www.example.com', function (res) {
    var statusCode = res.statusCode;

    if (statusCode !== 200) {
        console.log(` Request Failed.\n Status Code: ${statusCode}`);

        res.resume();
        return;
    }

    console.log(` Request Success.\n Status Code: ${statusCode}`);
});
```

3) Run `request.js` via Node.js:

``` cmd
node request.js
```

Post the output here.

**Comment by vitvad** [comment]
Hi @georgiy-abbasov ,
Sorry for delay, was on vacation and was not able to check.

I don't see any proxy settings in browser, but most probably we have it for all outgoing traffic somewhere on network level.

As for firewall - we don't have any capability to manage those rules.

I was just wondered that I was able to install testcafe without errors, because every other e2e client need some admin rights on PC to build and download some selenium packages + add PATH variables

script return:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND www.example.com www.example.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

So most probably i need set up some proxy, not sure about this. Just rise this ticket to understand what direction should I dig.

Thx. Any suggestion would be appreciated.

**Comment by georgiy-abbasov** [comment]
Hi!
Thanks for log, we need some time to investigate this behavior.
Please, bear with us.

**Comment by georgiy-abbasov** [comment]
>> I don't see any proxy settings in browser, but most probably we have it for all outgoing traffic somewhere on network level.

If i correctly understand, you have LAN settings in Internet options like [this](https://www.screencast.com/t/afl0wgHi), right ?

About firewall and script result - it looks like dns requests are blocked for node.js application (meanwhile they are allowed for browser). Can you run `cmd` with administrator privileges ? If yes, try to re-run script above and also run next command:
`ping www.example.com`

**Comment by andrewdang17** [comment]
@vitvad or @georgiy-abbasov did either of you ever figure out this issue?
I'm having this same issue using a rails development server `Failed to find a DNS-record for the resource at "http://localhost/3000"` even though I can access it in my browser

**Comment by georgiy-abbasov** [comment]
Hi @andrewdang17 
Did you try to run [this snippet](https://github.com/DevExpress/testcafe/issues/1135#issuecomment-272622367), that i recommended ? If no, please run it, cause your problem looks little different. It would be worth, if you also run [this snippet](https://github.com/DevExpress/testcafe/issues/949#issuecomment-258813553) and post the result here.

**Comment by andrewdang17** [comment]
@georgiy-abbasov I'm getting `Request Success. Status Code: 200` and also created a express server and that worked too . It's possible that a setting in my rails config is blocking testcafe....

**Comment by georgiy-abbasov** [comment]
@andrewdang17 , It's possible. Please, try perform request from [my first reply](https://github.com/DevExpress/testcafe/issues/1135#issuecomment-272622367) with your page - `http://localhost/3000`

**Comment by andrewdang17** [comment]
@georgiy-abbasov 3000 worked with express too :(

**Comment by georgiy-abbasov** [comment]
@andrewdang17, in that case it's hard to determine the cause of this behavior. Can you provide a link to your project page, if it's deployed ? You can do it [privately](mailto:georgiy@abbasov@devexpress.com).

**Comment by sagarvora** [comment]
The same issue is happening to me, but for `localhost`. I was trying to implement TestCafe + Nightmare for Travis but it's giving me this error.

Here's the Travis log:
https://travis-ci.org/sagarvora/frappe

Here's the Travis config:
https://github.com/sagarvora/frappe/blob/develop/.travis.yml

Here's the code I wrote:
https://github.com/sagarvora/frappe/blob/develop/login_test.js

Note that the first three steps upto logging in are working, and hence I am being redirected to the `/desk` page.

**Comment by AlexanderMoskovkin** [comment]
Hi @sagarvora,
Does it work locally on your computer?

**Comment by sagarvora** [comment]
@AlexanderMoskovkin I tried running the same script locally, it passed.. What could be the reason? :thinking:

**Comment by AlexanderMoskovkin** [comment]
It's hard to determine the reason without an investigation. 
Could you please compare [the server log on Travis](https://travis-ci.org/sagarvora/frappe#L3087) with the log from local running? (for example you can publish it on https://gist.github.com/).

**Comment by mjhea0** [comment]
I am seeing this same error on Circle CI. Just FYI. It's just popped up in the last few days. I pointed the tests at Travis and don't see the error after 50+ runs. It's not happening locally either.

**Comment by thecodejack** [comment]
Facing same issue while running tests in firefox(passes in chrome). I have a web worker in the application and supposed to load dynamically when I say `new Worker(host + '/testWorker.js')`. Host is same for application and worker. But getting this error.

```
1) Failed to find a DNS-record for the resource at
      "http://host/test.js"
```

**Comment by miherlosev** [comment]
I cannot reproduce this issue. I've created a simple [web_worker_example.zip](https://github.com/DevExpress/testcafe/files/1135654/web_worker.zip) that works well.
Please, try to modify this example to reproduce your issue.

**Comment by thecodejack** [comment]
did you try in firefox? Anyways will try to reproduce with your example as well.

**Comment by miherlosev** [comment]
Thanks, I've reproduced the problem and created a separate [issue](https://github.com/DevExpress/testcafe-hammerhead/issues/1216).

**Comment by AlexanderMoskovkin** [comment]
I'm closing this since there were no activity here for a long time. Some of other issues discussed here were resolved. Feel free to reopen the issue if the initial issue is actual or create a new issue if you have some other problem.
