### ISSUE TITLE
Readme sample does not work

### ISSUE THREAD

**Issue by StarpTech** [DevExpress/testcafe#1149]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
import { Selector } from 'testcafe';

fixture `Example page`
    .page `http://devexpress.github.io/testcafe/example/`;

test('Check property of element', async t => {
    const developerNameInput = Selector('#developer-name');

    await t
        .expect(developerNameInput.value).eql('', 'input is empty')
        .typeText(developerNameInput, 'Peter Parker')
        .expect(developerNameInput.value).constains('Peter', 'input contains text "Peter"');
});
```

Result:

```
> testcafe chrome test.js


 Running tests in:
 - Chrome 55.0.2883 / Windows 10 0.0.0

 Example page
 × Check property of element

   1) TypeError: t.expect(...).eql(...).typeText(...).expect(...).constains is not a function

      Browser: Chrome 55.0.2883 / Windows 10 0.0.0

          7 |    const developerNameInput = Selector('#developer-name');
          8 |
          9 |    await t
         10 |        .expect(developerNameInput.value).eql('', 'input is empty')
         11 |        .typeText(developerNameInput, 'Peter Parker')
       > 12 |        .expect(developerNameInput.value).constains('Peter', 'input contains text "Peter"');
         13 |});

         at <anonymous> (E:\Repositorys\testcafe\test.js:12:43)
         at step (E:\Repositorys\testcafe\test.js:1:545)
         at <anonymous> (E:\Repositorys\testcafe\test.js:1:785)
         at <anonymous> (E:\Repositorys\testcafe\test.js:1:446)
         at test (E:\Repositorys\testcafe\test.js:6:1)



 1/1 failed (0s)
npm ERR! Test failed.  See above for more details.
```

### Specify your

* operating system: Windows 10
* testcafe version: 0.11.1
* node.js version: 7.4.0

**Comment by AlexanderMoskovkin** [comment]
Hi @StarpTech,
Thanks for noticing that. It's a typo in the `constains` word, it should be [`contains`](https://devexpress.github.io/testcafe/documentation/test-api/assertions/assertion-api.html#contains). I've fixed it.

**Comment by StarpTech** [comment]
Oh,  thanks it was very late :)

Am 19.01.2017 05:02 schrieb "Alexander Moskovkin" <notifications@github.com
