### ISSUE TITLE
Crash on --harmony flag

### ISSUE THREAD

**Issue by WillemMali** [DevExpress/testcafe#1164]
### Are you requesting a feature or reporting a bug?

Reporting a bug

### What is the current behavior?

min.js:

```
require('testcafe');
```

```
$ node --harmony min.js

/home/willem/w/bizaline/testcafe/node_modules/testcafe-hammerhead/node_modules/lodash/lodash.js:1244
    set.forEach(function(value) {
        ^
TypeError: Object #<Set> has no method 'forEach'
    at setToArray (/home/willem/w/bizaline/testcafe/node_modules/testcafe-hammerhead/node_modules/lodash/lodash.js:1244:9)
    at runInContext (/home/willem/w/bizaline/testcafe/node_modules/testcafe-hammerhead/node_modules/lodash/lodash.js:5452:35)
    at Object.<anonymous> (/home/willem/w/bizaline/testcafe/node_modules/testcafe-hammerhead/node_modules/lodash/lodash.js:16955:11)
    at Object.<anonymous> (/home/willem/w/bizaline/testcafe/node_modules/testcafe-hammerhead/node_modules/lodash/lodash.js:16982:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

### What is the expected behavior?

TestCafe is loaded, no crash occurs and users using NodeJS 4 LTS (4.7.2 / 0.10.29) can use ES5 functionality such as `yield`, rest parameters and spread operators.

### How would you reproduce the current behavior (if this is a bug)?

Take up-to-date NodeJS from any supported Debian/Ubuntu, use `--harmony` flag, crash.

### Specify your

* operating system: Debian Testing
* testcafe version: 0.12.0
* node.js version: 0.10.29

**Comment by AndreyBelym** [comment]
Hello, @WillemMali! Unfortunately, the problem is in lodash package, just try `require('lodash')` with `node --harmony`: https://github.com/lodash/lodash/issues/2324. The reason is that some some ES6 classes have incomplete implementation under `--harmony` flag. However, `lodash` uses a polyfill, so it works fine without that flag. What's about ES6 features, you can use a transpiler, e.g. [babel](https://babeljs.io/). It takes couple of minutes to setup, but it's not so hard with yeoman template - https://www.npmjs.com/package/generator-babel.
