### ISSUE TITLE
Incorrect callstack for test error

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe#1226]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

```sh
         at <anonymous> (d:\temp\help.js:2:11)
!!!!     at step (d:\temp\help.js:1:538)
!!!!     at <anonymous> (d:\temp\help.js:1:778)
!!!!     at <anonymous> (d:\temp\help.js:1:439)
!!!!     at exports.default (d:\temp\help.js:4:42)
         at <anonymous> (d:\temp\test1.js:9:11)
!!!!     at step (d:\temp\test1.js:3:364)
```

### What is the expected behavior?

```sh
         at <anonymous> (d:\temp\help.js:2:11)
         at <anonymous> (d:\temp\test1.js:9:11)
```

### How would you reproduce the current behavior (if this is a bug)?

run the test

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: any

Test code

```js
// test.js
import help from './help.js';

fixture `Fixture`
    .page `http://devexpress.github.io/testcafe/example/`;

test('test', async t => {
    await help(t);
})

// help.js
export default async function (t) {
    throw new Error('error');
}
```

### Specify your

* operating system: win7
* testcafe version: 0.13.0-alpha2
* node.js version: `7.4.0`, `6.9.1`, `0.10.47`

**Comment by georgiy-abbasov** [comment]
Lines marked with exclamation point are related to asyncToRegenerator calls (it replaces `async` keyword in the original code). It placed in the first line of transpilled code

```js
'use strict';var _promise = require('D:\\Work\\testcafe-phoenix\\node_modules\\babel-runtime\\core-js\\promise.js');var _promise2 = _interopRequireDefault(_promise);var _help = require('./help.js');var _help2 = _interopRequireDefault(_help);function _interopRequireDefault(obj) {return obj && obj.__esModule ? obj : { default: obj };}function _asyncToGenerator(fn) {return function () {var gen = fn.apply(this, arguments);return new _promise2.default(function (resolve, reject) {function step(key, arg) {try {var info = gen[key](arg);var value = info.value;} catch (error) {reject(error);return;}if (info.done) {resolve(value);} else {return _promise2.default.resolve(value).then(function (value) {step("next", value);}, function (err) {step("throw", err);});}}return step("next");});};}

fixture`Fixture`.
page`http://devexpress.github.io/testcafe/example/`;

test('test', (() => {var _ref = _asyncToGenerator(function* (t) {
        yield (0, _help2.default)(t);
    });return function (_x) {return _ref.apply(this, arguments);};})());
```

@inikulin says, that it should be imported, not placed in the code.

**Comment by georgiy-abbasov** [comment]
During testing approach, which @inikulin recommended, i've found that odd lines still here:
```
at <anonymous> (D:\work\testcafe-phoenix\gh-1226\help.js:2:11)
at F (D:\work\testcafe-phoenix\node_modules\core-js\library\modules\_export.js:35:28)
at exports.default (D:\work\testcafe-phoenix\gh-1226\help.js:3:42)
at <anonymous> (D:\work\testcafe-phoenix\gh-1226\node.test.js:7:11)
```
It's due to the fact, that transpilled `require` and `export` keywords are shifted too.

**Comment by inikulin** [comment]
@georgiy-abbasov Which of them are odd? If you are talking about core-js stuff - yes, they should be filtered out by [stack filter](https://github.com/DevExpress/testcafe/blob/master/src/errors/create-stack-filter.js). Debug to figure out why they still where.
