### ISSUE TITLE
Can't take a screenshot

### ISSUE THREAD

**Issue by CommanderXL** [DevExpress/testcafe#1754]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Well, I update the testcafe-browser-tools to v1.4.3.And I try to take a screenshot. But it occur to 

```javascript
Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Command failed: /Users/xxxx/project/test-cafe-demo/node_modules/testcafe-browser-tools/bin/mac/generate-thumbnail
  /Users/xxxx/project/test-cafe-demo/screenshots/my-fixture/test1.png
  /Users/xxxx/project/test-cafe-demo/screenshots/my-fixture/thumbnails/test1.png 240 130
```

I have set the screenshots directory through the cli : `-s screenshots`.

I use the testcafe get started test script to test:

```javascript
fixture `My fixture`
    .page `https://www.baidu.com`;

test('Take a screenshot', async t => {
    await t
        .takeScreenshot('my-fixture/test1.png')
});
```
### What is the expected behavior?

It can work it with screenshot function.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.baidu.com

Test code

```js
fixture `My fixture`
    .page `https://www.baidu.com`;

test('Take a screenshot', async t => {
    await t
        .takeScreenshot('my-fixture/test1.png')
});
```

### Specify your

* operating system: mac 10.11.0
* testcafe version: 0.17.0
* node.js version: 8.0.0

**Comment by AlexanderMoskovkin** [comment]
Hi,

We've faced with the same issue and fixed it in the `testcafe-browser-tools@1.4.4`, please check it.

**Comment by CommanderXL** [comment]
Well , It doesn't work too.And the error message is :
```javascript
 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Command failed: /Users/xxx/project/test-cafe-demo/node_modules/testcafe/node_modules/testcafe-browser-tools/bin/mac/screenshot
  79919 /Users/xxx/project/test-cafe-demo/screenshots/my-fixture/test1.png
  There are no TestCafe windows
```

**Comment by AlexanderMoskovkin** [comment]
We're going to publish the `testcafe@0.17.2` version soon with updated `testcafe-browser-tools`

**Comment by CommanderXL** [comment]
I'm sorry, the `takeScreenshot` function can't work properly now.I did nothing about the test script.

**Comment by AndreyBelym** [comment]
Can you install `testcafe@0.17.2` and check how it works there, please?

**Comment by CommanderXL** [comment]
@AndreyBelym Hi, I had install `0.17.2`, and the `testcafe-browser-tools` is 1.4.5 now.It didn't make it .

Os: Mac 10.11.
Node:  8.0.0

**Comment by AndreyBelym** [comment]
Is it the same error, can you post it here? What browser do you use?

**Comment by CommanderXL** [comment]
Well, It log nothing in the terminal.And the process exit.

**Comment by AndreyBelym** [comment]
So you mean that you can't run tests with `0.17.2`? Or that tests was finished, but screenshots hadn't been created and there was no warning in the log? Have you tried to perform a fresh install (remove the `node_modules` durectory and install TestCafe locally)?

**Comment by CommanderXL** [comment]
Sorry, I rewrite the reporter plugin. I use the json reporter now.

And the terminal print the warning info:

```javascript
 Warnings (3):
 --
  Was unable to take a screenshot due to an error.

  Command failed: /Users/XRene/project/test-cafe-demo/node_modules/testcafe-browser-tools/bin/mac/generate-thumbnail ../screenshots/fixture/login-success.png
  ../screenshots/fixture/thumbnails/login-success.png 240 130

 --
  Was unable to take a screenshot due to an error.

  Command failed: /Users/XRene/project/test-cafe-demo/node_modules/testcafe-browser-tools/bin/mac/generate-thumbnail ../screenshots/fixture/ticket-list.png
  ../screenshots/fixture/thumbnails/ticket-list.png 240 130

 --
  Was unable to take a screenshot due to an error.

  Command failed: /Users/XRene/project/test-cafe-demo/node_modules/testcafe-browser-tools/bin/mac/generate-thumbnail
  ../screenshots/2017-09-06_08-36-11/test-1/Chrome_60.0.3112_Mac_OS_X_10.11.0/errors/1.png ../screenshots/2017-09-06_08-36-11/test-1/Chrome_60.0.3112_Mac_OS_X_10.11.0/errors/thumbnails/1.png 240 130
```

**Comment by AndreyBelym** [comment]
Just to be sure, can you please post the output of `testcafe -v` and give me the exact command you use to run tests? Was the browser closed successfully by TestCafe after tests?

**Comment by CommanderXL** [comment]
`testcafe -v` is : `0.17.2`

and I run the test through the node api:

```javascript
const createTestCafe = require('testcafe')
let runner = null
let testcafe = null

createTestCafe('localhost', 1337, 1338)
  .then(tc => {
    testcafe = tc
    runner = tc.createRunner()
  })
  .then(remoteConnection => {
    runner
      .src('fixtures/ticketbuyer.js')
      .browsers('chrome')
      .reporter(() => {
        return require('@my/testcafe-reporter-dtest')()
      })
      .screenshots('../screenshots', true)
      .run({
        skipJsErrors: true,
        assertionTimeout: 7000,
        speed: 0.3
      })
      .then(failedCount => {
        testcafe.close()
      })
      .catch(error => {
        console.log(error)
        testcafe.close()
      })
  })
```

After tests, the browser didn't close. But it show the `disconnected` info.

**Comment by AndreyBelym** [comment]
Hello again, unfortunately we couldn't be able to reproduce the problem. Can you please try to install a debug build (`npm install testcafe@0.17.3-git201709131433`), run your test, and post the contents of the `testcafe-browser-tools.log` and `find-window.log` files from your home directory?

**Comment by Li34** [comment]
Hello,  I did as you said, but it is always loading and last i got this error:

``` bash
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```

and this is the content of testcafe-browser-tools.log, what should i do?

``` bash
Thu Sep 14 2017 10:36:29 GMT+0800 (CST) find-window
Thu Sep 14 2017 10:36:29 GMT+0800 (CST) find-window before 1st exec
Thu Sep 14 2017 10:38:27 GMT+0800 (CST) close
Thu Sep 14 2017 10:38:27 GMT+0800 (CST) find-window
Thu Sep 14 2017 10:38:27 GMT+0800 (CST) find-window before 1st exec
Thu Sep 14 2017 10:38:27 GMT+0800 (CST) find-window Error: Command failed: /usr/bin/osascript /Users/xxx/node_modules/testcafe-browser-tools/bin/mac/find-window.scpt S1g74iPwcW
/Users/xxx/node_modules/testcafe-browser-tools/bin/mac/find-window.scpt: execution error: 文件许可错误。 (-54)

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Thu Sep 14 2017 10:38:27 GMT+0800 (CST) close failed to get window
```

**Comment by AndreyBelym** [comment]
Do you have the "find-window.log" file in your home directory?

**Comment by AndreyBelym** [comment]
By the way, could you try `testcafe@0.18.0-git201709141633` please, and try to attach the `find-window.<some number>.log` files and the `testcafe-browser-tools.log` file, please?

**Comment by AlexanderMoskovkin** [comment]
I'm closing this since there were no activity here for a long time. Feel free to reopen the issue if it's still needed.
Also, you can try to run your tests on the latest TestCafe version.
