### ISSUE TITLE
Should not count invisible elements when visibilityCheck is true

### ISSUE THREAD

**Issue by javiercbk** [DevExpress/testcafe#2058]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
The selector counts returns the total number of elements regardless if they are invisible when using `visibilityCheck: true`

### What is the expected behavior?
When setting `visibilityCheck: true` the `selector.count` should return the total amount of visible elements matched

### How would you reproduce the current behavior (if this is a bug)?
Test code provided below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codepen.io/javiercbk/full/MrxEME/

Test code

```js
import { Selector } from 'testcafe';

fixture('countVisible').page('https://codepen.io/javiercbk/full/MrxEME/');

test('count should not count visibile if visibilityCheck is true', async (t) => {
  await t.switchToIframe('#result');
  const p = Selector('p', { visibilityCheck: true });
  const visibleP = await p.count;
  await t.expect(visibleP).eql(1);
});
```

The html in the codepen is the following:

```html
<html>
  <body>
    <p>This p is visible</p>
    <p style="display:none">This p not is visible</p>
    <p style="visibility:hidden">This p not is visible either</p>
  </body>
</html>
```

### Specify your

* operating system: Mac OS X 10.13.2 (tested on Chrome 63.0.3239)
* testcafe version: 0.18.6
* node.js version: v8.9.3

**Comment by AlexanderMoskovkin** [comment]
Hi @javiercbk,

The `visibilityCheck` option works in another way. It checks that the element is visible when you perform operations with it (getting its property value, using in assertions).

For example the following test fails wit the the `Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.`:

```js
import { Selector } from 'testcafe';

fixture `gh-2058`
    .page `https://codepen.io/javiercbk/full/MrxEME/`;

test('visibilityCheck', async t => {
    const secondP = Selector('p', { visibilityCheck: true }).nth(1);
    
    await t.switchToIframe('#result');

    await t.expect(secondP.textContent).eql('This p not is visible');
});
```

I guess we should update the `visibilityCheck` option description in the documentation to make it more clear. /cc @VasilyStrelyaev 

Meanwhile, we plan to implement the `visible` filter in the context on the #1018 issue soon.

**Comment by javiercbk** [comment]
Thanks for your quick answer,

I've modified the test scenario to best explain the issue. consider three buttons. I want to click all visible buttons using a single selector.

```html
<html>
  <body>
    <button>Visible button</p>
    <button style="display:none">Invisible button</p>
    <button>Other visible button</p>
  </body>
</html>
```

So the strategy is the following. I create a function called *mapSelector*, it takes a selector and executes a function for every matched element by the selector. Alternatively you can modify how the *mapSelector* function grabs the following element by providing a third (optional) parameter. By default it chooses the next element.

The this test case proves that it is not easy to click only the visible buttons, even checking if the element is visible "manually".


```js
import { Selector } from 'testcafe';
import Promise from 'bluebird';

fixture('clickOnlyVisible').page('https://codepen.io/javiercbk/full/MrxEME/');

const nextNth = (selector, index) => selector.nth(index);

/**
 * mapSelector executes a function for every element selected by the selector
 * @param {Object} selector a Selector instance.
 * @param {Function} fun is the function to execute on every command. It should return a Promise
 * @param {Function} nth optional function that chooses the index.
 */
const mapSelector = async (selector, fun, nth = nextNth) => {
  const count = await selector.count; // counts even the invisible, thus triggering an error when attempting to click the element
  await Promise.map(new Array(count), (v, index) => fun(nth(selector, index)), { concurrency: 1 });
};

test('click all buttons', async (t) => {
  await t.switchToIframe('#result');
  const buttons = Selector('button', { visibilityCheck: true });
  // t.click(buttons); // will only click the first one, so does not fulfill my expectation
  await mapSelector(buttons, el => t.click(el)); // will fail because testcafe will try to click invisible elements
});

test('click all buttons #2', async (t) => {
  await t.switchToIframe('#result');
  const buttons = Selector('button', { visibilityCheck: true });
  await mapSelector(buttons, el =>
    el
      .with({ boundTestRun: t })
      .visible // now I check if it is visible
      .then(() => t.click(el))); // triggers an error, element does not exist (counts retuns 3 but selector only returns 2)
});

test('click all buttons #2', async (t) => {
  await t.switchToIframe('#result');
  const buttons = Selector('button', { visibilityCheck: true });
  await mapSelector(buttons, el =>
    el
      .with({ boundTestRun: t })
      .visible // now I check if it is visible with visibilityCheck: false
      .then(() => t.click(el))); // triggers an error, element does not exist
});

```

The test log output:

```
clickOnlyVisible
 ✖ click all buttons

   1) The element that matches the specified selector is not visible.

      Browser: Chrome 63.0.3239 / Mac OS X 10.13.2

         18 |
         19 |test('click all buttons', async (t) => {
         20 |  await t.switchToIframe('#result');
         21 |  const buttons = Selector('button', { visibilityCheck: true });
         22 |  // t.click(buttons); // will only click the first one, so does not fulfill my expectation
       > 23 |  await mapSelector(buttons, el => t.click(el)); // will fail because testcafe will try to click invisible elements
         24 |});
         25 |
         26 |test('click all buttons #2', async (t) => {
         27 |  await t.switchToIframe('#result');
         28 |  const buttons = Selector('button', { visibilityCheck: true });

         at <anonymous> (test/tests/click-all-buttons.test.js:23:38)
         at _bluebird2.default.map.concurrency (test/tests/click-all-buttons.test.js:16:53)
         at tryCatcher (test/node_modules/bluebird/js/release/util.js:16:23)
         at MappingPromiseArray._promiseFulfilled (test/node_modules/bluebird/js/release/map.js:61:38)
         at MappingPromiseArray._drainQueue (test/node_modules/bluebird/js/release/map.js:115:14)
         at MappingPromiseArray._promiseFulfilled (test/node_modules/bluebird/js/release/map.js:46:18)
         at Promise._settlePromise (test/node_modules/bluebird/js/release/promise.js:574:26)
         at Promise._settlePromise0 (test/node_modules/bluebird/js/release/promise.js:614:10)
         at Promise._settlePromises (test/node_modules/bluebird/js/release/promise.js:693:18)
         at Async._drainQueue (test/node_modules/bluebird/js/release/async.js:133:16)
         at Async._drainQueues (test/node_modules/bluebird/js/release/async.js:143:10)
         at Immediate.Async.drainQueues [as _onImmediate] (test/node_modules/bluebird/js/release/async.js:17:14)


 ✖ click all buttons #2

   1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

      Browser: Chrome 63.0.3239 / Mac OS X 10.13.2

         25 |
         26 |test('click all buttons #2', async (t) => {
         27 |  await t.switchToIframe('#result');
         28 |  const buttons = Selector('button', { visibilityCheck: true });
         29 |  await mapSelector(buttons, el =>
       > 30 |    el
         31 |      .with({ boundTestRun: t })
         32 |      .visible // now I check if it is visible
         33 |      .then(() => t.click(el))); // triggers an error, element does not exist (counts retuns 3 but selector only returns 2)
         34 |});
         35 |

         at <anonymous> (test/tests/click-all-buttons.test.js:30:5)
         at _bluebird2.default.map.concurrency (test/tests/click-all-buttons.test.js:16:53)
         at tryCatcher (test/node_modules/bluebird/js/release/util.js:16:23)
         at MappingPromiseArray._promiseFulfilled (test/node_modules/bluebird/js/release/map.js:61:38)
         at MappingPromiseArray._drainQueue (test/node_modules/bluebird/js/release/map.js:115:14)
         at MappingPromiseArray._promiseFulfilled (test/node_modules/bluebird/js/release/map.js:46:18)
         at Promise._settlePromise (test/node_modules/bluebird/js/release/promise.js:574:26)
         at Promise._settlePromise0 (test/node_modules/bluebird/js/release/promise.js:614:10)
         at Promise._settlePromises (test/node_modules/bluebird/js/release/promise.js:693:18)
         at Async._drainQueue (test/node_modules/bluebird/js/release/async.js:133:16)
         at Async._drainQueues (test/node_modules/bluebird/js/release/async.js:143:10)
         at Immediate.Async.drainQueues [as _onImmediate] (test/node_modules/bluebird/js/release/async.js:17:14)


 ✖ click all buttons #2

   1) The element that matches the specified selector is not visible.

      Browser: Chrome 63.0.3239 / Mac OS X 10.13.2

         38 |  const buttons = Selector('button', { visibilityCheck: false });
         39 |  await mapSelector(buttons, el =>
         40 |    el
         41 |      .with({ boundTestRun: t })
         42 |      .visible // now I check if it is visible with visibilityCheck: false
       > 43 |      .then(() => t.click(el))); // triggers an error, element does not exist
         44 |});
         45 |

         at <anonymous> (test/tests/click-all-buttons.test.js:43:21)
         at invokeCallback (test/node_modules/pinkie/index.js:60:12)
         at publish (test/node_modules/pinkie/index.js:147:32)
         at Array.publishFulfillment [as null] (test/node_modules/pinkie/index.js:152:2)
         at Immediate.asyncFlush [as _onImmediate] (test/node_modules/pinkie/index.js:17:19)



 3/3 failed (36s)
```

**Comment by AlexanderMoskovkin** [comment]
You can check the element visibility inside the `mapSelector` function in the following way:

```js
import { Selector } from 'testcafe';
import Promise from 'bluebird';

fixture('clickOnlyVisible').page('https://codepen.io/javiercbk/full/MrxEME/');

const nextNth = (selector, index) => selector.nth(index);

const mapSelector = async (t, selector, fun, nth = nextNth) => {
  const count = await selector.count;

  await Promise.map(new Array(count), async (v, index) => {
      const el = nth(selector.with({ boundTestRun: t }), index);

      if (await el.visible) // check visibility here
          return fun(el);

  }, { concurrency: 1 });
};

test('click all buttons', async (t) => {
  await t.switchToIframe('#result');

  const buttons = Selector('button');

  await mapSelector(t, buttons, el => t.click(el));
});
```
