### ISSUE TITLE
Browsers not launching through Jenkins

### ISSUE THREAD

**Issue by srikanthrbc** [DevExpress/testcafe#2238]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
Unable to open any browser from Jenkins and My tests are running fine when I execute locally

Message:
    Was unable to open the browser "chrome:" due to error.

Error: Unable to run the browser. The file at /Applications/Google Chrome.app does not exist or is not executable.
    at Object.callee$0$0$ (/Users/Shared/Jenkins/Home/workspace/Testcafe-Pipeline/testcafe-ui/node_modules/testcafe-browser-tools/lib/api/open.js:137:23)
    at tryCatch (/Users/Shared/Jenkins/Home/workspace/Testcafe-Pipeline/testcafe-ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at Generator.invoke [as _invoke] (/Users/Shared/Jenkins/Home/workspace/Testcafe-Pipeline/testcafe-ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at Generator.prototype.(anonymous function) [as throw] (/Users/Shared/Jenkins/Home/workspace/Testcafe-Pipeline/testcafe-ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/Users/Shared/Jenkins/Home/workspace/Testcafe-Pipeline/testcafe-ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/Users/Shared/Jenkins/Home/workspace/Testcafe-Pipeline/testcafe-ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:146:20)
    at /Users/Shared/Jenkins/Home/workspace/Testcafe-Pipeline/testcafe-ui/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:156:13
    at <anonymous>
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

### What is the expected behavior?
Launch the chrome/firefox/safari browser and execute tests

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 

Test code

```js

```

### Specify your

* operating system: Mac - Sierra
* testcafe version: 0.19.1
* node.js version: 8.10.0

**Comment by AndreyBelym** [comment]
Hello @srikanthrbc! When you run Jenkins service on a macOS machines, you should do some additional configuration steps for launching GUI apps from build jobs. Could you please try to follow [this answer from the forum](https://testcafe-discuss.devexpress.com/t/607/7) and report your results here?

**Comment by AlexanderMoskovkin** [comment]
I'm closing this since there were no activity here for a long time. Feel free to reopen the issue if you have some additional information.
