### ISSUE TITLE
RequestMock does not send response

### ISSUE THREAD

**Issue by flec** [DevExpress/testcafe#2336]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

The RequestMock does not send a response by using `respond`, there is a unhandled promise rejection.
```
(node:1812) UnhandledPromiseRejectionWarning: TypeError: ctx.destRes.pipe is not a function
    at Object.decideOnProcessingStrategy (C:\dev\tc\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:172:33)
    at next (C:\dev\tc\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:386:38)
    at Object.checkSameOriginPolicyCompliance (C:\dev\tc\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:148:9)
    at next (C:\dev\tc\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:386:38)
    at Object.sendDestinationRequest (C:\dev\tc\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:135:17)
    at next (C:\dev\tc\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:386:38)
    at Object.<anonymous> (C:\dev\tc\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:106:13)
    at Generator.next (<anonymous>)
    at step (C:\dev\tc\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:94:191)
    at C:\dev\tc\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:94:361
(node:1812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### What is the expected behavior?

The response should be sent

### How would you reproduce the current behavior (if this is a bug)?

Using the code below with `testcafe chrome`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://phppot.com/demo/jquery-ajax-autocomplete-country-example/

Test code

```js
import { Selector, RequestMock } from 'testcafe'

const requestMock = RequestMock()
    .onRequestTo('https://phppot.com/demo/jquery-ajax-autocomplete-country-example/readCountry.php')
    .respond(`<ul id="country-list"><li onClick="selectCountry('Sweden')">Sweden</li><li onClick="selectCountry('Switzerland')">Switzerland</li></ul>`)

fixture`Getting Started`
    .page`https://phppot.com/demo/jquery-ajax-autocomplete-country-example/`
    .requestHooks(requestMock)

test('My first test', async t => {
    await t
        .typeText('#search-box', 's')
        .expect(Selector('#country-list li:first-child').innerText).eql('Sweden')
})
```

### Specify your

* operating system: Windows 10.0.0
* browser and version: Chrome 65.0.3325
* testcafe version: 0.20.0-alpha.1
* node.js version: 8.11.1

**Comment by miherlosev** [comment]
I'm working on this
