### ISSUE TITLE
Unable to open any browser when running testcafe

### ISSUE THREAD

**Issue by imzhang1** [DevExpress/testcafe#2364]
### Are you requesting a feature or reporting a bug?
reporting a bug

### What is the current behavior?
when I run testcafe from node.js, I get an error that says 

ERROR Was unable to open the browser "chrome:" due to error.

Error: Unable to run the browser. The file at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe does not exist or is not executable.
    at Object.callee$0$0$ (C:\Users\user\node_modules\testcafe-browser-tools\lib\api\open.js:137:23)
    at tryCatch (C:\Users\user\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at Generator.invoke [as _invoke] (C:\Users\user\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at Generator.prototype.(anonymous function) [as throw] (C:\Users\user\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at tryCatch (C:\Users\user\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at invoke (C:\Users\user\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:146:20)
    at C:\Users\user\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:156:13
    at <anonymous>

this happens in IE as well.

### What is the expected behavior?
Browser should open and run tests.

### How would you reproduce the current behavior (if this is a bug)?
run a test from the command line

#### Provide the test code and the tested page URL (if applicable)
this happens with any test and any url including google.com

Tested page URL: google.com or any URL

Test code

```js

import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');
});

```

### Specify your

* operating system: Windows 10
* testcafe version: 0.19.2
* node.js version: 8.11.1

**Comment by bsmithb2** [comment]
Hi - can you please confirm the testcafe command line you are using - the error message looks slightly wonky as there is a colon in it that isn't clear. Secondly - is there a file at the location that testcafe is attempting to resolve? Thanks

**Comment by AndreyBelym** [comment]
Hi @imzhang1! Could you please provide a TestCafe command line with argument that you have used? Do you use a CI system (e,g, Jenkins), or non-standard environments like WSL, MinGW or Cygwin? Could you also please try to run TestCafe from a shell with Administrator privileges?

**Comment by miherlosev** [comment]
I will close the issue because no activity has been encountered for a long time.
Feel free to reopen the issue if the problem persists and you can provide information about your environment.

**Comment by webia1** [comment]
If you want to debug TestCafe on Windows within Visual Studio Code use the following launch configuration:

```json
{
  "version": "0.2.0",
  "configurations": [{
    "type": "node",
    "protocol": "inspector",
    "request": "launch",
    "name": "Launch test files with TestCafe",
    "program": "${workspaceRoot}/node_modules/testcafe/bin/testcafe.js",
    "args": [
      "chrome:c:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
      "${file}",
      
    ],
    "cwd": "${workspaceRoot}"
  }]
}
```
