### ISSUE TITLE
Error in onRequest() with RequestHook

### ISSUE THREAD

**Issue by rupeshmore** [DevExpress/testcafe#2453]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
```js
..\node_modules\testcafe-hammerhead\lib\request-pipeline\connection-reset-guard.js:20
        throw new Error(err);
        ^

Error: Error: Not implemented
    at Domain.<anonymous> (..\node_modules\testcafe-hammerhead\lib\request-pipeline\connection-reset-guard.js:20:15)
    at emitOne (events.js:96:13)
    at Domain.emit (events.js:188:7)
    at Domain._errorHandler (domain.js:97:23)
    at process._fatalException (bootstrap_node.js:293:33)
npm ERR! Test failed.  See above for more details.
```
### What is the expected behavior?
No error. New headers is added to the request headers object.

### How would you reproduce the current behavior (if this is a bug)?
Implement a RequestHook based on the below code or from the example provided in docs.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: NA

Test code

```js
import { Selector, RequestHook } from 'testcafe';
class Authorization extends RequestHook {
    constructor () {
        super();
    }
    onRequest (e) {
        e.requestOptions.headers['Authorization'] = 'negotiate some JWT token';
    }
}
const authorization:Authorization = new Authorization();

fixture('Test')
    .page(`https://devexpress.github.io/testcafe/example`)
    .requestHooks(authorization);

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button')

        // // Use the assertion to check if the actual header text is equal to the expected one
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});
```

### Specify your

* operating system: Windows 8.1
* testcafe version: 0.20.1
* node.js version: 6.11.2

**Comment by rupeshmore** [comment]
@AndreyBelym Thanks for the updated info. The documentation never mentions that one has to use both the methods regardless on modifying the request and response.
I was following the example mentioned here.
https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/#creating-a-custom-http-request-hook
