### ISSUE TITLE
Regression, selector working with IE 11 in 0.19.1, fails in 0.20.2

### ISSUE THREAD

**Issue by johnwebbcole** [DevExpress/testcafe#2469]
### Are you requesting a feature or reporting a bug?
We are using testcafe on some internal pages, intended to be used only in IE 11.  One of our tests is failing now in 0.20.2, while in 0.19.1 it passes.

### What is the current behavior?
```
✔ /d/src/test
14:35 $ npx testcafe@latest ie test5.js
npx: installed 1 in 6.274s
Path must be a string. Received undefined
npx: installed 271 in 51.405s
d:\npm\cache\_npx\17556\node_modules\testcafe\bin\testcafe-with-v8-flag-filter.js
 Running tests in:
 - IE 11.0.0 / Windows 10.0.0

 Getting Started
 × HelpIndex Test

   1) Error on page "http://docs.plm.automation.siemens.com/tdoc/se/110/se_help":

      Unable to get property 'parentNode' of undefined or null reference

      Browser: IE 11.0.0 / Windows 10.0.0

          3 |    .page `http://docs.plm.automation.siemens.com/tdoc/se/110/se_help#uid:index`;
          4 |
          5 |    test('HelpIndex Test', async t => {
          6 |        // Test code
          7 |        await t
       >  8 |   .click('div[id="gwt-uid-2"]')   // Help
          9 |    });
         10 |
         11 |

         at <anonymous> (D:\src\test\test5.js:8:3)
         at test (D:\src\test\test5.js:5:5)

 1/1 failed (6s)
✘-1 /d/src/test
```

### What is the expected behavior?
```
14:36 $ npx testcafe@0.19.1 ie test5.js
npx: installed 1 in 5.046s
Path must be a string. Received undefined
npx: installed 269 in 22.854s
d:\npm\cache\_npx\24788\node_modules\testcafe\bin\testcafe-with-v8-flag-filter.js
 Running tests in:
 - IE 11.0.0 / Windows 10.0.0

 Getting Started
 √ HelpIndex Test


 1 passed (6s)
✔ /d/src/test
```

### How would you reproduce the current behavior (if this is a bug)?
Run the included test on ie 11 with testcafe 0.19.1 and 0.20.2

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://docs.plm.automation.siemens.com/tdoc/se/110/se_help#uid:index

Test code

```js
import { Selector } from 'testcafe';
fixture `Getting Started`
    .page `http://docs.plm.automation.siemens.com/tdoc/se/110/se_help#uid:index`;     	
 
    test('HelpIndex Test', async t => {
        // Test code
        await t	
	.click('div[id="gwt-uid-2"]')	// Help	
    });
```

### Specify your

* operating system:
Windows 10
* testcafe version:
0.20.2
* node.js version:
8.11.1

**Comment by AndreyBelym** [comment]
Hi @johnwebbcole, I've reproduced the issue. Looks like it's a regression in the `testcafe-hammerhead` proxy caused by the overridden `document.write` method:
```
TypeError: Unable to get property 'parentNode' of undefined or null reference
      at Anonymous function (Unknown script code:1:755)
      at Global code (Unknown script code:1:87)
      at write (http://172.22.11.0:58561/hammerhead.js:9062:17)
      at _overridedDocumentWrite (http://172.22.11.0:58561/hammerhead.js:8551:17)
      at document.write (http://172.22.11.0:58561/hammerhead.js:8664:21)
      at B (http://172.22.11.0:58561/Isuz9CHcw!s!utf-8/https://docs.plm.automation.siemens.com/tdoc/tdoc_client/tdoc_client.nocache.js:5:223)
      at A (http://172.22.11.0:58561/Isuz9CHcw!s!utf-8/https://docs.plm.automation.siemens.com/tdoc/tdoc_client/tdoc_client.nocache.js:4:811)
      at m (http://172.22.11.0:58561/Isuz9CHcw!s!utf-8/https://docs.plm.automation.siemens.com/tdoc/tdoc_client/tdoc_client.nocache.js:10:1)
      at Anonymous function (http://172.22.11.0:58561/Isuz9CHcw!s!utf-8/https://docs.plm.automation.siemens.com/tdoc/tdoc_client/tdoc_client.nocache.js:11:57)
      at d (http://172.22.11.0:58561/Isuz9CHcw!s!utf-8/https://docs.plm.automation.siemens.com/tdoc/tdoc_client/tdoc_client.nocache.js:7:55)
```
