### ISSUE TITLE
[BUG] moment-loader fails to find default export

### ISSUE THREAD

**Issue by awilkins** [DevExpress/testcafe#2500]
### What is the current behavior?

Attempting to

```
import { Selector } from 'testcafe';
```

Get the stack trace below. I would suspect it's something to do with ...

* [This change in Babel behaviour](https://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default)

### What is the expected behavior?

Code works

Note that line error reported on is nothing to do with bug - project has a .babelrc, and these tests are being run from inside Jest, rather than from Testcafe - but they import modules that import Testcafe types. Line reported is somewhere in transpiled output.

```
TypeError: Cannot read property 'exports' of undefined

      2 | /* eslint-disable class-methods-use-this */
      3 | import typeof { t } from 'testcafe';
    > 4 | import type { Address } from './address';
      5 | 
      6 | const { Selector } = require('testcafe');
      7 | 
      
      at getMomentModuleWithDurationFormatPatch (node_modules/testcafe/lib/utils/moment-loader.js:85:37)
      at Object.<anonymous> (node_modules/testcafe/lib/utils/moment-loader.js:88:19)
      at Object.<anonymous> (node_modules/testcafe/lib/reporter/plugin-host.js:23:21)
      at Object.<anonymous> (node_modules/testcafe/lib/reporter/index.js:11:19)
      at Object.<anonymous> (node_modules/testcafe/lib/runner/index.js:47:17)
      at Object.<anonymous> (node_modules/testcafe/lib/testcafe.js:39:15)
      at Object.<anonymous> (node_modules/testcafe/lib/index.js:166:17)
      at Object.<anonymous> (test/acceptance/models/page-model.js:4:22)
      at Object.<anonymous> (test/acceptance/models/app-model.js:3:18)
      at Object.<anonymous> (test/unit/review.test.js:7:17)

```
### Workaround

Use testcafe version 0.20.2 which doesn't have `moment-loader.js`

### Specify your

* operating system: Ubuntu 16.04
* testcafe version: 0.20.3
* node.js version: 8.11.2
* jest : 22.4.4

.babelrc file 

```
{
  "plugins": ["transform-class-properties"],
  "presets": [
    [
      "env", {
        "targets": {
          "node": "current"
        }
      }
    ],
    "flow"
  ]
}
```

**Comment by AndreyBelym** [comment]
Hi @awilkins, likely it's related to `require.cache` invalidation, or installed modules structure. Could you share a minimal example project similar to your setup? Do you use packages that can modify package's cache?

**Comment by awilkins** [comment]
Here's a repo that demonstrates the bug : 

https://github.com/awilkins/testcafe-bug-2500

Running this produces a similar stack trace to above.

```
yarn install
yarn jest
```

**Comment by miherlosev** [comment]
Hi @awilkins 

Thank you for the example to reproduce. I've reproduced the bug.

**Comment by AndreyBelym** [comment]
Working on it. Looks like that jest prevents module caching: https://github.com/facebook/jest/issues/4940, we can work around it.
