### ISSUE TITLE
Error when browser starting.

### ISSUE THREAD

**Issue by marchcorpse** [DevExpress/testcafe#2617]
**Good day!**

**I have the following problem:**

**When i run any test i got this error:**

```
Using locally installed version of TestCafe.
ERROR Was unable to open the browser "chrome:" due to error.
Error: Command failed: FOR /F  "tokens=2 delims=:,." %i in ('chcp') do (chcp 65001 & reg query HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\ /s & chcp %i)
"chcp" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
#### Provide the test code and the tested page URL (if applicable)
```

**Tested page URL:**
http://devexpress.github.io/testcafe/example

**Test code**
```
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');
});
```

**Windows 10 Pro ver.1803 (17134.165)
TestCafe version: 0.20.4
Node.js version: 10.6.0**

**Comment by AndreyBelym** [comment]
Hi @marchcorpse, what language do you use on your machine? Could you please try to execute 
```
chcp 65001
```
before starting TestCafe?

**Comment by marchcorpse** [comment]
@AndreyBelym, hi!
What do you mean? System language? **Russian.**

When i try to execute

`chcp 65001`

I get this:

```
chcp : The term 'chcp' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ chcp 65001
+ ~~~~
+ CategoryInfo          : ObjectNotFound: (chcp:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
