### ISSUE TITLE
Problem with file upload function.

### ISSUE THREAD

**Issue by marchcorpse** [DevExpress/testcafe#2642]
**Good Day!**

**I need to test the file upload form. There is that form:** https://ibb.co/ey5TKJ

 **Here's a piece of DOM tree for this form:**

```
<td class="contentdelimiter">
<h2 class="headertext">Upload new files</h2>
<form action="/exec/performer/gallery/video/add" method="post" enctype="multipart/form-data" class="upload">
<input type="hidden" name="picture_resize_width" value="1024"><input type="hidden" name="picture_resize_height" value="768"><input type="hidden" name="picture_resize_fixed" value="0"> 

<table>

<tbody><tr id="file_row_0" style="">
  <td><input type="file" onchange="showNextUploadFile('file_row_1', 'button_next_0');" name="picture_file" class="file"></td>
  <td><input type="button" id="button_next_0" value="Next file" class="btn btn-default" onclick="showNextUploadFile('file_row_1', 'button_next_0');"></td>
</tr>

<tr id="file_row_1" style="display:none">
  <td><input type="file" onchange="showNextUploadFile('file_row_2', 'button_next_1');" name="picture_file" class="file"></td>
  <td><input type="button" id="button_next_1" value="Next file" class="btn btn-default" onclick="showNextUploadFile('file_row_2', 'button_next_1');"></td>
</tr>

<tr>
  <td colspan="2">
    Select existing set:<br>
    <select name="gallery_set_id" style="width: 100%">
    <option value="0">My Video</option><option value="17">test</option>
    </select>
  </td>
</tr>
<tr>
  <td colspan="2">
    Or enter new set name:<br>
    <input type="text" name="gallery_set_name" value="" maxlength="255" style="width: 100%" class="text" onchange="this.form.elements[&quot;gallery_set_id&quot;].selectedIndex=0;">
    <br>
    and description:<br>
    <textarea name="gallery_set_description" style="width: 100%" class="text" cols="10" rows="5"></textarea>
  </td>
</tr>
<tr>
  <td colspan="2" class="a-center">
    <br>
    <input type="submit" value="Upload" class="btn btn-default">
  </td>
</tr>
</tbody></table>
</form>

```
**In the test, I used the following command to upload the file:**

`await t.setFilesToUpload(Selector('#file_row_0').find('input[type="file"]'), '../../samples_for_testing/test.jpg')`

**The test is "green", but in the field where the name of the selected file should appear, the "File is not selected" is set, and after clicking on the "Upload" button, the download "freezing", it looks like this:**  https://ibb.co/cusm6y

**Also, despite the fact that the test is "green", the console fell out:**

```
(node:14736) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at FormDataEntry.addFileInfo (C:\Testing\Automated_Testing\Tests\TestProject1\node_modules\testcafe-hammerhead\lib\upload\form-data-entry.js:51:57)
    at C:\Testing\Automated_Testing\Tests\TestProject1\node_modules\testcafe-hammerhead\lib\upload\form-data.js:65:26
    at Array.forEach (<anonymous>)
    at FormData._injectFileInfo (C:\Testing\Automated_Testing\Tests\TestProject1\node_modules\testcafe-hammerhead\lib\upload\form-data.js:64:17)
    at C:\Testing\Automated_Testing\Tests\TestProject1\node_modules\testcafe-hammerhead\lib\upload\form-data.js:96:30
    at Array.forEach (<anonymous>)
    at FormData.expandUploads (C:\Testing\Automated_Testing\Tests\TestProject1\node_modules\testcafe-hammerhead\lib\upload\form-data.js:95:19)
    at inject (C:\Testing\Automated_Testing\Tests\TestProject1\node_modules\testcafe-hammerhead\lib\upload\index.js:21:14)
    at createReqOpts (C:\Testing\Automated_Testing\Tests\TestProject1\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:245:46)
    at Object.sendDestinationRequest (C:\Testing\Automated_Testing\Tests\TestProject1\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:107:27)
(node:14736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**What am I doing wrong?**

**Thank you!**

**Windows 10 Pro ver.1803 (17134.165)
TestCafe version: 0.20.4
Node.js version: 10.6.0**

**Comment by LavrovArtem** [comment]
Hi @marchcorpse,
I've reproduced this issue and I will fix it soon.
