### ISSUE TITLE
TestCafe on Windows 10 (version 1803) - Error: Unable to run the browser. The browser path or command template is not specified.

### ISSUE THREAD

**Issue by nabeenj** [DevExpress/testcafe#2701]
### Are you requesting a feature or reporting a bug?

Possible bug

### What is the current behavior?

Can't run testcafe scripts in Windows 10 (version 1803). TestCafe doesn't seem to be able to find any of the browsers installed on the machine.

The output we get when trying to run testcafe is -

D:\temp>testcafe chrome test1.js --debug-mode
ERROR Was unable to open the browser "chrome:" due to error.

Error: Unable to run the browser. The browser path or command template is not specified.
    at checkBrowserPath$ (C:\Users\mag.CORPDOM\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\lib\api\open.js:47:23)
    at tryCatch (C:\Users\mag.CORPDOM\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at Generator.invoke [as _invoke] (C:\Users\mag.CORPDOM\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\mag.CORPDOM\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at tryCatch (C:\Users\mag.CORPDOM\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at invoke (C:\Users\mag.CORPDOM\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:146:20)
    at C:\Users\mag.CORPDOM\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:191:11
    at new Promise (<anonymous>)
    at new F (C:\Users\mag.CORPDOM\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\node_modules\core-js\library\modules\$.export.js:30:36)
    at callInvokeWithMethodAndArg (C:\Users\mag.CORPDOM\AppData\Roaming\npm\node_modules\testcafe\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:190:16)

Type "testcafe -h" for help.

D:\temp>testcafe --list-browsers

D:\temp>

If we specify the full path to the browser executable, as in -
testcafe "path:`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`" test1.js

that does work.

### What is the expected behavior?

Browsers installed on the machine are available to testcafe and we should be able to run the .js scripts.

### How would you reproduce the current behavior (if this is a bug)?

On a Windows 10 (version 1803) machine, run the command to list browsers:
testcafe -b

It doesn't list any of the browsers available on the Windows machine.

### Specify your

* operating system: Windows 10 (version 1803)
* testcafe version: 0.21.0
* node.js version: 10.8.0

**Comment by MarinaRukavitsyna** [comment]
@nabeenj 
It looks like you opened a duplicate issue. Let's continue our discussion in the following thread:
https://www.devexpress.com/Support/Center/Question/Details/T661384

**Comment by nabeenj** [comment]
@MarinaRukavitsyna 
Yes, I wasn't sure where to post this question. There are three forums -
The DevExpress Support Center, where Marion (is that you?) has been helping us;
This github.com/DevExpress/testcafe forum; and
The stackoverflow.com/questions/tagged/testcafe forum

Thanks, will continue on the DevExpress Support Center forum.

Please let me know which one is the correct forum to post questions to and I will keep it to that one in future.

Many thanks.

**Comment by MarinaRukavitsyna** [comment]
@nabeenj 
We process inquiries on all these sources :) So, it is enough to post your question/issue anywhere only once. 
If you need to provide private information, I suggest you use Support Center as it is possible to post private tickets their. 
If you think that your question/scenario/possible answer will be helpful to other users, it is better to use stackoverflow. 
Use GitHub to post bugs as we process them here.
 
>>Marion (is that you?)

Yes, it's me.
