### ISSUE TITLE
Saucelabs error: Unexpected data in simpleCallback

### ISSUE THREAD

**Issue by ZeleniiZmey** [DevExpress/testcafe#2831]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
For some saucelabs configuration getting an simpleCallback error:
```
Error: [get("http://localhost:1337/browser/connect/kH4dsKC")] Unexpected data in simpleCallback.
    at exports.newError (/home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/lib/utils.js:149:13)
    at /home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/lib/callbacks.js:61:12
    at /home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/lib/webdriver.js:185:5
    at Request._callback (/home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/lib/http-utils.js:89:7)
    at Request.self.callback (/home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
```
I've manually updated wd module to version: wd@1.10.3
After update got another error:
```
Error: [get("http://localhost:1337/browser/connect/ycZfK9r")] Error response status: 21, Timeout - An operation did not complete before its timeout expired. Selenium error: Automation Server Error -- Selenium didn't complete your last command on time.
For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
    at exports.newError (/home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/lib/utils.js:149:13)
    at /home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/lib/callbacks.js:36:19
    at /home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/lib/webdriver.js:185:5
    at Request._callback (/home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/lib/http-utils.js:89:7)
    at Request.self.callback (/home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/polly/guidewire/worksapce/elixir-main/tests/node_modules/wd/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)

```
### How would you reproduce the current behavior (if this is a bug)?
Reproducible for:
```
"saucelabs:Safari@11.1:macOS 10.13"
"saucelabs:Safari@11.0:macOS 10.12"
"saucelabs:Safari@10.1:macOS 10.12"
"saucelabs:Safari@10.0:OS X 10.11"
"saucelabs:Safari@9.0:OS X 10.11"
"saucelabs:Safari@8.0:OS X 10.10"
"saucelabs:Safari@7.0:OS X 10.9"
"saucelabs:MicrosoftEdge@16.16299:Windows 10"
"saucelabs:MicrosoftEdge@14.14393:Windows 10"
"saucelabs:MicrosoftEdge@17.17134:Windows 10"
"saucelabs:MicrosoftEdge@13.10586:Windows 10"
"saucelabs:MicrosoftEdge@15.15063:Windows 10"
```
Not all saucelabs configurations provide this callback error. E.g. Chrome and FF works as expected
```
saucelabs:Chrome@68.0:Windows 10
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
```

### Specify your

* operating system: 4.18.5-arch1-1-ARCH
* testcafe version: 0.22.0
* node.js version: 8.9.4

**Comment by AndreyBelym** [comment]
Hi @ZeleniiZmey! Unfortunately, I can't reproduce the issue. Could you please check in the Saucelabs Dashboard if a Saucelabs VM was created before the connection timed out? If you have access to Saucelabs Manual testing, could you also please try to start a problematic browser and [Sauce Connect](https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy) tunnel manually, and try to connect it as a [remote browser](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#remote-browsers)?

**Comment by ZeleniiZmey** [comment]
Ok. Closing issue, as fixed local problem.
Just did full cleanup of npm packages, that was installed globally.

@AndreyBelym thanks for response.
