### ISSUE TITLE
Invalid calling object in IE 11

### ISSUE THREAD

**Issue by sophalch** [DevExpress/testcafe#2871]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Test failed with "Invalid calling object" in IE 11 only. Chrome, Edge, and Firefox are fine.

1) Error on page ".../6CF134EFF8788553F5A82C19A750B4DC.cache.html":

  Invalid calling object

  Browser: IE 11.0.0 / Windows 10.0.0

   > 33 |    .click(Selector('#search'))

     at click (C:\sp\tests\ic\tests\login.js:33:6)
     at test (C:\sp\tests\ic\tests\login.js:13:1)
     at markeredfn (C:\Users\sp\AppData\Roaming\npm\node_modules\testcafe\src\api\wrap-test-function.js:18:28)
     at <anonymous> (C:\Users\sp\AppData\Roaming\npm\node_modules\testcafe\src\api\wrap-test-function.js:8:5)
     at fn (C:\Users\sp\AppData\Roaming\npm\node_modules\testcafe\src\test-run\index.js:238:19)
     at TestRun._executeTestFn (C:\Users\sp\AppData\Roaming\npm\node_modules\testcafe\src\test-run\index.js:234:38)
     at _executeTestFn (C:\Users\sp\AppData\Roaming\npm\node_modules\testcafe\src\test-run\index.js:279:24)

### What is the expected behavior?
Expect test to pass

### Specify your

* operating system: Windows 10
* testcafe version: 0.22.0
* node.js version: 8.9.4

Since this is an internal site with login credential required, I'm not sure how you could replicate it.
This site is using multiple iframes, and when the search button is pressed, the issue appears as above.

Please let me know how I could debug it.

**Comment by AndreyBelym** [comment]
Hi @sophalch! Unfortunately I can't reproduce the issue without an example? Could you please provide access to your page, or HTML code of the page which can be used to reproduce the issue?

**Comment by sophalch** [comment]
Hi @AndreyBelym, this is the test script:


    import { Selector } from 'testcafe'
    
    fixture `Test`
      .page('contentdev-intelliconnect.wkasiapacific.com')
    
    test('Main page', async t => {
      await t
        .wait(3000)
        .typeText(Selector('#username'), 'testuser2018')
        .typeText(Selector('#password'), 'password')
        .click(Selector('button[type=submit]'))
        .wait(5000)

        // search
        .typeText(Selector('#searchInput_comboBox'), 'tax')
        .click(Selector('#searchGoBtn'))
        .wait(5000)
    })

**Comment by miherlosev** [comment]
Hi @sophalch 

I've encountered the problem when loading the test page - 'Sign On Error.  Authentication Failed...' (
see this [video](https://www.screencast.com/t/MUyf9TKpQo)) .
Is it a problem with your site or do we need to perform some actions on our side (your site check location and etc.) to reproduce the issue?

**Comment by sophalch** [comment]
Hi @miherlosev, I'm surprised you didn't get to the login screen at all. There shouldn't be anything else that need to be done.

Could you try this site instead with the credentials above?

    https://intelliconnect.wkasiapacific.com

It should redirect to the login page at:

    https://login.wkasiapacific.com/idp/SSO.saml2

Thanks

**Comment by miherlosev** [comment]
I've reproduce the problem.
```js
 "http://intelliconnect.wkasiapacific.com/scion/secure/6CF134EFF8788553F5A82C19A750B4DC.cache.html":

      TypeError: Invalid calling object
         at find (http://localhost:1337/hammerhead.js:15431:11)
         at Anonymous function
      (http://localhost:1337/hammerhead.js:16453:16)
         at processHtmlInternal
      (http://localhost:1337/hammerhead.js:16437:11)
         at cleanUpHtml (http://localhost:1337/hammerhead.js:16450:11)
         at getter (http://localhost:1337/hammerhead.js:11815:24)
         at VF

   (http://intelliconnect.wkasiapacific.com/scion/secure/6CF134EFF8788553F5A82C19A750B4DC.cache.html:17428:106)
         at btc

   (http://intelliconnect.wkasiapacific.com/scion/secure/6CF134EFF8788553F5A82C19A750B4DC.cache.html:13924:50)
         at bvl

   (http://intelliconnect.wkasiapacific.com/scion/secure/6CF134EFF8788553F5A82C19A750B4DC.cache.html:20422:9942)
         at Pvl

   (http://intelliconnect.wkasiapacific.com/scion/secure/6CF134EFF8788553F5A82C19A750B4DC.cache.html:20422:15237)
         at nNe

   (http://intelliconnect.wkasiapacific.com/scion/secure/6CF134EFF8788553F5A82C19A750B4DC.cache.html:20292:22053)
```
