### ISSUE TITLE
Getting  'Error: { type: 'uncaughtErrorOnPage' while running my suite

### ISSUE THREAD

**Issue by shariqMohammed92** [DevExpress/testcafe#2886]
### Are you requesting a feature or reporting a bug?
I have written a piece of code which is BDD integrated in javascript now when I run the code,
I am getting the following error  in test cafe:
   Error: { type: 'uncaughtErrorOnPage',
         isTestCafeError: true,
         callsite:
          CallsiteRecord {
            filename:
             '/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/features/step_definitions/login.js',
            lineNum: 13,
            callsiteFrameIdx: 6,
            stackFrames:
             [ [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite],
               [CallSite] ],
            isV8Frames: true },
         **errMsg: 'ReferenceError: Can\'t find variable: System',**
         pageDestUrl: 'http://111.93.108.38:4200/' }
           at Function.<anonymous> (/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/node_modules/cucumber/src/user_code_runner.js:74:17)
           at Generator.throw (<anonymous>)
           at Generator.tryCatcher (/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/node_modules/bluebird/js/release/util.js:16:23)
           at PromiseSpawn._promiseRejected (/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/node_modules/bluebird/js/release/generators.js:107:10)
           at Promise._settlePromise (/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/node_modules/bluebird/js/release/promise.js:576:26)
           at Promise._settlePromise0 (/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/node_modules/bluebird/js/release/promise.js:614:10)
           at Promise._settlePromises (/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/node_modules/bluebird/js/release/promise.js:690:18)
           at _drainQueueStep (/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/node_modules/bluebird/js/release/async.js:138:12)
           at _drainQueue (/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/node_modules/bluebird/js/release/async.js:131:9)
           at Async._drainQueues (/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/node_modules/bluebird/js/release/async.js:147:5)
           at Immediate.Async.drainQueues (/Users/shariq/Documents/Repo/CantizConnect_UI-Automation/node_modules/bluebird/js/release/async.js:17:14)
           at runCallback (timers.js:694:18)
           at tryOnImmediate (timers.js:665:5)
           at processImmediate (timers.js:647:5)
           at process.topLevelDomainCallback (domain.js:121:23)
   - And user enters username # features/step_definitions/login.js:27
   - And user enters incorrect password # features/step_definitions/login.js:33
   - And clicks login button # features/step_definitions/login.js:38
   - Then Authentiction message should be shown # features/step_definitions/login.js:43
   ✔ After # features/support/hooks.js:60
   ✔ After # features/support/hooks.js:55

### What is the current behavior?
The navigation to desired URL works.But the click action after that is not performed and the above error is thrown.

The script executes well in other sites.

### What is the expected behavior?
Expecting the actions given in script is performed.

[CantizConnect_UI-Automation.zip](https://github.com/DevExpress/testcafe/files/2401482/CantizConnect_UI-Automation.zip)

### How would you reproduce the current behavior (if this is a bug)?
I have attached the project folder with the issue.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:http://111.93.108.38:4200/landing

Test code

```js

```

### Specify your

* operating system:Mac Sierra
* testcafe version: v0.20.5
* node.js version: 10.10.0

**Comment by anandxp** [comment]
Getting "Uncaught ReferenceError: System is not defined"

Is this something related to this specific webpage. We are getting this issue on a simple testcafe studio recording on the same page

![image](https://user-images.githubusercontent.com/21304150/45861171-c732d780-bd88-11e8-9df7-4ff311c08af9.png)

URL : http://111.93.108.38:4200/landing

**Comment by AndreyBelym** [comment]
Hi @shariqMohammed92, @anandxp, this error means that you have an uncaught exception on your page. I can reproduce it without TestCafe:

![image](https://user-images.githubusercontent.com/4479386/45876015-0faabf00-bda2-11e8-8a74-9ff1190e17bf.png)

You can fix the error on your page, or clear the `Fail if a JavaScript error occurs on a page` checkbox in the [Run Configurations dialog](https://testcafe-studio.devexpress.com/documentation/user-interface/run-configurations-dialog.html#review-fails-and-debug). You can also use the [Skip JS errors flag](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) in the TestCafe CLI or [skipJsErrors option](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#run) in TestCafe API to ignore the error.

**Comment by anandxp** [comment]
Thanks  @AndreyBelym
