### ISSUE TITLE
Docker Image Node Version Compile Mismatch

### ISSUE THREAD

**Issue by aboe026** [DevExpress/testcafe#2890]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When attempting to use the `testcafe/testcafe` docker image, i'm getting the following error:
```
Error: Command failed: node /app/build/server_bundle.js
Error: The module '/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/build/webpack:/external "bcrypt":1:1)
    at n (/app/build/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/app/build/webpack:/src/server/mongodb/user-store.js:1:1)
    at n (/app/build/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/app/build/webpack:/src/server/resolvers.js:7:1)
    at n (/app/build/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/app/build/webpack:/src/server/schema.js:4:1)
    at n (/app/build/webpack:/webpack/bootstrap:19:1)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
    at /opt/testcafe/src/runner/tested-app.js:50:28
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

### What is the expected behavior?
I should install/build the server on the same version of node that the `testcafe/testcafe` image uses. I don't know how to find that out though.

### How would you reproduce the current behavior (if this is a bug)?
Attempt to use the `testcafe/testcafe` docker image to test against an app that has a bcrypt dependency and was compiled on a version of node that is different than the one in the `testcafe/testcafe` image.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Linux Debian 9.5
* testcafe version: 0.20.4
* node.js version: v10.10.0

**Comment by AndreyBelym** [comment]
Hi @aboe026! It's a limitation caused by the Docker containers structure.

Since each Docker container provides an independent operating system, you have to ship all required software binaries in it. It also means that if you need to execute a binary in a container, you have to install it using container's OS package manager, or recompile it in the container.

So you can create you own Docker image, based on the official `testcafe/testcafe` image, and a Node.js modules installation step to its Dockerfile, or override the entrypoint of the `testcafe/testcafe` image to your own shell script that will install your project's dependencies.

**Comment by aboe026** [comment]
Thanks @AndreyBelym. I've actually decided to run my app outside the context of the TestCafe image and have the tests take an environment variable to point the URL where the tests are actually running.
