### ISSUE TITLE
DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'testcafe|driver|Zlbvo42jY' exceeded the quota.

### ISSUE THREAD

**Issue by eljenso** [DevExpress/testcafe#2895]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
I'm trying to run a single test (marked with `test.only`) which creates a project on our website, adds a few data (images) and saves it (upload to a server).
During the upload phase, this error appears mutliple times in console:
```
Uncaught (in promise) DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'testcafe|driver|Zlbvo42jY' exceeded the quota.
    at r.save (http://localhost:39435/testcafe-driver.js:1:67215)
    at r.setItem (http://localhost:39435/testcafe-driver.js:1:67318)
    at i.set (http://localhost:39435/testcafe-driver.js:1:54469)
    at i._onConsoleMessage (http://localhost:39435/testcafe-driver.js:1:44019)
    at t.<anonymous> (http://localhost:39435/testcafe-driver.js:1:43360)
    at t.e.emit (http://localhost:39435/hammerhead.js:10:6517)
    at console.window.console.(anonymous function) (http://localhost:39435/hammerhead.js:2:12688)
    at console.log (http://localhost:39435/Zlbvo42jY!s!utf-8/https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.4.4/rollbar.min.js:3:25171)
    at e.value (http://localhost:39435/Zlbvo42jY!s!utf-8/https://storage.googleapis.com/SOMEAPP/app/mainc1dab717472c45bf1347.bundle.js?c1dab717472c45bf1347:571:11591)
    at t.printTrace (http://localhost:39435/Zlbvo42jY!s!utf-8/https://storage.googleapis.com/SOMEAPP/app/mainc1dab717472c45bf1347.bundle.js?c1dab717472c45bf1347:571:11104)
    at t.logErrorToRollbar (http://localhost:39435/Zlbvo42jY!s!utf-8/https://storage.googleapis.com/SOMEAPP/app/mainc1dab717472c45bf1347.bundle.js?c1dab717472c45bf1347:516:76741)
    at Object._handleSaveError (http://localhost:39435/Zlbvo42jY!s!utf-8/https://storage.googleapis.com/SOMEAPP/app/mainc1dab717472c45bf1347.bundle.js?c1dab717472c45bf1347:10:49087)
    at http://localhost:39435/Zlbvo42jY!s!utf-8/https://storage.googleapis.com/SOMEAPP/app/mainc1dab717472c45bf1347.bundle.js?c1dab717472c45bf1347:10:40449
```
The upload never finishes and the test never continues.

### What is the expected behavior?
Upload should succeed and the test should go on.

### Specify your

* operating system: Fedora 28
* testcafe version: 0.22.0 (also tested with 0.21.1)
* node.js version: 10.11.0

**Comment by eljenso** [comment]
Looks like this is an error on our side.

**Comment by eljenso** [comment]
See #2942 for more info.
