### ISSUE TITLE
crypto.randomFillSync is not a function

### ISSUE THREAD

**Issue by Turkirafaa** [DevExpress/testcafe#2905]
### Are you requesting a feature or reporting a bug?
Yes

### What is the current behavior?
TypeError: crypto.randomFillSync is not a function
    at module.exports (/var/lib/jenkins/jobs/automated-test/workspace/node_modules/nanoid/random.js:5:10)
    at module.exports (/var/lib/jenkins/jobs/automated-test/workspace/node_modules/nanoid/index.js:24:15)
    at new Role (/var/lib/jenkins/jobs/automated-test/workspace/node_modules/testcafe/src/role/index.js:19:22)
    at createRole (/var/lib/jenkins/jobs/automated-test/workspace/node_modules/testcafe/src/role/index.js:85:12)
    at Role (/var/lib/jenkins/jobs/automated-test/workspace/node_modules/testcafe/src/api/exportable-lib/index.js:10:12)
    at Object.<anonymous> (/var/lib/jenkins/jobs/automated-test/workspace/src/Users.js:6:12)
    at Object._compile [as .js] (/var/lib/jenkins/jobs/automated-test/workspace/node_modules/testcafe/src/compiler/test-file/api-based.js:84:25)
    at Object.<anonymous> (/var/lib/jenkins/jobs/automated-test/workspace/src/authentication.js:2:1)
    at Function._compile [as _execAsModule] (/var/lib/jenkins/jobs/automated-test/workspace/node_modules/testcafe/src/compiler/test-file/api-based.js:50:13)
    at ESNextTestFileCompiler._execAsModule [as compile] (/var/lib/jenkins/jobs/automated-test/workspace/node_modules/testcafe/src/compiler/test-file/api-based.js:144:42)

### What is the expected behavior?

Testcafe working with browserstack 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your 

* operating system: os 
* testcafe version: v0.22.0
* node.js version: v10.10.0

**Comment by AndreyBelym** [comment]
@Turkirafaa, please check the Node.js version on your Jenkins machine. I guess it's lesser than `7.10.0` - the version that introduced the [crypto.randomFillSync](https://nodejs.org/api/crypto.html#crypto_crypto_randomfillsync_buffer_offset_size) function. By the way, it's a [breaking change](https://github.com/ai/nanoid/commit/8db78bad0f11da03e9fe7c707b2feac13e0f6801#diff-b195669f6653037f4481cc8d9488b507) in the `nanoid` package,

**Comment by Turkirafaa** [comment]
@AndreyBelym  Thank you so much for you'r quick response we update the Node.js version to v8.12.0
and it's working now.
