### ISSUE TITLE
Can't reload page using await t.eval(() => location.reload(true)) in TestCafe (v0.23.2)

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#2916]
### Are you requesting a feature or reporting a bug?
Regression bug.

### What is the current behavior?
- Page reload doesn't work and browser hangs. TestCafe leaves control at location.reload(true) or location.reload(). Tried in Chrome and Firefox both but no luck. I re-installed node modules so no caching issue, using latest packages.

### What is the expected behavior?
- Page reload should be working.

### How would you reproduce the current behavior (if this is a bug)?
await t.eval(() => location.reload(true));

It was working fine with 20.0 version for me.

```js
   1) TypeError: Cannot read property '0' of null

      Browser: Chrome 69.0.3497 / Windows 7 0.0.0

         266 |        this._handlePlainObject(val);
         267 |};
         268 |
         269 |DecodingTransformer.prototype.transform = function () {
         270 |    this.visitedRefs[0] = true;
       > 271 |    this._handleValue(this.references[0], this.references, 0);
         272 |
         273 |    return this.references[0];
         274 |};
         275 |
         276 |

         at DecodingTransformer.transform (c:\git\repo\node_modules\replicator\index.js:271:38)
         at module.exports.Replicator.decode (c:\git\repo\node_modules\replicator\index.js:559:24)
         at ClientFunctionBuilder.decode [as _processResult] (c:\git\repo\node_modules\testcafe\src\client-functions\client-function-builder.js:142:32)
         at _processResult (c:\git\repo\node_modules\testcafe\src\client-functions\client-function-builder.js:137:25)
         at $$testcafe_test_run$$2PLNpRhxU$$ (c:\git\repo\node_modules\testcafe\src\api\test-run-tracker.js:76:16)
         at $$testcafe_test_run$$2PLNpRhxU$$ (c:\git\repo\node_modules\testcafe\src\api\test-run-tracker.js:76:16)
```
* operating system: Windows7
* testcafe version: 0.22.1-alpha.2
* node.js version: v9.2.0

**Comment by miherlosev** [comment]
I've tried to reproduce the problem with following test:
```js
fixture `Fixture`
    .page('http://example.com');

test('test', async t => {
    await t.eval(() => location.reload(true));
});
```

and it works fine.

Could you please provide a small example to reproduce or direct access to the tested page?

**Comment by miherlosev** [comment]
I will close the issue because no activity has been encountered for a long time.
Feel free to reopen the issue if the problem persists and you can provide an example to reproduce it.

**Comment by jiteshsojitra** [comment]
Yes, i would like to really reopen this bug because reload problem is still exists and really affecting us to upgrade. Sometime it works fine 2 out of 10 attempts with one browser instance ONLY, when try with 10 instances it always fails for me. I even tried https://stackoverflow.com/questions/39599736/window-reload-doesnt-reload-my-page but no luck and TestCafe hangs at reload page and takes forever. After manually reloading page, it shows below error assuming TestCafe was hanged there?

    await t.eval(() => window.location.href = window.location.href);

```
DecodingTransformer.prototype.transform = function () {
         270 |    this.visitedRefs[0] = true;
       > 271 |    this._handleValue(this.references[0], this.references, 0);
         272 |
         273 |    return this.references[0];
         274 |};

```

I'm quite sure something is wrong in this area and it blocks us to upgrade TestCafe v0.23.2. We didn't upgrade TestCafe just because of this reason since reported in October and previous release was certainly fine. Any solution/work around please?

**Comment by jiteshsojitra** [comment]
Wow, it worked with latest alpha version (0.23.3-alpha.2) instead of last stable release (0.23.2). Thanks @LavrovArtem for fixing this and i can see stability back. Awesome, i can go ahead and upgrade now.

**Comment by LavrovArtem** [comment]
Thank you for the update. This is great news! I'm happy to hear that the issue is resolved.
