### ISSUE TITLE
IE doesn't support?

### ISSUE THREAD

**Issue by moffsugita** [DevExpress/testcafe#2935]
### Are you requesting a feature or reporting a bug?

run `testcafe-live ie`

url is like `192.168.1.8`.

It is bug. others works fine. (Edge, Firefox(Mac), Chrome(Mac), safari(Mac))
```
 Getting Started
(node:1152) UnhandledPromiseRejectionWarning: Error: Protocol "about:" not supported. Expected "https:"
    at new ClientRequest (_http_client.js:131:11)
    at Object.request (http.js:38:10)
    at Domain.<anonymous> (C:\Users\IEUser\Documents\react_e2e\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:97:51)
    at Domain.run (domain.js:242:14)
    at exports.default (C:\Users\IEUser\Documents\react_e2e\node_modules\testcafe-hammerhead\lib\request-pipeline\connection-reset-guard.js:6:27)
    at DestinationRequest._send (C:\Users\IEUser\Documents\react_e2e\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:94:44)
    at new DestinationRequest (C:\Users\IEUser\Documents\react_e2e\node_modules\testcafe-hammerhead\lib\request-pipeline\destination-request\index.js:87:15)
    at sendRequest (C:\Users\IEUser\Documents\react_e2e\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:346:77)
    at Object.sendDestinationRequest (C:\Users\IEUser\Documents\react_e2e\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:122:20)
    at next (C:\Users\IEUser\Documents\react_e2e\node_modules\testcafe-hammerhead\lib\request-pipeline\index.js:373:38)
(node:1152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### What is the current behavior?

I wrote above.

### What is the expected behavior?

run fine.

### How would you reproduce the current behavior (if this is a bug)?

(node:1152) UnhandledPromiseRejectionWarning: Error: Protocol "about:" not supported. Expected "https:"

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

sorry secret.

Test code

```js
test('test name', async t => {
    await t.setNativeDialogHandler(() => true)
        .useRole(regularAccUser)
        .navigateTo(url);
```

### Specify your

* operating system: Windows 8(Virtual Machine)
* testcafe version: 0.20.0
* node.js version: v8.11.3

**Comment by miherlosev** [comment]
Hi @moffsugita 

I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a small example so that we can reproduce it on our side?

**Comment by miherlosev** [comment]
I will close the issue because no activity has been encountered for a long time.
Feel free to reopen the issue if the problem persists and you can provide an example to reproduce it.
