### ISSUE TITLE
authorization redirect never happens

### ISSUE THREAD

**Issue by two7sclash** [DevExpress/testcafe#3048]
### What is your Test Scenario?
Testing login flow with redirection to auth server
 
### What is the Current behavior?
Testcafe never redirects and bombs out with "1) AssertionError: expected 'https://***-web-dev.app.dev.pcf.***.com/' to include 'authorization-dev.app.dev.pcf.***.com'"
 
### What is the Expected behavior?

After loading 'https://***-web-dev.app.dev.pcf.***.com/' Testcafe should redirect to and test 'authorization-dev.app.dev.pcf.***.com'
 
### What is your web application and your TestCafe test code?
Lies behind VPN :(
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 // @flow

import { ClientFunction } from 'testcafe';

fixture('Log In').page('https://xxx-web-dev.app.dev.pcf.xxx.com/');

test('Ignite Auth', async (t) => {
  const location = ClientFunction(() => document.location.href.toString());
  await t
    .wait(10000)
    .expect(location()).contains('authorization-dev.app.dev.pcf.xxx.com', { timeout: 10000 });

  await t
    .wait(2000)
    .typeText('#username', 'guywithstick4')
    .typeText('#password', 'P@55word')
    .click('#login');

  await t.expect(location()).contains('/initiate-otp', { timeout: 10000 });

  await t
    .click('[data-test="send-otp-code-button"]');

  await t.expect(location()).contains('/validate-otp', { timeout: 10000 });

  await t
    .typeText('#otp-code', '0000')
    .click('#verify-code');

  await t
    .wait(2000)
    .expect(location()).contains('xxx-web-dev.app.dev.pcf.xxx.com/');
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```
502487632@USSYFRMTM210897[± jf|develop {5} U:2 ✗]:~/workspace/syb-xxx-web $ yarn test:cafe
yarn run v1.10.1
$ testcafe --hostname localhost chrome-canary ./src/tests/e2e/ -e
 Running tests in:
 - Chrome 72.0.3592 / Mac OS X 10.13.5

 Log In
 ✖ xxx Auth

   1) AssertionError: expected 'https://xxx-web-dev.app.dev.pcf.xxx.com/' to include 'authorization-dev.app.dev.pcf.xxx.com'

      Browser: Chrome 72.0.3592 / Mac OS X 10.13.5

          6 |
          7 |test('xxx Auth', async (t) => {
          8 |  const location = ClientFunction(() => document.location.href.toString());
          9 |  await t
         10 |    .wait(100000)
       > 11 |    .expect(location()).contains('authorization-dev.app.dev.pcf.xxx.com', { timeout: 10000 });
         12 |
         13 |  await t
         14 |    .wait(2000)
         15 |    .typeText('#username', 'guywithstick4')
         16 |    .typeText('#password', 'P@55word')

         at contains (/Users/502487632/workspace/syb-xxx-web/src/tests/e2e/authxxx.js:11:25)
         at test (/Users/502487632/workspace/syb-xxx-web/src/tests/e2e/authxxx.js:7:1)
         at markeredfn (/Users/502487632/workspace/syb-xxx-web/node_modules/testcafe/src/api/wrap-test-function.js:18:28)
         at <anonymous> (/Users/502487632/workspace/syb-xxx-web/node_modules/testcafe/src/api/wrap-test-function.js:8:5)
         at fn (/Users/502487632/workspace/syb-xxx-web/node_modules/testcafe/src/test-run/index.js:238:19)
         at TestRun._executeTestFn (/Users/502487632/workspace/syb-xxx-web/node_modules/testcafe/src/test-run/index.js:234:38)
         at _executeTestFn (/Users/502487632/workspace/syb-xxx-web/node_modules/testcafe/src/test-run/index.js:279:24)



 1/1 failed (1m 51s)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

 
### Your Environment details:
 
* testcafe version:                   0.22.0
* node.js version:                    v8.11.0
* command-line arguments:  testcafe --hostname localhost chrome-canary ./src/tests/e2e/ -e
* browser name and version: Version 72.0.3590.0 (Official Build) canary (64-bit)
* platform and version:          macOS 10.13.5

**Comment by miherlosev** [comment]
Unfortunately, without direct access to your website, it's difficult to understand the cause of the problem. Could you please set up access to your website or provide a small example in which we can reproduce the problem?
