### ISSUE TITLE
Getting ERR_STREAM_WRITE_AFTER_END error while executing test suite

### ISSUE THREAD

**Issue by anandxp** [DevExpress/testcafe#3130]
Error Details

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:248:12)
    at WriteStream.Writable.write (_stream_writable.js:296:5)
    at ProgressFormatter.log [as logProgress] (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/cucumber/src/formatter/progress_formatter.js:25:10)
    at EventEmitter.emit (events.js:187:15)
    at EventEmitter.emit (domain.js:441:20)
    at TestCaseRunner.emit (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/cucumber/src/runtime/test_case_runner.js:61:27)
    at TestCaseRunner.emit (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/cucumber/src/runtime/test_case_runner.js:160:10)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/anandxavier/Documents/shariq-testcafe/connect-ui-automation/node_modules/bluebird/js/release/async.js:147:5)

**Comment by AlexKamaev** [comment]
This information is not sufficient to discover the cause of the issue. Could you please create a separate ticket using this `bug report` template https://github.com/DevExpress/testcafe/issues/new?labels=&template=bug-report.md
Please complete all template sections and provide us as many details as possible.

**Comment by AlexKamaev** [comment]
@juliusgonawan Could you please clarify what TestCafe version you are using? If you can reproduce the issue with the latest version, could you share your test project and code?

**Comment by AlexKamaev** [comment]
The problem seems to be related to the problem we discussed at https://github.com/DevExpress/testcafe/issues/3114
Could you please try to install the latest TestCafe version from the following link https://github.com/AndreyBelym/testcafe/releases/download/gh-3114-4/testcafe-0.23.3-alpha.gh3114.4.tgz

**Comment by miherlosev** [comment]
I will close the issue because no activity has been encountered for a long time.
Feel free to reopen the issue if the problem persists and you can provide an example to reproduce it.

**Comment by umbrella-vladislav-pisarev** [comment]
Have the same issue. I have two reporters. One from which - 'testacafe-reporter-spec', and the second it's my custom reporter. 'spec' reporter printing logs to console. My reporter printing logs to file.

Part of .testcaferc.json:
```json
"reporter": [
    {
      "name": "my-reporter",
      "output": "reports/report.log"
    },
    {
      "name": "spec"
    }
  ]
```

In my reporter wrote logic for printing logs in `reportTaskDone` method. 

Logs
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:248:12)
    at WriteStream.Writable.write (_stream_writable.js:296:5)
    at ReporterPluginHost.newline (/Users/vladislavpisarev/projects/Automate/node_modules/testcafe/lib/reporter/plugin-host.js:132:22)
    at ReporterPluginHost.reportTaskDone (/Users/vladislavpisarev/projects/Automate/node_modules/testcafe-reporter-my-reporter/lib/index.js:128:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

Code of `reportTaskDone` method:

```javascript
async reportTaskDone(endTime, passed, warnings, result) {
      const closeResponse = await this.reporter.closeRun();
      if (closeResponse) {
        const runUrl = get(closeResponse, 'url', null);
        this.write(`Click to link for open Test run: ${runUrl}`)
          .newline()
          .write(`End time: ${endTime}`)
          .newline()
          .write(`Test passed: ${passed}/${result.failedCount}. Skipped test: ${result.skippedCount}`);
      } else {
        this.write('Error trying close run');
      }
    },
```

---
### Your Environment details:
 
* testcafe version:                   1.1.2
* node.js version:                    v11.12.0
* command-line arguments:  I use custom runner similar to [this](https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/using-testcafe/programming-interface/runner.md). For run use command `ts-node src/e2eRunner.ts`
* browser name and version: chrome
* platform and version:          macOS 10.14.3
* other:                                   My reporter wrote on JS. Test and runner wrote on TypeScript

**Comment by AlexKamaev** [comment]
Since this issue is closed, I would ask you to create a separate issue using this [form](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md).
Please also provide us with as much detailed information as possible: your project or the url to public website, your test code, full code of your custom reporter, and full code of your runner configuration. Thank you in advance.
