### ISSUE TITLE
Reach Router doesn't navigate in Testcafe tests

### ISSUE THREAD

**Issue by jagregory** [DevExpress/testcafe#3208]
### What is your Test Scenario?

A single-page app built using [Reach Router](https://reach.tech/router).
 
### What is the Current behavior?

Any navigation using Reach Router doesn't work.
 
### What is the Expected behavior?

Links are followed.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): https://lyzwj8w0qz.codesandbox.io/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector } from "testcafe";

fixture("reach router")
  .page("https://lyzwj8w0qz.codesandbox.io/");

test("can click links using history api", async (t) => {
  await t.click(Selector("a").withExactText("Dashboard"))
    .expect(Selector("h2").withExactText("Dashboard").exists).ok();
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
testcafe chrome 'test.ts'
 Running tests in:
 - Chrome 70.0.3538 / Mac OS X 10.14.1

 reach router
 ✖ can click links using history api

   1) AssertionError: expected false to be truthy

      Browser: Chrome 70.0.3538 / Mac OS X 10.14.1

          3 |fixture("reach router")
          4 |  .page("https://lyzwj8w0qz.codesandbox.io/");
          5 |
          6 |test("can click links using history api", async (t) => {
          7 |  await t.click(Selector("a").withExactText("Dashboard"))
       >  8 |    .expect(Selector("h2").withExactText("Dashboard").exists).ok();
          9 |});

         at Object.<anonymous> (/Users/jag/dev/demo/test.ts:8:63)
         at <anonymous> (/Users/jag/dev/demo/test.ts:7:71)
         at __awaiter (/Users/jag/dev/demo/test.ts:3:12)
         at test (/Users/jag/dev/demo/test.ts:6:55)
         at markeredfn (/Users/jag/dev/demo/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at step (/Users/jag/dev/demo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
         at <anonymous> (/Users/jag/dev/demo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14)
         at new F (/Users/jag/dev/demo/node_modules/core-js/library/modules/_export.js:36:28)
         at <anonymous> (/Users/jag/dev/demo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
         at <anonymous> (/Users/jag/dev/demo/node_modules/testcafe/src/api/wrap-test-function.js:7:5)



 1/1 failed (14s)
```
</details>

### Steps to Reproduce:

Open the codesandbox, click the Dashboard link and see the heading text change. Repeat that in testcafe and see it not change...
 
### Your Environment details:
 
* testcafe version:                   0.23.2
* node.js version:                    v8.11.4
* command-line arguments:  testcafe chrome test.ts
* browser name and version: Chrome 70.0.3538
* platform and version:          Mac OS X 10.14.1

**Comment by miherlosev** [comment]
Hi @jagregory 

Thank you for the detailed description. I've reproduced the problem.
