### ISSUE TITLE
Hard to debug assertion error without selector string

### ISSUE THREAD

**Issue by nicgirault** [DevExpress/testcafe#3229]
I would like to be able to understand what is wrong in my tests easily but I miss the selector information in my assertion error message.

![image](https://user-images.githubusercontent.com/551837/50013452-761a3480-ffc1-11e8-8bb0-c006a751256c.png)

For example when writing:

```javascript
const selector = Selector('#testcafe_is_awesome')

await t.expect(selector.exists).ok()
```

I would like to see:

`AssertionError: expected "#testcafe_is_awesome" to exists` instead of `AssertionError: expected false to be truthy`.

Or at least, I would like to be able to access the selector init parameter ('#testcafe_is_awesome') like `selector.init` to display a custom message.

**Comment by hdorgeval** [comment]
I also suggest to have an enhanced `spec` reporter that enables to have the source code not only on the last error in the stack trace but for each file inside the stack trace, like in this example:

```txt
1) The specified selector does not match any element in the DOM tree.

   Browser: Firefox 59.0.0 / Mac OS X 10.12.0

      13 |
      14 |  const value = inputData.name || "";
      15 |
      16 |  await t
      17 |    .setTestSpeed(config.testcafe.testSpeed)
   --------------------------------------------
    → 18 |    .hover(selector.userNameInputBox)
   --------------------------------------------
      19 |    .expect(selector.userNameInputBox.hasAttribute("disabled")).notOk()
      20 |    .typeText(selector.userNameInputBox, value, {replace: true})
      21 |    .pressKey("tab");
      22 |};
      23 |

      at Object.(anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/domains/testcafe-sample-page/steps/i-enter-my-name.ts:18:6)
      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/domains/testcafe-sample-page/steps/i-enter-my-name.ts:7:71)
      at __awaiter (/Users/HDO/VSCodeProjects/testcafe-starter/domains/testcafe-sample-page/steps/i-enter-my-name.ts:3:12)
      at exports.default (/Users/HDO/VSCodeProjects/testcafe-starter/domains/testcafe-sample-page/steps/i-enter-my-name.ts:7:36)


       6 |  if (canExecute === false) {
       7 |    return;
       8 |  }
       9 |  const foundStep = stepMappings[stepName];
      10 |  if (typeof foundStep === "function" ) {
   --------------------------------------------
    → 11 |    await foundStep(stepName);
   --------------------------------------------
      12 |    return;
      13 |  }
      14 |  throw new Error(`Step "${stepName}" is not mapped to an executable code.`);
      15 |}
      16 |export async function given(stepName: GivenStep) {

      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:11:11)
      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:7:71)
      at __awaiter (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:3:12)
      at executeStep (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:14:12)
      at Object.(anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:20:9)
      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:7:71)
      at __awaiter (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:3:12)
      at Object.when (/Users/HDO/VSCodeProjects/testcafe-starter/step-runner.ts:34:12)


      19 |  await  then("no name should be populated");
      20 |  await   and("I cannot submit my feedback on testcafe");
      21 |});
      22 |
      23 |test("Scenario: can send feedback with my name only", async () =) {
   --------------------------------------------
    → 24 |  await  when("I enter my name");
   --------------------------------------------
      25 |  await  then("I can submit my feedback on testcafe");
      26 |});
      27 |
      28 |test("Scenario: send feedback", async () =) {
      29 |  await env.only( "devci");

      at Object.(anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/features/testcafe-sample-page.spec.ts:24:10)
      at (anonymous) (/Users/HDO/VSCodeProjects/testcafe-starter/features/testcafe-sample-page.spec.ts:7:71)
      at __awaiter (/Users/HDO/VSCodeProjects/testcafe-starter/features/testcafe-sample-page.spec.ts:3:12)
      at test (/Users/HDO/VSCodeProjects/testcafe-starter/features/testcafe-sample-page.spec.ts:23:66)
```

**Comment by VasilyStrelyaev** [comment]
@nicgirault, thank you for your proposal.

I agree that TestCafe could benefit from more informative assertion messages. However, we are technically unable to implement the message you propose with the current assertion system.

Regarding custom assertion messages, you can pass them in the assertion's `message` parameter. See https://devexpress.github.io/testcafe/documentation/test-api/assertions/assertion-api.html#ok.

You can hardcode a custom message for each assertion or generate messages dynamically if required (so that they can include a CSS selector). However, the best practice is to provide a detailed individual message for each assertion instead of generating them from a template.

@hdorgeval, thank you for your idea. However, it is difficult to process two proposals in one issue. Could you please [create a separate issue](https://github.com/DevExpress/testcafe/issues/new?template=feature_request.md) for your suggestion?
