### ISSUE TITLE
Flaky test select elements: click triggers "Cannot read property 'parent' of undefined"

### ISSUE THREAD

**Issue by mweibel** [DevExpress/testcafe#3285]
### What is your Test Scenario?
Open a page with one to `n` `<select>` tags. We select the first select tag out of it and select a specific option. Then we click on that option.

```javascript
fixture`The failing test`
  .page`${baseURL}/SOMERELATIVEURL`

test('Has interactive variants', async t => {
  const variants = await testIdSelector('product-variants-select')
  const variant = variants.nth(0)

  const variantOptions = variant.find('option')
  await t.expect(variantOptions.count).eql(9)

  const optionToSelect = variantOptions.withText('140.0 cm')
  await t.expect(optionToSelect.exists).ok()

  const getPageUrl = ClientFunction(() => window.location.href.toString())

  await t.click(variant)
    .click(optionToSelect)
    .expect(getPageUrl()).contains(`${baseURL}/SOME_OTHER_RELATIVE_URL`, { timeout: 10000 })
})
```
 
### What is the Current behavior?
This specific test is quite flaky on the CI where we execute it in a docker container. The error we get in that case is always the same:
```

 The failing test
 ✖ Has interactive variants

   1) Error on page "http://localhost:3002/SOMERELATIVEURL":

      TypeError: Cannot read property 'parent' of undefined
          at b (http://172.17.0.3:33154/hammerhead.js:10:2044)
          at s (http://172.17.0.3:33154/hammerhead.js:1:26914)
          at Function.t._getCurrentInfoManager
      (http://172.17.0.3:33154/hammerhead.js:9:13976)
          at http://172.17.0.3:33154/hammerhead.js:9:14160
          at http://172.17.0.3:33154/hammerhead.js:3:21621
          at HTMLSelectElement.dispatchEvent
      (http://172.17.0.3:33154/hammerhead.js:3:15741)
          at e._raiseDispatchEvent
      (http://172.17.0.3:33154/hammerhead.js:4:17959)
          at e._dispatchEvent
      (http://172.17.0.3:33154/hammerhead.js:4:17650)
          at e.change (http://172.17.0.3:33154/hammerhead.js:4:20479)
          at B (http://172.17.0.3:33154/testcafe-ui.js:1:17061)

      Browser: HeadlessChrome 0.0.0 / Linux 0.0.0

          98 |  await t.expect(optionToSelect.exists).ok()
          99 |
         100 |  const getPageUrl = ClientFunction(() =>
      window.location.href.toString())
         101 |
         102 |  await t.click(variant)
       > 103 |    .click(optionToSelect)
         104 |
      .expect(getPageUrl()).contains(`${baseURL}/SOME_OTHER_RELATIVE_URL`, {
      timeout: 10000 })
         105 |})
         106 |
         107 |fixture`The failing test`
         108 |
      .page`${baseURL}/SOMERELATIVEURL`

         at click
      (/relative/path/to/test/productDetail/sometest.test.js:103:6)
```
Seldomly it fails on the local devs machines too, but that's quite seldom.  

### What is the Expected behavior?
It should work always or fail in some way that is predictable.
 
### Your Environment details:
 
* testcafe version:                   0.23.2
* node.js version:                    v10.12.0
* command-line arguments:  testcafe --app='npm run test:mock-api' 'chromium:headless' ./test
* browser name and version: Chromium
* platform and version:          Linux

**Comment by LavrovArtem** [comment]
Thank you for the provided information.
However, I cannot reproduce this issue in my simple example (see below).
The information you provided is not sufficient to find the cause of the issue. There can be many causes, and therefore we cannot give you advice without analyzing your page or code. Would you please give me a link to your site if it is public?
Also, could you try to update the testcafe version to the latest stable `0.23.3` or the latest alpha `1.0.0-alpha.1`.

### index.html
```html
<form>
    <select name="select" >
        <option value="value1">100.0 cm</option> 
        <option value="value2" selected>110.0 cm</option>
        <option value="value3">120.0 cm</option>
        <option value="value4">130.0 cm</option>
        <option value="value5">140.0 cm</option>
        <option value="value6">150.0 cm</option>
        <option value="value7">160.0 cm</option>
        <option value="value8">170.0 cm</option>
        <option value="value9">180.0 cm</option>
    </select>
</form>
```
### test.js
```js
import { Selector } from 'testcafe';

fixture`The failing test`
  .page`./index.html`

test('Has interactive variants', async t => {
  const variants = await Selector('select')
  const variant = variants.nth(0)

  const variantOptions = variant.find('option')
  await t.expect(variantOptions.count).eql(9)

  const optionToSelect = variantOptions.withText('140.0 cm')
  await t.expect(optionToSelect.exists).ok();

  await t
    .click(variant)
    .click(optionToSelect)
    .wait(20 * 1000);
})
```

**Comment by mweibel** [comment]
Hi @LavrovArtem 
thanks for the response. I expected as much :( 

Unfortunately the site is not yet public so I can't share the URL. 
I'll update to latest testcafe!
Is there any strategy to somehow collect some more useful information if such a test failure occurs? E.g. outputting the current HTML which the browser had?
Can I catch the error from occurring to log some details and then rethrow?

**Comment by LavrovArtem** [comment]
I've figured out the [place](https://github.com/DevExpress/testcafe-hammerhead/blob/v14.4.8/src/client/utils/dom.js#L210) where the error occurs by the stack trace from the first message. The `window` argument comes to the `getTopSameDomainWindow` function from [this](https://github.com/DevExpress/testcafe-hammerhead/blob/v14.4.8/src/client/sandbox/upload/index.js#L28) place. Our proxy server processes all elements on a web page and if the `INTERNAL_PROPS.processedContext` property of an element does not exist, it means that the element is not processed. We cannot answer you why the element is not processed without analyzing your page or code.
