### ISSUE TITLE
Not finding element in IE11

### ISSUE THREAD

**Issue by alisonhall** [DevExpress/testcafe#3293]
### What is your Test Scenario?

I am trying to click a button on a webpage using testcafe with IE11.
 
### What is the Current behavior?

The button is found when testing in Chrome, Firefox, Safari, and Edge, but is not found when testing in IE 11. When testing in IE11, the page is loaded, but due to the button not being found, the test fails. Additionally, the testcafe status bar which usually is displayed at the bottom of the browser window is not shown in IE11.

I have tried multiple versions of code, different methods of element selection, different computers, and different node versions, but none of them have worked in IE11.
 
### What is the Expected behavior?

I expect that the button would be found in IE11, and then allow the test to click on it.
 
### What is the web application and the TestCafe test code?

<summary>Complete test code:</summary>

 
```js
import { Selector } from 'testcafe';

fixture('Age Gate')
    .page('https://cannabis.shoppersdrugmart.ca/en_CA');

test('select Yes button', async t => {
    const el = Selector('button').withText('Yes');
    await t.wait(2000);
    await t.click(el);
});
```

Command used to run the test by VSCode and the 'TestCafe Test Runner' extension:
```js
cd 'c:\Users\IEUser\Documents\TestCafe Testing'; & 'C:\Program Files\nodejs\node.exe' '--no-deprecation' '--inspect-brk=16173' 'node_modules\testcafe\lib\cli\index.js' 'ie' 'c:\Users\IEUser\Documents\TestCafe Testing\test-script2.js' '--test' 'select Yes button'
```

<summary>Complete test report:</summary>

```
Debugger listening on ws://127.0.0.1:37863/5662344c-d136-49fc-9084-7832f5fcf724
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
 Running tests in:
 - IE 11.0.0 / Windows 10.0.0

 Age Gate
 × select Yes button

   1) Error on page "https://cannabis.shoppersdrugmart.ca/en_CA":

      TypeError: Invalid calling object
         at Ie (http://10.0.2.15:51807/hammerhead.js:10:15306)
         at t.prototype.addClass (http://10.0.2.15:51807/hammerhead.js:8:30687)
         at a.prototype._create (http://10.0.2.15:51807/testcafe-ui.js:1:24683)
         at a.prototype._createBeforeReady (http://10.0.2.15:51807/testcafe-ui.js:1:25184)
         at Anonymous function (http://10.0.2.15:51807/testcafe-ui.js:1:25230)

      Browser: IE 11.0.0 / Windows 10.0.0

         10 |    .page('https://cannabis.shoppersdrugmart.ca/en_CA');
         11 |
         12 |test('select Yes button', async t => {
         13 |    const el = Selector('button').withText('Yes');
         14 |    await t.wait(2000);
       > 15 |    await t.click(el);
         16 |});
         17 |

         at click (C:\Users\IEUser\Documents\TestCafe Testing\test-script2.js:15:13)



 1/1 failed (10s)
Waiting for the debugger to disconnect...
```

When changing the test code to the following:
```js
import { Selector } from 'testcafe';

fixture('Age Gate')
    .page('https://cannabis.shoppersdrugmart.ca/en_CA');

test('select Yes button', async t => {
    const el = Selector('button').withText('Yes');
    if (await el.exists) {
        await t.wait(2000);
        await t.click(el);
    }
});
```
the test doesn't fail, but it stalls due to not finding the button.

### Steps to Reproduce:

1. Save the code given above in a new file
2. Install the dependencies
3. Execute the testcafe command to run the file with IE11
4. See the stalled page
 
### Environment details:
 
* testcafe version: 0.23.3                  
* node.js version: 8.11.3                   
* npm version: 5.6.0
* testcafe-hammerhead version: 14.4.8
* command-line arguments: ie 
* browser name and version: IE 11 
* platform and version: Windows 10

**Comment by Farfurix** [comment]
@alisonhall, 
Thank you for your detailed description. I've reproduced this issue. Our team will research it and find a suitable solution, if any.
