### ISSUE TITLE
useRole does not work in Gitlab CI

### ISSUE THREAD

**Issue by ctmay4** [DevExpress/testcafe#3294]
### What is your Test Scenario?

Attempting to do a simple test of an authenticated user using `useRole`.  Works locally but fails under Gitlab CI.

### What is the Current behavior?
I've written tests which incorporate `useRole` and all work perfectly when run on my local machine.  I followed the instructions at https://devexpress.github.io/testcafe/documentation/continuous-integration/ to run the same tests in Gitlab CI and they fail.  The only failures occur when I try to use roles.  The first time the role is encountered it works passes but all the other tests after that try to use the role fail.

If I manually log for each test they pass.  In other words if I replace all `useRole` instances with the code from the role (i.e. enter user/password and click login) then all the tests pass on Gitlab CI.

If I reorder the tests it is always the first one that passed and after that all fail.  I assume that TestCafe is using cookies to save the authentication and that seems to not work under Gitlab CI.

I've searched through other issues and didn't see anything that looks like it was related to roles and continuous integration.  
 
### What is the Expected behavior?
The tests that work locally should also work under Gitlab CI.
 
### What is your web application and your TestCafe test code?

<details>
<summary>Your complete test code (or attach your test files):</summary>

Here is a simple example:

```js
import {Selector} from 'testcafe';
import roles from '../helpers/roles';
import config from '../helpers/config';

fixture`Home page`
    .page`${config.baseUrl}`;

test('News', async t => {
    await t
        .useRole(roles.userMin)

        .expect(Selector('#news-section > div.section_top > div > div').innerText).contains('Latest News')
});

test('System information popup', async t => {
    await t
        .useRole(roles.userMin)

        // check some of the values of the version popup
        .click("#logo > span.version.dms-link > a")
        .expect(Selector('#info-build-date_label').innerText).contains('Build Date')
        .expect(Selector('#info-build-date').value).match(/\d{2}-\d{2}-\d{4} \d{2}:\d{2}:\d{2}(AM|PM)/)
}); 
```

Here is the role definition I am using:

```js
import {Role, Selector} from 'testcafe';
import config from './config';

const userMin = Role(`${config.baseUrl}`, async t => {
    await t
        .typeText('#username', 'username_for_testing')
        .typeText('#password', 'password_for_testing')
        .click(Selector('button').withExactText('Login'));
});

export default {
    userMin
}
```

Here is my `.gitlab.ci.yml` which is copied directly from the documentation and simplified to only run against Chromuim.  I also tested against firefox:headless and it failed the same way.

```yml
e2e_tests:
  image:
    name: testcafe/testcafe
    entrypoint: ["/bin/sh", "-c"]
  script:
    - /opt/testcafe/docker/testcafe-docker.sh chromium tests/**/*
```

</details>

<details>
<summary>Your complete test report:</summary>

When I run locally this results look like this:

```
> testcafe chrome:headless tests/

 Running tests in:
 - HeadlessChrome 71.0.3578 / Windows 10.0.0

 Home page
 √ News
 √ System information popup


 2 passed (4s)
```

Here is what it looks like when running through Gitlab CI:

```
Checking out 156cd2cc as master...
Skipping Git submodules setup
$ /opt/testcafe/docker/testcafe-docker.sh chromium tests/**/*
 Running tests in:
 - Chrome 68.0.3440 / Linux 0.0.0

 Home page
 ✓ News
 ✖ System information popup

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('#logo > span.version.dms-link > a')

      Browser: Chrome 68.0.3440 / Linux 0.0.0

         15 |test('System information popup', async t => {
         16 |    await t
         17 |        .useRole(roles.userMin)
         18 |
         19 |        // check some of the values of the version popup
       > 20 |        .click("#logo > span.version.dms-link > a")
         21 |
      .expect(Selector('#info-build-date_label').innerText).contains('Build
      Date')
         22 |
      .expect(Selector('#info-build-date').value).match(/\d{2}-\d{2}-\d{4}
      \d{2}:\d{2}:\d{2}(AM|PM)/)
         23 |});
         24 |
         25 |

         at click (/builds/seer/seerdms-testcafe/tests/home.js:20:10)
         at test (/builds/seer/seerdms-testcafe/tests/home.js:15:1)
         at markeredfn
      (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous>
      (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:239:19)
         at TestRun._executeTestFn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:235:38)
         at _executeTestFn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:284:24)



 1/2 failed (48s)
ERROR: Job failed: exit code 1
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   0.23.3
* node.js version:                    v10.14.1
* command-line arguments:  testcafe chrome:headless tests/
* browser name and version: Chrome 71; Chromium 68
* platform and version:          Windows 10 locally and a remote Gitlab CI

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue using Gitlab and the roles mechanism. All tests passed.
![image](https://user-images.githubusercontent.com/1678902/50969625-26f7ee80-14f0-11e9-852b-2d319902072b.png)
Here is my test code:
```JS
import { Role } from 'testcafe';

fixture `fixture`
    .page `https://demos.devexpress.com/RWA/documents/`;

const regularAccUser = Role('https://demos.devexpress.com/RWA/documents/', async t => {
    await t.click('#SignInButton');
}, { preserveUrl: true });

test('test1', async t => {
    await t.useRole(regularAccUser);

    await t.click('.UserMenuItem img');
})

test('test2', async t => {
    await t.useRole(regularAccUser);

    await t.click('.UserMenuItem img');
})

test('test3', async t => {
    await t.useRole(regularAccUser);

    await t.click('.UserMenuItem img');
})

```
And here is my .gitlab-cl.yml file:
```
e2e_tests:
  image:
    name: testcafe/testcafe
    entrypoint: ["/bin/sh", "-c"]
  script:
    - /opt/testcafe/docker/testcafe-docker.sh firefox:headless,chromium test.js
```

Could you please provide us with a link to your website and create a test user to help us reproduce and research the issue?

**Comment by ctmay4** [comment]
Thanks for getting back so quickly.  I tried to run your example above and it doesn't run for me locally or in CI.  It just hangs and never returns.  Not sure why.

However I put together the smallest example I could to show the issue.  I set up a temporary testing user for you to use.

```js
import {ClientFunction, Role, Selector} from 'testcafe';

const getLocation = ClientFunction(() => document.location.href);

fixture`Login page`
    .page`https://demo.seerdms.com/`;

const userMin = Role(`https://demo.seerdms.com/`, async t => {
    await t
        .typeText('#username', 'bug_test')
        .typeText('#password', 'test#1234')
        .click(Selector('button').withExactText('Login'));
});

test('Successful login #1', async t => {
    await t
        .useRole(userMin)
        .expect(getLocation()).contains('/home/home.action')
});

test('Successful login #2', async t => {
    await t
        .useRole(userMin)
        .expect(getLocation()).contains('/home/home.action')
});
```

This works locally:

```
> testcafe chrome:headless tests/

 Running tests in:
 - HeadlessChrome 71.0.3578 / Windows 10.0.0

 Login page
 √ Page elements
 √ Successful login #1
 √ Successful login #2
```

Interestingly enough, now none of the useRole tests work in CI.  I'm not sure why that changes as this is basically the same code simplified.

```
Checking out 0fd42f76 as working-test-case...
Skipping Git submodules setup
$ /opt/testcafe/docker/testcafe-docker.sh firefox:headless,chromium tests/**/*
 Running tests in:
 - Firefox 62.0.0 / Linux 0.0.0
 - Chrome 68.0.3440 / Linux 0.0.0

 Login page
 ✓ Page elements
 ✖ Successful login #1

   1) AssertionError: expected 'https://demo.seerdms.com/' to include
      '/home/home.action'

      Browser: Firefox 62.0.0 / Linux 0.0.0

         19 |});
         20 |
         21 |test('Successful login #1', async t => {
         22 |    await t
         23 |        .useRole(userMin)
       > 24 |        .expect(getLocation()).contains('/home/home.action')
         25 |});
         26 |
         27 |test('Successful login #2', async t => {
         28 |    await t
         29 |        .useRole(userMin)

         at contains (/builds/seer/seerdms-testcafe/tests/login.js:24:32)
         at test (/builds/seer/seerdms-testcafe/tests/login.js:21:1)
         at markeredfn
      (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous>
      (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:239:19)
         at TestRun._executeTestFn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:235:38)
         at _executeTestFn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:284:24)


 ✖ Successful login #2

   1) AssertionError: expected 'https://demo.seerdms.com/' to include
      '/home/home.action'

      Browser: Chrome 68.0.3440 / Linux 0.0.0

         25 |});
         26 |
         27 |test('Successful login #2', async t => {
         28 |    await t
         29 |        .useRole(userMin)
       > 30 |        .expect(getLocation()).contains('/home/home.action')
         31 |});

         at contains (/builds/seer/seerdms-testcafe/tests/login.js:30:32)
         at test (/builds/seer/seerdms-testcafe/tests/login.js:27:1)
         at markeredfn
      (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous>
      (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:239:19)
         at TestRun._executeTestFn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:235:38)
         at _executeTestFn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:284:24)


   2) AssertionError: expected 'https://demo.seerdms.com/' to include
      '/home/home.action'

      Browser: Firefox 62.0.0 / Linux 0.0.0

         25 |});
         26 |
         27 |test('Successful login #2', async t => {
         28 |    await t
         29 |        .useRole(userMin)
       > 30 |        .expect(getLocation()).contains('/home/home.action')
         31 |});

         at contains (/builds/seer/seerdms-testcafe/tests/login.js:30:32)
         at test (/builds/seer/seerdms-testcafe/tests/login.js:27:1)
         at markeredfn
      (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous>
      (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:239:19)
         at TestRun._executeTestFn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:235:38)
         at _executeTestFn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:284:24)



 2/3 failed (47s)
ERROR: Job failed: exit code 2
```

**Comment by ctmay4** [comment]
One other interesting note.  If I change the role to use `preseverUrl: true`, it still works locally, but now Gitlab will succeed with the first `useRole` usage and then hang indefinitely on the second one.

```
Checking out 36c84455 as working-test-case...
Skipping Git submodules setup
$ /opt/testcafe/docker/testcafe-docker.sh firefox:headless,chromium tests/**/*
 Running tests in:
 - Firefox 62.0.0 / Linux 0.0.0
 - Chrome 68.0.3440 / Linux 0.0.0

 Login page
 ✓ Page elements
 ✓ Successful login #1

```

**Comment by ctmay4** [comment]
This seems related to another open issue: #2015.  That issue is marked as closed but I think the bug still exists.  There were a few workarounds mentioned one of which which included not using `useRole`.  Not really a workaround but it does work:

```js
import {ClientFunction, Selector} from 'testcafe';

const getLocation = ClientFunction(() => document.location.href);

fixture`Login page`
    .page`https://demo.seerdms.com/`;

const LoginAsMin = async (t) => {
    await t
        .typeText('#username', 'bug_test')
        .typeText('#password', 'test#1234')
        .click(Selector('button').withExactText('Login'));
};

test('Page elements', async t => {
    await t
        .expect(Selector('#login-form > div.disclaimer').innerText).contains('This information system is made available only for authorized purposes and users.')
        .expect(Selector('#login-form > div.login-version').innerText).match(/IMS, Inc\. v\d+\.\d+/);
});

test('Successful login #1', async t => {
    await LoginAsMin(t);
    await t.expect(getLocation()).contains('/home/home.action')
});

test('Successful login #2', async t => {
    await LoginAsMin(t);
    await t.expect(getLocation()).contains('/home/home.action')
});
```

Here is the Gitlab CI output:

```
Checking out ec757cfc as working-test-case...
Skipping Git submodules setup
$ /opt/testcafe/docker/testcafe-docker.sh firefox:headless,chromium tests/**/*
 Running tests in:
 - Firefox 62.0.0 / Linux 0.0.0
 - Chrome 68.0.3440 / Linux 0.0.0

 Login page
 ✓ Page elements
 ✓ Successful login #1
 ✓ Successful login #2


 3 passed (12s)
Job succeeded
```

That is not really a solution because it removes the ability to use multiple roles in a single test.

**Comment by LavrovArtem** [comment]
@ctmay4, I've reproduced some problem with the `307` redirect on your site. Steps to reproduce:
1. login on site
2. try to load the `https://demo.seerdms.com/` url
3. it redirects with `302` status code to the `http://demo.seerdms.com/home/home.action` url
4. it redirects with `307` status code to the `https://demo.seerdms.com/home/home.action` url

Without Testcafe it works fine, but the Testcafe proxy server hangs out on the resource which should respond with the `307` status code.
I need additional time to investigate this behavior.

**Comment by LavrovArtem** [comment]
I've investigated the problem and figured out that your site uses the [HTTP Strict Transport Security](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) mechanism which our proxy server doesn't support yet. It is unlikely that we will address this limitation in the near future. So, it looks like there is no solution we can offer at the moment.
