### ISSUE TITLE
testcafe live mode fails after first rerun

### ISSUE THREAD

**Issue by joma74** [DevExpress/testcafe#3322]
Rerun in new integrated live mode exits process with failure and stacktrace
```
Warnings (4):
 --
  The file at
  "/home/joma/entwicklung/design/inetingishard/floats/target/reports/screenshots/actual/Index_Page_Test/dom_has_critical_elements/HeadlessChrome_71.0.3578_Linux_0.0.0/scsh_1.png"
  already exists. It has just been rewritten with a recent screenshot. This situation can possibly cause issues. To avoid them,
  make sure that each screenshot has a unique path. If a test runs in multiple browsers, consider including the user agent in
  the screenshot path or generate a unique identifier in another way.
 --
 ...
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at WriteStream.Writable.write (_stream_writable.js:291:5)
    at ReporterPluginHost.write [as newline] (/home/joma/entwicklung/design/inetingishard/floats/node_modules/testcafe/src/reporter/plugin-host.js:108:22)
    at ReporterPluginHost.reportTaskDone (/home/joma/entwicklung/design/inetingishard/floats/node_modules/testcafe-reporter-xunit/lib/index.js:84:67)
    at reportTaskDone (/home/joma/entwicklung/design/inetingishard/floats/node_modules/testcafe/src/reporter/index.js:176:31)
    at Generator.next (<anonymous>)
    at step (/home/joma/entwicklung/design/inetingishard/floats/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/joma/entwicklung/design/inetingishard/floats/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/joma/entwicklung/design/inetingishard/floats/node_modules/core-js/library/modules/_export.js:36:28)
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at WriteStream.Writable.write (_stream_writable.js:291:5)
    at ReporterPluginHost.write [as newline] (/home/joma/entwicklung/design/inetingishard/floats/node_modules/testcafe/src/reporter/plugin-host.js:108:22)
    at ReporterPluginHost.reportTaskDone (/home/joma/entwicklung/design/inetingishard/floats/node_modules/testcafe-reporter-xunit/lib/index.js:84:67)
    at reportTaskDone (/home/joma/entwicklung/design/inetingishard/floats/node_modules/testcafe/src/reporter/index.js:176:31)
    at Generator.next (<anonymous>)
    at step (/home/joma/entwicklung/design/inetingishard/floats/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/joma/entwicklung/design/inetingishard/floats/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/joma/entwicklung/design/inetingishard/floats/node_modules/core-js/library/modules/_export.js:36:28)
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at WriteStream.Writable.write (_stream_writable.js:291:5)
    at ReporterPluginHost.write [as newline] (/home/joma/entwicklung/design/inetingishard/floats/node_modules/testcafe/src/reporter/plugin-host.js:108:22)
    at ReporterPluginHost.reportTaskDone (/home/joma/entwicklung/design/inetingishard/floats/node_modules/testcafe-reporter-xunit/lib/index.js:84:67)
    at reportTaskDone (/home/joma/entwicklung/design/inetingishard/floats/node_modules/testcafe/src/reporter/index.js:176:31)
    at Generator.next (<anonymous>)
    at step (/home/joma/entwicklung/design/inetingishard/floats/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/joma/entwicklung/design/inetingishard/floats/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/joma/entwicklung/design/inetingishard/floats/node_modules/core-js/library/modules/_export.js:36:28)
error Command failed with exit code 1.
```

### What is your Test Scenario?
develop in live mode
 
### What is the Current behavior?
fails after first rerun
 
### What is the Expected behavior?
no failure after first rerun
 
### What is your web application and your TestCafe test code?

https://github.com/joma74/inetingishard-floats/commits/testcafelivemodefails

https://github.com/joma74/inetingishard-floats/blob/7303517c1652f69df4aa3b85e8578ede6d90c3a5/src/tests/index-test.js

### Steps to Reproduce:

1. `yarn install`
2. first terminal  `yarn run start`
3. second terminal `yarn run testcafe-live`
4. test failures are expected(as of now :flushed:)
5. Press CTRL-r
6. Process exits with failure and stacktrace
 
### Your Environment details:
 
* testcafe version:                   1.0.0-alpha.2
* node.js version:                    10.13.0
* command-line arguments:  testcafe 'firefox:headless,chrome:headless --no-sandbox --disable-gpu' -L -S -s $npm_package_config_screenshots -p $npm_package_config_screenshot_path_pattern -r spec,xunit:$npm_package_config_reports/report.xml src/tests/index-test.js
* browser name and version: Chrome 71.0.3578.98-1 Firefox 64.0+build3-0ubuntu0.16.04.1
* platform and version:         Ubuntu 16.04.5 LTS
* other:

**Comment by joma74** [comment]
Can you also make up a configuration for the presence of above logs of warnings? While technically and DX-related totally sensible, maybe a certain log filter level (screenshottaker.fileoverwrite.occured=OFF) set via config/env or cli helps in reducing terminal distraction.

**Comment by joma74** [comment]
As i see it now - removing xunit reporter(cause of above failure) in testcafe-live mode  is a viable solution for me. 

P.S. After short testing, integrated Live Mode works stable. Only that is does not catch up changes to my index-test.js file. Have to do manually CTRL + r.

**Comment by joma74** [comment]
Hey @Farfurix, hope i have things sorted out. It's the Windows OS :smile: vs Unix(my bread and butter OS), with all their beautiful different path separators, among other things. As in the regex of webpack config - which is still strict webpack 3 - describing a file path to exclude the acitvition of a plugin, which resulted in the above error.

I tested under Windows 10, although only inside git bash. Which i must call out for as a prerequisite to use the application. Any other than this, i expect the application to run with the commands described above. I can still see the error.

******

P.S. I spent a good part of my free time the last days to get this build run on windows on travis. That offer is in beta and around since October 2018(Windows Server 2016, shell is git bash). Learned Firefox as addon is not supported, but  may be installed via chocolatery, so i thought i woudl give it a go. But i cant get the Windows build to run. Always ended with
> ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
as in https://travis-ci.org/joma74/inetingishard-floats/jobs/483337236

I think i narrowed it down to firefox. chrome only build was successful. If you hear of any "me also" or otherwise success stories about Travis Windows with firefox, leave me a note.

_Sidestep - perhaps you can define above ERROR Unable to establish message more clearly if it's FF or chrome browser connection? Or maybe run a  report on the good ones, but fail the overall result?_
