### ISSUE TITLE
Tests starts to fail after page model moved to separate NPM package

### ISSUE THREAD

**Issue by mt0erfztxt** [DevExpress/testcafe#3526]
### What is your Test Scenario?

I use page model pattern for tests and all models are extended from base model provided as a separate package. During initial development I work through using of package linking (`npm link`) and all works, but a few days ago I published base model [package on npmjs.com](https://www.npmjs.com/package/nebula-test-fragment) and when I use it my tests start to fail with error `Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead.` During pinpointing cause of issue I found that same error occurs also in linked package setup but only when `babel` compiled version is used - `main` in [package.json](https://github.com/mt0erfztxt/nebula-test-fragment/blob/master/package.json#L11) set to `lib/index.js` opposed to `src/index.js`.
 
### What is the Current behavior?

Tests fails with error above.
 
### What is the Expected behavior?

Tests successfully completed.
 
### What is your web application and your TestCafe test code?

1. GitHub [repo](https://github.com/mt0erfztxt/nebula-test-fragment) with base page model
2. GitHub [repo](https://github.com/mt0erfztxt/nebula-widgets/tree/feature/use-npm-published-fragment) with app and page models that extends base page model. Page model used in tests for this issue can be found in this [file](https://github.com/mt0erfztxt/nebula-widgets/blob/feature/use-npm-published-fragment/src/js/widgets/checkable-input/index.js)
3. tests used for this issue can be found in this [file](https://github.com/mt0erfztxt/nebula-widgets/blob/feature/use-npm-published-fragment/test/js/browser/fragments/input/010-fragment.js)

<details>
<summary>One of failed tests:</summary>

 
```js
 // Below is one of failed tests (copied from file seen at point 3 in paragraph above, but
 // here I deleted some comments intentionally as they might lead to some misunderstanding
 // because usually I have tests that my models fails in expected cases.
 test("020 It should allow assert on whether input is disabled using '#expectIsDisabled()'", async () => {
  const { knob, sut } = await getHelperFragments('disabled');

  await knob.clickItem({ value: 'true' });
  await sut.hover();
  await sut.expectIsDisabled();

  await knob.clickItem({ value: 'false' });
  await sut.hover();

  let isThrown = false;

  try {
    await sut.expectIsDisabled();
  }
  catch (e) {
    expect(
      e.errMsg,
      'to match',
      /AssertionError:.+\.checkable-input.+must have BEM modifier 'disabled,'.+but it doesn't/
    );

    isThrown = true;
  }

  expect(isThrown, 'to be true');
});
```
</details>

<details>
<summary>Complete test report:</summary>

```
Using locally installed version of TestCafe.
 Running tests in:
 - Chromium 71.0.3578 / Ubuntu 0.0.0

 Widgets :: Input :: 010 Fragment
 ✓ 010 It should allow get input's 'Disabled' part of state using '#getDisabledPartOfState()'
 ✖ 020 It should allow assert on whether input is disabled using '#expectIsDisabled()'

   1) Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead.

      Browser: Chromium 71.0.3578 / Ubuntu 0.0.0

         414 |      .cloneBemBase()
         415 |      .setMod(bemModifier)
         416 |      .toString();
         417 |
         418 |    await t
       > 419 |      .expect(this.selector.hasClass(className))
         420 |      .ok(
         421 |        `'${this.displayName}' fragment must have BEM modifier ` +
         422 |        `'${bemModifier}' (${className}) but it doesn't`
         423 |      );
         424 |  }

         at CheckableInput.expect [as expectHasBemModifier] (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:419:8)
         at CheckableInput.expectExistsAndConformsRequirements (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:338:15)


 ✖ 030 It should allow assert on whether input isn't disabled using '#expectIsNotDisabled()'

   1) Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead.

      Browser: Chromium 71.0.3578 / Ubuntu 0.0.0

         437 |    const className = this
         438 |      .cloneBemBase()
         439 |      .setMod(bemModifier);
         440 |
         441 |    await t
       > 442 |      .expect(this.selector.hasClass(className.toString()))
         443 |      .notOk(
         444 |        `'${this.displayName}' fragment must not have BEM modifier ` +
         445 |        `'${bemModifier}' (${className}) but it does`
         446 |      );
         447 |  }

         at CheckableInput.expect [as expectHasNoBemModifier] (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:442:8)
         at CheckableInput.expectExistsAndConformsRequirements (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:338:15)


 ✖ 040 It should allow assert on whether input is enabled using '#expectIsEnabled()'

   1) Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead.

      Browser: Chromium 71.0.3578 / Ubuntu 0.0.0

         437 |    const className = this
         438 |      .cloneBemBase()
         439 |      .setMod(bemModifier);
         440 |
         441 |    await t
       > 442 |      .expect(this.selector.hasClass(className.toString()))
         443 |      .notOk(
         444 |        `'${this.displayName}' fragment must not have BEM modifier ` +
         445 |        `'${bemModifier}' (${className}) but it does`
         446 |      );
         447 |  }

         at CheckableInput.expect [as expectHasNoBemModifier] (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:442:8)
         at CheckableInput.expectExistsAndConformsRequirements (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:338:15)


 ✖ 050 It should allow assert on whether input isn't enabled using '#expectIsNotEnabled()'

   1) Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead.

      Browser: Chromium 71.0.3578 / Ubuntu 0.0.0

         414 |      .cloneBemBase()
         415 |      .setMod(bemModifier)
         416 |      .toString();
         417 |
         418 |    await t
       > 419 |      .expect(this.selector.hasClass(className))
         420 |      .ok(
         421 |        `'${this.displayName}' fragment must have BEM modifier ` +
         422 |        `'${bemModifier}' (${className}) but it doesn't`
         423 |      );
         424 |  }

         at CheckableInput.expect [as expectHasBemModifier] (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:419:8)
         at CheckableInput.expectExistsAndConformsRequirements (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:338:15)


 ✓ 060 It should allow get input's 'Invalid' part of state using '#getInvalidPartOfState()'
 ✖ 070 It should allow assert on whether input is invalid using '#expectIsInvalid()'

   1) Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead.

      Browser: Chromium 71.0.3578 / Ubuntu 0.0.0

         414 |      .cloneBemBase()
         415 |      .setMod(bemModifier)
         416 |      .toString();
         417 |
         418 |    await t
       > 419 |      .expect(this.selector.hasClass(className))
         420 |      .ok(
         421 |        `'${this.displayName}' fragment must have BEM modifier ` +
         422 |        `'${bemModifier}' (${className}) but it doesn't`
         423 |      );
         424 |  }

         at CheckableInput.expect [as expectHasBemModifier] (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:419:8)
         at CheckableInput.expectExistsAndConformsRequirements (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:338:15)


 ✖ 080 It should allow assert on whether input isn't invalid using '#expectIsNotInvalid()'

   1) Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead.

      Browser: Chromium 71.0.3578 / Ubuntu 0.0.0

         437 |    const className = this
         438 |      .cloneBemBase()
         439 |      .setMod(bemModifier);
         440 |
         441 |    await t
       > 442 |      .expect(this.selector.hasClass(className.toString()))
         443 |      .notOk(
         444 |        `'${this.displayName}' fragment must not have BEM modifier ` +
         445 |        `'${bemModifier}' (${className}) but it does`
         446 |      );
         447 |  }

         at CheckableInput.expect [as expectHasNoBemModifier] (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:442:8)
         at CheckableInput.expectExistsAndConformsRequirements (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:338:15)


 ✖ 090 It should allow assert on whether input is valid using '#expectIsValid()'

   1) Cannot implicitly resolve the test run in the context of which the test controller action should be executed. Use test function's 't' argument instead.

      Browser: Chromium 71.0.3578 / Ubuntu 0.0.0

         437 |    const className = this
         438 |      .cloneBemBase()
         439 |      .setMod(bemModifier);
         440 |
         441 |    await t
       > 442 |      .expect(this.selector.hasClass(className.toString()))
         443 |      .notOk(
         444 |        `'${this.displayName}' fragment must not have BEM modifier ` +
         445 |        `'${bemModifier}' (${className}) but it does`
         446 |      );
         447 |  }

         at CheckableInput.expect [as expectHasNoBemModifier] (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:442:8)
         at CheckableInput.expectExistsAndConformsRequirements (/home/mt0erfztxt/Downloads/nebula-widgets-feature-use-npm-published-fragment/node_modules/nebula-test-fragment/src/base-fragment.js:338:15)



 7/9 failed (16s)
```
</details>

### Steps to Reproduce:

Because app under testing is built using Clojure it requires additional tooling (not available from NPM) to be built, I provide pre-built app in attached file [nebula-widgets-feature-use-npm-published-fragment.zip](https://github.com/DevExpress/testcafe/files/2928030/nebula-widgets-feature-use-npm-published-fragment.zip).
1. extract attached archive
2. `cd` into directory from extracted archive, run command `npm install && npx grunt kitchenSink:prod:run` in terminal and wait until greeting from server appears
```
Serving!
- Local:            http://localhost:3449
...
```
4. optionally, open http://localhost:3449/ in browser
5. in another terminal in same directory run command `testcafe chromium test/js/browser/fragments/input/010-fragment.js -T '^0\d0'`

 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    v8.12.0
* command-line arguments:  testcafe chromium test/js/browser/fragments/input/010-fragment.js -T '^0\d0'
* browser name and version: Chromium 71.0
* platform and version:          Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)
* other: I tried solution from issue #3424 but it doesn't work for me

**Comment by miherlosev** [comment]
Hi @mt0erfztxt 

I could not reproduce the problem.
When the test navigates to the target page, it gets the 404 HTTP error.

![image](https://user-images.githubusercontent.com/4133518/53806478-231ba200-3f5e-11e9-8972-2755d27a794b.png)

Please correct the example and feel free to reopen this issue.

**Comment by mt0erfztxt** [comment]
Hi @miherlosev 

I re-check steps to reproduce problem and don't get 404 HTTP error. I attach recording of problem reproduction on my system - can you please check whether you done it same way.

Attachment: [cinnamon-20190305-14.webm.zip](https://github.com/DevExpress/testcafe/files/2931891/cinnamon-20190305-14.webm.zip)

**Comment by miherlosev** [comment]
I've reproduced the problem.

**Comment by AndreyBelym** [comment]
The problem caused by native `async` functions used in your page model. The test controller must be called in a stack trace that contains a test body signature. `setTimeout`/`clearInterval`, `Promise`s and `async` functions create a new clean stack frame, so the test controller can't find a test body signature resolve a test context when used in this constructs.

You can add `"babel-runtime": "^6.22.2"` to the "dependencies" field of your page model's `package.json` and compile it with the following `.babelrc` as a workaround:
```json
{
  "presets": 
    [
      [ { "plugins": "transform-runtime" } ],
      ["env"]
    ]
  ,
  "sourceMaps": "inline"
}
```

This `babel` configuration transforms `async` functions to synchronous state machines that preserve stack frames.

**Comment by mt0erfztxt** [comment]
Thank you for pointing me in right direction. Tests now work with following `.babelrc`:
```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "esmodules": true
        }
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ],
  "sourceMaps": "inline"
}
```
In my case `"esmodules": true` was mandatory, otherwise errors like `TypeError: Class constructor GroupInput cannot be invoked without 'new'` were thrown.

**Comment by Farfurix** [comment]
@mt0erfztxt, we are happy to hear that the problem is solved. If you have other questions related to this issue, feel free to reopen it.
