### ISSUE TITLE
Cookies get cleared unexpectedly

### ISSUE THREAD

**Issue by tronza** [DevExpress/testcafe#3583]
### What is your Test Scenario?
Cookies get cleared unexpectedly during a test execution.

### What is the Current behavior?
I have a test that visits a domain that generates a cookie. Then I press the browser's back-button to go back to the domain where I initiated the test and then the forward-button. Previously generated cookie was now deleted and new one was created.
 
### What is the Expected behavior?
Cookies should persist during one test case between different domains.
 
### What is your web application and your TestCafe test code?
The "app", i.e. `example.html`. Can be run with `php -S localhost:8880 example.html`.
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Example for cookies</title>
    <script>
      window.onload = function() {
        // Check whether the cookie already exists.
        if (document.cookie.indexOf('myLittleCookie=') === -1) {
          // If cookie does not exist, make a new one.
          document.cookie = 'myLittleCookie=' + Date.now();
        }
      };
    </script>
  </head>
  <body>
  </body>
</html>
```

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```typescript
import { ClientFunction, t } from 'testcafe';

const cookieGet = ClientFunction(() => document.cookie);
const browserBackButton = ClientFunction(() => window.history.back());
const browserForwardButton = ClientFunction(() => window.history.forward());

fixture(`test`).page('https://www.devexpress.com/');

test('Cookie is maintained', async () => {
  await t.navigateTo('http://localhost:8880');

  const cookies = await cookieGet();

  await t.expect(cookies).contains('myLittleCookie');

  await browserBackButton();
  await browserForwardButton();

  await t.expect(cookieGet()).eql(cookies); // will fail
});
```
</details>

<details>
<summary>Test report:</summary>

```

$ npx testcafe chrome example.ts
Running tests in:
 - Chrome 72.0.3626 / Mac OS X 10.14.0

 test
 ✖ Cookie is maintained

   1) AssertionError: expected 'myLittleCookie=1552999991089' to deeply equal 'myLittleCookie=1552999989235'

      Browser: Chrome 72.0.3626 / Mac OS X 10.14.0

         17 |  await t.expect(cookies).contains('myLittleCookie');
         18 |
         19 |  await browserBackButton();
         20 |  await browserForwardButton();
         21 |
       > 22 |  await t.expect(cookieGet()).eql(cookies); // will fail
         23 |});
         24 |

         at Object.<anonymous> (/Users/ay52259/projects/fcom-checkout/tests/browser/src/example.ts:22:31)
         at fulfilled (/Users/ay52259/projects/fcom-checkout/tests/browser/src/example.ts:4:58)

 1/1 failed (10s)
```

</details>

### Steps to Reproduce:
1. Make a `example.html`
2. Run it with for example `php -S localhost:8880 example.html`
3. Make a `example.ts`
4. Run `npx testcafe chrome example.ts`
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    v8.10.0
* command-line arguments:  npx testcafe chrome example.ts
* browser name and version: Chrome 72.0.3626
* platform and version:           Mac OS X 10.14.0
* other:                                     TypeScript 3.3.3333

**Comment by AlexKamaev** [comment]
Thank you for the detailed project. I was able to reproduce the issue. The cause of the problem is unclear so we need to research it. I also found that using `await t.navigateTo('http://localhost:8880')` instead of `await browserForwardButton()` fixes the issue, so I recommend you use this command as a workaround while we are working on the issue.

**Comment by AlexKamaev** [comment]
I've researched the issue in detail and found that the cause of the issue is a browser cache which prevents cookies to load correctly. It's TestCafe specifics however, it can not be solved easily, so I can not give any estimates on it. I found that the test works if when browser cache is disabled in Chrome Developer Tools Network tab.
I recommend using the `navigateTo` method, since it works stably. However, if you still want to use your `history` functions you can also use the following approach:
```JS
test('Cookie is maintained', async t => {
    const bc  = t.testRun.browserConnection;
    const cdp = bc.provider.plugin.openedBrowsers[bc.id];
    await cdp.client.Network.setCacheDisabled({ cacheDisabled: true });

    await t.navigateTo('http://localhost:8080);
    const cookies = await cookieGet();
    await t.expect(cookies).contains('myLittleCookie');
    await browserBackButton();
    await browserForwardButton();

    await t.expect(cookieGet()).eql(cookies); // will fail
});

```
Here I use the [Chrome Debug Protocol](https://chromedevtools.github.io/devtools-protocol/) object to prevent browser caching at runtime. Please note, that this workaround uses a private API, which can be changed in the future.
