### ISSUE TITLE
Wrong response body content encoding

### ISSUE THREAD

**Issue by prubiellajoyners** [DevExpress/testcafe#3596]
### What is your Test Scenario?

 I'm trying to test a credit card payment process. So I log the request with a RequestLogger
### What is the Current behavior?

 When te request and it's response are logged, I can see request body is properly encoded and stringified but not the response body, instead of returning a json it returns weird characters.
```
response: 
   { statusCode: 200,
     headers: 
      { date: 'Thu, 21 Mar 2019 14:57:49 GMT',
        server: 'Apache/2.4.25 (Debian)',
        'set-cookie': [Array],
        expires: 'Thu, 19 Nov 1981 08:52:00 GMT',
        'cache-control': 'no-store, no-cache, must-revalidate',
        pragma: 'no-cache',
        'x-debug-tag': '5c93a66dedf68',
        'x-debug-duration': '319',
        'x-debug-link': 'http://local.joyners.com/debug/default/view?tag=5c93a66dedf68&language=en',
        vary: 'Accept-Encoding',
        'content-encoding': 'gzip',
        'x-frame-options': 'deny',
        'x-content-type-options': 'nosniff',
        'x-xss-protection': '1;mode=block',
        'content-length': '99',
        'keep-alive': 'timeout=5, max=100',
        connection: 'Keep-Alive',
        'content-type': 'text/html; charset=UTF-8' },
     body: '\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0003\u0015�;\n�@\f\u0005��<R)X��v\u0016\u001e$$qw�\u000f$Z�wWˁ�).\u0011����\u001a�����Q�i��\u001f�C�r7\u0005��=�,\u0006�\\O\b�����0�cK�\u000b��N\u0018W\u0000\u0000\u0000' } }

```

### What is the Expected behavior?

 RequestLogger should stringify with the right encoding and return a json string. like this:
```
{"success":false,"message":"An error has occurred adding the credit card (Error: 101)"}
```
### What is your web application and your TestCafe test code?

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 const logger = RequestLogger(/save-addon-response/, {
// const logger = RequestLogger('*', {
    logResponseHeaders: true ,
    logResponseBody: true,
    stringifyResponseBody: true,
    logRequestHeaders: true,
    logRequestBody: true,
    stringifyRequestBody: true,

});

fixture`Owner Payments`
    .page(config.params.path.webapp)
    .requestHooks(logger);

test('Owner - Add credit card Addon Denied', async t => {
    await config.methods.ownerLogin()
    // Go to Settings and Payments
    await t
        .click('a[href="#user/profile"]')
        .expect(Selector('h1[class="title"]').innerText).notEql('')
        .wait(500)
        .click('input[type="radio"][name="form-profile-payment_method"][value="credit_card"]')
        // Go to Add/modify cards, Add a card in AddonPayments
        .click('a[href="javascript:APP.router.navigate(\'credit-cards\')"]');

    // open lightbox and add credit card
    await t
        .click('a[id="owner-credit-card-new"]')
        .switchToIframe(Selector('iframe[seamless="seamless"]'))
            .expect(Selector('input#pas_ccnum').value).eql('')
            .wait(500)
            .typeText('input[id="pas_ccnum"]', config.params.owner.tpv.addon.visa.cardKo102)
            .expect(Selector('input#pas_ccnum').value).notEql('')
            .expect(Selector('input#pas_expiry').value).eql('')
            .wait(500)
            .typeText('input[id="pas_expiry"]', config.params.owner.tpv.addon.visa.expiresMonth+config.params.owner.tpv.addon.visa.expiresYear)
            .expect(Selector('input#pas_expiry').value).notEql('')
            .expect(Selector('input#pas_cccvc').value).eql('')
            .wait(500)
            .typeText('input[id="pas_cccvc"]', config.params.owner.tpv.addon.visa.cvv)
            .expect(Selector('input#pas_cccvc').value).notEql('')
            .expect(Selector('input#pas_ccname').value).eql('')
            .wait(500)
            .typeText('input[id="pas_ccname"]', config.params.owner.tpv.addon.visa.name)
            .expect(Selector('input#pas_ccname').value).notEql('')
            .click('button#rxp-primary-btn')
        .switchToMainWindow()
        .wait(2000);
    console.log(logger.requests[0]);
    await t
        .expect(JSON.parse(logger.requests[0].response.body).success ).eql(false)
        .expect(logger.requests[0].response.statusCode ).eql(200);

});
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```
1) SyntaxError: Unexpected token  in JSON at position 0

      Browser: Chrome 73.0.3683 / Linux 0.0.0

          98 |            .click('button#rxp-primary-btn')
          99 |        .switchToMainWindow()
         100 |        .wait(2000);
         101 |    console.log(logger.requests[0]);
         102 |    await t
       > 103 |        .expect(JSON.parse(logger.requests[0].response.body).success ).eql(false)
         104 |        .expect(logger.requests[0].response.statusCode ).eql(200);
         105 |
         106 |});
         107 |

         at parse (/var/www/joyners-web/tests/testcafe/app-owner-payments-addon.js:103:22)
         at $$testcafe_test_run$$painoYyYa$$ (/usr/lib/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
         at $$testcafe_test_run$$painoYyYa$$ (/usr/lib/node_modules/testcafe/src/api/test-run-tracker.js:76:16)



 1/1 failed (17s)

```
</details>

### Steps to Reproduce:

1. just execute the basic testcafe command on chrome browser and will fail when trying to parse the response. 
2. when done manually in my browser, the response is well parsed. 
### Your Environment details:
 
* testcafe version:                   `1.1.0`
* node.js version:                    `8.15.1`
* command-line arguments:  `testcafe "chrome -incognito" tests/testcafe/app-owner-payments-addon.js
`
* browser name and version: `Chrome 73.0.3683 / Linux 0.0.0`
* platform and version:          `Debian 9`
* other:                                   doesn't matter if it's executed with incognito mode or not. always fails. but in browser it's decoding fine when I debug it.

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. It's a duplicate of https://github.com/DevExpress/testcafe/issues/3243. Take a look at the response headers. The `'content-encoding': 'gzip'` header means that the response body is compressed. TestCafe's request hooks don't support logging and mocking compressed responses yet.
