### ISSUE TITLE
unable to open the browser "locally-installed:edge" due to error.

### ISSUE THREAD

**Issue by mledour** [DevExpress/testcafe#3649]
Hi,

I'm trying to run tescafe on a windows vps with ssh over cygwin.
The tests pass when i'm connected whith RDP but fail without.

Here is the error:
```js
C:\cygwin64\home\mledour\builds\tWovsUbr\0\mledour2\brennus\node_modules\.bin\testcafe edge e2e/**/**.spec.ts --app "yarn start" --app-init-delay 40000
ERROR Was unable to open the browser "locally-installed:edge" due to error.

Error: Unable to run the browser. The file at undefined does not exist or is not executable.
    at Object.callee$0$0$ (C:\cygwin64\home\mledour\builds\tWovsUbr\0\mledour2\brennus\node_modules\testcafe-browser-tools\lib\api\open.js:137:23)
    at tryCatch (C:\cygwin64\home\mledour\builds\tWovsUbr\0\mledour2\brennus\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at Generator.invoke [as _invoke] (C:\cygwin64\home\mledour\builds\tWovsUbr\0\mledour2\brennus\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at Generator.prototype.(anonymous function) [as throw] (C:\cygwin64\home\mledour\builds\tWovsUbr\0\mledour2\brennus\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at tryCatch (C:\cygwin64\home\mledour\builds\tWovsUbr\0\mledour2\brennus\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at invoke (C:\cygwin64\home\mledour\builds\tWovsUbr\0\mledour2\brennus\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:146:20)
    at C:\cygwin64\home\mledour\builds\tWovsUbr\0\mledour2\brennus\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:156:13
```

Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    v11.13.0
* command-line arguments:  yarn testcafe edge e2e/**/**.spec.ts --app "yarn start" --app-init-delay 40000
* browser name and version: edge
* platform and version:          windows 10

**Comment by Farfurix** [comment]
@mledour 

Hello.

As stated in [this thread](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11041291/), "All Universal Windows Platforms require a user session to be running to work. As WebDriver uses Edge, it also requires this".

I suggest you use [this solution](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11041291/#comment-1).

This inquiry also looks like a question that would be best asked on [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
