### ISSUE TITLE
Clicking on a custom element within a custom element does not work

### ISSUE THREAD

**Issue by craigjennings11** [DevExpress/testcafe#3653]
### What is your Test Scenario?
Click on a custom element within a custom element
 
### What is the Current behavior?
Nothing happens
 
### What is the Expected behavior?
Click event is fired
 
### What is your web application and your TestCafe test code?
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">

  <script>
    const myButtonTemplate = document.createElement('template');
    myButtonTemplate.innerHTML = `
      <style>
        :host { display: inline-block; }
      </style>

      <button>
        <slot></slot>
      </button>
    `;

    const mySubButtonTemplate = document.createElement('template');
    mySubButtonTemplate.innerHTML = `
      <style>
        :host { display: block; }
      </style>

      <div>Custom Element Scenario</div>
    `;

    class MyButton extends HTMLElement {
      constructor() {
        super();

        this.attachShadow({ mode: 'open' });
      }

      connectedCallback() {
        const content = myButtonTemplate.content.cloneNode(true);

        this.shadowRoot.appendChild(content);
      }
    }

    class MySubButton extends HTMLElement {
      constructor() {
        super();

        this.attachShadow({ mode: 'open' });
      }

      connectedCallback() {
        const content = mySubButtonTemplate.content.cloneNode(true);

        this.shadowRoot.appendChild(content);
      }
    }

    window.customElements.define('my-button', MyButton);
    window.customElements.define('my-sub-button', MySubButton);
  </script>
  <title>TestCafé</title>
</head>

<body>
  <my-button>Basic Scenario</my-button>

  <my-button>
    <my-sub-button></my-sub-button>
  </my-button>

  <script>
    const myButton = document.querySelectorAll('my-button');

    myButton[0].addEventListener('click', () => {
      const div = document.createElement('div');
      div.className = 'clicked-basic';
      div.innerText = 'Basic scenario clicked';

      document.body.append(div);
    });

    myButton[1].addEventListener('click', () => {
      const div = document.createElement('div');
      div.className = 'clicked-custom';
      div.innerText = 'Custom element scenario clicked';

      document.body.append(div);
    });
  </script>
</body>
</html>
```

```js
import { Selector } from 'testcafe';

fixture`My Fixture`
  .page`http://127.0.0.1:8080`;

test('My Test', async (t) => {
  const basicScenario = Selector('.clicked-basic');
  const customElementScenario = Selector('.clicked-custom');
  const customElementButton = Selector('my-button');

  await t
    .click(customElementButton.nth(0))
    .expect(basicScenario.exists).ok()
    .click(customElementButton.nth(1))
    .expect(customElementScenario.exists).ok();
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Running tests in:
 - Chrome 73.0.3683 / Windows 10.0.0

 My Fixture
 × My Test

   1) AssertionError: expected false to be truthy

      Browser: Chrome 73.0.3683 / Windows 10.0.0

         10 |
         11 |  await t
         12 |    .click(customElementButton.nth(0))
         13 |    .expect(basicScenario.exists).ok()
         14 |    .click(customElementButton.nth(1))
       > 15 |    .expect(customElementScenario.exists).ok();
         16 |});
         17 |

         at ok (C:\github\wishlist\test.spec.js:15:43)
         at test (C:\github\wishlist\test.spec.js:6:1)
         at markeredfn (C:\github\wishlist\node_modules\testcafe\src\api\wrap-test-function.js:17:28)
         at <anonymous> (C:\github\wishlist\node_modules\testcafe\src\api\wrap-test-function.js:7:5)
         at fn (C:\github\wishlist\node_modules\testcafe\src\test-run\index.js:240:19)
         at LiveModeTestRun._executeTestFn
      (C:\github\wishlist\node_modules\testcafe\src\test-run\index.js:236:38)
         at _executeTestFn (C:\github\wishlist\node_modules\testcafe\src\test-run\index.js:289:24)



 1/1 failed (6s)
```
</details>

<details>
<summary>Screenshots:</summary>
Manually clicking on buttons:

![image](https://user-images.githubusercontent.com/1683368/55733493-86787400-59e3-11e9-8580-e439490bf496.png)

After a testcafe run:

![image](https://user-images.githubusercontent.com/1683368/55733145-ecb0c700-59e2-11e9-9c1f-bba08a38e4f9.png)
</details>

### Your Environment details:
 
* testcafe version:                   1.1.1
* node.js version:                    8.15.1
* command-line arguments:  testcafe chrome test.spec.js
* browser name and version: Chrome 73
* platform and version:          Windows 10

**Comment by AlexKamaev** [comment]
This issue was fixed with this PR — [https://github.com/DevExpress/testcafe-hammerhead/pull/2262](https://github.com/DevExpress/testcafe-hammerhead/pull/2262)
Please update to the latest TestCafe version.
