### ISSUE TITLE
Salesforce custom lightning components not visible to testcafe

### ISSUE THREAD

**Issue by blokeefe** [DevExpress/testcafe#3727]
### What is your Test Scenario?
Login to Salesforce and interact with any custom lightning component.
 
### What is the Current behavior?
No custom lightning components appear to be visible to testcafe
 
### What is the Expected behavior?
testcafe should be able to interact with custom lightning components just like a user in browser
 
### What is your web application and your TestCafe test code?
Salesforce
 
Your website URL (or attach your complete example):
![custom_lightning_component_in_testcafe](https://user-images.githubusercontent.com/5287694/56438984-a9900700-62b2-11e9-8144-5e44c15ff7ba.jpg)
![custom_lightning_component_in_browser](https://user-images.githubusercontent.com/5287694/56438985-a9900700-62b2-11e9-813d-f9cb8759b2dd.jpg)

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
import { Selector } from 'testcafe'; 

fixture`Custom Lightning Component issue`// declare the fixture
    .page`https://brave-bear-e42cd9-dev-ed.my.salesforce.com/`;  // specify the start page

test('Lightning Component', async t => {
    await t
        .typeText('#username','watkinssf@brave-bear-e42cd9.com')
       .typeText('#password','Password1234')
        .click('#Login')
        .click('.slds-icon-waffle')
        .click(Selector('ul li a span .label.slds-truncate.slds-text-link').withText('Accounts'))
        .click(Selector('.slds-truncate.outputLookupLink.slds-truncate.forceOutputLookup').withText('United Oil & Gas Corp.'))
        .expect(Selector('div.slds-card__body div').innerText).contains('Hello I\'m a custom lightning component')
}); 

</details>

<details>
<summary>

```
</summary>

```
✖ Lightning Component

   1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

       > | Selector('div.slds-card__body div')

      Browser: Chrome 73.0.3683 / Mac OS X 10.14.4

          9 |        .typeText('#password','Password1234')
         10 |        .click('#Login')
         11 |        .click('.slds-icon-waffle')
         12 |        .click(Selector('ul li a span .label.slds-truncate.slds-text-link').withText('Accounts'))
         13 |        .click(Selector('.slds-truncate.outputLookupLink.slds-truncate.forceOutputLookup').withText('United Oil & Gas Corp.'))
       > 14 |        .expect(Selector('div.slds-card__body div').innerText).contains('Hello I\'m a custom lightning component')
         15 |        .debug()
         16 |});

         at Object.<anonymous> (/Users/brian.okeefe/Projects/DevExpress-TestCafe/e2e/tests/lightning_comp_test.ts:14:64)
         at <anonymous> (/Users/brian.okeefe/Projects/DevExpress-TestCafe/e2e/tests/lightning_comp_test.ts:7:71)
         at __awaiter (/Users/brian.okeefe/Projects/DevExpress-TestCafe/e2e/tests/lightning_comp_test.ts:3:12)
         at test (/Users/brian.okeefe/Projects/DevExpress-TestCafe/e2e/tests/lightning_comp_test.ts:6:39)
         at markeredfn (/usr/local/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous> (/usr/local/lib/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn (/usr/local/lib/node_modules/testcafe/src/test-run/index.js:242:19)
         at TestRun._executeTestFn (/usr/local/lib/node_modules/testcafe/src/test-run/index.js:238:38)
         at _executeTestFn (/usr/local/lib/node_modules/testcafe/src/test-run/index.js:291:24)



 1/1 failed (30s)
```
</details>

<details>
<summary>Screenshots:</summary>

```
attached
```
</details>

### Steps to Reproduce:

1. Go to the salesforce scratch org https://brave-bear-e42cd9-dev-ed.my.salesforce.com
3. log in with credentials in test
4. Navigate to Accounts
5. Assert on custom lightning component with text "Hello I'm a custom lightning component"
 
### Your Environment details:
 
* testcafe version:  1.1.3
* node.js version:  v11.14.0
* command-line arguments:  testcafe chrome e2e/tests/lightning_comp_test.ts
* browser name and version: Chrome 73.0.3683
* platform and version: Mac OS X 10.14.4
* other:  have tried across multiple browsers and multiple versions of testcafe.  bumping up to hammerhead v 14.6.0 resolved another issue for us where the navigation bar was not appearing in testcafe. 
Noticed the issue in our production like QA environment.  
Custom Lightning Component for this example was created through this trailhead https://trailhead.salesforce.com/en/content/learn/projects/quickstart-lightning-components/quickstart-lightning-components3

**Comment by Farfurix** [comment]
@blokeefe 

Hello.

I didn't reproduce this issue (I used my own account) under Windows 10 / macOS Mojave 10.14.4 / Chrome 73 / `testcafe-hammerhead@14.6.2` (https://github.com/DevExpress/testcafe-hammerhead/commit/05d2788732c9b3e3549170f93a78cb52f0ac39d6).

`testcafe-hammerhead` result:
![Capture](https://user-images.githubusercontent.com/30019338/56491993-0aa61d80-64f3-11e9-9330-176ba5d52aac.PNG)

It is impossible to debug Salesforce with your credentials because of the "email verification" action.

There are two ways to reproduce the issue:
1. Disable the "email verification" on your account if it is possible. This way I can debug your test case.
2. Describe steps I can use to get your screenshot page with the "Contact list for ..." section.

**Comment by blokeefe** [comment]
@Farfurix i cannot disable email verification but we can white list your ip address to bypass that step.  Would that work for you?

**Comment by Farfurix** [comment]
@blokeefe, OK, our IP: 188.128.36.80

**Comment by blokeefe** [comment]
@Farfurix Added. 
when you navigate to this url as a user you will see the custom lightning component. 
https://brave-bear-e42cd9-dev-ed.lightning.force.com/lightning/r/Account/0012E00001pSKxpQAG/view

Testcafe will not see it. 
Thanks for your help. 

![Salesforce 2019-04-22](https://user-images.githubusercontent.com/5287694/56504273-fc053980-64e5-11e9-82d4-7052941c4f3b.jpg)

**Comment by Farfurix** [comment]
@blokeefe 

Thank you.

I've reproduced the issue under Window 10 / Chrome 73 / testcafe-hammerhead@14.6.2 (DevExpress/testcafe-hammerhead@05d2788).
We need some time to investigate this issue using your credentials.
