### ISSUE TITLE
ReferenceError: fixture is not defined

### ISSUE THREAD

**Issue by renanbastos93** [DevExpress/testcafe#3940]
I tried to run test and it doesn't found method fixture native. 

```bash
$ ERROR Cannot prepare tests due to an error.
$ ReferenceError: fixture is not defined
    at Object.fixture (/Users/renan.bastos/Desktop/git/caffeine/tests/behavior/main.js:10:1)
    at Object._compile [as .js] (/Users/renan.bastos/.npm-global/lib/node_modules/testcafe/src/compiler/test-file/api-based.js:91:25)
    at Object.<anonymous> (/Users/renan.bastos/Desktop/git/caffeine/main.js:6:1)
    at Function._compile [as _execAsModule] (/Users/renan.bastos/.npm-global/lib/node_modules/testcafe/src/compiler/test-file/api-based.js:50:13)
    at ESNextTestFileCompiler._execAsModule [as _runCompiledCode] (/Users/renan.bastos/.npm-global/lib/node_modules/testcafe/src/compiler/test-file/api-based.js:149:42)
    at ESNextTestFileCompiler._runCompiledCode [as execute] (/Users/renan.bastos/.npm-global/lib/node_modules/testcafe/src/compiler/test-file/api-based.js:173:21)
    at ESNextTestFileCompiler.execute (/Users/renan.bastos/.npm-global/lib/node_modules/testcafe/src/compiler/test-file/api-based.js:179:21)
    at compile (/Users/renan.bastos/.npm-global/lib/node_modules/testcafe/src/compiler/index.js:98:31)
    at Compiler._getTests (/Users/renan.bastos/.npm-global/lib/node_modules/testcafe/src/compiler/index.js:94:66)
    at _getTests (/Users/renan.bastos/.npm-global/lib/node_modules/testcafe/src/compiler/index.js:110:35)
```

 
* testcafe version:                   1.1.3
* node.js version:                    v10.15.0
* command-line arguments:  testcafe 'firefox' main.js 
* browser name and version: firefox and chrome I test both
* platform and version:          MacOS Mojava

**Comment by AllSidesCreative** [comment]
Heya,
Can you paste a snippet of your code?

**Comment by LavrovArtem** [comment]
This information is not sufficient to find the cause of the issue. There can be many causes, and therefore, we cannot give you recommendations without analyzing your code. As @AllSidesCreative said, could you please provide your test code?

**Comment by renanbastos93** [comment]
My struct is:
```bash
.
├── Dockerfile
├── README.md
├── clear.js
├── helpers
│   ├── README.md
│   ├── generate.js
│   └── skip.js
├── main.js
├── package-lock.json
├── package.json
├── page-models
│   ├── README.md
│   ├── auth.js
├── settings
│   ├── README.md
│   ├── base.js
│   ├── local.js
│   ├── production.js
│   └── stage.js
├── tests
│   ├── behavior
│   │   └── main.js
│   └── edge_application
│       └── main.js
```

main.js -> execute all tests

file with error behavior/main.js

```js
import { testData } from '../../settings/base';
import makeId from '../../helpers/generate';

// Defines the address and name for the test session
fixture('Behavior Tests').page(testData.page); // line 10
```

**Comment by AllSidesCreative** [comment]
Hmm, I cant reproduce this. Try upgrading testcafe to latest version?
At the moment it's 1.2.1

**Comment by renanbastos93** [comment]
I tried the test in 2 machines, I don't upgrade version.

**Comment by AndreyBelym** [comment]
I guess that you specify the `caffeine/main.js` as a test file, and this file imports other test files (like `tests/behavior/main.js`). TestCafe doesn't allow calling `test` and `fixture` in files that were not specified as test files explicitly to avoid polluting the global namespace. Once we implement https://github.com/DevExpress/testcafe/issues/1735, it will be possible to define tests and fixture in any files. Right now there are the following ways to accomplish your goals:

1. TestCafe executes test files in the order they were specified in CLI. So you can specify the main test file as a first test file and specify all other test files after the main test file.

2. You can create a `testcafe-defs.js` file with the following content and specify it as the first test file:
```js
const fixture = global.fixture;
const test    = global.test;

export fixture;
export test;
```
After that, you can use `import { fixture, test } from './testcafe-defs'` to define test and fixtures in any JS file.
