### ISSUE TITLE
Test passes on Mac OS X, but fails on Linux

### ISSUE THREAD

**Issue by anthony-fp** [DevExpress/testcafe#3956]
### What is your Test Scenario?
Testcafe should click on a dropdown and select an item. This test works on Mac OS X but fails on Linux.

 
```
 import {Selector} from 'testcafe'

fixture('Test')
    .page('https://www.fantasypros.com/nfl/rankings/consensus-cheatsheets.php');


test('Broken Hover', async t => {
    await t
        .click(Selector('.nav').find('a').withText('Ranks'))
        .click(Selector('.fp-dropdown-menu').find('a').withText('Stats (Totals)'))
});

```

```
Running tests in:
 - HeadlessChrome 75.0.3770 / Linux 0.0.0

 Test
(node:3778) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
 ✖ Broken Hover

   1) The element that matches the specified selector is not visible.

      Browser: HeadlessChrome 75.0.3770 / Linux 0.0.0

          5 |
          6 |
          7 |test('Broken Hover', async t => {
          8 |    await t
          9 |        .click(Selector('.nav').find('a').withText('Ranks'))
       > 10 |        .click(Selector('.fp-dropdown-menu').find('a').withText('Stats (Totals)'))
         11 |});
         12 |
         13 |

         at click (/home/ubuntu/af.js:10:10)
         at test (/home/ubuntu/af.js:7:1)
         at <anonymous> (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn (/usr/lib/node_modules/testcafe/src/test-run/index.js:243:19)
         at TestRun.start (/usr/lib/node_modules/testcafe/src/test-run/index.js:292:24)



 1/1 failed (37s)
```

 
### Your Environment details:
 
* testcafe version:                   1.2.1
* node.js version:                    11.15.0
* command-line arguments:   testcafe -e chrome:headless test.js
* browser name and version: HeadlessChrome 75.0.3770 
* platform and version:           Mac OS X 10.14.5 & Linux

**Comment by aleks-pro** [comment]
Hello @anthony-fp ,

I was able to reproduce the issue. We will research it and update this thread as soon as we have any results.

**Comment by highspotjeremy** [comment]
I'm not exactly sure why, but using emulation to pass in the user agent from my Mac version of Chrome seemed to resolve the issue, even though the version matches what is reported in our Linux-based CI environment.
```shell
testcafe "chrome:headless:emulation:userAgent='Mozilla/5.0 (Macintosh\; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36',firefox:headless" tests
```

**Comment by miherlosev** [comment]
Hi @anthony-fp

I cannot reproduce the issue because the tested web site was modified. Could you please update the example?
