### ISSUE TITLE
Hover pseudo class is not applied during test when css style is added as a Blob link.

### ISSUE THREAD

**Issue by akozlov-sovarto** [DevExpress/testcafe#3971]
### What is your Test Scenario?
When html element is hovered, css hover style should apply.
 
### What is the Current behavior?
The css hover style is applied when it is defined in external file or inside <style> tag. However it is not applied if the style is added via link to Blob object.

 
### What is the Expected behavior?
CSS style from Blob object should also apply on hover.
 
### What is your web application and your TestCafe test code?

 https://github.com/akozlov-sovarto/testing-hover-blob

Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```html
 <!DOCTYPE html>
<html>

<head>
    <title>Testcafe style issue</title>
    <style>
        .root:hover {
            background-color: rgb(0, 128, 0);
        }
        .root {
            width: 200px;
            height: 200px;
        }
    </style>

    <script>
        var blob = new Blob(['.root:hover { background-color: rgb(0, 0, 0); } .root { color: red }'], {type: 'text/css'});
        var link = document.createElement('link');
        link.rel = 'stylesheet';
        link.href = window.URL.createObjectURL(blob);
        document.head.appendChild(link);
    </script>
</head>

<body>
<h1>Test</h1>
<div class="root">
    root
</div>
</body>
</html>
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "name": "testcafe-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "testcafe chrome tests/ --app \"http-server . -s -p 38010\""
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "testcafe": "^1.2.1"
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
import { Selector } from 'testcafe';

fixture`Selection`
    .page('http://127.0.0.1:38010/index.html');

test('On hover element should have background-color from blob css', async t => {
    await t
        .hover('.root')
        .wait(3000)
        .expect(Selector('.root').getStyleProperty('background-color'))
        .eql('rgb(0, 0, 0)');
});

 Selection
 × On hover element should have background-color from blob css

   1) AssertionError: expected 'rgb(0, 128, 0)' to deeply equal 'rgb(0, 0, 0)'

      Browser: Chrome 75.0.3770 / Windows 10.0.0

          6 |test('On hover element should have background-color from blob css', async t => {
          7 |    await t
          8 |        .hover('.root')
          9 |        .wait(3000)
         10 |        .expect(Selector('.root').getStyleProperty('background-color'))
       > 11 |        .eql('rgb(0, 0, 0)');
         12 |});

         at eql (F:\Projects\1\testing-hover-blob\tests\test.js:11:10)
         at test (F:\Projects\1\testing-hover-blob\tests\test.js:6:1)
         at <anonymous> (F:\Projects\1\testing-hover-blob\node_modules\testcafe\src\api\wrap-test-function.js:17:28)
         at TestRun._executeTestFn (F:\Projects\1\testing-hover-blob\node_modules\testcafe\src\test-run\index.js:263:19)
         at TestRun.start (F:\Projects\1\testing-hover-blob\node_modules\testcafe\src\test-run\index.js:312:24)



 1/1 failed (8s)
npm ERR! Test failed.  See above for more details.

```
</details>

**Comment by Farfurix** [comment]
@akozlov-sovarto 

Hello,
 
Thank you for the detailed description. I've reproduced the issue. Our team will research it to find a suitable solution.
