### ISSUE TITLE
Error: "Cannot read property 'exports' of null" using live mode in Node 12.6.0

### ISSUE THREAD

**Issue by devmondo** [DevExpress/testcafe#4052]
### What is your Test Scenario?
import `PageModel` code or any custom util lib.
 
### What is the Current behavior?
if you, for example, create a library to abstract some testing code as a `PageModel` or whatever...
and import it in your test file then start testcafe in live mode, first time everything runs fine. now make any modification to your lib code. life mode will kick in because of the update but you will see the error detailed below.

### What is the Expected behavior?
testcafe live mode should run fine without the error when i update my external lib.

it does not matter what browser you use or what code is in your lib. the behavior persists.  

now this happens specifically in node v12, in node v10 everything works fine.
  
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>
lib/index.ts

```js
 import {t} from "testcafe";

console.log(2222);
export class PageModel {
    public async wait (n){
         await t.wait(n)
    }
}

export const pageModel = new PageModel();
```

project/example.ts

```js
import {pageModel} from "node12-test";

console.log(pageModel);
fixture(`fixture 1`);

test(`test 1`,async (t)=>{
await pageModel.wait(100);
})


```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```js
const createTestCafe = require('testcafe');
let testcafe = null;

createTestCafe('localhost')
    .then(tc => {
        testcafe = tc;
        const runner = testcafe.createLiveModeRunner();

        return runner
            .src(['./src/**/*.ts'])
            .browsers(['chrome:headless'])
            .run();
    })
    .then(failedCount => {
        console.log('Tests failed: ' + failedCount);
        testcafe.close();
    });

```
</details>

<details>
<summary>Your complete test report:</summary>

```bash
TypeError: Cannot read property 'exports' of null
    at Module.module_1.default.require (C:\projects\test\node12-testcafe\node_modules\testcafe\src\live\bootstrapper.js:44:36)
    at Object.<anonymous> (C:\projects\test\node12-testcafe\src\example.ts:1:1)
    at Function._execAsModule (C:\projects\test\node12-testcafe\node_modules\testcafe\src\compiler\test-file\api-based.js:50:13)
    at TypeScriptTestFileCompiler._runCompiledCode (C:\projects\test\node12-testcafe\node_modules\testcafe\src\compiler\test-file\api-based.js:150:42)
    at TypeScriptTestFileCompiler.execute (C:\projects\test\node12-testcafe\node_modules\testcafe\src\compiler\test-file\api-bas

    at Module.module_1.default.require (C:\projects\test\node12-testcafe\node_modules\testcafe\src\live\bootstrapper.
js:44:36)
    at Object.<anonymous> (C:\projects\test\node12-testcafe\src\example.ts:1:1)
    at Function._execAsModule (C:\projects\test\node12-testcafe\node_modules\testcafe\src\compiler\test-file\api-base
    at Module.module_1.default.require (C:\projects\test\node12-testcafe\node_modules\testcafe\src\live\bootstrapper.js:44:36)
    at Object.<anonymous> (C:\projects\test\node12-testcafe\src\example.ts:1:1)
    at Function._execAsModule (C:\projects\test\node12-testcafe\node_modules\testcafe\src\compiler\test-file\api-based.js:50:13)
    at TypeScriptTestFileCompiler._runCompiledCode (C:\projects\test\node12-testcafe\node_modules\testcafe\src\compiler\test-file\api-based.js:150:42)
    at TypeScriptTestFileCompiler.execute (C:\projects\test\node12-testcafe\node_modules\testcafe\src\compiler\test-file\api-based.js:174:21)
    at Compiler._getTests (C:\projects\test\node12-testcafe\node_modules\testcafe\src\compiler\index.js:85:35)
    at Compiler._compileTestFiles (C:\projects\test\node12-testcafe\node_modules\testcafe\src\compiler\index.js:99:35)
    at Compiler.getTests (C:\projects\test\node12-testcafe\node_modules\testcafe\src\compiler\index.js:112:34)
    at LiveModeBootstrapper._getTests (C:\projects\test\node12-testcafe\node_modules\testcafe\src\runner\bootstrapper.js:81:26) {
  code: 'E1035',
  data: [ "TypeError: Cannot read property 'exports' of null" ]
}
>

```
</details>

 
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/1266367/61568705-5be39000-aa95-11e9-99b4-25931a606f44.png)

### Steps to Reproduce:

1. create a lib project
3. add simple PageModel code
4. NPM Link
5. run testcafe in live mode
6. Update the lib code
 
### Your Environment details:
 
* testcafe version:                   1.3.3
* node.js version:                    12.6.0
* command-line arguments:  node testcafe.js
* browser name and version: Chrome  75
* platform and version:          Windows 10 64bit
* other:

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I have reproduced this behavior on my side. We need some additional time to research this issue. Please bear with us.
