### ISSUE TITLE
Relative navigation after pushState does not respect new URL

### ISSUE THREAD

**Issue by bxt** [DevExpress/testcafe#4334]
### What is your Test Scenario?

I saw some error pages that only happened in TestCafé but not when I execute the text manually. Turns out navigating with `location.href` works differently in TestCafé when you also do `history.pushState` on the page (as e.g. `react-router` does)
 
### What is the Current behavior?

* Load a website
* Use `history.pushState` with a URL on another level (e.g. use `/` somewhere in the 3rd argument)
* Use `location.href="relative"` to navigate
* The navigations happens relative to the initial URL and not relative to the updated URL
 
### What is the Expected behavior?

The navigation should happen relative to the URL currently displayed in the address bar, just like it does in the browser.
 
### What is your web application and your TestCafe test code?
 
Your website URL: I created a test that runs on some random GitHub pages, see test code below.

<details>
<summary>Your complete test code:</summary>

 
```js
 import {ClientFunction} from 'testcafe';

fixture`testcafe 2140`.page`https://github.com/bxt/testcafe-2140`;

const goAway = ClientFunction(() => {
  window.location.href = 'pulls';
});

const virtualNavigation = ClientFunction(() => {
  history.pushState({}, "page 2", "testcafe-2140/deeper");
});

const getPageUrl = ClientFunction(() => window.location.href);

test(`navigates to the correct URL on GitHub`, async t => {
  await t.expect(getPageUrl()).eql('https://github.com/bxt/testcafe-2140');

  await virtualNavigation();

  await t.expect(getPageUrl()).eql('https://github.com/bxt/testcafe-2140/deeper');

  await goAway();

  await t.expect(getPageUrl()).eql('https://github.com/bxt/testcafe-2140/pulls');
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```
> testcafe chrome test.ts 
 Running tests in:
 - Chrome 77.0.3865 / Mac OS X 10.14.6

 testcafe 2140
 ✖ has the correct value in Request('/').url on GitHub

   1) AssertionError: expected 'https://github.com/bxt/pulls' to deeply equal
      'https://github.com/bxt/testcafe-2140/pulls'

      Browser: Chrome 77.0.3865 / Mac OS X 10.14.6

         19 |
         20 |  await t.expect(getPageUrl()).eql('https://github.com/bxt/testcafe-2140/deeper');
         21 |
         22 |  await goAway();
         23 |
       > 24 |  await t.expect(getPageUrl()).eql('https://github.com/bxt/testcafe-2140/pulls');
         25 |});
         26 |

         at <anonymous> (/Users/bxt/test.ts:24:32)
         at fulfilled (/Users/bxt/test.ts:5:58)



 1/1 failed (6s)
```
</details>

### Steps to Reproduce:

Execute the code below "Your complete test code" above in a file e.g. using `testcafe chrome test.ts`.
 
### Your Environment details:
 
* testcafe version:                   1.5.0
* node.js version:                    v12.10.0
* command-line arguments:  `testcafe chrome test.ts`
* browser name and version: Chrome 77
* platform and version:          macOS 10.14.6
* other:                                   none

**Comment by miherlosev** [comment]
Hi @bxt 

I've reproduced the problem. Thank you for the provided example.
