### ISSUE TITLE
My test gives error: await is a reserved word for  await element.with({visibilityCheck: true })(); 

### ISSUE THREAD

**Issue by gpawel** [DevExpress/testcafe#4338]
### What is your Test Scenario?

I am creating a page object from a test:
var formTools = await designer.openToolsList();	

 
### What is the Current behavior?

computer:~/workspace/project$ testcafe chrome js/CaffeTest.js 
await element.with({visibilityCheck: true })(); 
or 
//await t.expect(element.visible).ok();
returns error message: await is a reserved word.

```
ERROR Cannot prepare tests due to an error.

SyntaxError: /home/pavel/workspace/project/js/page/FormToolList.js: await is a reserved word (13:8)
  11 |     constructor() {
  12 |         const element = Selector(powerToolsBoxOpened);
> 13 |         await element.with({visibilityCheck: true })();
     |         ^
  14 |         //await t.expect(element.visible).ok();
  15 |     }
  16 | 
    at ESNextTestFileCompiler._compileCode (/usr/local/lib/node_modules/testcafe/src/compiler/test-file/formats/es-next/compiler.js:57:32)
    at Object..js (/usr/local/lib/node_modules/testcafe/src/compiler/test-file/formats/es-next/compiler.js:65:50)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/testcafe/src/compiler/test-file/api-based.js:88:63)
    at Object.<anonymous> (/home/pavel/workspace/project/js/page/Designer.js:3:1)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/testcafe/src/compiler/test-file/api-based.js:92:25)
    at Object.<anonymous> (/home/pavel/workspace/project/js/page/FormsNavigator.js:2:1)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/testcafe/src/compiler/test-file/api-based.js:92:25)
    at Object.<anonymous> (/home/pavel/workspace/project/js/CaffeTest.js:3:1)
    at Function._execAsModule (/usr/local/lib/node_modules/testcafe/src/compiler/test-file/api-based.js:50:13)
    at ESNextTestFileCompiler._runCompiledCode (/usr/local/lib/node_modules/testcafe/src/compiler/test-file/api-based.js:150:42)

Type "testcafe -h" for help.
computer:~/workspace/project$ ^C

``` 
### What is the Expected behavior?

No error is expected. Obviosly I am doing something wrong but don't understand what exactly.
 
### What is your web application and your TestCafe test code?

Here is the model:
```
import { Selector, t } from 'testcafe';
import { ClientFunction } from 'testcafe';

const powerToolsBoxOpened = "section[class='powerFormsTools open']";
const actionTools = powerToolsBoxOpened + " span[class='toolmenu ToolsList1']";
const actionToolsOpened = powerToolsBoxOpened + " span[class='toolmenu ToolsList1 open']";
const inputTools = powerToolsBoxOpened + " span[class='toolmenu ToolsList4']";
const inputToolsOpened = powerToolsBoxOpened + " span[class='toolmenu ToolsList4 open']";

export default class FormToolList {
    constructor() {
        const element = Selector(powerToolsBoxOpened);
        await element.with({visibilityCheck: true })();
        //t.expect(await .visible).ok();
    }

}
```
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 test("Using Forms class", async t => {
	console.log("test two");
	await forms.openFormDrafts();
	var designer = await forms.openFormDesigner();
	await designer.startBuildForm();
	var formTools = await designer.openToolsList();	
	await formTools.openActionsList();
	await formTools.openInputsList();	
});

in designer object:
async openToolsList() {		
		await t.click(insertNewElement);
		return await FormToolList();
	}
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

 
### Your Environment details:
 
* testcafe version:      1.5.0            
* node.js version:     v8.10.0               
* command-line arguments:  testcafe chrome js/CaffeTest.js 
* browser name and version: chrome Version 77.0.3865.90 (Official Build) (64-bit)
* platform and version:          Linux Ubuntu 18.04.1

**Comment by gpawel** [comment]
Note:
when the FormListTool constructor is written as:
constructor() {
        const element = Selector(powerToolsBoxOpened);
        //await element.with({visibilityCheck: true })();
        t.expect(await element.visible).ok();
    }
The test runs but returns the following message:

```
✖ Using Forms class

   1) TypeError: Class constructor FormToolList cannot be invoked without 'new'

      Browser: Chrome 77.0.3865 / Linux 0.0.0

         19 |    	await t.expect(Selector(newElement).visible).ok();
         20 |	}
         21 |
         22 |	async openToolsList() {
         23 |		await t.click(insertNewElement);
       > 24 |		return await FormToolList();
         25 |	}
         26 |
         27 |}
         28 |

         at <anonymous> (/home/pavel/workspace/powerfulforms/js/page/Designer.js:24:16)
         at $$testcafe_test_run$$ynlSLGDAR$$
      (/usr/local/lib/node_modules/testcafe/src/api/test-run-tracker.js:76:16)
         at $$testcafe_test_run$$ynlSLGDAR$$
      (/usr/local/lib/node_modules/testcafe/src/api/test-run-tracker.js:76:16)



 1/1 failed (11s)

```

**Comment by LavrovArtem** [comment]
The javascript syntax you are using has certain issues. `await` is valid only in the `async` function and a class constructor may not be an `async` method. Therefore, the constructor is not the place where you can execute actions or assertions.
