### ISSUE TITLE
Issue with RC Build 1

### ISSUE THREAD

**Issue by sharathgrao** [DevExpress/testcafe#4393]
**Steps to reproduce:**

1. Consume the v1.6.0-rc.1 and try executing some tests.
2. Errors are shown and no tests are executed

`Using locally installed version of TestCafe.
ERROR Error: Cannot find module 'mime-db'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/create-temp-profile.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Module._compile (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/source-map-support/source-map-support.js:521:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/runtime-info.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Module._compile (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/source-map-support/source-map-support.js:521:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Module._compile (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/source-map-support/source-map-support.js:521:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/testcafe/src/browser/provider/built-in/index.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Module._compile (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/source-map-support/source-map-support.js:521:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/testcafe/src/browser/provider/pool.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Module._compile (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/source-map-support/source-map-support.js:521:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/testcafe/src/runner/bootstrapper.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Module._compile (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/source-map-support/source-map-support.js:521:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/testcafe/src/runner/index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Module._compile (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/source-map-support/source-map-support.js:521:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at lazy (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/import-lazy/index.js:2:51)
    at Object.construct (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/import-lazy/index.js:18:11)
    at TestCafe._createRunner (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/testcafe/src/testcafe.js:71:27)
    at TestCafe.createRunner (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/testcafe/src/testcafe.js:86:21)
    at runTests (/Users/sharg/Documents/GitHub/testcafe-cucumber-master/node_modules/testcafe/src/cli/cli.js:81:75)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)`

Solution: Add the "mime-db": "^1.42.0", dependency into package.json resolves the above errors.

PR raised for the same - https://github.com/DevExpress/testcafe/pull/4392/

**Comment by Farfurix** [comment]
@sharathgrao 

Hello,

Thank you for [your contribution](https://github.com/DevExpress/testcafe/pull/4392). This fix is already merged [here](https://github.com/DevExpress/testcafe/pull/4382). Please update your TestCafe to the latest `v1.6.0` version.
