### ISSUE TITLE
Error running example code with default Chrome profile

### ISSUE THREAD

**Issue by ZhaofengWu** [DevExpress/testcafe#4418]
### What is your Test Scenario?
Ran `testcafe chrome:userProfile test.js`. `test.js` is what's in the README:

```js
import { Selector } from 'testcafe'; // first import testcafe selectors

fixture `Getting Started`// declare the fixture
    .page `https://devexpress.github.io/testcafe/example`;  // specify the start page


//then create a test and place your code there
test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button')

        // Use the assertion to check if the actual header text is equal to the expected one
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});
```
 
### What is the Current behavior?
The program crashes with the following error trace:

```
Running tests in:
 - Chrome 77.0.3865 / Mac OS X 10.14.6

 Getting Started
 ✖ My first test

   1) A JavaScript error occurred on
      "https://devexpress.github.io/testcafe/example/".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You
      can fix it or disable tracking JavaScript errors in TestCafe. To do
      the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:

   "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      SyntaxError: JSON.parse
          at exports.parse
      (http://192.168.1.108:62235/hammerhead.js:17:11381)
          at Function.t._getMessageData
      (http://192.168.1.108:62235/hammerhead.js:7:19896)
          at t.r._onMessage
      (http://192.168.1.108:62235/hammerhead.js:7:19961)
          at n (http://192.168.1.108:62235/hammerhead.js:14:12264)
          at n (http://192.168.1.108:62235/hammerhead.js:7:21247)
          at http://192.168.1.108:62235/hammerhead.js:7:13145

      Browser: Chrome 77.0.3865 / Mac OS X 10.14.6

          5 |
          6 |
          7 |//then create a test and place your code there
          8 |test('My first test', async t => {
          9 |    await t
       > 10 |        .typeText('#developer-name', 'John Smith')
         11 |        .click('#submit-button')
         12 |
         13 |        // Use the assertion to check if the actual header text
      is equal to the expected one
         14 |
      .expect(Selector('#article-header').innerText).eql('Thank you, John
      Smith!');
         15 |});

         at typeText (~/Desktop/testcafe/test.js:10:10)
         at <anonymous> (~/Desktop/testcafe/test.js:8:1)
         at <anonymous>

   (/usr/local/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn
      (/usr/local/lib/node_modules/testcafe/src/test-run/index.js:290:19)
         at TestRun.start
      (/usr/local/lib/node_modules/testcafe/src/test-run/index.js:341:24)



 1/1 failed (1s)
```
 
### What is the Expected behavior?
It should pass. Notably, running the command _without_ `:userProfile` succeeds.

### Your Environment details:
 
* testcafe version:                   1.6.0
* node.js version:                    v12.12.0
* command-line arguments:  `testcafe chrome:userProfile test.js`
* browser name and version: Chrome 77.0.3865
* platform and version:          Mac OS X 10.14.6

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I've reproduced this issue on my side. We'll research it and update this thread as soon as we have any result.

**Comment by Dmitry-Ostashev** [comment]
This behavior may be caused by Chrome extensions or the built-in ad blocker. You can try to turn off your chrome extensions and switch the following setting to "Allowed": chrome://settings/content/ads.
