### ISSUE TITLE
Tests wont run on CrossBrowserTesting re a syntax error

### ISSUE THREAD

**Issue by ljones87** [DevExpress/testcafe#4442]
### What is your Test Scenario?
I have a relatively simple integration test suite for a single React page. The page has a view toggle nav "Papers" and "Products". I am testing by clicking the nav to "Papers", making assertions as to what should be on the page, then navigating back to "Products". Then I'm opening filter options, and checking that two of the filters work. Aka, I click a filter and fewer products should show on the page etc. 
 
### What is the Current behavior?
the tests usually work when running against local browsers (chrome, firefox, safari), but sometimes when running locally and always when running remotely using "testcafe-browser-provider-crossbrowsertesting" the first few tests error with the following message:
```
1) A JavaScript error occurred on "http://localhost:3000/my/route".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      SyntaxError: JSON.parse
         at exports.parse (http://localhost:1337/hammerhead.js:17:11375)
         at h (http://localhost:1337/hammerhead.js:13:20510)
```
There are no errors in the console when I visit my locally running site, but there is a SSR related `warning: index.js:1 Warning: Did not expect server HTML to contain a <div> in <div>.`
 
### What is the Expected behavior?
The tests run without error
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
I have swapped any identifying information for fake generic info. If I mess up a data-id etc, it is in generalizing it here and not an actual issue with the test. I have watched and had all the tests passing successfully before.
```
import { Selector } from 'testcafe'
fixture`Detail Test`.page(`http://localhost:3000/my/route`)

const productsNav = Selector('#products-nav')
const papersNav = Selector('#papers-nav')
const filtersButton = Selector('[data-testid="filter-button"]')

test('should have the basic page data', async t => {
  await t.expect(papersNav).ok()
  await t.expect(productsNav).ok()
  await t.expect(filtersButton).ok('doesnt have filters button')
  const labels = await Selector('[data-testid="label"]')
  await t.expect(labels.count).eql(4)
  const categories = Selector('[data-testId="category-name"]')
  await t.expect(categories.count).eql(8)
})

 // links should contain number displayed 
test('should have the same id displayed in link', async t => {
  const links = await Selector('a[data-testid|="link"]')
  const linkNodes = await links.count
  for (let i = 0; i < linkNodes; i++) {
    const linkId = await links.nth(i).id
    await t.expect(links.nth(i).textContent).contains(`${linkId}`)
  }
})

test('should have working papers navigation and links to papers on page', async t => {
  await t.click(papersNav)
  await t.wait(1000)
  const paperCount = await Selector('#paper-matches')
  await t.expect(paperCount).ok('didnt show paper count')
  const paperTitles = await Selector('[data-testid="paper-title"]')
  await t.expect(paperTitles.visible).ok()
  await t.expect(paperTitles.count).eql(5)
})

test('should navigate back to the products page from papers', async t => {
  await t.click(papersNav)
  const paperTitle = await Selector('[data-testid="paper-title"]')
  // verify I'm on the papers page
  await t.expect(paperTitle.length).lte(5)
  await t.click(productsNav)
  const title = await Selector('[data-testid="title"]')
  const infoLabels = await Selector('[data-testid="info-label"]')
  await t.expect(title).ok('no title')
  await t.expect(filtersButton).ok('no filters button')
  await t.expect(infoLabels).ok('no info labels')
})

test('should apply selected category filters correctly', async t => {
  await t.expect(filtersButton.visible).ok()
  await t.click(filtersButton)
  const categoryFilter = await Selector(
    '[data-testid="category-filter"]'
  )
  await t.expect(categoryFilter.visible).ok('Couldnt find filter')
  await t.click(categoryFilter)
  await t.click(filtersButton)
  const productCategories = await Selector('[data-testid="category-name"]')
  await t.expect(productCategories.count).eql(1)
})

test('should apply selected color filters correctly', async t => {
  await t.expect(filtersButton.visible).ok()
  await t.click(filtersButton)
  const colorFilter = await Selector(
    '[data-testid="color-filter-red"]'
  )
  await t.expect(colorFilter.visible).ok('Couldnt find filter')
  await t.click(colorFilter)
  await t.click(filtersButton)
  const productsListed = await Selector('[data-testid="products"]')
  const productNodes = await productsListed.count
  for (let i = 0; i < productNodes; i++) {
    await t.expect(productsListed.nth(i).textContent).contains('red')
  }
})

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

runner file:
```
const createTestCafe = require('testcafe')
let runner = null
let testcafe = null

process.env.CBT_TUNNELS_USERNAME = my_user_name
process.env.CBT_TUNNELS_AUTHKEY = my_auth_key

createTestCafe('localhost', 1337, 1338)
  .then(tc => {
    testcafe = tc
    runner = testcafe.createRunner()
    return testcafe.createBrowserConnection()
  })
  .then(remoteConnection => {
    console.log('remote connection ready:', remoteConnection.url)

    runner
      .src('./integration-tests/*test*')
      .browsers(
         'crossbrowsertesting:Internet Explorer@11:Windows 7'
      )
      .run({
        selectorTimeout: 30000,
        assertionTimeout: 60000,
        pageLoadTimeout: 60000
      })
      .then(failed => {
        console.log('failed tests:', failed)
        testcafe.close()
      })
      .catch(error => {
        console.log(error)
      })
  })
```
</details>

<details>
<summary>Your complete test report:</summary>

```
(feature/testCafe-sample) $ yarn tc
yarn run v1.17.3
$ node ./bin/integration.js --skip-js-errors
remote connection ready: http://localhost:1337/browser/connect/9egz7G8
[2019-11-04T14:49:38.817] [INFO] default - Connecting as simpleproxy.
[2019-11-04T14:49:38.987] [ERROR] default - Your version of cbt_tunnels is out-of-date,  but still supported. In order to update it now exit this program and run:

         npm update -g cbt_tunnels
[2019-11-04T14:49:39.607] [INFO] default - Completely connected!
 Running tests in:
 - IE 11.0.0 / Windows 7.0.0

Detail Test
 ✖ should have the basic page data

   1) A JavaScript error occurred on "http://localhost:3000/my/route".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      SyntaxError: JSON.parse
         at exports.parse (http://localhost:1337/hammerhead.js:17:11375)
         at h (http://localhost:1337/hammerhead.js:13:20510)

      Browser: IE 11.0.0 / Windows 7.0.0


 ✖ should have the same id displayed in link

   1) A request to "http://localhost:3000/my/route" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to complete a request to "http://localhost:3000/my/route" within the timeout period. The problem may be related to local machine's network or firewall settings, server outage, or network problems that
      make the server inaccessible.

      Browser: IE 11.0.0 / Windows 7.0.0


 ✖ should have working Papers Navigation and links to papers on page

   1) A request to "http://localhost:3000/my/route" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to find a DNS-record for the resource at "http://localhost:3000/my/route".

      Browser: IE 11.0.0 / Windows 7.0.0

         25 |    await t.expect(links.nth(i).textContent).contains(`${linkId}`)
         26 |  }
         27 |})
         28 |
         29 |test('should have working Papers Navigation and links to papers on page', async t => {
       > 30 |  await t.click(papersNav)
         31 |  await t.wait(1000)
         32 |  const paperCount = await Selector('#paper-matches')
         33 |  await t.expect(paperCount).ok('didnt show paper count')
         34 |  const paperTitles = await Selector('[data-testid="paper-title"]')
         35 |  await t.expect(paperTitles.visible).ok()

         at <anonymous> (/detail.integration.test.js:30:11)
         at test (/detail.integration.test.js:29:1)
         at <anonymous> (/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn (/node_modules/testcafe/src/test-run/index.js:290:19)
         at TestRun.start (/node_modules/testcafe/src/test-run/index.js:341:24)


 ✖ should navigate back to the products page from peer papers

   1) A request to "http://localhost:3000/my/route" has failed.
      Use quarantine mode to perform additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to complete a request to "http://localhost:3000/my/route" within the timeout period. The problem may be related to local machine's network or firewall settings, server outage, or network problems that
      make the server inaccessible.

      Browser: IE 11.0.0 / Windows 7.0.0

         36 | 
         37 |  await t.expect(paperTitles.count).eql(5)
         38 |})
         39 |
         40 |test('should navigate back to the products page from papers', async t => {
       > 41 |  await t.click(papersNav)
         42 |  const paperTitle = await Selector('[data-testid="paper-title"]')
         43 |  // verify I'm on the papers page
         44 |  await t.expect(paperTitle.length).lte(5)
         45 |  await t.click(productsNav)
         46 |  const geneTitle = await Selector('[data-testid="title"]')

         at <anonymous> (/detail.integration.test.js:41:11)
         at test (/detail.integration.test.js:40:1)
         at <anonymous> (/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn (/node_modules/testcafe/src/test-run/index.js:290:19)
         at TestRun.start (/node_modules/testcafe/src/test-run/index.js:341:24)


 ✖ should apply selected category filters correctly

   1) A JavaScript error occurred on "http://localhost:3000/my/route".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      SyntaxError: JSON.parse
         at exports.parse (http://localhost:1337/hammerhead.js:17:11375)
         at h (http://localhost:1337/hammerhead.js:13:20510)

      Browser: IE 11.0.0 / Windows 7.0.0

         50 |  await t.expect(infoLabels).ok('no info labels')
         51 |})
         52 |
         53 |test('should apply selected gene category filters correctly', async t => {
         54 |  await t.expect(filtersButton.visible).ok()
       > 55 |  await t.click(filtersButton)
         56 |  const categoryFilter = await Selector(
         57 |    '[data-testid="category-filter"]'
         58 |  )
         59 |  await t.expect(categoryFilter.visible).ok('Couldnt find filter')
         60 |  await t.click(categoryFilter)

         at <anonymous> (/detail.integration.test.js:55:11)


[2019-11-04T14:56:54.405] [ERROR] default - User requested ending this tunnel.
[2019-11-04T14:56:54.413] [ERROR] default - Disconnected from CBT server.

[2019-11-04T14:56:54.744] [INFO] default - Local connection disconnected.
[2019-11-04T14:56:54.745] [INFO] default - Bye!
✨  Done in 446.78s.
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Your Environment details:
 
* testcafe version:                   1.6.0
* node.js version:                    v10.16.0
* command-line arguments:  yarn script: `"tc": "node ./bin/integration.js --skip-js-errors"`
* browser name and version: crossbrowsertesting:Internet Explorer@11:Windows 7
* platform and version:         macOS 10.14.6
* other:

**Comment by arubtsov** [comment]
Hello @ljones87,

Thank you for reaching out to us. I see that you pass the `--skip-js-errors` option as a command-line argument and use the programming interface at the same time. To make this option work, you need to add it to the options object of the [`run`](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#run) method as follows:
```
.run({
        selectorTimeout: 30000,
        assertionTimeout: 60000,
        pageLoadTimeout: 60000,
        skipJsErrors: true
})
```

Please let us know if this solves your issue.

I also noticed that you create a remote connection, but do not use it in the `browsers` method. If this is not related to corrections you've made in order to post your code here, you may not create the remote connection.
