### ISSUE TITLE
line numbers for stacktrace of uncaughtErrorOnPage are not accurate

### ISSUE THREAD

**Issue by signed** [DevExpress/testcafe#4469]
### What is your Test Scenario?
Any test where an error is thrown in the application under test
 
### What is the Current behavior?
Line numbers in the stacktrace are not as accurate as they could be with the information available

#### Browser
```
Uncaught Error: [object Object]
    at t.callstack (stacktrace.tsx:29)
    at t.deep (stacktrace.tsx:25)
    at t.very (stacktrace.tsx:21)
    at t.triggerError (stacktrace.tsx:17)
    at Object.h (react-dom.production.min.js:15)
    at k (react-dom.production.min.js:15)
    at react-dom.production.min.js:16
    at S (react-dom.production.min.js:16)
    at N (react-dom.production.min.js:17)
    at _ (react-dom.production.min.js:17)
```

#### Testcafe command line

```
JavaScript error details:
Error: [object Object]
    at t.callstack (https://signed.github.io/talk-testcafe/stacktrace.js:31:5629)
    at t.deep (https://signed.github.io/talk-testcafe/stacktrace.js:31:5577)
    at t.very (https://signed.github.io/talk-testcafe/stacktrace.js:31:5536)
    at t.triggerError (https://signed.github.io/talk-testcafe/stacktrace.js:31:5495)
    at Object.h (https://signed.github.io/talk-testcafe/stacktrace.js:23:1108)
    at k (https://signed.github.io/talk-testcafe/stacktrace.js:23:1251)
    at https://signed.github.io/talk-testcafe/stacktrace.js:23:1397
    at S (https://signed.github.io/talk-testcafe/stacktrace.js:23:1483)
    at N (https://signed.github.io/talk-testcafe/stacktrace.js:23:1948)
    at _ (https://signed.github.io/talk-testcafe/stacktrace.js:23:1744)

Browser: Chrome 78.0.3904 / Mac OS X 10.13.6
```
 
### What is the Expected behavior?
Line numbers are in sync with the line number I get by manually testing in the browser
 
### What is your web application and your TestCafe test code?
https://github.com/signed/talk-testcafe/blob/master/fixtures/stacktrace/stacktrace.fixture.ts
 
Your website URL (or attach your complete example):
https://signed.github.io/talk-testcafe/stacktrace.html

<summary>Your complete test code (or attach your test files):</summary>

 
```ts
import { Selector } from 'testcafe';

fixture('stack trace from application on console')
  .page('https://signed.github.io/talk-testcafe/stacktrace.html');

test('line numbers should match', async (tc) => {
  const button = Selector('button').nth(0);
  await tc.click(button);
  // have a look at the stack trace printed in the console
});
```

### Steps to Reproduce:

1. Go to my website ...
2. Click the button
3. See the error in the console
4. Run the test fixture and compare the stacktrace from the command line with the one from the browser

**Comment by miherlosev** [comment]
Hi @signed

It's expected behavior. TestCafe injects its own service code into the content of the tested website (pages, scripts, CSS styles, etc.) The content of the tested page is changed and line numbers of the stack trace are changed too.
