### ISSUE TITLE
runner.screenshots({takeOnFails: true}) - TypeError: input.replace is not a function

### ISSUE THREAD

**Issue by Pr60** [DevExpress/testcafe#4475]
### What is your Test Scenario?
Using runner class to run tests.

```
const createTestCafe = require('testcafe');

let testcafe = null;

createTestCafe('localhost', 1337, 1338)
  .then((tc) => {
    testcafe = tc;
    const runner1 = testcafe.createRunner();
    const promise1 = runner1
      .src('/tests/uitests/**/conctests/accounttest.js')
      .browsers('chromium:headless')
      .screenshots({
        takeOnFails: false,
      })
      .reporter(['spec', {
        name: 'html',
        output: 'resultsrunner1.html' }, {
        name: 'xunit',
        output: 'res1.xml',
      }])
      .concurrency(3)
      .run({
        skipJsErrors: true,
        // quarantineMode: true,
      });

    return Promise.all([promise1]);
  })
.then(() => {
    testcafe.close();
    process.exit();
  })
  .catch((err) => {
    console.log(err);
    testcafe.close();
    process.exit(1);
  });
```

### What is the Current behavior?
Any argument used to the `screenshots` fails not just the `takeOnFails`. 
Below is the error I see when I run my tests as: 
```
docker run --net=host -v `pwd`:/tests -v `pwd`/reporter:/reporters -w /reporters --entrypoint node testcafe /tests/testrunner.js
```

```
TypeError: input.replace is not a function
    at sanitize (/tests/node_modules/sanitize-filename/index.js:41:6)
    at module.exports (/tests/node_modules/sanitize-filename/index.js:51:16)
    at exports.default (/tests/node_modules/testcafe/src/utils/check-file-path.js:30:5)
    at Runner._validateScreenshotPath (/tests/node_modules/testcafe/src/runner/index.js:285:36)
    at Runner._validateScreenshotPath [as _validateScreenshotOptions] (/tests/node_modules/testcafe/src/runner/index.js:224:18)
    at _validateScreenshotOptions (/tests/node_modules/testcafe/src/runner/index.js:267:14)
    at Generator.next (<anonymous>)
    at step (/tests/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /tests/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/tests/node_modules/core-js/library/modules/_export.js:36:28)
    at /tests/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at Runner._validateRunOptions (/tests/node_modules/testcafe/src/runner/index.js:266:34)
    at _validateRunOptions (/tests/node_modules/testcafe/src/runner/index.js:434:30)
    at invokeCallback (/tests/node_modules/pinkie/index.js:60:12)
    at Array.forEach (<anonymous>)
    at publish (/tests/node_modules/pinkie/index.js:147:32)
    at Array.publishFulfillment (/tests/node_modules/pinkie/index.js:152:2)
    at Immediate.asyncFlush (/tests/node_modules/pinkie/index.js:17:19)
    at processImmediate (internal/timers.js:441:21)
    at process.topLevelDomainCallback (domain.js:131:23)
```
 
### What is the Expected behavior?
I expect it to run and provide screenshot on failure. If I just do this:

`runner.screenshots()` then it doesn't throw any error. But it throws error only after providing argument. Also, the argument works well with `-s` [prefix](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-s---screenshots-optionvalueoption2value2) from the command line.
 
### Your Environment details:
 
* testcafe version:                 1.6.1
* node.js version:                   8.11.1
* browser name and version: HeadlessChrome 77.0.3865 / Linux 0.0.0
* platform and version:      Mac, Mojave 10.14.6

**Comment by arubtsov** [comment]
Hello @Pr60,

Thank you for reaching out to us. We will try to research this problem in the context of https://github.com/DevExpress/testcafe/issues/4477.

**Comment by AlexKamaev** [comment]
The cause can be that you use `require('testcafe')` in your runner class and you code requires a wrong version. TestCafe in the official docker image is installed globally, however, you cannot have access to it without pointing to the global modules directory. This means that the `require('testcafe')` command should not work. However, it works. That's because you probably already have the `node_modules` folder with `testcafe` installed in your project. So this folder is mapped to the docker container.
Thus, in the container, you have two testcafe versions: local (mapped from your project) and global (installed by us). So when you execute the `require` command, it takes the local version, which probably is not latest.
Thus, the recommendations will be the following:
Update your TestCafe version in your local project and do not use global TestCafe
or
Use globally installed TestCafe from an image, but specify the correct path to it (probably it's `/usr/lib/node_modules/testcafe`).

**Comment by Pr60** [comment]
@AlexKamaev - that was a really nice explanation and yes you are right there is a local installation as well and I didn't realize that it took the local TestCafe installation and yes, the local installation was older version. Thank you so much for you recommendation.
