### ISSUE TITLE
Wrong error output when there are JS errors on the page and using resizeWindow

### ISSUE THREAD

**Issue by amitzur** [DevExpress/testcafe#4595]
### What is your Test Scenario?
Running a simple test with `t.resizeWindow` on a website that has a JavaScript error.
 
### What is the Current behavior?
Output shows a stack trace as if `t.resizeWindow` threw the error:
```
Running tests in:
 - HeadlessChrome 79.0.3945 / Linux 0.0.0

 A TestCafe test
 ✖ TestCafe reports the wrong stack trace for page's JavaScript error when using the test controller API

   1) A JavaScript error occurred on "https://www.youtube.com/".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: Illegal invocation
          at Object.We [as nodeListToArray] (http://192.168.1.65:43937/hammerhead.js:14:5694)
          at t.r._addNodeCore (http://192.168.1.65:43937/hammerhead.js:10:18705)
          at HTMLElement.appendChild (http://192.168.1.65:43937/hammerhead.js:10:20469)
          at HTMLElement.attachShadow [as __shady_attachShadow] (https://www.youtube.com/yts/jsbin/webcomponents-sd-vflDA4_4l/webcomponents-sd.js:63:371)
          at K.k.attachShadow (https://www.youtube.com/yts/jsbin/webcomponents-sd-vflDA4_4l/webcomponents-sd.js:89:45)
          at HTMLElement.a._attachDom (https://www.youtube.com/yts/jsbin/desktop_polymer_v2-vflw15Sml/desktop_polymer_v2.js:6022:96)
          at HTMLElement.a._readyClients (https://www.youtube.com/yts/jsbin/desktop_polymer_v2-vflw15Sml/desktop_polymer_v2.js:6021:70)
          at HTMLElement.a._flushClients (https://www.youtube.com/yts/jsbin/desktop_polymer_v2-vflw15Sml/desktop_polymer_v2.js:5946:125)
          at HTMLElement.a._propertiesChanged (https://www.youtube.com/yts/jsbin/desktop_polymer_v2-vflw15Sml/desktop_polymer_v2.js:5952:69)
          at HTMLElement.b._flushProperties (https://www.youtube.com/yts/jsbin/desktop_polymer_v2-vflw15Sml/desktop_polymer_v2.js:5826:200)

      Browser: HeadlessChrome 79.0.3945 / Linux 0.0.0

          4 |fixture`A TestCafe test`
          5 |  .page(`https://www.youtube.com`)
          6 |
          7 |test('TestCafe reports the wrong stack trace for page\'s JavaScript error when using the test controller API', async t => {
          8 |  // await t.eval(() => window.location);
       >  9 |  await t.resizeWindow(1000, 800);
         10 |});

         at <anonymous> (/.../test.js:9:11)
         at <anonymous> (/.../test.js:7:1)
         at <anonymous> (/.../node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn (/.../node_modules/testcafe/src/test-run/index.js:289:19)
         at TestRun.start (/.../node_modules/testcafe/src/test-run/index.js:338:24)



 1/1 failed (5s)
```
 
### What is the Expected behavior?
Output should not show a stack trace. If instead of calling `t.resizeWindow` we call `t.eval(() => window.location)` then it behaves as expected (see commented out line in the output above).
 
### What is your web application and your TestCafe test code?
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture`A TestCafe test`
  .page(`https://www.youtube.com`)

test("TestCafe reports the wrong stack trace for page's JavaScript error when using the test controller API", async t => {
  // await t.eval(() => window.location);
  await t.resizeWindow(1000, 800);
}); 
```
</details>

### Steps to Reproduce:

1. Save the code above in a file, e.g. `test.js`, under a testcafe project
3. Run `npx testcafe chrome:headless test.js`
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.7.1 (and also 1.6 and 1.5)
* node.js version:                    12.13.1
* command-line arguments:  `testcafe chrome:headless test.js
* browser name and version: HeadlessChrome 79
* platform and version:          Linux Ubuntu 18.04.1

**Comment by alexey-lin** [comment]
Hi @amitzur!

Thank you for contacting us. I've reproduced the problem. We will look into it and update this thread once we have any results.
