### ISSUE TITLE
Take a Screenshot of the Entire Page not working 

### ISSUE THREAD

**Issue by RemigiusL** [DevExpress/testcafe#4621]
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
C:\ProcessDrive\TestCafe\Trails\Keyword_Driven\TestScript>testcafe chrome screenshot.js
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 79.0.3945 / Windows 10.0.0

 My fixture
 × Take a screenshot of a fieldset

   1) The "path" argument is expected to be a non-empty string, but it was object.

      Browser: Chrome 79.0.3945 / Windows 10.0.0

          5 |
          6 |test('Take a screenshot of a fieldset', async t => {
          7 |    await t
          8 |        .typeText('#developer-name', 'Peter Parker')
          9 |        .click('#submit-button')
       > 10 |        .takeScreenshot({

C:\ProcessDrive\TestCafe\Trails\Keyword_Driven\TestScript>testcafe chrome screenshot.js
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 79.0.3945 / Windows 10.0.0

 My fixture
 × Take a screenshot of a fieldset

   1) The "path" argument is expected to be a non-empty string, but it objected.

      Browser: Chrome 79.0.3945 / Windows 10.0.0

          5 |
          6 |test('Take a screenshot of a fieldset', async t => {
          7 |    await t
          8 |        .typeText('#developer-name', 'Peter Parker')
          9 |        .click('#submit-button')
       > 10 |        .takeScreenshot({
         11 |            path:     'my-fixture/thank-you-page.png',
         12 |            fullPage: true
         13 |        });
         14 |});

         at takeScreenshot (C:\ProcessDrive\TestCafe\Trails\Keyword_Driven\TestScript\screenshot.js:10:10)
         at test (C:\ProcessDrive\TestCafe\Trails\Keyword_Driven\TestScript\screenshot.js:6:1)
         at <anonymous> (C:\ProcessDrive\TestCafe\Trails\Keyword_Driven\node_modules\testcafe\src\api\wrap-test-function.js:17:28)
         at TestRun._executeTestFn (C:\ProcessDrive\TestCafe\Trails\Keyword_Driven\node_modules\testcafe\src\test-run\index.js:288:19)
         at TestRun.start (C:\ProcessDrive\TestCafe\Trails\Keyword_Driven\node_modules\testcafe\src\test-run\index.js:337:24)



 1/1 failed (3s)
```
</details>

<details>
<summary>Screenshots:</summary>

```
![image](https://user-images.githubusercontent.com/54391573/71817214-2a926700-30ab-11ea-80f1-3998a0df86eb.png)
```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:       1.4.3            
* node.js version:        v10.16.0            
* command-line arguments:  
* browser name and version: chrome  
* platform and version:     Windows     
* other:

**Comment by AlexSkorkin** [comment]
These screenshot options appeared in [version 1.6](https://devexpress.github.io/testcafe/blog/testcafe-v1-6-0-released.html).
Upgrade to the latest version.
