### ISSUE TITLE
JavaScript Error with testcafe: TypeError: e.match is not a function

### ISSUE THREAD

**Issue by tabassumSpringernature** [DevExpress/testcafe#4623]
I am getting following error when i try to open my project page
open player with windowType as pop-up

   1) - Error in fixture.beforeEach hook -
      A JavaScript error occurred on

   "http://localhost:3000/#window-type=tab&link-origin=hotspot&user-role=teacher&student-id=student123&display-type=windowed
&activity-set-id=2b3f6a296e6240e7a1e9f25d2b00d98e".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript
      errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: e.match is not a function
          at Object.g [as isSupportedProtocol] (http://172.27.27.212:57935/hammerhead.js:16:29766)
          at y (http://172.27.27.212:57935/hammerhead.js:15:6455)
          at o (http://172.27.27.212:57935/hammerhead.js:15:4316)
          at r.open (http://172.27.27.212:57935/hammerhead.js:11:13181)
          at openInNewTab (http://localhost:3000/static/js/main.chunk.js:26071:10)
          at App._callee4$ (http://localhost:3000/static/js/main.chunk.js:24932:79)
          at tryCatch (http://localhost:3000/static/js/1.chunk.js:32990:17)
          at Generator.invoke [as _invoke] (http://localhost:3000/static/js/1.chunk.js:33203:22)
          at Generator.next (http://localhost:3000/static/js/1.chunk.js:33040:58)
          at n (http://172.27.27.212:57935/hammerhead.js:14:8429)
          at value (http://172.27.27.212:57935/hammerhead.js:6:2620)
          at asyncGeneratorStep (http://localhost:3000/static/js/1.chunk.js:1453:17)
          at _next (http://localhost:3000/static/js/1.chunk.js:1475:9)
          at http://localhost:3000/static/js/1.chunk.js:1482:7
          at new Promise (<anonymous>)
          at App.<anonymous> (http://localhost:3000/static/js/1.chunk.js:1471:12)
          at App.onOpenRcfPlayerClick (http://localhost:3000/static/js/main.chunk.js:24936:187)
          at App.onChooseClickAction (http://localhost:3000/static/js/main.chunk.js:25061:14)
          at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/1.chunk.js:6727:18)
          at HTMLUnknownElement.dispatchEvent (http://172.27.27.212:57935/hammerhead.js:7:8337)
          at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/1.chunk.js:6776:20)
          at invokeGuardedCallback (http://localhost:3000/static/js/1.chunk.js:6830:35)
          at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/1.chunk.js:6845:29)
          at executeDispatch (http://localhost:3000/static/js/1.chunk.js:7149:7)
          at executeDispatchesInOrder (http://localhost:3000/static/js/1.chunk.js:7174:9)
          at executeDispatchesAndRelease (http://localhost:3000/static/js/1.chunk.js:7273:9)
          at executeDispatchesAndReleaseTopLevel (http://localhost:3000/static/js/1.chunk.js:7282:14)
          at forEachAccumulated (http://localhost:3000/static/js/1.chunk.js:7254:12)
          at runEventsInBatch (http://localhost:3000/static/js/1.chunk.js:7422:7)
          at runExtractedEventsInBatch (http://localhost:3000/static/js/1.chunk.js:7430:7)
          at handleTopLevel (http://localhost:3000/static/js/1.chunk.js:11585:9)
          at batchedUpdates$1 (http://localhost:3000/static/js/1.chunk.js:28020:16)
          at batchedUpdates (http://localhost:3000/static/js/1.chunk.js:8825:16)
          at dispatchEvent (http://localhost:3000/static/js/1.chunk.js:11665:9)
          at http://localhost:3000/static/js/1.chunk.js:28077:18
          at Object.unstable_runWithPriority (http://localhost:3000/static/js/1.chunk.js:34354:16)
          at interactiveUpdates$1 (http://localhost:3000/static/js/1.chunk.js:28076:26)
          at interactiveUpdates (http://localhost:3000/static/js/1.chunk.js:8846:14)
          at dispatchInteractiveEvent (http://localhost:3000/static/js/1.chunk.js:11641:7)
          at l (http://172.27.27.212:57935/hammerhead.js:14:6803)
          at HTMLDocument.<anonymous> (http://172.27.27.212:57935/hammerhead.js:7:13391)
          at HTMLButtonElement.dispatchEvent (http://172.27.27.212:57935/hammerhead.js:7:8337)
          at e.t._raiseDispatchEvent (http://172.27.27.212:57935/hammerhead.js:8:9062)
          at e.t._dispatchMouseEvent (http://172.27.27.212:57935/hammerhead.js:8:7631)
          at e.t._dispatchMouseRelatedEvents (http://172.27.27.212:57935/hammerhead.js:8:6542)
          at u (http://172.27.27.212:57935/hammerhead.js:8:1081)
          at e.t._simulateEvent (http://172.27.27.212:57935/hammerhead.js:8:1537)
          at e.t.click (http://172.27.27.212:57935/hammerhead.js:8:9151)
          at n.run (http://172.27.27.212:57935/testcafe-automation.js:1:7568)
          at r._click (http://172.27.27.212:57935/testcafe-automation.js:1:12476)

      Browser: Chrome 79.0.3945 / Mac OS X 10.12.6

Note: i tried opening the testURl manually and it works well without any errors
testurl: "http://localhost:3000/#window-type=tab&link-origin=hotspot&user-role=teacher&student-id=student123&display-type=windowed"

### Test Scenario:
1-Open the project page (which has multiple links)
2- `click on one of the link to open it in new tab (ex.: http://localhost:3000/#window-type=tab&...)

### Current behavior
fails with the above error on click to the link
 
###  Expected behavior
the page should open and the link should be opened in new tab.
 
### What is your web application and your TestCafe test code?

 
cannot provide website URL as its an internal project.

 
### Your Environment details:
 
* testcafe version:                   1.7.1
* node.js version:                    v8.11.4
* browser name and version: Chrome 79
* platform and version:          macOS 10.14

**Comment by AlexSkorkin** [comment]
The error can be displayed in the browser console. Have you checked it?

Also, did you try to run TestCafe with the [--skip-js-errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) flag as mentioned in the message?

If this still does not help, we will need a sample project to examine this issue and without it, we can't help much.

**Comment by tabassumSpringernature** [comment]
the error cannot be seen on browser window, the above error i am getting on testcafe console. 
Its does say try pasting the error on browser and if that works fine then the issue is not with the test website.

And i can confirm that i cannot see the error on browser console.

**Comment by AlexSkorkin** [comment]
Thank you for your clarification. We will need a sample project to examine this issue and without it, we can't help much.
