### ISSUE TITLE
beforeinput does not fire for contenteditable elements

### ISSUE THREAD

**Issue by dstrelau** [DevExpress/testcafe#4644]
### What is your Test Scenario?

Attempting to use `typeText` into a `contenteditable` elements should fire the `beforeinput` event, allowing the input to be prevented.
 
### What is the Current behavior?

The `beforeinput` event is not fired.
 
### What is the Expected behavior?

The `beforeinput` event should be fired.
 
### What is your web application and your TestCafe test code?

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
  <body>
    <input type="text" id="input"></input>
    <div contenteditable="true" id="div"></div>
    <script>
      document.addEventListener("beforeinput", function(evt) { evt.preventDefault(); })
    </script>
  </body>
</html>
```

</details>

<details>
<summary>test.js</summary>

```js
import { Selector } from 'testcafe';

fixture `index`.page `./index.html`;

test('beforeinput fires on input', async t => {
    await t
        .typeText('#input', 'hello world')
        .expect(Selector('#input').value).eql('');
});

test('beforeinput fires on contenteditable', async t => {
    await t
        .typeText('#div', 'hello world')
        .expect(Selector('#div').innerText).eql('');
});
```

</details>

<details>
<summary>Your complete test report:</summary>

```
$ testcafe chrome test.js
Running tests in:
 - Chrome 79.0.3945.117 / macOS 10.15.2

 index
 ✓ beforeinput fires on input
 ✖ beforeinput fires on contenteditable

   1) AssertionError: expected 'hello world' to deeply equal ''

      Browser: Chrome 79.0.3945.117 / macOS 10.15.2

          9 |});
         10 |
         11 |test('beforeinput fires on contenteditable', async t => {
         12 |    await t
         13 |        .typeText('#div', 'hello world')
       > 14 |        .expect(Selector('#div').innerText).eql('');
         15 |});
         16 |

         at <anonymous> (/Users/dstrelau/src/dstrelau/testcafe-beforeinput/test.js:14:45)
         at <anonymous> (/Users/dstrelau/src/dstrelau/testcafe-beforeinput/test.js:11:1)
         at <anonymous>
      (/usr/local/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn
      (/usr/local/lib/node_modules/testcafe/src/test-run/index.js:294:19)
         at TestRun.start (/usr/local/lib/node_modules/testcafe/src/test-run/index.js:345:24)


 1/2 failed (5s)
```

</details>
 
### Your Environment details:
 
* testcafe version:                   `1.7.1`
* node.js version:                    `v13.2.0`
* command-line arguments:  `testcafe chrome test.js`
* browser name and version: `Chrome 79.0.3945.117`
* platform and version:          `macOS 10.15.2`

**Comment by AlexKamaev** [comment]
Thank you for your report. I was able to reproduce the issue.
