### ISSUE TITLE
ERROR TypeError: Cannot read property 'test' of undefined in version 1.8.0

### ISSUE THREAD

**Issue by devmondo** [DevExpress/testcafe#4661]
### What is your Test Scenario?
simple one from the docs
https://devexpress.github.io/testcafe/documentation/getting-started/ 
### What is the Current behavior?
just upgraded to 1.8.0 and wither you use CLI or programmatic interface we get this error:
ERROR TypeError: Cannot read property 'test' of undefined
it does not happen with 1.7.xxx

### What is the Expected behavior?
run as usual
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
ERROR TypeError: Cannot read property 'test' of undefined
    at C:\projects\test\testcafe-simple-test\node_modules\testcafe-browser-tools\src\api\get-installations.js:61:24
    at Array.some (<anonymous>)
    at addInstallation (C:\projects\test\testcafe-simple-test\node_modules\testcafe-browser-tools\src\api\get-installations.js:58:30)
    at async Promise.all (index 3)
    at searchInRegistry (C:\projects\test\testcafe-simple-test\node_modules\testcafe-browser-tools\src\api\get-installations.js:97:5)
    at findWindowsBrowsers (C:\projects\test\testcafe-simple-test\node_modules\testcafe-browser-tools\src\api\get-installations.js:104:39)
    at findBrowsers (C:\projects\test\testcafe-simple-test\node_modules\testcafe-browser-tools\src\api\get-installations.js:170:16)
    at Object.default_1 [as default] (C:\projects\test\testcafe-simple-test\node_modules\testcafe-browser-tools\src\api\get-installations.js:223:30)
    at Object.default_1 [as getBrowserInfo] (C:\projects\test\testcafe-simple-test\node_modules\testcafe-browser-tools\src\api\get-browser-info.js:24:27)
    at BrowserProviderPluginHost.isValidBrowserName (C:\projects\test\testcafe-simple-test\node_modules\testcafe\src\browser\provider\built-in\dedicated\base.js:25:29)
    at BrowserProvider.isValidBrowserName (C:\projects\test\testcafe-simple-test\node_modules\testcafe\src\browser\provider\index.ts:279:16)
    at Object.getBrowserInfo (C:\projects\test\testcafe-simple-test\node_modules\testcafe\src\browser\provider\pool.js:108:14)
    at async Promise.all (index 0)
    at Bootstrapper._getBrowserInfo (C:\projects\test\testcafe-simple-test\node_modules\testcafe\src\runner\bootstrapper.ts:206:29)
    at Bootstrapper.createRunnableConfiguration (C:\projects\test\testcafe-simple-test\node_modules\testcafe\src\runner\bootstrapper.ts:421:29)

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.8.0
* node.js version:                    12.6.0
* command-line arguments:  
* browser name and version: 
* platform and version:          Window x64 bit
* other:

**Comment by AndreyBelym** [comment]
Thank you for your report, I've reproduced the issue.
