### ISSUE TITLE
Errors in FireFox after switch to `useRole`

### ISSUE THREAD

**Issue by ChrisLane** [DevExpress/testcafe#4726]
### What is your Test Scenario?

Load a page using a role in FireFox

### What is the Current behavior?

Tests fail due to JS error
 
### What is the Expected behavior?

The test passes with no JS errors
 
### What is your web application and your TestCafe test code?

TestCafe code:
```js
fixture("Load OneView page tests")
    .page(process.env.CUBE19_APP_TEST_URL)
    .beforeEach(t => t
        .useRole(roleFromEnv)
        .addRequestHooks(cube19ApplicationLayerLogger)
        .click(appPage.menuBar.aONEVIEW))
    .afterEach(t => testAllResponses200(t, cube19ApplicationLayerLogger));

test("load oneview", t => t
    .expect(appPage.contentRegion.exists).ok()
    .expect(appPage.modalRegion.exists).ok()
    .expect(appPage.buildInfoRegion.exists).ok()
    .expect(appPage.cube19img.exists).ok()
    .expect(appPage.cube19footer.exists).ok());

```
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
Unable to provide app code at this time.

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>
[testcafe-src.zip](https://github.com/DevExpress/testcafe/files/4159404/testcafe-src.zip)
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```json
{
  "assertionTimeout": 10000,
  "browsers": ["firefox:headless"]
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
chris@cube19pc% testcafe firefox testcafe/test-oneview.js -t "load oneview" -d
Using locally installed version of TestCafe.
The "browsers", "filter" options from the configuration file will be ignored.
 Running tests in:
 - Firefox 72.0 / macOS 10.15

 Load OneView page tests
 ✖ load oneview

   1) - Error while restoring configuration after Role switch -
      A JavaScript error occurred on "http://localhost:4000/".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable
      the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      this.get(...) is undefined:
      canAccessApp@http://localhost:4000/build.js:245535:33
      userCanAccess@http://localhost:4000/build.js:154652:30
      shouldShowFn@http://localhost:4000/build.js:154237:22
      render/<@http://localhost:4000/build.js:154360:44
      filterFactory/filterSequence.__iterateUncached/<@http://localhost:4000/build.js:240186:25
      __iterate@http://localhost:4000/build.js:241927:17
      filterFactory/filterSequence.__iterateUncached@http://localhost:4000/build.js:240185:20
      __iterate@http://localhost:4000/build.js:239253:21
      forEach@http://localhost:4000/build.js:243301:21
      List/<@http://localhost:4000/build.js:241781:16
      withMutations@http://localhost:4000/build.js:241041:9
      List@http://localhost:4000/build.js:241779:22
      reify@http://localhost:4000/build.js:240669:61
      filter@http://localhost:4000/build.js:243616:16
      render@http://localhost:4000/build.js:154359:14
      finishClassComponent@http://localhost:4000/build.js:209433:37
      updateClassComponent@http://localhost:4000/build.js:209410:18
      beginWork@http://localhost:4000/build.js:209789:22
      performUnitOfWork@http://localhost:4000/build.js:211734:31
      workLoop@http://localhost:4000/build.js:211843:34
      callCallback@http://localhost:4000/build.js:200541:20
      dispatchEvent@http://10.244.113.136:64755/hammerhead.js:7:16258
      invokeGuardedCallbackDev@http://localhost:4000/build.js:200580:22
      invokeGuardedCallback@http://localhost:4000/build.js:200437:33
      performWork@http://localhost:4000/build.js:211961:36
      scheduleUpdateImpl@http://localhost:4000/build.js:212346:36
      scheduleUpdate@http://localhost:4000/build.js:212285:18
      scheduleTopLevelUpdate@http://localhost:4000/build.js:212547:25
      updateContainer@http://localhost:4000/build.js:212577:35
      renderSubtreeIntoContainer/<@http://localhost:4000/build.js:216215:25
      unbatchedUpdates@http://localhost:4000/build.js:212417:20
      renderSubtreeIntoContainer@http://localhost:4000/build.js:216214:23
      render@http://localhost:4000/build.js:216239:18
      onShow@http://localhost:4000/build.js:192739:42
      Marionette._triggerMethod</<@http://localhost:4000/src/libs/backbone.marionette.js:676:25
      triggerMethod@http://localhost:4000/src/libs/backbone.marionette.js:1925:28
      Marionette.triggerMethodOn@http://localhost:4000/src/libs/backbone.marionette.js:712:16
      show@http://localhost:4000/src/libs/backbone.marionette.js:1175:20
      execute/<@http://localhost:4000/build.js:180565:30
      triggerEvents@http://localhost:4000/src/libs/backbone.js:207:65
      trigger@http://localhost:4000/src/libs/backbone.js:149:32
      request/<@http://localhost:4000/build.js:244951:30

      Browser: Firefox 72.0 / macOS 10.15

         22 |
         23 |
         24 |fixture("Load OneView page tests")
         25 |    .page(process.env.CUBE19_APP_TEST_URL)
         26 |    .beforeEach(async t => await t
       > 27 |        .useRole(roleFromEnv)
         28 |        .addRequestHooks(cube19ApplicationLayerLogger)
         29 |        .click(appPage.menuBar.aONEVIEW))
         30 |    .afterEach(t => testAllResponses200(t, cube19ApplicationLayerLogger));
         31 |
         32 |test("load oneview", async t => await t

         at <anonymous> (/Users/chris/git/app-ui/testcafe/test-oneview.js:27:10)
         at <anonymous> (/Users/chris/git/app-ui/testcafe/test-oneview.js:24:1)
         at <anonymous> (/Users/chris/git/app-ui/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at TestRun._executeTestFn (/Users/chris/git/app-ui/node_modules/testcafe/src/test-run/index.js:294:19)
         at TestRun._runBeforeHook (/Users/chris/git/app-ui/node_modules/testcafe/src/test-run/index.js:316:31)
         at TestRun.start (/Users/chris/git/app-ui/node_modules/testcafe/src/test-run/index.js:344:24)


   2) - Error while restoring configuration after Role switch -
      Unhandled promise rejection:

        { code: 'E1', isTestCafeError: true, callsite: CallsiteRecord { filename: '/Users/chris/git/app-ui/testcafe/test-oneview.js', lineNum: 26, callsiteFrameIdx:
      6, stackFrames: [
      [CallSite],  [CallSite],
      [CallSite],  [CallSite],
      [CallSite],  [CallSite],
      [CallSite],  CallSite {},
      [CallSite],  [CallSite],
      CallSite {}, [CallSite],
      [CallSite],  [CallSite],
      [CallSite],  [CallSite],
      [CallSite],  [CallSite],
      [CallSite],  [CallSite]
      ], isV8Frames: true }, errStack: 'this.get(...) is

   undefined:\ncanAccessApp@http://localhost:4000/build.js:245535:33\nuserCanAccess@http://localhost:4000/build.js:154652:30\nshouldShowFn@http://localhost:4000/build.js:154237:22\nrender/<@http://localhost:4000/build.js:154360:44\nfilterFactory/filterSequence.__iterateUncached/<@http://localhost:4000/build.js:240186:25\n__iterate@http://localhost:4000/build.js:241927:17\nfilterFactory/filterSequence.__iterateUncached@http://localhost:4000/build.js:240185:20\n__iterate@http://localhost:4000/build.js:239253:21\nforEach@http://localhost:4000/build.js:243301:21\nList/<@http://localhost:4000/build.js:241781:16\nwithMutations@http://localhost:4000/build.js:241041:9\nList@http://localhost:4000/build.js:241779:22\nreify@http://localhost:4000/build.js:240669:61\nfilter@http://localhost:4000/build.js:243616:16\nrender@http://localhost:4000/build.js:154359:14\nfinishClassComponent@http://localhost:4000/build.js:209433:37\nupdateClassComponent@http://localhost:4000/build.js:209410:18\nbeginWork@http://localhost:4000/build.js:209789:22\nperformUnitOfWork@http://localhost:4000/build.js:211734:31\nworkLoop@http://localhost:4000/build.js:211843:34\ncallCallback@http://localhost:4000/build.js:200541:20\ndispatchEvent@http://10.244.113.136:64755/hammerhead.js:7:16258\ninvokeGuardedCallbackDev@http://localhost:4000/build.js:200580:22\ninvokeGuardedCallback@http://localhost:4000/build.js:200437:33\nperformWork@http://localhost:4000/build.js:211961:36\nscheduleUpdateImpl@http://localhost:4000/build.js:212346:36\nscheduleUpdate@http://localhost:4000/build.js:212285:18\nscheduleTopLevelUpdate@http://localhost:4000/build.js:212547:25\nupdateContainer@http://localhost:4000/build.js:212577:35\nrenderSubtreeIntoContainer/<@http://localhost:4000/build.js:216215:25\nunbatchedUpdates@http://localhost:4000/build.js:212417:20\nrenderSubtreeIntoContainer@http://localhost:4000/build.js:216214:23\nrender@http://localhost:4000/build.js:216239:18\nonShow@http://localhost:4000/build.js:192739:42\nMarionette._triggerMethod</<@http://localhost:4000/src/libs/backbone.marionette.js:676:25\ntriggerMethod@http://localhost:4000/src/libs/backbone.marionette.js:1925:28\nMarionette.triggerMethodOn@http://localhost:4000/src/libs/backbone.marionette.js:712:16\nshow@http://localhost:4000/src/libs/backbone.marionette.js:1175:20\nexecute/<@http://localhost:4000/build.js:180565:30\ntriggerEvents@http://localhost:4000/src/libs/backbone.js:207:65\ntrigger@http://localhost:4000/src/libs/backbone.js:149:32\nrequest/<@http://localhost:4000/build.js:244951:30\n',
      pageDestUrl: 'http://localhost:4000/' }

      Browser: Firefox 72.0 / macOS 10.15



 1/1 failed (1m 13s)
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Execute test on FireFox
2. See the error
 
### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    v13.7.0
* command-line arguments:  testcafe firefox:headless testcafe/test-oneview.js -t "load oneview"
* browser name and version: Firefox 72.0
* platform and version:          macOS 10.15

### More Info
While I was attempting to debug this issue I found that the JS error occurs because a function is called on an undefined `this`. This function should never be called unless all required app data has already loaded, meaning that `this` would never be undefined.

We log output when our required data is loaded. I added a `throw "function called here"` line and found that when the app is loaded via TestCafe at the point of `useRole(roleFromEnv)` being called, the "function called here" message occurs BEFORE all our required data is loaded.
When these steps are repeated normally by loading the app in FireFox, the "function called here" message only occurs AFTER all required data is loaded. This is why I believe that the issue is within TestCafe.

Interestingly, this issue does not occur if I run the test on Chrome or if I login via `.click()` and `.typeText()` functions. The issue appeared after I switched to using TestCafe Roles for logins.

**Comment by Farfurix** [comment]
@ChrisLane 

Hello,

It is difficult to find the cause of the issue without debugging your code. Could you please provide us with a sample project (or a public URL) and your test code? We will examine it and check for a suitable solution.
