### ISSUE TITLE
Tests fail when run together via cmdline, pass when run with individual js files

### ISSUE THREAD

**Issue by 14fordnw** [DevExpress/testcafe#4753]
### What is your Test Scenario?
Just testing if my endpoint renders correctly.
 
### What is the Current behavior?
When I run the tests as a group (testcafe chrome:headless <testingFolder>), 3 or 4 tests fail because they cannot find the DOM element specified in a Selector. When I take the file(s) with the errors and run them individually, the tests pass.
 
### What is the Expected behavior?
The tests should behave the same way, whether being ran individual or as a group. 
 
### What is your web application and your TestCafe test code?
all in development still :(
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
import { Selector, ClientFunction } from 'testcafe';
import config from '../../../Page-Models/ConfigManager.js';
import {LoginFunc} from '../../../Utility/LoginFunction.js';


//Headers
fixture `VotingAttendanceHeaders (BradTestGroup)`
    .page `${config.attdRptUrl}` //point to config file once dummy data in place
    .beforeEach(async (t) => {
        await LoginFunc(`${config.sigStaffUser}`, `${config.password}`);
})
    .afterEach(async t => {
    await t.eval(() => localStorage.clear());
});



test('VerifyLogoDisplayed', async t =>{
    const logoSelector = Selector('.logo');
    const logoURL = logoSelector.withAttribute('src', 
                    'https://3pl46c46ctx02p7rzdsvsg21-wpengine.netdna-ssl.com/wp-content/themes/bluetooth/images/logos/bluetooth-logo-color-black.svg');                   
    const timeHolder = await logoSelector();

    await t
        .expect(logoURL.exists).ok()
        .expect(logoSelector.visible).ok();
       
});

test('VerifyAttendanceReportTitle', async t =>{
    const titleSelector  = Selector('#app').find('h1').withText('Attendance');
    const timeHolder = await titleSelector();

    await t
        .expect(titleSelector.textContent).eql(' Attendance Report (Brad\'s Test Group) ');
});

test('VerifyGroupPageLinkDisplayed', async t => {
    const gpLinkSelector = Selector('#app').find('button').withText('Group');
    const timeHolder = await gpLinkSelector();

    await t
        .expect(gpLinkSelector.textContent).eql(' Group Page ');

});

//
// //Change, currently set to 'John Smith'. Uncomment once feature enabled
// test('VerifyUserLinkDisplayed', async t => {
//     const userLink = Selector('a').withText('John smith');

//     await t.expect(userLink.textContent).eql('John smith');
// });

//change to check url HTTP code once user roles enabled.
test('VerifyLogoutButtonDisplayed', async t => {
    const logoutLink = Selector('a').withText('Log Out');
    // const status = await getRequestResult(logoutLink.url);
    // console.log(logoutLink.url);
    // console.log(status);
    const timeHolder = await logoutLink();
    await t
        .expect(logoutLink.textContent).eql('Log Out');
        // .expect(status).notEql(404);
});

 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
 VA_DropDownSelectionValidation (BradTestGroup)
 √ EventTypeOptions
 √ ResultsFilterOptions

 VotingAttendanceFooters (BradTestGroup)
 √ VerifyCopyright2020
 × VerifyPrivacyLink (screenshots: C:\Git\RQE.VA_Azure\screenshots\2020-02-11_10-57-05\test-4\Chrome_75.0.3770.80_Windows_10\errors\1.png)

   1) AssertionError: expected 'https://va.btstage.net/group/503/attendance' to include '/privacy'

      Browser: Chrome 75.0.3770.80 / Windows 10
      Screenshot: C:\Git\RQE.VA_Azure\screenshots\2020-02-11_10-57-05\test-4\Chrome_75.0.3770.80_Windows_10\errors\1.png

         26 |    const timer = await privacyLink();
         27 |
         28 |    await t
         29 |        .expect(privacyLink.textContent).eql('Privacy')
         30 |        .click(privacyLink)
       > 31 |        .expect(getPageUrl()).contains('/privacy');
         32 |});
         33 |
         34 |test('VerifyTermsOfUse', async t => {
         35 |    const termsLink = Selector('.small').find('a').withText('Terms Of Use');
         36 |    const timer = await termsLink();

         at <anonymous> (C:\Git\RQE.VA_Azure\TestSuite\Group_EventAttendance\TestCase\Footers.js:31:31)


 √ VerifyTermsOfUse
 √ VerifyCodeOfConduct
 √ VerifyCopyrightPolicy
 √ VerifySIGPoliciesRules

 VotingAttendanceHeaders (BradTestGroup)
 √ VerifyLogoDisplayed
 × VerifyAttendanceReportTitle (screenshots: C:\Git\RQE.VA_Azure\screenshots\2020-02-11_10-57-05\test-10\Chrome_75.0.3770.80_Windows_10\errors\1.png)

   1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

         | Selector('#app')
       > |   .find('h1')
         |   .withText('Attendance')

      Browser: Chrome 75.0.3770.80 / Windows 10
      Screenshot: C:\Git\RQE.VA_Azure\screenshots\2020-02-11_10-57-05\test-10\Chrome_75.0.3770.80_Windows_10\errors\1.png

         31 |test('VerifyAttendanceReportTitle', async t =>{
         32 |    const titleSelector  = Selector('#app').find('h1').withText('Attendance');
         33 |    const timeHolder = await titleSelector();
         34 |
         35 |    await t
       > 36 |        .expect(titleSelector.textContent).eql(' Attendance Report (Brad\'s Test Group) ');
         37 |});
         38 |
         39 |test('VerifyGroupPageLinkDisplayed', async t => {
         40 |    const gpLinkSelector = Selector('#app').find('button').withText('Group');
         41 |    const timeHolder = await gpLinkSelector();

         at <anonymous> (C:\Git\RQE.VA_Azure\TestSuite\Group_EventAttendance\TestCase\Headers.js:36:44)


 √ VerifyGroupPageLinkDisplayed
 √ VerifyLogoutButtonDisplayed

 Test Date Picker
 × VerifyFromDatePicker (screenshots: C:\Git\RQE.VA_Azure\screenshots\2020-02-11_10-57-05\test-13\Chrome_75.0.3770.80_Windows_10\errors\1.png)

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('.vdp-datepicker')
         |   .find('div')
         |   .find('input')

      Browser: Chrome 75.0.3770.80 / Windows 10
      Screenshot: C:\Git\RQE.VA_Azure\screenshots\2020-02-11_10-57-05\test-13\Chrome_75.0.3770.80_Windows_10\errors\1.png

         20 |
         21 |//Verify that on clicking the FROM date field, a calendar widget should open
         22 |test('VerifyFromDatePicker', async t => {
         23 |    const timer = await fDatePicker();
         24 |    await t
       > 25 |        .click(fDatePicker)
         27 |});
         28 |
         29 |//Verify that on clicking the TO date field, a calendar widget should open
         30 |test('VerifyToDatePicker', async t => {

         at <anonymous> (C:\Git\RQE.VA_Azure\TestSuite\Group_EventAttendance\TestCase\VerifyDatePicker.js:25:10)


 √ VerifyToDatePicker


 3/14 failed (2m 55s)
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    6.13.6
* command-line arguments:  "testcafe chrome:headless TestSuite\**\*"
* browser name and version:  Chrome 75.0.3770.80
* platform and version:          Windows 10
* other:                                   I added the afterEach local storage clearance to the fixture, but the tests still fail when they are run as a group. If i type testcafe chrome:headless headers.js, all pass.
![2020-02-11_11-08-32](https://user-images.githubusercontent.com/49650750/74271783-59ab8200-4cc2-11ea-93fb-152c296df523.png)

**Comment by Farfurix** [comment]
@14fordnw 

Hello,

This information is not sufficient to reproduce the issue. As far as I understand, the issue may occur when you start running your test. I suggest you use some timeouts in this case:
1. [`option.timeout` in the problematic `Selector`](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/selector-options.html#optionstimeout)
2. [Page load timeout](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#setting-page-load-timeout)

If it doesn't resolve the "... the specified selector does not match any node in the DOM tree" error, you can share a small project with us or a public URL. We will examine it and check for a suitable solution.

**Comment by 14fordnw** [comment]
@Farfurix I will try this tomorrow and let you know how it goes. Thanks for the support! 👍

**Comment by 14fordnw** [comment]
We are still having the issue even with the timout options enabled. We have gotten around this by running multiple scripts with the test: tag when our CI Pipeline calls npm test.

**Comment by 14fordnw** [comment]
Edit: running two testcafe commands still gives us the same error. When I run the individual file manually, it passes. If its part of a group run, it fails.

**Comment by 14fordnw** [comment]
Final update, I am able to tag -q and succesfully test. The three appear to past but are tagged as unstable
