### ISSUE TITLE
Should not finalize the "ExecuteSelectorCommand" command on driver starting

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#4855]
Example (pseudo code):
```js
  await t
    .click('a[target=blank]')
   .click('link on child page') // a few page redirects here
    .expect(('selector-on-child-page').textContent).ok()
```

The test execution report will contain the following error:
```js
TypeError: Cannot read property '0' of null
    at DecodingTransformer.transform (C:\repos\testcafe\node_modules\replicator\index.js:279:27)
    at module.exports.Replicator.decode (C:\repos\testcafe\node_modules\replicator\index.js:565:24)
    at SelectorBuilder._processResult (C:\repos\testcafe\src\client-functions\client-function-builder.js:146:32)
    at SelectorBuilder._processResult (C:\repos\testcafe\src\client-functions\selectors\selector-builder.js:197:32)
    at re_executable_promise_1.default.fromFn (C:\repos\testcafe\src\client-functions\client-function-builder.js:141:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Found in 'Login via Google' case.

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe/commit/36337d3afcc2c2954530b1e5d8a271fef8ed5dbb
