### ISSUE TITLE
Javascript error on fileupload

### ISSUE THREAD

**Issue by JohnBerendsenQA** [DevExpress/testcafe#4965]
### What is your Test Scenario?
Upload file to a file upload input element
 
### What is the Current behavior?
A JavaScript error occurred on 
JavaScript error details:
TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.
    at FormData.r.FormData.r.FormData.append (http://10.49.5.89:53610/hammerhead.js:12:24062)
    at t.Constructor.d.startUpload (https://portaltest.entreepgb.svb.nl/Scripts-built/app/modules/shared/layoutbundle/_layout.js?v=012028140:39:5167)
    at v (https://portaltest.entreepgb.svb.nl/Scripts-built/app/modules/shared/layoutbundle/_layout.js?v=012028140:39:12109)
    at b (https://portaltest.entreepgb.svb.nl/Scripts-built/app/modules/shared/layoutbundle/_layout.js?v=012028140:39:12424)
    at Constructor.m.fileProcessor (https://portaltest.entreepgb.svb.nl/Scripts-built/app/modules/shared/layoutbundle/_layout.js?v=012028140:39:12805)
    at HTMLInputElement.a (https://portaltest.entreepgb.svb.nl/Scripts-built/app/modules/shared/layoutbundle/_layout.js?v=012028140:21:7069)
    at HTMLInputElement.dispatch (https://portaltest.entreepgb.svb.nl/Scripts-built/vendor/jquery/jquery-3.3.1.js?v=012028140:3:19185)
    at HTMLInputElement.v.handle (https://portaltest.entreepgb.svb.nl/Scripts-built/vendor/jquery/jquery-3.3.1.js?v=012028140:3:17053)
    at HTMLInputElement.dispatchEvent (http://10.49.5.89:53610/hammerhead.js:7:29559)
    at e.t._raiseDispatchEvent (http://10.49.5.89:53610/hammerhead.js:9:1114)
 
### What is the Expected behavior?
File upload succeeds without js errors
 
### What is your web application and your TestCafe test code?
<details>
<summary>Your website URL (or attach your complete example):</summary>
```
***************************
<widget-uploadcontrol params="id: 'tkbFileUpload', data: uploadfile, label: 'TKB uploaden&nbsp;*'"><div class="form-group">
	<div class="col-sm-5 control-label">
		<h5 data-bind="text: label">TKB uploaden&nbsp;*</h5>
	</div>
	<div class="col-sm-7">
		<div class="well well-dashed filedrag" data-bind="fileDrag: $component.data.fileProcessor, hasMultiUpload: $component.data.hasMultiUpload" file-drag-injected="1">
            <fieldset>
                <legend data-bind="text:label" class="sr-only">TKB uploaden&nbsp;*</legend>
                <input class="sr-only" title="Bestand uploaden van uw computer" type="file" data-bind="file: $component.data.fileProcessor, attr: {multiple: $component.data.hasMultiUpload, 'data-ui': 'fileProcessor' + id, id: id }" multiple="true" data-ui="fileProcessortkbFileUpload" id="tkbFileUpload">
                <label class="btn btn-primary" data-bind="attr: {for: id}" for="tkbFileUpload">Kies een bestand</label>
            </fieldset>
			
			<div class="margin-top hidden-xs hidden-sm" data-bind="text: $component.data.hasMultiUpload() ? 'Of sleep één of meerdere bestand(en) naar dit vak' : 'Of sleep een bestand naar dit vak'">Of sleep één of meerdere bestand(en) naar dit vak</div>
                <small class="margin-top block">
                Toegestane bestandsformaten zijn <span data-bind="text: $component.data.geaccepteerdeFileTypes()">.xml</span>, maximaal <span data-bind="text: $component.data.maximumFileSizeInMb()">10 MB</span><!-- ko if: $component.data.maximumSharedFileSize() !== 0--><!-- /ko-->.
                </small>
            </div>

		<div data-bind="if: $component.data.alleUploadFiles().length > 0"></div>

	</div>
</div>

<widget-validationmessage params="field: $component.data.isAllesKlaarMetUploaden"><div class="validation-message-container" data-bind="validationElement: field">
    <div class="clearfix padding-bottom--2 negative-margin-top--1">
        
        <!-- ko if: $data.errorMessageClass --><!-- /ko -->

        <!-- ko ifnot: $data.errorMessageClass -->
        <span class="col-sm-7 col-sm-offset-5 validation-error-message" data-ui="" data-bind="validationMessage: field, attr: { 'data-ui': $data.dataUi === undefined ? '' : $data.dataUi }" style="display: none;"></span>    
        <!-- /ko -->
        
    </div>
</div></widget-validationmessage></widget-uploadcontrol>
******************************************************
```
</details>
<details>
<summary>Your complete test code (or attach your test files):</summary>
```

import { Selector as $ } from 'testcafe'

fixture`F-Domein`

test('A. TKB Uploaden > TKB wordt verwerkt', async t => {
  await t.navigateTo('xxxxxxxxxxx')
  var tkbUploadInput = $('[data-ui="fileProcessortkbFileUpload"]') // input type="file"
  await t.setFilesToUpload(tkbUploadInput, 'C:\\test-projects\\pgb-env-intake-smoke-test\\lib\\assets\\STUF_Template.xml')
})
```

```
</details>

<details>
<summary>Your complete test report:</summary>

A JavaScript error occurred on "https://portaltest.entreepgb.svb.nl/#/tkb2/upload".
Repeat test actions in the browser and check the console for errors.
If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
If this error does not occur, please write a new issue at:
"https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

JavaScript error details:
TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.
    at FormData.r.FormData.r.FormData.append (http://10.49.5.89:53610/hammerhead.js:12:24062)
    at t.Constructor.d.startUpload (https://portaltest.entreepgb.svb.nl/Scripts-built/app/modules/shared/layoutbundle/_layout.js?v=012028140:39:5167)
    at v (https://portaltest.entreepgb.svb.nl/Scripts-built/app/modules/shared/layoutbundle/_layout.js?v=012028140:39:12109)
    at b (https://portaltest.entreepgb.svb.nl/Scripts-built/app/modules/shared/layoutbundle/_layout.js?v=012028140:39:12424)
    at Constructor.m.fileProcessor (https://portaltest.entreepgb.svb.nl/Scripts-built/app/modules/shared/layoutbundle/_layout.js?v=012028140:39:12805)
    at HTMLInputElement.a (https://portaltest.entreepgb.svb.nl/Scripts-built/app/modules/shared/layoutbundle/_layout.js?v=012028140:21:7069)
    at HTMLInputElement.dispatch (https://portaltest.entreepgb.svb.nl/Scripts-built/vendor/jquery/jquery-3.3.1.js?v=012028140:3:19185)
    at HTMLInputElement.v.handle (https://portaltest.entreepgb.svb.nl/Scripts-built/vendor/jquery/jquery-3.3.1.js?v=012028140:3:17053)
    at HTMLInputElement.dispatchEvent (http://10.49.5.89:53610/hammerhead.js:7:29559)
    at e.t._raiseDispatchEvent (http://10.49.5.89:53610/hammerhead.js:9:1114)

Browser: Chrome 80.0.3987.149 / Windows 10
Screenshot: C:\test-projects\pgb-env-intake-smoke-test\screenshots\2020-04-09_09-25-56\test-1\Chrome_80.0.3987.149_Windows_10\errors\1.png

    7 |  confirmButton: $('.btn-success').withText('Indienen'),
    8 |
    9 |  async uploadTkB2 () {
   10 |    await t
   11 |      .click(this.uploadButton)
 > 12 |      .setFilesToUpload(this.thbUploadInput, 'C:\\test-projects\\pgb-env-intake-smoke-test\\lib\\assets\\STUF_Template.xml')
   13 |      .click(this.nextStepButton)
   14 |  }
   15 |}
   16 |
   17 |export default { ...tkb2UploadsPage }

   at <anonymous> (C:\test-projects\pgb-env-intake-smoke-test\pages\tkb2UploadsPage.js:12:8)
   at Object.uploadTkB2 (C:\test-projects\pgb-env-intake-smoke-test\pages\tkb2UploadsPage.js:9:23)
   at <anonymous> (C:\test-projects\pgb-env-intake-smoke-test\tests\fDomeinTest.js:18:25) 
```

```
</details>

<details>
<summary>Screenshots:</summary>
<!-- If applicable, add screenshots to help explain the issue. -->

```

```
</details>

### Steps to Reproduce:
<!-- Describe what we should do to reproduce the behavior you encountered. -->

1. Go to upload form
3. Execute this command: setFilesToUpload
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.8.4-rc.1
* node.js version:                    v12.13.1
* command-line arguments:  --screenshots path=./screenshots,takeOnFails=true,fullPage=true chrome:headless tests/fDomeinTest.js --reporter nunit:te-report.xml,html:report-te.html"
* browser name and version: Browser: Chrome 80.0.3987.149
* platform and version:          Windows 10
* other:                                  The Application under test is a government application with heavy security/privacy policies. I wish I could provide you access on either a test or dev environment or supply the project to you but this is simply not possible. Hopefully the supplied info is sufficient to fix it. If you need anymore info please let me know.

**Comment by AlexKamaev** [comment]
This information is insufficient to reproduce the issue. Since you cannot share your project here, please provide us with a sample that demonstrates the issue.

Based on the description, I can only recommend you use the `--skip-js-errors` options. The issue may not be related to TestCafe. So, please check your browser console without TestCafe as well.
