### ISSUE TITLE
I have been unable to get testcafe working with electron in a headless environment

### ISSUE THREAD

**Issue by alwick** [DevExpress/testcafe#5099]
I am trying to build and test my electron application in a debian-node base image using xvfb for the x11 display.

Here is my dockerfile
```
FROM node:13.4.0-buster AS builder

ENV DEBIAN_FRONTEND noninteractive

# Python dependencies in some npm modules
RUN apt-get update && \
    apt-get install -y -q curl && \
    apt-get install -y gnupg libx11-xcb1 libgtk2.0-0 libxtst6 libxss1 libnss3 libasound2 xorg && \
    apt-get install -y fluxbox && \
    apt-get remove -y cmdtest

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update

RUN apt-get install yarn git git-lfs -y && \
    apt-get install --fix-missing -y xvfb
#  apk --no-cache add --virtual native-deps git openssh-client \
#  g++ gcc libgcc libstdc++ linux-headers make python && \
#  npm install --quiet

# Create directory for the application
WORKDIR /app

COPY package.json yarn.lock 

# Docker base image is already NODE_ENV=production
RUN npm i -g testcafe && \
    yarn

# Build the tests
RUN yarn build-e2e
RUN export NODE_ENV=development && \
    xvfb-run -e /dev/stdout -s '-screen 0 1024x768x24' testcafe electron:./app ./test/e2e/*.js
```

Everything builds and when it gets to the last command I get the following:
Using locally installed version of TestCafe.

```
ERROR Was unable to open the browser "electron:./app" due to error.

Error: Unable to connect
    at NodeInspect._callee2$ (/app/node_modules/testcafe-browser-provider-electron/lib/node-inspect.js:123:39)
    at tryCatch (/app/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/app/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/app/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

These are the testcafe npm versions:
```
    "testcafe": "^1.8.4",
    "testcafe-browser-provider-electron": "^0.0.14",
    "testcafe-live": "^0.1.4",
    "testcafe-react-selectors": "^3.3.0",
```

**Comment by LavrovArtem** [comment]
Could you please add the line below, run your tests and send us the output?

```export DEBUG="testcafe:browser-provider-electron"```

**Comment by alwick** [comment]
testcafe:browser-provider-electron:spawn:stderr [122:0520/185130.933152:FATAL:atom_main_delegate.cc(211)] Running as root without --no-sandbox is not supported. 
See https://crbug.com/63818ERROR Was unable to open the browser "electron:./app" due to error.

**Comment by SergeyShurygin** [comment]
This question was already answered on SO: [https://stackoverflow.com/questions/61920843/issue-running-testcafe-with-electron-in-a-headless-container](https://stackoverflow.com/questions/61920843/issue-running-testcafe-with-electron-in-a-headless-container), so I'm closing this issue.
