### ISSUE TITLE
Uncaught exception: socket has been ended by the other party

### ISSUE THREAD

**Issue by Arthy000** [DevExpress/testcafe#5443]
Hello!

I implemented a runner for the project I'm working on using the TestCafe API.
With my coworkers, we noticed that some tests started failing after we upgraded NodeJS past version 10.15.3
(basically, no problem with 10.15.3 or below, but anything newer and we get the issue described here)

We randomly receive the following error:
```
× Scenario: Successful registration process (single step)
   1) Uncaught exception:
      Error: This socket has been ended by the other party
      at TLSSocket.writeAfterFIN [as write] (net.js:407:14)
      at Socket.ondata (_stream_readable.js:713:22)
      at Socket.emit (events.js:200:13)
      at Socket.EventEmitter.emit (domain.js:471:20)
      at addChunk (_stream_readable.js:294:12)
      at readableAddChunk (_stream_readable.js:275:11)
      at Socket.Readable.push (_stream_readable.js:210:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
      Browser: Chrome 84.0.4147.125 / Windows 10
```
Otherwise, the test itself does not have any reason to fail (one test will be fine for several runs, then fail with that error - and only that error)

I manage to trigger it by chaining a lot of navigateTo to our website.
=> I usually get a few fails out of 10 identical tests (see the test code)

My investigation so far shows that it seems to be linked to our usage of WebSocket.
The issue **only happens with Chrome**, but we want coverage of all browsers (plus Firefox seems to not always close properly but that's an issue for another time)
**Downgrading NodeJS solves the issue** but the rest of the project now relies on a newer version, meaning we have to switch back and forth, which is not ideal.

I'm not sure you will have access to the website in the example - it is protected against access out of belgium. I might be able to arrange something if needed.
I've reproduced the issue with another website (a completely different front-end, that we started from scratch so it does not have much in common with the current site)
I was NOT able to reproduce the issue with external websites that use WebSocket (again, we might have a heavier load on the WS than the websites I tried)
 
<details>
<summary>Your website URL (or attach your complete example):</summary>
https://www.circus.be
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture`Test the runner`;

test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
test('Basic V3 test', async (t) => {
  await t.navigateTo('https://www.circus.be').wait(5000);
});
```
</details>
 
### Your Environment details:
 
* testcafe version:  1.9.1                 
* node.js version:   12.18.3                 
* browser name and version: Chrome 84 
* platform and version:   Windows 10       

[report.zip](https://github.com/DevExpress/testcafe/files/5108979/report.zip)

**Comment by Farfurix** [comment]
@Arthy000

> I'm not sure you will have access to the website in the example - it is protected against access out of Belgium. I might be able to arrange something if needed.

I wasn't able to find any available Belgium proxy. Could you help us here? For example, you can add our public IP (188.128.36.80) to the "green" IP list or give us some proxy (you can use our support@devexpress.com mailbox to share private information with us).

**Comment by Arthy000** [comment]
Hello, sorry for the delay, I was taking some time off. I'll ask if we can greenlist your public IP and keep you posted.

**Comment by Arthy000** [comment]
Hello again, the public IP has been whitelisted, you should be able to access circue.be :D

**Comment by Farfurix** [comment]
@Arthy000 

Hello,

I tried to reproduce the issue, but there were some connection issues (not related to TestCafe). We need some time to examine your case.

For the team.
I wasn't able to reproduce the "TLSSocket" error. The website's main page is not reachable due to some website checks, I guess:
![Capture](https://user-images.githubusercontent.com/30019338/93330603-b1493780-f827-11ea-88cb-4eeb203596f7.PNG)

**Comment by Farfurix** [comment]
@Arthy000 

I came back to research the issue, but I couldn't go to the website using our public IP. Could you please help us with this connection issue?

**Comment by Arthy000** [comment]
Damn, sorry about that.

Do you have the same problem if you try to access it normally ? (without testcafé?) 
I need to know if it's still linked to your location or not.

**Comment by Farfurix** [comment]
@Arthy000 

Yes, I have the same problem without using TestCafe:
![Capture](https://user-images.githubusercontent.com/30019338/93564627-aeb72100-f992-11ea-85c8-834f545996f0.PNG)

**Comment by Arthy000** [comment]
Can you please try again?
(I'm not the one doing the configuration, I'm just acting as a messenger atm)

**Comment by Farfurix** [comment]
@Arthy000 

Thank you, your website is reachable now. However, I sometimes have an unstable connection:
![Capture](https://user-images.githubusercontent.com/30019338/93580876-08c2e100-f9a9-11ea-8dc3-9a1ffc312cf6.PNG)

We need some time to examine your website code.
