### ISSUE TITLE
TestCafe not running on MacOS after installation

### ISSUE THREAD

**Issue by MrSrsen** [DevExpress/testcafe#5531]
### What is your Test Scenario?
None.
 
### What is the Current behavior?
TestCafe is not running.
 
### What is the Expected behavior?
TestCafe is running.
 
### Steps to Reproduce:

1. Install TestCafe with: `npm install -g testcafe`
2. Run: `testcafe`
 
### Console output:

```
> testcafe
ERROR TypeError: "listener" argument must be a function
    at _addListener (events.js:239:11)
    at Server.addListener (events.js:297:10)
    at new Server (_http_server.js:269:10)
    at createServer (http.js:34:10)
    at new Proxy (/usr/local/lib/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/proxy/index.js:91:20)
    at new TestCafe (/usr/local/lib/node_modules/testcafe/src/testcafe.js:30:41)
    at Object.construct (/usr/local/lib/node_modules/testcafe/node_modules/import-lazy/index.js:19:20)
    at Object.createTestCafe [as default] (/usr/local/lib/node_modules/testcafe/src/index.js:74:22)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

Type "testcafe -h" for help.
```
 
### Your Environment details:
 
* testcafe version:                   1.9.2
* node.js version:                    v8.11.3
* npm version:                        5.6.0
* platform and version:          MacOS 10.14.6; Darwin Kernel Version 18.7.0

---

I installed TestCafe on Ubuntu today and it worked perfectly, then on MacOS and I can't even run it.

**Comment by AndreyBelym** [comment]
Thank you for your report. Node.js 8 is outdated and is not supported by Node.js Foundation since 01/01/2020: [nodejs/Releases](https://github.com/nodejs/Release#end-of-life-releases). TestCafe doesn't support out-of-support Node.js versions. The minimal required Node.js version is 10: [package.json](https://github.com/DevExpress/testcafe/blob/master/package.json#L19). Please update your Node.js or use an older TestCafe version that is compatible with Node.js 8.
