### ISSUE TITLE
RangeError [ERR_INVALID_OPT_VALUE]: The value "7662819937" is invalid for option "size"

### ISSUE THREAD

**Issue by andrzej-kodify** [DevExpress/testcafe#5547]
### What is your Test Scenario?
I'm running a long set of tests over resource heavy website
 
### What is the Current behavior?
At some point tests crash with an error
```
/home/runner/work/xxx/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/connection-reset-guard.js:21
  throw err;
  ^

RangeError [ERR_INVALID_OPT_VALUE]: The value "7662819937" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:382:3)
    at Function.concat (buffer.js:563:25)
    at IncomingMessage.<anonymous> (/home/runner/work/xxx/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/utils/promisify-stream.js:10:38)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:548:15)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_INVALID_OPT_VALUE',
  domainThrown: true
}
Thrown at:
    at addCodeToName (internal/errors.js:301:11)
    at NodeError (internal/errors.js:268:7)
    at buffer.js:360:11
    at hidden (internal/errors.js:288:14)
    at allocUnsafe (buffer.js:382:3)
    at concat (buffer.js:563:25)
    at /home/runner/work/xxx/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/utils/promisify-stream.js:10:38
    at emit (events.js:326:22)
    at EventEmitter.emit (domain.js:548:15)
    at endReadableNT (_stream_readable.js:1252:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
```

The issue is not bound to a specific test as far as I can see
 
### What is the Expected behavior?
Best case scenario would be to find a fix, but I'd at least expect that tests can continue execution even if an error happens.
 
### What is your web application and your TestCafe test code?
Can't share :(

### Steps to Reproduce:
I couldn't isolate steps to reproduce other than just running my large test suite

### Your Environment details:
 
* testcafe version:                  1.8.8
* node.js version:                    14.10.1
* browser name and version: Chrome
* platform and version:          macOS 10.15.6

**Comment by miherlosev** [comment]
Hi @andrzej-kodify 
 
It looks like TestCafe is trying to process a very large file. Try to increase the memory limit for the Node.js process and let us know your results:

```js
node --max-old-space-size=2048 node_modules/.bin/testcafe chrome tests
```

**Comment by andrzej-kodify** [comment]
Hi @miherlosev 

I already have it at `--max-old-space-size=3072` any hints on my side on what exactly is it trying to process?

**Comment by miherlosev** [comment]
Hi @andrzej-kodify 
 
> any hints on tracing on my side on what exactly is it trying to process?
 
TestCafe has internal logging functionality that is implemented with the [debug](https://www.npmjs.com/package/debug) module.
Could you please run the following command:

```js
set DEBUG=hammerhead:*
testcafe chrome index.js 2> hammerhead.log
```

and share the 'hammerhead.log' file.

**Comment by andrzej-kodify** [comment]
Thanks, I think I've found it. It was huge video file that wasn't properly intercepted by one of my mocks.
I still think this might be improved a bit, by for example giving better error message or even limiting the file size for processing and throwing an error based on content-size header or something like that.

**Comment by miherlosev** [comment]
Yes, it's a good idea. We can improve the error message.
For example, it will look like this:

```js
Cannot fetch data for the <url> resource due to the error:
Original error message:
Original error stack:
```
