### ISSUE TITLE
Please add support for Optional Chaining (Elvis) & Nullish Operators

### ISSUE THREAD

**Issue by PaulMEdwards** [DevExpress/testcafe#5587]
I would like to be able to use the Optional Chaining & Nullish Operators in my test code to simplify it and make it more readable.

Attempting to do so results in `Unexpected token` errors.

```
➜  verus-test git:(master) ✗ npx testcafe chrome specs/* --env=stage_securus -c 4 -s takeOnFails=false
The "screenshots.takeOnFails" option from the configuration file will be ignored.
ERROR Cannot prepare tests due to an error.

SyntaxError: /Users/pauledwards/Projects/Cogility/verus-test/pageobjects/App.page.js: Unexpected token (183:40)
  181 |                             );
  182 | 
> 183 |                             if (session?.authenticated?.username) {
      |                                         ^
  184 |                                 loggedIn = true;
  185 |                             }
  186 |                             attempts += 1;
    at Object.<anonymous> (/Users/pauledwards/Projects/Cogility/verus-test/pageobjects/Calls.page.js:3:1)
    at Object.<anonymous> (/Users/pauledwards/Projects/Cogility/verus-test/specs/e2e/calls.spec.js:4:1)
```

```
➜  verus-test git:(maintenance-20200928) ✗ npx testcafe chrome specs/* --env=stage_securus -c 6 -q -s takeOnFails=false -F "Calls.*|Dashboard.*"
The "filter", "screenshots.takeOnFails" options from the configuration file will be ignored.
ERROR Cannot prepare tests due to an error.

SyntaxError: /Users/pauledwards/Projects/Cogility/verus-test/pageobjects/App.page.js: Unexpected token (111:87)
  109 |         try {
  110 |             session =
> 111 |                 JSON.parse(await api.getLocalStorage(api.localStorageAuthSessionKey)) ??
      |                                                                                        ^
  112 |                 null;
  113 |         } catch (error) {
  114 |             // ignore failure
    at Object.<anonymous> (/Users/pauledwards/Projects/Cogility/verus-test/pageobjects/Calls.page.js:3:1)
    at Object.<anonymous> (/Users/pauledwards/Projects/Cogility/verus-test/specs/e2e/calls.spec.js:4:1)
```

Using these new operators requires node 14, which I have installed. Performing additional research indicates that the Babel modules to support this are only available in Babel 7 with TypeScript 3.7 while TestCafe is still using Babel 6.22 and TypeScript 3.3.

#3425 would therefore be a prerequisite for supporting these new operators.

**Comment by miherlosev** [comment]
Hi @PaulMEdwards 

Thank you for your inquiry. This functionality will be implemented in the context of #3425.
