### ISSUE TITLE
Investigate the problem with BrowserProvider caused by extended log reporter

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5589]
RROR TypeError: Cannot read property 'config' of undefined

[03:43:20] at BrowserProviderPluginHost.isHeadlessBrowser (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\browser\provider\built-in\dedicated\base.js:46:51)

[03:43:20] at BrowserProvider.isHeadlessBrowser (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\browser\provider\index.ts:265:28)

[03:43:20] at BrowserConnection.isHeadlessBrowser (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\browser\connection\index.ts:422:30)

[03:43:20] at Object.getBrowser [as default] (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\utils\get-browser.ts:13:77)

[03:43:20] at TestController._browser$getter (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\api\test-controller\index.js:183:26)

[03:43:20] at TestController.fn (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\utils\delegated-api.js:39:36)

[03:43:20] at Reporter._prepareReportTestActionEventArgs (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\reporter\index.js:193:41)

[03:43:20] at Reporter._onTaskTestActionDone (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\reporter\index.js:305:29)

[03:43:20] at C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\reporter\index.js:350:59

[03:43:20] at C:\BuildAgent\work\3dedf19a4f79c665\node_modules\emittery\index.js:69:13

[03:43:20]

[03:43:20]Type "testcafe -h" for help.

[03:43:20]TypeError: Cannot read property 'config' of undefined

[03:43:20] at BrowserProviderPluginHost.isHeadlessBrowser (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\browser\provider\built-in\dedicated\base.js:46:51)

[03:43:20] at BrowserProvider.isHeadlessBrowser (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\browser\provider\index.ts:265:28)

[03:43:20] at BrowserConnection.isHeadlessBrowser (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\browser\connection\index.ts:422:30)

[03:43:20] at Object.getBrowser [as default] (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\utils\get-browser.ts:13:77)

[03:43:20] at TestController._browser$getter (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\api\test-controller\index.js:183:26)

[03:43:20] at TestController.fn (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\utils\delegated-api.js:39:36)

[03:43:20] at Reporter._prepareReportTestActionEventArgs (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\reporter\index.js:193:41)

[03:43:20] at Reporter._onTaskTestActionDone (C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\reporter\index.js:305:29)

[03:43:20] at C:\BuildAgent\work\3dedf19a4f79c665\node_modules\testcafe\src\reporter\index.js:350:59

[03:43:20] at C:\BuildAgent\work\3dedf19a4f79c665\node_modules\emittery\index.js:69:13

**Comment by wentwrong** [comment]
Possibly related: https://github.com/DevExpress/testcafe/issues/5360#issuecomment-665464600 (the same error occurred)

> 02:16:38 Tue, 28 Jul 2020 23:16:38 GMT testcafe:browser:connection:EEZ29 TypeError: Cannot read property 'config' of undefined
02:16:38 at BrowserProviderPluginHost.isHeadlessBrowser (C:\Users\Administrator.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\provider\built-in\dedicated\base.js:45:47)
02:16:38 at BrowserProvider.canUseDefaultWindowActions (C:\Users\Administrator.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\provider\index.ts:215:53)
02:16:38 at BrowserProvider.closeBrowser (C:\Users\Administrator.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\provider\index.ts:276:44)
02:16:38 at BrowserConnection._closeBrowser (C:\Users\Administrator.jenkins\workspace\Regression\TestCafe\node_modules\testcafe\src\browser\connection\index.ts:178:13)

**Comment by wentwrong** [comment]
Easy to reproduce:
```js
// test.js
fixture `Some fixture`
    .beforeEach(async t => {
        await t
            .wait(1000)
            .eval(() => {});
    });

test(`Some test`, async t => { });
```
```js
const createTestCafe = require('testcafe');

const customReporter = () => {
    return {
        async reportTaskStart() {},
        async reportFixtureStart() {},
        async reportTestDone() {},
        async reportTaskDone() {},
        async reportTestActionStart() {},
        async reportTestActionDone() {}
    };
};

(async () => {
    const testCafe = await createTestCafe('localhost', 1337, 1338);
    const runner = testCafe.createRunner();

    await runner
        .src('test.js')
        .browsers('chrome')
        .reporter(customReporter)
        .run();

    await testCafe.close();
})();
```

**Comment by wentwrong** [comment]
Closing as it was investigated. See #5650 and #5648 for more context.
