### ISSUE TITLE
-   Was unable to take a screenshot due to an error.

### ISSUE THREAD

**Issue by testcafeuser** [DevExpress/testcafe#5657]
Steps to reproduce:
Clone this repo - https://github.com/testcafeuser/TestcafeIssue.git
npm install
execute the command from terminal testcafe chrome test1.js --hostname localhost
Executed on MacOS catalina

I get the following error

```
mbp-010210:TestcafeIssue myusername$ testcafe chrome test1.js --hostname localhost
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 86.0.4240.111 / macOS 10.15.7

 Getting Started
 ✓ My first test


 1 passed (3s)

 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Error: not opened
      at WebSocket.send (/Users/myusername/dev/github/TestcafeIssue/node_modules/ws/lib/WebSocket.js:359:18)
      at Chrome.enqueueCommand (/Users/myusername/dev/github/TestcafeIssue/node_modules/chrome-remote-interface/lib/chrome.js:130:16)
      at /Users/myusername/dev/github/TestcafeIssue/node_modules/chrome-remote-interface/lib/chrome.js:88:28
      at new Promise (<anonymous>)
      at Chrome.send (/Users/myusername/dev/github/TestcafeIssue/node_modules/chrome-remote-interface/lib/chrome.js:87:16)
      at Object.handler [as captureScreenshot]
  (/Users/myusername/dev/github/TestcafeIssue/node_modules/chrome-remote-interface/lib/api.js:32:23)
      at Object.getScreenshotData
  (/Users/myusername/dev/github/TestcafeIssue/node_modules/testcafe/src/browser/provider/built-in/dedicated/chrome/cdp.ts:129:46)
      at BrowserProviderPluginHost.takeScreenshot
  (/Users/myusername/dev/github/TestcafeIssue/node_modules/testcafe/src/browser/provider/built-in/dedicated/base.js:68:52)
      at BrowserProvider.takeScreenshot
  (/Users/myusername/dev/github/TestcafeIssue/node_modules/testcafe/src/browser/provider/index.ts:354:31)
```

**Comment by testcafeuser** [comment]
Works Fine when headless is used:
"test": "testcafe chrome:headless test1.js --hostname localhost"
