### ISSUE TITLE
Typescript compilation fails because "files" property in tsconfig.json appears to be ignored

### ISSUE THREAD

**Issue by ericbiewener** [DevExpress/testcafe#5790]
### What is your Test Scenario?
I enable importing `*.graphql` files as strings in my app via webpack's raw-loader, and tell TS to consider these imports to be strings via a declaration file:

**assets.d.ts**
```tsx
declare module "*.graphql" {
  const content: string;
  export default content;
}
```

I then tell the TS compiler about this declaration file via the `files` property in `tsconfig.json`:

**tsconfig.json**
```json
{
  ...
  "files": ["./types/assets.d.ts"]
}
```

Finally, I provide the path to this `tsconfig.json` via `runner.tsConfigPath(tsConfigPath)`.
 
### What is the Current behavior?
Testcafe fails to compile the TypeScript test:

```
/Users/eric/my-repo/libs/account/data-access/src/__mock-api__/schema.ts (1, 38): Cannot find module '../schema.graphql' or its corresponding type declarations.

    at Function._reportErrors (/Users/eric/my-repo/node_modules/testcafe/lib/compiler/test-file/formats/typescript/compiler.js:41:15)
    at TypeScriptTestFileCompiler._compileFilesToCache (/Users/eric/my-repo/node_modules/testcafe/lib/compiler/test-file/formats/typescript/compiler.js:58:40)
    at TypeScriptTestFileCompiler._precompileCode (/Users/eric/my-repo/node_modules/testcafe/lib/compiler/test-file/formats/typescript/compiler.js:79:18)
    at TypeScriptTestFileCompiler._compileCodeForTestFiles (/Users/eric/my-repo/node_modules/testcafe/lib/compiler/test-file/api-based.js:86:29)
    at /Users/eric/my-repo/node_modules/testcafe/lib/compiler/test-file/formats/typescript/compiler.js:46:26
    at Compiler._precompileFiles (/Users/eric/my-repo/node_modules/testcafe/lib/compiler/index.js:47:33)
    at Function.all (<anonymous>:null:null)
    at Compiler._compileTestFiles (/Users/eric/my-repo/node_modules/testcafe/lib/compiler/index.js:72:9)
    at Compiler.getTests (/Users/eric/my-repo/node_modules/testcafe/lib/compiler/index.js:84:34)
    at LiveModeBootstrapper._getTests (/Users/eric/my-repo/node_modules/testcafe/lib/runner/bootstrapper.js:129:21)
    at Function.all (<anonymous>:null:null)
    at LiveModeBootstrapper._bootstrapParallel (/Users/eric/my-repo/node_modules/testcafe/lib/runner/bootstrapper.js:226:38)
    at LiveModeBootstrapper.createRunnableConfiguration (/Users/eric/my-repo/node_modules/testcafe/lib/runner/bootstrapper.js:254:69)
```
 
### What is the Expected behavior?
TS compiles without error
 
### Your Environment details:
 
* testcafe version: 1.9.4                   
* node.js version: 14.11.0                   
* command-line arguments: Let me know if there is a way to output this. I'm running the tests via a JS script that uses `createTestCafe`
* browser name and version: N/A
* platform and version: N/A

**Comment by SergeyShurygin** [comment]
Hi,

In the upcoming 1.10.0 version, we plan to release the Custom Compiler Options feature, which should allow you to implement your scenario. Here is corresponding [issue](https://github.com/DevExpress/testcafe/issues/2659) and [PR](https://github.com/DevExpress/testcafe/pull/5607). Once the 1.10.0 version is released, can you check if it solves the issue? Otherwise, we would appreciate if you send us a working example reproducing the problem.

**Comment by ericbiewener** [comment]
Are you sure that will fix it? My concern is that the `files` property in `tsconfig.json` is _not_ part of the `compilerOptions` object property -- it's a top-level property. Perhaps your naming the feature "compiler options" doesn't mean that it is only going to consider the `compilerOptions` property in tsconfig, but the naming makes me nervous :)

**Comment by SergeyShurygin** [comment]
Yes, the "Compiler Options" is the name of the CLI parameter and the runner method: [https://devexpress.github.io/testcafe/documentation/guides/concepts/typescript-and-coffeescript.html#customize-compiler-options](https://devexpress.github.io/testcafe/documentation/guides/concepts/typescript-and-coffeescript.html#customize-compiler-options)
You can try it with the latest 1.10.0 RC version, (1.10.0-rc.7) available on npm.

**Comment by thansber** [comment]
Will this Compiler Options feature handle custom "paths" mappings in tsconfig.json files as well? Specifically will it address  #4144?

**Comment by miherlosev** [comment]
Hi @thansber

No. The 'Compiler Options' feature will not handle custom path mappings. You can use any workaround from the #4144 issue.
