### ISSUE TITLE
hammerhead.js throwing Uncaught DOMException: Failed to construct 'Worker' error on recaptcha call

### ISSUE THREAD

**Issue by lynners** [DevExpress/testcafe#5803]
I have been using testcafe for the last four months without any issue. It has been a smooth transition from selenium! But in the last day I'm running into a new issue that I cannot seem to fix. The most irritating part is that the error does not happen on all chrome instances. It seems to only affect the two machines I have to run the test suites. No changes have been made to the machine or version or testcafe - so I'm wondering what else to try.

### What is your Test Scenario?
When opening the log in dialog or log in page for our app - a call is made to recaptcha. A subsequent webworker call is made.
 
### What is the Current behavior?
Visiting the log in page or opening the log in dialog in chrome works just fine. When using testcafe, there is a console error for the webworker call:
 
### What is the Expected behavior?
No error and the webworker call is made
 
### What is your web application and your TestCafe test code?
You can see this error by visiting https://migraine.com/member-login/
 
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { t } from 'testcafe';

fixture`Recaptcha error`

test('Go to login', async t => {
  await t.navigateTo('https://migraine.com/member-login');
  await t.debug();
})
```
</details>

<details>
<summary>Your complete test report:</summary>

```
VM818 hammerhead.js:12 Uncaught DOMException: Failed to construct 'Worker': Script at 'https://www.google.com/recaptcha/api2/webworker.js?hl=en&v=NTa-8tBgsAw62CYTJPliVdrV' cannot be accessed from origin 'http://192.168.1.243:53482'.
    at new Worker (http://192.168.1.243:53482/hammerhead.js:12:12048)
    at b3.<anonymous> (http://192.168.1.243:53482/yKj9vwo6f*vnYx2GOLE!s!utf-8/https://www.gstatic.com/recaptcha/releases/NTa-8tBgsAw62CYTJPliVdrV/recaptcha__en.js:107:362)
    at new b3 (http://192.168.1.243:53482/yKj9vwo6f*vnYx2GOLE!s!utf-8/https://www.gstatic.com/recaptcha/releases/NTa-8tBgsAw62CYTJPliVdrV/recaptcha__en.js:408:252)
    at Er.<anonymous> (http://192.168.1.243:53482/yKj9vwo6f*vnYx2GOLE!s!utf-8/https://www.gstatic.com/recaptcha/releases/NTa-8tBgsAw62CYTJPliVdrV/recaptcha__en.js:287:235)
    at new Er (http://192.168.1.243:53482/yKj9vwo6f*vnYx2GOLE!s!utf-8/https://www.gstatic.com/recaptcha/releases/NTa-8tBgsAw62CYTJPliVdrV/recaptcha__en.js:393:179)
    at Object.init (http://192.168.1.243:53482/yKj9vwo6f*vnYx2GOLE!s!utf-8/https://www.gstatic.com/recaptcha/releases/NTa-8tBgsAw62CYTJPliVdrV/recaptcha__en.js:508:2457)
    at http://192.168.1.243:53482/yKj9vwo6f*vnYx2GOLE!i/https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LfD7o8UAAAAAGDI5DRhS6Jrvl0hFxmLh7es1GG0&co=aHR0cHM6Ly9taWdyYWluZS5jb206NDQz&hl=en&v=NTa-8tBgsAw62CYTJPliVdrV&size=invisible&cb=vvrbtdopncld:189:29
Worker @ VM818 hammerhead.js:12
(anonymous) @ VM828 recaptcha__en.js:107
b3 @ VM828 recaptcha__en.js:408
(anonymous) @ VM828 recaptcha__en.js:287
Er @ VM828 recaptcha__en.js:393
(anonymous) @ VM828 recaptcha__en.js:508
(anonymous) @ anchor?ar=1&k=6LfD7o8UAAAAAGDI5DRhS6Jrvl0hFxmLh7es1GG0&co=aHR0cHM6Ly9taWdyYWluZS5jb206NDQz&hl=en&v=NTa-8tBgsAw62CYTJPliVdrV&size=invisible&cb=vvrbtdopncld:189

```
</details>

### Steps to Reproduce:

1. Go to https://migraine.com/member-login via testcafe
 
### Your Environment details:
 
* testcafe version:                1.8.8
* node.js version:                    12.0
* command-line arguments:  --skip-js-errors
* browser name and version: Chrome 87
* platform and version:         macOS 10.13, 10.12
* other:                                  Not seeing this on macOS 10.15 with the same version of Chrome

**Comment by konwinkler** [comment]
We have the same issue (error in browser console) when running testcafe tests against a NextJS app with recaptcha v3. This seems to be an issue for chromium/chrome where as Safari seems to work fine.

**Comment by lynners** [comment]
@konwinkler Thanks, glad you mentioned that - i totally forgot to put that in my report. Safari and Firefox are working just fine for me also

**Comment by Farfurix** [comment]
@lynners 

Hello,

I tried to reproduce this issue under TestCafe v1.10.0/Chrome 87 and it works without any errors.
I suggest you run your tests with the latest TestCafe version (`v1.10.0`) and let us know your results.

**Comment by lynners** [comment]
Thanks @Farfurix ! I thought I had tried that but I'm using nvm and looks like I did not update in the correct place. This fixes the problem for Chrome and I am able to log in. While I am also able to log in with Safari now with v1.10.0, just wanted to mention that I still do get a bunch of the errors in the console. Same test case as above but run in Safari 14.0 / macOS 10.15.7:

`Blocked a frame with origin "http://192.168.5.239:64866" from accessing a frame with origin "http://192.168.5.239:64865". Protocols, domains, and ports must match.
a — hammerhead.js:14:29555
c — hammerhead.js:14:30027
p — hammerhead.js:14:30242
h — hammerhead.js:14:30825
(anonymous function) — hammerhead.js:6:21432
(anonymous function) — hammerhead.js:6:23164
(anonymous function) — hammerhead.js:6:24353
(anonymous function) — hammerhead.js:6:26824
(anonymous function) — hammerhead.js:15:13551
(anonymous function) — hammerhead.js:8:1744
n — hammerhead.js:15:16354
n — hammerhead.js:8:2853
(anonymous function) — hammerhead.js:7:27218
a — hammerhead.js:14:29555`

**Comment by arubtsov** [comment]
@lynners, Thank you for your input. I was able to reproduce the behavior you described.
