### ISSUE TITLE
RequestLogger fails to detect network requests within dynamically added iframe

### ISSUE THREAD

**Issue by Aaronius** [DevExpress/testcafe#6060]
### What is your Test Scenario?
Our test page creates and appends an iframe dynamically, then creates and appends an image element to that iframe. The image element loads an image from a remote server.

 
### What is the Current behavior?
The RequestLogger fails to log the image's network request.

 
### What is the Expected behavior?
The RequestLogger logs the image's network request.

 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>React App</title>
  </head>
  <body>
    <div id="root"></div>
    <script>
      document.addEventListener("DOMContentLoaded", () => {
        const iframe = document.createElement("iframe");
        document.body.appendChild(iframe);

        const iframeDoc = iframe.contentWindow.document;
        const img = iframeDoc.createElement("img");
        img.src = "https://cataas.com/cat/cute";
        iframeDoc.body.appendChild(img);
      });
    </script>
  </body>
</html>
```

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { RequestLogger } from "testcafe";

const networkLoggerOptions = {
  logRequestHeaders: true,
  logRequestBody: true,
  logResponseBody: true,
  stringifyResponseBody: false,
  stringifyRequestBody: true,
  logResponseHeaders: true,
};

const requestLogger = RequestLogger(
  "https://cataas.com/cat/cute",
  networkLoggerOptions
);

fixture("Bug Test").page("http://localhost:3000").requestHooks(requestLogger);

test("should pass without errors", async (t) => {
  await t.expect(requestLogger.requests.length).eql(1);
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```
Watching the following files:
  /Users/aahardy/dev/testcafe-test/tests/index.spec.js
 Running tests in:
 - Chrome 89.0.4389.90 / macOS 10.15.7

 Bug Test
 ✖ should pass without errors

   1) AssertionError: expected 0 to deeply equal 1
      
      + expected - actual
      
      -0
      +1
      

      Browser: Chrome 89.0.4389.90 / macOS 10.15.7

         15 |);
         16 |
         17 |fixture("Bug Test").page("http://localhost:3000").requestHooks(requestLogger);
         18 |
         19 |test("should pass without errors", async (t) => {
       > 20 |  await t.expect(requestLogger.requests.length).eql(1);
         21 |});
         22 |

         at <anonymous> (/Users/aahardy/dev/testcafe-test/tests/index.spec.js:20:49)
         at asyncGeneratorStep (/Users/aahardy/dev/testcafe-test/tests/index.spec.js:1:224)
         at _next (/Users/aahardy/dev/testcafe-test/tests/index.spec.js:1:562)
         at <anonymous> (/Users/aahardy/dev/testcafe-test/tests/index.spec.js:1:727)
         at <anonymous> (/Users/aahardy/dev/testcafe-test/tests/index.spec.js:1:468)
         at <anonymous> (/Users/aahardy/dev/testcafe-test/tests/index.spec.js:19:5)



 1/1 failed (1s)

```
</details>

### Steps to Reproduce:

You can clone https://github.com/Aaronius/testcafe-bugs
Check out the `iframe-requests` branch.
Run `npm install`
Run `npm start`
In a different terminal, run `npm test`
 
### Your Environment details:
 
* testcafe version: 1.12.0
* node.js version:  14.15.3
* command-line arguments: testcafe firefox
* browser name and version: Firefox 86.0
* platform and version:  macOS 10.15.7
* other:

**Comment by shammowla** [comment]
+1 Facing the same issue

**Comment by SergeyShurygin** [comment]
I reproduced this.  We'll look into it.

**Comment by miherlosev** [comment]
Hi @Aaronius 

You need to wait until the image is loaded. The updated test code will look as follows:
```js
test("should pass without errors", async (t) => {
    await t.expect(requestLogger.contains(r => r.response.statusCode === 200)).ok();
    await t.expect(requestLogger.requests.length).eql(1);
});
```
