### ISSUE TITLE
await call in IIAFE wrapper causes "ReferenceError: test is not defined" error

### ISSUE THREAD

**Issue by jantonypdx** [DevExpress/testcafe#6080]
### What is your Test Scenario?
The use case is similar to your Data-Driven Tests example:
https://devexpress.github.io/testcafe/documentation/recipes/best-practices/create-data-driven-tests.html

But instead, I'm trying to load the data from an async call before running the data-driven tests. I've wrapped the data setup, fixture, and test inside an Immediately Invoked Async Function Express (IIAFE) wrapper (see test code).
 
### What is the Current behavior?
The test runs fine if the data is setup with a regular synchronous call. It fails when you try to retrieve the data using an async await call instead.
 
### What is the Expected behavior?
The expectation is for the test to run regardless of how the test data is loaded (synchronously or asynchronously)
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>
DevExpress Example page:
[https://devexpress.github.io/testcafe/example/](https://devexpress.github.io/testcafe/example/)

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
let dataSet;

function setDataSet() {
  dataSet = [
    {
      name: 'John Heart'
    },
    {
      name: 'Olivia Peyton'
    }
  ];
}

function timeout(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function sleep(time, fn, ...args) {
  await timeout(time);
  return fn(...args);
}

// IIAFE for making async/await call
(async () => {
  fixture`Data-Driven Tests`
    .page`https://devexpress.github.io/testcafe/example/`;

  // THIS DOESN'T WORK
  // async call - setup dataSet, but simulate a long call
  await (async () => {
    await sleep(3000, () => setDataSet());
  })();

  // THIS DOES WORK
  // synchronous call - setup dataSet
  // setDataSet();

  // then try to run tests
  for (let i = 0; i < dataSet.length; i += 1) {
    const data = dataSet[i];
    test(`Enter '${data.name}'`, async (t) => {
      await t.typeText('#developer-name', data.name);
    });
  }
})();
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "selectorTimeout": 15000
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'testcafe',
0 verbose cli   'chrome',
0 verbose cli   'asyncTestCafe.js',
0 verbose cli   '-e',
0 verbose cli   '--hostname',
0 verbose cli   '127.0.0.1'
0 verbose cli ]
1 info using npm@7.5.1
2 info using node@v15.8.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:~/<repo_name>/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:~/.npmrc Completed in 2ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 10ms
19 verbose npm-session 7137a33f9e5dc137
20 timing npm:load Completed in 20ms
21 timing command:exec Completed in 9880ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:378:20)
22 verbose stack     at maybeClose (node:internal/child_process:1067:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
23 verbose pkgid x1-testcafe@1.0.0
24 verbose cwd ~/<repo_name>
25 verbose Darwin 19.6.0
26 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "testcafe" "chrome" "asyncTestCafe.js" "-e" "--hostname" "127.0.0.1"
27 verbose node v15.8.0
28 verbose npm  v7.5.1
29 error code 1
30 error path ~/<repo_name>
31 error command failed
32 error command sh -c testcafe "chrome" "asyncTestCafe.js" "-e" "--hostname" "127.0.0.1"
33 verbose exit 1
```
</details>

<details>
<summary>Screenshots:</summary>

none
</details>

### Steps to Reproduce:

1. Save the example code as "asyncTestCafe.js"
2. Execute this command: `npx testcafe "chrome" asyncTestCafe.js -e --hostname 127.0.0.1`
3. The test fails:
```
ReferenceError: test is not defined
    at ~/asyncTestCafe.js:39:5
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (~/asyncTestCafe.js:1:114)
    at _next (~/asyncTestCafe.js:1:452)
```
4. Comment out the async await command (lines 30-32) and uncomment the synchronous command (line 36)
5. Execute command again: `npx testcafe "chrome" asyncTestCafe.js -e --hostname 127.0.0.1`
6. The test now succeeds:
```
 Running tests in:
 - Chrome 89.0.4389.90 / macOS 10.15.7

 Data-Driven Tests
 ✓ Enter 'John Heart'
 ✓ Enter 'Olivia Peyton'
```
### Your Environment details:
 
* testcafe version: v1.13.0       
* node.js version: v15.8.0       
* command-line arguments:  testcafe "chrome" asyncTestCafe.js -e --hostname 127.0.0.1 
* browser name and version: Chrome 89.0.4389.90 (Official Build) (x86_64) 
* platform and version: Mac 10.15.7

**Comment by jantonypdx** [comment]
@SergeyShurygin - updated TestCafe to v1.13.0. Issue is still present.

**Comment by felis2803** [comment]
It's not possible to create tests asynchronously. You can use workarounds as follows:

```js
// runner.js

const { promises: { writeFile, unlink } } = require('fs');
const { execSync } = require('child_process');
const dataFileName = 'data.json';

function getData () {
    return [
        { name: 'John Heart' },
        { name: 'Olivia Peyton' }
    ];
}

async function requestData (timeout) {
    return new Promise(resolve => setTimeout(resolve, timeout, getData()));
}

(async () => {
    const data = await requestData(2000);
    await writeFile(dataFileName, JSON.stringify(data));
    execSync('testcafe chrome test.js', { stdio: 'inherit' });
    await unlink(dataFileName)
})();
```
```js
//test.js

const data = require('./data.json');

fixture`Data-Driven Tests`
    .page`https://devexpress.github.io/testcafe/example/`;

for (const { name } of data) {
    test(`Enter '${name}'`, async t => {
        await t.typeText('#developer-name', name);
    });
}
```

Then, run it: `node runner.js`
