### ISSUE TITLE
Uncaught exception: Error: write EPIPE

### ISSUE THREAD

**Issue by rmkranack** [DevExpress/testcafe#6104]
I am using TestCafe version 1.13.0 and am receiving the following error when attempting to run multiple tests on Chrome, Safari, and Edge. The test pass on these browsers if running one test at a time. Multiple tests run without issue on Firefox. 

1) Uncaught exception:
      
      Error: write EPIPE
      at afterWriteDispatched (internal/stream_base_commons.js:156:25)
      at writeGeneric (internal/stream_base_commons.js:147:3)
      at Socket._writeGeneric (net.js:785:11)
      at Socket._write (net.js:797:8)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at Socket.Writable.write (internal/streams/writable.js:303:10)
      at TLSSocket.ondata (internal/streams/readable.js:719:22)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket.EventEmitter.emit (domain.js:529:15)
      at addChunk (internal/streams/readable.js:309:12)

      Browser: Chrome 89.0.4389.114 / macOS 10.15.7

### What is your Test Scenario?
The problem is occurring when the test reaches the registration form. The url does end in "getstarted#/info" Not sure if the "#" is causing an issue. On Chrome, I do see a message in the console "Autofocus processing was blocked because a document's URL has a fragment '#/info'."
![image](https://user-images.githubusercontent.com/7255854/113334519-a2fccd80-92d8-11eb-8759-f0b22be527d6.png)

<details>

 Running tests in:
 - Chrome 89.0.4389.114 / macOS 10.15.7

 Register
 ✓ Register_Signup | C24
 ✓ Register_Splash_Continue | C37
 ✖ GetStarted_Continue | C38

   1) Uncaught exception:
      
      Error:

      Browser: Chrome 89.0.4389.114 / macOS 10.15.7

 ✖ GetStartedMore_Continue | C41

   1) Uncaught exception:
      
      Error:

      Browser: Chrome 89.0.4389.114 / macOS 10.15.7

 ✖ GetStarted_AddAccount_No  | C43

   1) Uncaught exception:
      
      Error: write EPIPE
      at afterWriteDispatched (internal/stream_base_commons.js:156:25)
      at writeGeneric (internal/stream_base_commons.js:147:3)
      at Socket._writeGeneric (net.js:785:11)
      at Socket._write (net.js:797:8)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at Socket.Writable.write (internal/streams/writable.js:303:10)
      at TLSSocket.ondata (internal/streams/readable.js:719:22)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket.EventEmitter.emit (domain.js:529:15)
      at addChunk (internal/streams/readable.js:309:12)

      Browser: Chrome 89.0.4389.114 / macOS 10.15.7

 ✖ GetStarted_AddAccount_Yes  | C42

   1) Uncaught exception:
      
      Error: write EPIPE
      at afterWriteDispatched (internal/stream_base_commons.js:156:25)
      at writeGeneric (internal/stream_base_commons.js:147:3)
      at Socket._writeGeneric (net.js:785:11)
      at Socket._write (net.js:797:8)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at Socket.Writable.write (internal/streams/writable.js:303:10)
      at TLSSocket.ondata (internal/streams/readable.js:719:22)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket.EventEmitter.emit (domain.js:529:15)
      at addChunk (internal/streams/readable.js:309:12)

      Browser: Chrome 89.0.4389.114 / macOS 10.15.7

 ✖ GetStarted_AddAccount_Yes_TellMore_Cancel  | C45

   1) Uncaught exception:
      
      Error: write EPIPE
      at afterWriteDispatched (internal/stream_base_commons.js:156:25)
      at writeGeneric (internal/stream_base_commons.js:147:3)
      at Socket._writeGeneric (net.js:785:11)
      at Socket._write (net.js:797:8)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at Socket.Writable.write (internal/streams/writable.js:303:10)
      at TLSSocket.ondata (internal/streams/readable.js:719:22)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket.EventEmitter.emit (domain.js:529:15)
      at addChunk (internal/streams/readable.js:309:12)

      Browser: Chrome 89.0.4389.114 / macOS 10.15.7

 ✖ GetStarted_AddAccount_Yes_TellMore_Continue  | C44

   1) Uncaught exception:
      
      Error:

      Browser: Chrome 89.0.4389.114 / macOS 10.15.7

 6/8 failed (2m 05s)
</details>

### Steps to Reproduce:

1. Run multiple tests on Chrome, Safari, or Edge
2. Tests fail when reaching the registration form
 
### Your Environment details:
 
* testcafe version: 1.13.0                  
* node.js version: v14.16.0 (also tried with v 15)                   
* command-line arguments:  testcafe chrome tests/src/e2e/Register/Register.js --env='dev'
* browser name and version: Chrome 89.0.4389.114, Safari 14.0.3, Edge 88.0.705.81
* platform and version:  mac os 10.15.7        
* other:

**Comment by wentwrong** [comment]
I answered you at: [Test Frequently Lose Connected (EPIPE error)](https://github.com/DevExpress/testcafe/issues/6106). Let's continue there and consider this issue a duplicate.
