### ISSUE TITLE
No page redirection after login

### ISSUE THREAD

**Issue by Holger2233** [DevExpress/testcafe#6153]
Since recently, several of our regression tests with Testcafe are running into problems, where a page (Account settings page SPA) fails to load following the successful login to the application. It appears that the problem has been introduced with the recent browser upgrade of Chrome v89 and Firefox to v87, before which the tests were completing successfully, and they are still failing in the current versions Chrome v90 and Firefox v88. 

### What is your Test Scenario?
Login in Xero and navigate to the account settings page to change the user settings. 
 
### What is the Current behavior?
the test times out waiting for the page to load. The attached screenshot show the errors logged in the browser console in Chrome. 
 
### What is the Expected behavior?
the page loads correctly and provides access to the user settings
 
### What is your web application and your TestCafe test code?
The following script allows login to Xero as a trial user and replicate the issue

<details>
<summary>Your complete test code (or attach your test files):</summary>

```
import {Selector} from 'testcafe';

const username = 'testcafe.user@test.xero.com'
const password = 'Password123'

fixture('Accountsettings_Login')
  .page('https://login.xero.com/identity/user/login')

test('login_to_Account_settings', async (browser) => {
  await browser
    //login
    .expect(Selector('input[data-automationid="Username--input"]').visible).ok()
    .typeText('input[data-automationid="Username--input"]', username)
    .typeText('input[data-automationid="PassWord--input"]', password)
    .click('button[data-automationid="LoginSubmit--button"]')

    //navigate to the accountsettings page and check for the change password button
    .navigateTo("https://identity.xero.com/account")
    .expect(Selector('button[data-automationid="settings-change-password--button"]').visible).ok()
});

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "screenshots": {
    "path": "./screenshots",
    "pathPattern": "${DATE}_${TIME}/${FIXTURE}_${TEST}.png",
    "takeOnFails": true,
    "fullPage": false
  },
  "pageLoadTimeout": 60000,
  "assertionTimeout": 30000,
  "selectorTimeout": 30000,
  "skipJsErrors": true,
  "concurrency": 1,
  "speed": 0.9,
  "stopOnFirstFail": false,
  "disablePageCaching": true,
  "debugOnFail": false
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Using locally installed version of TestCafe.
The "browsers" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 90.0.4430.72 / Windows 10

 Accountsettings_Login
 × login_to_Account_settings (screenshots:
 C:\Dev\identity2\test\Xero.Identity.RegressionTests.Testcafe\screenshots\2021-04-20_17-23-43\Accountsettings_Login_login_to_Account_settings.png)

   1) AssertionError: expected false to be truthy

      Browser: Chrome 90.0.4430.72 / Windows 10
      Screenshot: C:\Dev\identity2\test\Xero.Identity.RegressionTests.Testcafe\screenshots\2021-04-20_17-23-43\Accountsettings_Login_login_to_Account_settings.png

         14 |    .typeText('input[data-automationid="PassWord--input"]', password)
         15 |    .click('button[data-automationid="LoginSubmit--button"]')
         16 |
         17 |    //navigate to the accountsettings page and check for the change password button
         18 |    .navigateTo("https://identity.xero.com/account")
       > 19 |    .expect(Selector('button[data-automationid="settings-change-password--button"]').visible).ok()
         20 |});
         21 |

         at <anonymous> (C:\Dev\identity2\test\Xero.Identity.RegressionTests.Testcafe\tests\id_reg\accountsettings_login.js:19:95)
         at asyncGeneratorStep (C:\Dev\identity2\test\Xero.Identity.RegressionTests.Testcafe\tests\id_reg\accountsettings_login.js:1:261)
         at _next (C:\Dev\identity2\test\Xero.Identity.RegressionTests.Testcafe\tests\id_reg\accountsettings_login.js:1:599)
         at <anonymous> (C:\Dev\identity2\test\Xero.Identity.RegressionTests.Testcafe\tests\id_reg\accountsettings_login.js:1:764)
         at <anonymous> (C:\Dev\identity2\test\Xero.Identity.RegressionTests.Testcafe\tests\id_reg\accountsettings_login.js:1:505)
         at <anonymous> (C:\Dev\identity2\test\Xero.Identity.RegressionTests.Testcafe\tests\id_reg\accountsettings_login.js:9:5)



 1/1 failed (51s)
```
</details>

<details>
<summary>Screenshots:</summary>

```
![image](https://user-images.githubusercontent.com/25468236/115342056-bfb46300-a1fd-11eb-8524-1825e3f56caa.png)

![image](https://user-images.githubusercontent.com/25468236/115342003-a7444880-a1fd-11eb-8b23-10d454da467e.png)

```
</details>

### Steps to Reproduce:

1. Go to my website https://login.xero.com/identity/user/login
3. Login (credentials included in the script)
4. navigate to https://identity.xero.com/account
5. wait for page to load until the test times out. Note: This does not happen if the test is performed manually, only if it is run automated with Testcafe.
 
### Your Environment details:
 
* testcafe version:                   1.14.0
* node.js version:                    v12.18.4
* command-line arguments:  testcafe -e chrome .\tests\accountsettings_login.js
* browser name and version: Chrome 89 and later, Firefox 87 and later, Edge 89 and later
* platform and version:          Windows 10, Docker container running Linux / Debian 10 
* other:

**Comment by Holger2233** [comment]
We managed to find a workaround ourselves by running Chrome with the --disable-web-security flag.
