### ISSUE TITLE
GitHub sign in fails with SecurityError for SharedWorker in Chrome only

### ISSUE THREAD

**Issue by aeneasr** [DevExpress/testcafe#6199]
### What is your Test Scenario?

I am trying to test a social sign in flow using GitHub as the identity provider:

```
test.page(`${APP_URL}/registration`)(
  'able to sign up using oidc',
  async (t) => {
    await signup.isReady()
    await t.click(signup.github())
    await t.typeText('input[name="login"]', '...')
    await t.typeText(
      'input[name="password"]',
      '...'
    )
    await t.click('input[type="submit"]')
    await t.click('button[name="authorize"][value="1"]:enabled')
  }
)
```

To do so, I initialize the flow (`await t.click(signup.github())`) which redirects me to the OAuth2 URL for GitHub:

```
http://10.123.0.113:64226/OHp1HHN7Z*3KdcYamgu!f/https://github.com/login?client_id=8ae38d2b8220467b8e0e&return_to=/login/oauth/authorize?client_id=8ae38d2b8220467b8e0e&redirect_uri=https%3A%2F%2Fproject.console.ory%3A8080%2Fapi%2Fkratos%2Fpublic%2Fself-service%2Fmethods%2Foidc%2Fcallback%2Fgithub&response_type=code&scope=user%3Aemail+read%3Auser&state=4152d9c0-a0e7-4da3-8d89-c9cab836c345
```

This shows the login screen and testcafe properly executes `typeText`. However, on the next page where I would want to run `await t.click('button[name="authorize"][value="1"]:enabled')`, testCafe fails with:

```
 ✖ able to sign up using oidc

   1) A JavaScript error occurred on

   "https://github.com/login/oauth/authorize?client_id=8ae38d2b8220467b8e0e&redirect_uri=https%3A%2F%2Fproject.console.ory%3A8080%2Fapi%2Fkratos%2Fpublic%2Fself-service%2Fmethods%2Foidc%2Fcallback%2Fgithub&response_type=code&scope=user%3Aemail+read%3Auser&state=e17241a4-88bf-4f27-8799-3386da1b191e".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors" configuration file property to
      "true".
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      SecurityError: Failed to construct 'SharedWorker': Script at 'https://github.com/socket-worker-3f088aa2.js' cannot be accessed from origin
      'http://10.123.0.113:64226'.
      Error: Failed to construct 'SharedWorker': Script at 'https://github.com/socket-worker-3f088aa2.js' cannot be accessed from origin
      'http://10.123.0.113:64226'.
          at new AliveSessionProxy (https://github.githubassets.com/assets/behaviors-efa97295.js:2:145308)
          at cr (https://github.githubassets.com/assets/behaviors-efa97295.js:2:146897)
          at https://github.githubassets.com/assets/behaviors-efa97295.js:2:147346

      Browser: Chrome 90.0.4430.93 / macOS 10.15.7

         14 |    await t.typeText(
         15 |      'input[name="password"]',
         16 |      '.....'
         17 |    )
         18 |    await t.click('input[type="submit"]')
       > 19 |    await t.click('button[name="authorize"][value="1"]:enabled')
         20 |  }
         21 |)
         22 |
         23 |// test.page(`${APP_URL}/registration`)(
         24 |//   'able to sign up using password',

         at <anonymous> (/Users/foobar/workspace/go/src/github.com/ory-corp/cloud/test/e2e/tests/signup.ts:19:13)
         at fulfilled (/Users/foobar/workspace/go/src/github.com/ory-corp/cloud/test/e2e/tests/signup.ts:5:58)
```

### What is the Current behavior?

As stated above, the second page on GitHub fails with said error:

<img width="2032" alt="Bildschirmfoto 2021-05-03 um 14 35 03" src="https://user-images.githubusercontent.com/3372410/116876498-dce52a80-ac1c-11eb-9e30-6c8ff41be825.png">

This is visible in the console:

<img width="2032" alt="Bildschirmfoto 2021-05-03 um 14 36 29" src="https://user-images.githubusercontent.com/3372410/116876564-fb4b2600-ac1c-11eb-86b5-6024956e4ab4.png">

 
### What is the Expected behavior?

In FireFox, this works fine. It does not work in Chrome though. I would expect Chrome to also work as expected.

### What is your web application and your TestCafe test code?

See above! The app is currently in development. If the code / flow is required to help debug, I can deploy it somewhere.

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { APP_URL, gen } from '../pkg'
import signup from '../models/signup'

fixture`Signup`

const developer = gen.identity()

test.page(`${APP_URL}/registration`)(
  'able to sign up using oidc',
  async (t) => {
    await signup.isReady()
    await t.click(signup.github())
    await t.typeText('input[name="login"]', '...')
    await t.typeText(
      'input[name="password"]',
      '...'
    )
    await t.click('input[type="submit"]')
    await t.click('button[name="authorize"][value="1"]:enabled')
  }
)
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>
none
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```
A test run is starting...
 Running tests in:
 - Chrome 90.0.4430.93 / macOS 10.15.7

 Signup
 ✖ able to sign up using oidc

   1) A JavaScript error occurred on

   "https://github.com/login/oauth/authorize?client_id=8ae38d2b8220467b8e0e&redirect_uri=https%3A%2F%2Fproject.console.ory%3A8080%2Fapi%2Fkratos%2Fpublic%2Fself-service%2Fmethods%2Foidc%2Fcallback%2Fgithub&response_type=code&scope=user%3Aemail+read%3Auser&state=e17241a4-88bf-4f27-8799-3386da1b191e".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors" configuration file property to
      "true".
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      SecurityError: Failed to construct 'SharedWorker': Script at 'https://github.com/socket-worker-3f088aa2.js' cannot be accessed from origin
      'http://10.123.0.113:64226'.
      Error: Failed to construct 'SharedWorker': Script at 'https://github.com/socket-worker-3f088aa2.js' cannot be accessed from origin
      'http://10.123.0.113:64226'.
          at new AliveSessionProxy (https://github.githubassets.com/assets/behaviors-efa97295.js:2:145308)
          at cr (https://github.githubassets.com/assets/behaviors-efa97295.js:2:146897)
          at https://github.githubassets.com/assets/behaviors-efa97295.js:2:147346

      Browser: Chrome 90.0.4430.93 / macOS 10.15.7

         14 |    await t.typeText(
         15 |      'input[name="password"]',
         16 |      '...'
         17 |    )
         18 |    await t.click('input[type="submit"]')
       > 19 |    await t.click('button[name="authorize"][value="1"]:enabled')
         20 |  }
         21 |)
         22 |
         23 |// test.page(`${APP_URL}/registration`)(
         24 |//   'able to sign up using password',

         at <anonymous> (/Users/foobar/workspace/go/src/github.com/ory-corp/cloud/test/e2e/tests/signup.ts:19:13)
         at fulfilled (/Users/foobar/workspace/go/src/github.com/ory-corp/cloud/test/e2e/tests/signup.ts:5:58)



 1/1 failed (8s)

Make changes to the source files or press Ctrl+R to restart the test run.

```
</details>

### Steps to Reproduce:

1. Initiate an OAuth2 flow with GitHub using TestCafe
2. You can try using `visit('https://github.com/login?client_id=8ae38d2b8220467b8e0e&return_to=/login/oauth/authorize?client_id=8ae38d2b8220467b8e0e&redirect_uri=https%3A%2F%2Fproject.console.ory%3A8080%2Fapi%2Fkratos%2Fpublic%2Fself-service%2Fmethods%2Foidc%2Fcallback%2Fgithub&response_type=code&scope=user%3Aemail+read%3Auser&state=4152d9c0-a0e7-4da3-8d89-c9cab836c345')`
3. Execute the test
4. See the error
 
### Your Environment details:
 
* testcafe version:                   1.14.0

* node.js version:                   v16.0.0

* command-line arguments:  `NODE_TLS_REJECT_UNAUTHORIZED=0 testcafe -L "chrome '--window-size=1920,1280'" tests/signup.ts`
* browser name and version: Chrome Version 90.0.4430.93 (Offizieller Build) (x86_64)
* platform and version:         macOS 11.3

**Comment by Farfurix** [comment]
@aeneasr 

Hello,

I reproduced the "SecurityError: Failed to construct 'SharedWorker': ..." error with the "https://github.com/login" login form. We will update this thread once we have any news.

You can [ignore JS errors](https://testcafe.io/documentation/402639/reference/command-line-interface#-e---skip-js-errors) and try to continue your tests.

For the team.
Simple test:
```js
fixture `Fixture`
    .page('https://github.com/login');

test('test', async t => {
   await t
       .typeText('#login_field', '*******************')
       .typeText('#password', '*******************')
       .click('#login > div.auth-form-body.mt-3 > form > div > input.btn.btn-primary.btn-block');

   await t
       .debug();
});

```
Result:
```
>testcafe chrome test.js
 Running tests in:
 - Chrome 90.0.4430.93 / Windows 10

 Fixture
 × test

   1) A JavaScript error occurred on "https://github.com/".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors"
      configuration file property to "true".
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      SecurityError: Failed to construct 'SharedWorker': Script at 'https://github.com/socket-worker-3f088aa2.js'
      cannot be accessed from origin 'http://192.168.77.254:55789'.
      Error: Failed to construct 'SharedWorker': Script at 'https://github.com/socket-worker-3f088aa2.js' cannot be
      accessed from origin 'http://192.168.77.254:55789'.
          at new AliveSessionProxy (https://github.githubassets.com/assets/behaviors-8b537059.js:2:145686)
          at ur (https://github.githubassets.com/assets/behaviors-8b537059.js:2:147275)
          at https://github.githubassets.com/assets/behaviors-8b537059.js:2:147724
...
```

**Comment by aeneasr** [comment]
Awesome, thank you for reproducing the issue! I will try out the proposed workaround with ignoring JS errors!

**Comment by miherlosev** [comment]
The issue is not reproduced with `testcafe@1.17.2-rc.2`.
