### ISSUE TITLE
Error: TypeScript compilation failed

### ISSUE THREAD

**Issue by ofirrifo** [DevExpress/testcafe#6328]
### What is the Current behavior?
I start to get error after I'm trying to execute a test  using this command `./node_modules/.bin/testcafe 'chrome --incognito' e2e/tests`

Error:
```
ERROR Cannot prepare tests due to an error.
Error: TypeScript compilation failed.
/.../node_modules/@ngrx/store/src/feature_creator.d.ts (9, 23): ']' expected.
/.../node_modules/@ngrx/store/src/feature_creator.d.ts (9, 48): '(' expected.
/.../node_modules/@ngrx/store/src/feature_creator.d.ts (13, 43): ',' expected.
/.../node_modules/@ngrx/store/src/feature_creator.d.ts (13, 50): ',' expected.
/.../node_modules/@ngrx/store/src/feature_creator.d.ts (13, 64): '(' expected.
/.../node_modules/@ngrx/store/src/feature_creator.d.ts (18, 1): Unterminated template literal.
/.../node_modules/@ngrx/store/src/reducer_creator.d.ts (31, 16): ',' expected.
/.../node_modules/@ngrx/store/src/reducer_creator.d.ts (32, 12): ',' expected.
    at TypeScriptTestFileCompiler._reportErrors (/.../node_modules/testcafe/src/compiler/test-file/formats/typescript/compiler.ts:118:15)
    at TypeScriptTestFileCompiler._compileFilesToCache (/.../node_modules/testcafe/src/compiler/test-file/formats/typescript/compiler.ts:143:18)
    at TypeScriptTestFileCompiler._precompileCode (/.../node_modules/testcafe/src/compiler/test-file/formats/typescript/compiler.ts:172:18)
    at TypeScriptTestFileCompiler._compileCodeForTestFiles (/.../node_modules/testcafe/src/compiler/test-file/api-based.js:111:29)
    at /.../node_modules/testcafe/src/compiler/test-file/formats/typescript/compiler.ts:124:30
    at Compiler._precompileFiles (/.../node_modules/testcafe/src/compiler/index.js:64:33)
    at Compiler._compileTestFiles (/.../node_modules/testcafe/src/compiler/index.js:99:9)
    at Compiler.getTests (/.../node_modules/testcafe/src/compiler/index.js:117:34)
    at /.../node_modules/testcafe/src/runner/bootstrapper.ts:266:25
    at Object.guardTimeExecution [as default] (/.../node_modules/testcafe/src/utils/guard-time-execution.ts:6:31)

```

- The NGRX is a 3 party package  that not relevant to Testcafe
- When I execute my build script all pass.
- I check if there are real issue with the file above for example on this file `feature_creator.d.ts` it say `it (9, 23): ']' expected.` but I check this file and everything is correct.

Here is the file `feature_creator.d.ts` 
```
import { ActionReducer } from './models';
import { MemoizedSelector } from './selector';
export declare type Feature<AppState extends Record<string, any>, FeatureName extends keyof AppState & string, FeatureState extends AppState[FeatureName]> = FeatureConfig<FeatureName, FeatureState> & FeatureSelector<AppState, FeatureName, FeatureState> & NestedSelectors<AppState, FeatureState>;
export interface FeatureConfig<FeatureName extends string, FeatureState> {
    name: FeatureName;
    reducer: ActionReducer<FeatureState>;
}
declare type FeatureSelector<AppState extends Record<string, any>, FeatureName extends keyof AppState & string, FeatureState extends AppState[FeatureName]> = {
    [K in FeatureName as `select${Capitalize<K>}State`]: MemoizedSelector<AppState, FeatureState>;
};
declare type Primitive = string | number | bigint | boolean | null | undefined;
declare type NestedSelectors<AppState extends Record<string, any>, FeatureState> = FeatureState extends Primitive | unknown[] | Date ? {} : {
    [K in keyof FeatureState & string as `select${Capitalize<K>}`]: MemoizedSelector<AppState, FeatureState[K]>;
};
declare type NotAllowedFeatureStateCheck<FeatureState> = FeatureState extends Required<FeatureState> ? unknown : 'optional properties are not allowed in the feature state';
export declare function createFeature<AppState extends Record<string, any>, FeatureName extends keyof AppState & string = keyof AppState & string, FeatureState extends AppState[FeatureName] = AppState[FeatureName]>({ name, reducer, }: FeatureConfig<FeatureName, FeatureState> & NotAllowedFeatureStateCheck<FeatureState>): Feature<AppState, FeatureName, FeatureState>;
export {};

```

 
### What is the Expected behavior?
To not throw error and run the automation 
 
### What is your web application and your TestCafe test code?
This is private project and I can't share it

 
### Your Environment details:
 
* testcafe version: 1.14.0                
* node.js version:  v14.15.5                  
* command-line arguments:  'chrome --incognito'
* browser name and version: Chrome Version 91.0.4472.114 (Official Build) (x86_64)
* platform and version:         macOS big sur 11.4
* other:           typescript 4.2.4

**Comment by felis2803** [comment]
Hello,

The TS compiler used in TestCafe cannot parse such complex expressions as in the `feature_creator.d.ts` file.
Try connecting another compiler as written in the documentation: https://testcafe.io/documentation/402639/reference/command-line-interface#--compiler-options-options.

**Comment by ofirrifo** [comment]
@felis2803 
Can you upgrade please your typescript ?

**Comment by felis2803** [comment]
Updating the typescript compiler to 4.x is a breaking change. So, we can't do this until we release TestCafe 2.0. Meanwhile, please use the workaround I suggested.
