### ISSUE TITLE
--skip-js-errors is not skipping our JS errors

### ISSUE THREAD

**Issue by jbradenclickfunnels** [DevExpress/testcafe#6448]
### What is your Test Scenario?
Attempting to run tests with --skip-js-errors enabled

 
### What is the Current behavior?
Tests are failing with the report saying to skip js errors

 
### What is the Expected behavior?
Tests to run without the report telling me there are JS errors.

 
### What is your web application and your TestCafe test code?
Project is private at this time

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
 test ('valid_user_is_able_to_login', async t => {

        // Purpose: Verify when a valid user logs in, the dashboard page is displayed. 

        await LoginPageObjects.login(data.user_email, data.user_password)
        await t
            .expect(Selector('#desktop-user-menu').visible).ok(); // Asserts the dashboard page is displayed after signing in.
    })
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
    "assertionTimeout": 5000,
    "browsers": ["chrome --window-size=1920,1159"],
    "concurrency": 7,
    "pageLoadTimeout": 15000,
    "reporter": {
        "name": "spec",
        "output": "artifacts/reports/test_suite_results"
    },
    "screenshots": {
        "path": "artifacts/screenshots",
        "pathPattern": "${TEST}_${DATE}_${TIME}.png",
        "takeOnFails": true
    },
    "selectorTimeout": 5000,
    "src": "tests",
    "videoEncodingOptions": {
        "aspect": "16:9",
        "framerate": 30
    },
    "videoOptions": {
        "failedOnly": true,
        "pathPattern": "${TEST}_${DATE}_${TIME}.mp4",
        "singleFile": false
    }, 
    "videoPath": "artifacts/recordings"
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Chrome 92.0.4515.131 / macOS 10.15.7

 login
 ✖ valid_user_is_able_to_login

   1) A JavaScript error occurred on
      "https://myworkspace850a16.reborncf.com/account/workspaces/89".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the
      "--skip-js-errors" CLI option, or set the "skipJsErrors"
      configuration file property to "true".
      If the website only throws this error when you test it with
      TestCafe, please create a new issue at:

   "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: Cannot read property 'digest' of undefined
          at

   https://statics.reborncf.com/packs/js/vendors~eva~light-e9e4e81aa2a0eac52d62.chunk.js:2:962089
          at l

   (https://statics.reborncf.com/packs/js/vendors~eva~light-e9e4e81aa2a0eac52d62.chunk.js:2:323601)
          at Generator._invoke

   (https://statics.reborncf.com/packs/js/vendors~eva~light-e9e4e81aa2a0eac52d62.chunk.js:2:323354)
          at Generator.next

   (https://statics.reborncf.com/packs/js/vendors~eva~light-e9e4e81aa2a0eac52d62.chunk.js:2:323970)
          at Gs (http://10.0.0.6:63570/hammerhead.js:2:23709)
          at value (http://10.0.0.6:63570/hammerhead.js:12:32001)
          at H

   (https://statics.reborncf.com/packs/js/vendors~eva~light-e9e4e81aa2a0eac52d62.chunk.js:2:961577)
          at a

   (https://statics.reborncf.com/packs/js/vendors~eva~light-e9e4e81aa2a0eac52d62.chunk.js:2:961794)
          at

   https://statics.reborncf.com/packs/js/vendors~eva~light-e9e4e81aa2a0eac52d62.chunk.js:2:961853
          at nrWrapper
      (https://myworkspace850a16.reborncf.com/account/workspaces/89:12:28988)

      Browser: Chrome 92.0.4515.131 / macOS 10.15.7



 1/1 failed (17s)
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Run tests on pages with js errors while having --skip-js-errors in the CLI command
3. Wait for tests to finish
4. View reporter and see JS error babel
 
### Your Environment details:
 
* testcafe version:                   1.15.0
* node.js version:                    16.5.0
* command-line arguments:  testcafe --skip-js-errors
* browser name and version: See report section
* platform and version:          See report section
* other:

**Comment by AndreyBelym** [comment]
This issue should be fixed in `testcafe@1.15.2-rc.1`. Please try this version in your environment and reopen the issue if it still can be reproduced.
