### ISSUE TITLE
[TypeScript]: Complex type declaration breaks testcafe typescript compiler

### ISSUE THREAD

**Issue by r1ckyrockz** [DevExpress/testcafe#6472]
### What is your Test Scenario?
I would like to test my application with complex typescript definitions. 
 
### What is the Current behavior?
on current version of testcafe 1.15.2 with a complex ts type it breaks with this error message:

```
Error: TypeScript compilation failed.
***/src/utils/types.d.ts (18, 61): ']' expected.
***/src/utils/types.d.ts (18, 64): ';' expected.
***/src/utils/types.d.ts (18, 69): ';' expected.
***/src/utils/types.d.ts (18, 90): ';' expected.
***/src/utils/types.d.ts (18, 91): Declaration or statement expected.
***/src/utils/types.d.ts (18, 95): Declaration or statement expected.
***/src/utils/types.d.ts (18, 97): Expression expected.
***/src/utils/types.d.ts (19, 9): ';' expected.

    at TypeScriptTestFileCompiler._reportErrors (/***/node_modules/testcafe/lib/compiler/test-file/formats/typescript/compiler.js:75:15)
at TypeScriptTestFileCompiler._compileFilesToCache (/***/node_modules/testcafe/lib/compiler/test-file/formats/typescript/compiler.js:94:18)
at TypeScriptTestFileCompiler._precompileCode (/***/node_modules/testcafe/lib/compiler/test-file/formats/typescript/compiler.js:116:18)
at TypeScriptTestFileCompiler._compileCodeForTestFiles (/***/node_modules/testcafe/lib/compiler/test-file/api-based.js:83:29)
at /***/node_modules/testcafe/lib/compiler/test-file/formats/typescript/compiler.js:80:26
at Compiler._precompileFiles (/***/node_modules/testcafe/lib/compiler/index.js:47:33)
at Function.all (<anonymous>:null:null)
at Compiler._compileTestFiles (/***/node_modules/testcafe/lib/compiler/index.js:72:9)
at Compiler.getTests (/***/node_modules/testcafe/lib/compiler/index.js:84:34)
at /***/node_modules/testcafe/lib/runner/bootstrapper.js:102:70
at Object.guardTimeExecution [as default] (/***/node_modules/testcafe/lib/utils/guard-time-execution.js:5:20)
at LiveModeBootstrapper._getTests (/***/node_modules/testcafe/lib/runner/bootstrapper.js:102:21)
at Function.all (<anonymous>:null:null)
at LiveModeBootstrapper._bootstrapParallel (/***/node_modules/testcafe/lib/runner/bootstrapper.js:195:38)
at LiveModeBootstrapper.createRunnableConfiguration (/***/node_modules/testcafe/lib/runner/bootstrapper.js:214:69)
{
  code: 'E1035',
      data: [
  'Error: TypeScript compilation failed.\n' +
  "***/src/utils/types.d.ts (18, 61): ']' expected.\n" +
  "***/src/utils/types.d.ts (18, 64): ';' expected.\n" +
  "***/src/utils/types.d.ts (18, 69): ';' expected.\n" +
  "***/src/utils/types.d.ts (18, 90): ';' expected.\n" +
  '***/src/utils/types.d.ts (18, 91): Declaration or statement expected.\n' +
  '***/src/utils/types.d.ts (18, 95): Declaration or statement expected.\n' +
  '***/src/utils/types.d.ts (18, 97): Expression expected.\n' +
  "***/src/utils/types.d.ts (19, 9): ';' expected.\n"
]
}
```
 
 ```js
// type declaration where testcafe typescript compiler is failing
export type KeysWithValOfType<T, V> = keyof { [P in keyof T as T[P] extends V ? P : never]: P } & keyof T;
```
 
### What is the Expected behavior?
test should be running

<details>
```js
 // type declaration where testcafe typescript compiler is failing
export type KeysWithValOfType<T, V> = keyof { [P in keyof T as T[P] extends V ? P : never]: P } & keyof T;
```
</details>
 
### Your Environment details:
 
* testcafe version:                  1.15.2
* node.js version:                   14.15.0
* command-line arguments:  testcafe
* browser name and version: chrome 91
* platform and version:          macOS 10.15.7

**Comment by pavsenin** [comment]
Hello,

At present, TestCafe uses TypeScript v3. TypeScript v4 support will be added in a future major release.
As a workaround, if you want to use the latest version of TypeScript, you can install it and specify the path to it via [compilerOptions](https://testcafe.io/documentation/402638/reference/configuration-file#compileroptions).
