### ISSUE TITLE
iFrame request canceled

### ISSUE THREAD

**Issue by TimotheeVille** [DevExpress/testcafe#6488]
### What is your Test Scenario?
We are testing a Jira addon which is rendered in an iFrame in Jira
 
### What is the Current behavior?
Since the version 1.15.3 of testcafe, the iFrame is not rendered. The request to get the iFrame is canceled by the browser
 
### What is the Expected behavior?
We expect the iFrame to be rendered normaly
 
### What is your web application and your TestCafe test code?
We don't have a simple app to provide but you can try the plugin in a Jira instance
https://marketplace.atlassian.com/apps/1221264/cucumber-for-jira-bdd-natively-in-jira?tab=overview&hosting=cloud
 
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { getUrl } from '../support/client_helpers'
import { jiraUser } from '../support/roles'
import { Selector } from 'testcafe'

fixture`Living Documentation`
  .page`https://cucumber-for-jira-preprod.atlassian.net/projects/CM`
  .beforeEach(async test => {
    await test.useRole(jiraUser)
  })

test('I can access all information of a living documentation', async test => {
  const homepageLink = Selector('a').withText('Cucumber for Jira')
  const livingDocumentationName = Selector('h3').withText('c4j-preprod/hps-cucumber-javascript:master')
  const livingDocumentationMenu = Selector('div[role=panel-header] button')

  const livingDocumentationInformationMenuEntry = Selector('[role=menu] span[role=menuitem][title="Living documentation"]')
  const livingDocumentationInformationDialogTitle = Selector('[role=dialog] caption').withText('Living Documentation information')
  const livingDocumentationInformationRepository = Selector('[role=dialog] td').withText('c4j-preprod/hps-cucumber-javascript')
  const livingDocumentationInformationBranch = Selector('[role=dialog] td').withText('master')

  const ciConfigurationMenuEntry = Selector('[role=menu] span[role=menuitem][title="CI configuration"]')
  const ciConfigurationDialogTitle = Selector('[role=dialog] span').withText('CI configuration')

  const webhookUrlMenuEntry = Selector('[role=menu] span[role=menuitem][title="Webhook URL"]')
  const webhookUrlDialogTitle = Selector('[role=dialog] span').withText('Webhook URL')

  const closeDialogButton = Selector('[role=dialog] button').withText('Close')

  await test
    .expect(getUrl()).contains('secure/RapidBoard')
    .click(homepageLink)
    .switchToIframe('[id^="com.smartbear.cucumber__web-item-c4j"]')
    .expect(livingDocumentationName.exists).ok()

    // Expect living documentation information to be accessible
    .click(livingDocumentationMenu)
    .click(livingDocumentationInformationMenuEntry)
    .expect(livingDocumentationInformationDialogTitle.exists).ok()
    .expect(livingDocumentationInformationRepository.exists).ok()
    .expect(livingDocumentationInformationBranch.exists).ok()
    .click(closeDialogButton)

    // Expect ci configuration to be accessible
    .click(livingDocumentationMenu)
    .click(ciConfigurationMenuEntry)
    .expect(ciConfigurationDialogTitle.exists).ok()
    .click(closeDialogButton)

    // Expect webhook url to be accessible
    .click(livingDocumentationMenu)
    .click(webhookUrlMenuEntry)
    .expect(webhookUrlDialogTitle.exists).ok()
    .click(closeDialogButton)
})

```
</details>

<details>
<summary>Your complete test report:</summary>

```json
{
  "startTime": "2021-08-20T13:06:27.662Z",
  "endTime": "2021-08-20T13:07:37.662Z",
  "userAgents": [
    "Chrome 92.0.4515.159 / Linux 0.0"
  ],
  "passed": 0,
  "total": 1,
  "skipped": 0,
  "fixtures": [
    {
      "name": "Living Documentation",
      "path": "/home/timotheeville/Workspace/cucumber-for-jira/testcafe/tests/living_documentation.test.js",
      "meta": {},
      "tests": [
        {
          "name": "I can access all information of a living documentation",
          "meta": {},
          "errs": [
            "The specified selector does not match any element in the DOM tree.\n\n > | Selector('[id^=\"com.smartbear.cucumber__web-item-c4j\"]')\n\nBrowser: Chrome 92.0.4515.159 / Linux 0.0\n\n   27 |  const closeDialogButton = Selector('[role=dialog] button').withText('Close')\n   28 |\n   29 |  await test\n   30 |    .expect(getUrl()).contains('secure/RapidBoard')\n   31 |    .click(homepageLink)\n > 32 |    .switchToIframe('[id^=\"com.smartbear.cucumber__web-item-c4j\"]')\n   33 |    .expect(livingDocumentationName.exists).ok()\n   34 |\n   35 |    // Expect living documentation information to be accessible\n   36 |    .click(livingDocumentationMenu)\n   37 |    .click(livingDocumentationInformationMenuEntry)\n\n   at <anonymous> (/home/timotheeville/Workspace/cucumber-for-jira/testcafe/tests/living_documentation.test.js:32:6)\n   at asyncGeneratorStep (/home/timotheeville/Workspace/cucumber-for-jira/testcafe/tests/living_documentation.test.js:3:226)\n   at _next (/home/timotheeville/Workspace/cucumber-for-jira/testcafe/tests/living_documentation.test.js:3:564)\n   at <anonymous> (/home/timotheeville/Workspace/cucumber-for-jira/testcafe/tests/living_documentation.test.js:3:729)\n   at <anonymous> (/home/timotheeville/Workspace/cucumber-for-jira/testcafe/tests/living_documentation.test.js:3:470)\n   at <anonymous> (/home/timotheeville/Workspace/cucumber-for-jira/testcafe/tests/living_documentation.test.js:11:5)"
          ],
          "durationMs": 69963,
          "unstable": false,
          "screenshotPath": null,
          "skipped": false
        }
      ]
    }
  ],
  "warnings": []
}
```
</details>

<details>
<summary>Screenshots:</summary>

![Capture d’écran du 2021-08-20 14-47-43](https://user-images.githubusercontent.com/29116953/130239213-b0d10881-b0d4-4779-bec6-23858fac69bf.png)

![Screenshot2](https://user-images.githubusercontent.com/29116953/130237478-ced3838f-7369-4ff2-b9e2-7ddcf7702576.png)
</details> 

### Your Environment details:
 
* testcafe version: 1.15.3
* node.js version: v12.18.2
* command-line arguments:  testcafe chrome
* browser name and version: chrome Version 92.0.4515.159 (Official Build) (64-bit)
* platform and version: Ubuntu 20.10

**Comment by aleks-pro** [comment]
Hello @TimotheeVille ,

Thank you for pointing out this issue to us. I reproduced it. We will research it and will update this thread once we have any results. Please bear with us.
