### ISSUE TITLE
Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by felis2803** [DevExpress/testcafe#6558]
### What is your Test Scenario?
1. Open the page https://reborncf.com/users/sign_in.
2. Wait for the login form to be redrawn. 
 
### What is the Current behavior?
In many cases, the test will fail with the "Uncaught exception" error.
 
### What is the Expected behavior?
The test always succeeds.
 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

https://reborncf.com/users/sign_in
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
 import { Selector } from 'testcafe';

fixture `Login form`
    .page `https://reborncf.com/users/sign_in`;

for (let i = 0; i < 12; i++) {
    test(`test ${i}`, async t => {
        await t.expect(Selector('#user_password').visible).notOk();
    });
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Chrome 93.0.4577.82 / Windows 10

 Login form
 √ test 0
 × test 1

   1) Uncaught exception:

      Error: This socket has been ended by the other party
      at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
      at Socket.ondata (internal/streams/readable.js:745:22)
      at Socket.emit (events.js:376:20)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      at TCP.callbackTrampoline (internal/async_hooks.js:134:14)

      Browser: Chrome 93.0.4577.82 / Windows 10


 × test 2

   1) Uncaught exception:

      Error: This socket has been ended by the other party
      at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
      at Socket.ondata (internal/streams/readable.js:745:22)
      at Socket.emit (events.js:376:20)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      at TCP.callbackTrampoline (internal/async_hooks.js:134:14)

      Browser: Chrome 93.0.4577.82 / Windows 10


 × test 3

   1) Uncaught exception:

      Error: This socket has been ended by the other party
      at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
      at Socket.ondata (internal/streams/readable.js:745:22)
      at Socket.emit (events.js:376:20)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      at TCP.callbackTrampoline (internal/async_hooks.js:134:14)

      Browser: Chrome 93.0.4577.82 / Windows 10


 × test 4

   1) Uncaught exception:

      Error: This socket has been ended by the other party
      at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
      at Socket.ondata (internal/streams/readable.js:745:22)
      at Socket.emit (events.js:376:20)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      at TCP.callbackTrampoline (internal/async_hooks.js:134:14)

      Browser: Chrome 93.0.4577.82 / Windows 10


 × test 5

   1) Uncaught exception:

      Error: This socket has been ended by the other party
      at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
      at Socket.ondata (internal/streams/readable.js:745:22)
      at Socket.emit (events.js:376:20)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      at TCP.callbackTrampoline (internal/async_hooks.js:134:14)

      Browser: Chrome 93.0.4577.82 / Windows 10


 √ test 6
 × test 7

   1) Uncaught exception:

      Error: This socket has been ended by the other party
      at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
      at Socket.ondata (internal/streams/readable.js:745:22)
      at Socket.emit (events.js:376:20)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      at TCP.callbackTrampoline (internal/async_hooks.js:134:14)

      Browser: Chrome 93.0.4577.82 / Windows 10


 √ test 8
 × test 9

   1) Uncaught exception:

      Error: This socket has been ended by the other party
      at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
      at Socket.ondata (internal/streams/readable.js:745:22)
      at Socket.emit (events.js:376:20)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      at TCP.callbackTrampoline (internal/async_hooks.js:134:14)

      Browser: Chrome 93.0.4577.82 / Windows 10


 √ test 10
 √ test 11


 7/12 failed (28s)
Error: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.ondata (internal/streams/readable.js:745:22)
    at TLSSocket.emit (events.js:376:20)
    at TLSSocket.emit (domain.js:532:15)
    at addChunk (internal/streams/readable.js:309:12)
```
</details>

### Steps to Reproduce:

Run this test:
```js
 import { Selector } from 'testcafe';

fixture `Login form`
    .page `https://reborncf.com/users/sign_in`;

for (let i = 0; i < 12; i++) {
    test(`test ${i}`, async t => {
        await t.expect(Selector('#user_password').visible).notOk();
    });
}
```
 
### Your Environment details:
 
* testcafe version:                   1.16.0
* node.js version:                    14.17.0
* command-line arguments:  `testcafe chrome test.js`
* browser name and version: Google Chrome (Version 93.0.4577.82 (Official Build) (64-bit))
* platform and version:          Windows 10

**Comment by Farfurix** [comment]
@jbradenclickfunnels 

We are now trying to find the cause of this socket issue with your website, but I cannot give you any estimates.
