### ISSUE TITLE
Create React App + Typescript template + testcafe throwing "Cannot find module: '@babel/plugin-proposal-private-methods'"

### ISSUE THREAD

**Issue by nandastone** [DevExpress/testcafe#6561]
### What is your Test Scenario?
1. Install create-react-app with TypeScript template:  `npx create-react-app my-app --template typescript`

2. Install testcafe: `yarn add --dev testcafe`

3. Create simple testcafe test:

```
// e2e/test.ts
import { fixture, test, Selector } from "testcafe";

fixture("Index").page("http://localhost:3004/");

test("tells you how to edit the app", async (t) => {
  const instructionText = Selector("p").withText(
    "Edit src/App.tsx and save to reload."
  );

  await t.expect(instructionText.exists).ok();
});
```

4. Start CRA dev server: `yarn start`

5. Run testcafe tests: `yarn run testcafe chrome e2e/`
 
### What is the Current behavior?

Tests fail with `Error: Cannot find module '@babel/plugin-proposal-private-methods'`.

Full stack trace:

```
ERROR Error: Cannot find module '@babel/plugin-proposal-private-methods'
Require stack:
- /Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/lib/compiler/babel/load-libs.js
- /Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/lib/compiler/test-file/formats/es-next/compiler.js
- /Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/lib/compiler/compilers.js
- /Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/lib/compiler/index.js
- /Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/lib/runner/bootstrapper.js
- /Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/lib/runner/index.js
- /Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/lib/testcafe.js
- /Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/lib/index.js
- /Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/lib/cli/cli.js
- /Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/lib/cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.loadLibs [as default] (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/compiler/babel/load-libs.js:64:38)
    at downgradeES (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/compiler/compile-client-function.js:42:36)
    at Object.compileClientFunction [as default] (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/compiler/compile-client-function.js:89:14)
    at ClientFunctionBuilder._getCompiledFnCode (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/client-functions/client-function-builder.js:122:41)
    at new ClientFunctionBuilder (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/client-functions/client-function-builder.js:31:36)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/client-functions/selectors/add-api.js:19:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/client-functions/selectors/selector-builder.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/test-run/commands/actions.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/api/test-controller/index.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/api/wrap-test-function.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/api/structure/fixture.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/compiler/test-file/api-based.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/compiler/test-file/formats/es-next/compiler.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/compiler/compilers.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/compiler/index.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/runner/bootstrapper.ts:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/runner/index.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at lazy (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/import-lazy/index.js:2:51)
    at Object.construct (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/import-lazy/index.js:18:11)
    at TestCafe._createRunner (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/testcafe.js:72:27)
    at TestCafe.createRunner (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/testcafe.js:92:21)
    at runTests (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/cli/cli.js:99:75)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at cli (/Users/mattstone/Work/experiments/cra-testcafe/node_modules/testcafe/src/cli/cli.js:174:13)
```
 
### What is the Expected behavior?

testcafe runs tests.
 
### What is your web application and your TestCafe test code?

App is vanilla CRA, test details are above in **What is your Test Scenario?** section.

### Steps to Reproduce:

Test steps are detailed above in **What is your Test Scenario?** section.

### Your Environment details:
 
* testcafe version:                   1.16.0
* node.js version:                    14.17.3
* command-line arguments:  `yarn run testcafe chrome e2e/`
* browser name and version: Chrome
* platform and version:          MacOS 11.5.2
* other:                                   create-react-app 4.0.3

**Comment by pavsenin** [comment]
Thank you for pointing out this issue. I reproduced it on my side.

**Comment by hyunil-shin** [comment]
I got the same issue. I am going to use yarn2 instead of npm. Finally I got stuck by this issue.
If it takes long, might be there any workaround?

**Comment by pavsenin** [comment]
Hello,

As a temporary workaround, you can downgrade to TestCafe 15.0.0.

We will notify you once a release with a fix is available.
