### ISSUE TITLE
Feature: decoupling of BrowserClient and RuntimeInfo

### ISSUE THREAD

**Issue by aafeltowicz** [DevExpress/testcafe#6570]
### What is your Test Scenario?
Have a chrome, chrome:headless, edge, edge:headless set as default browser in .testcaferc.json config file.
Command: testcafe src/**/*-test.js -L
 
### What is the Current behavior?
Got error:
```
Make changes to the source files or press Ctrl+R to restart the test run.
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'ChromeRuntimeInfo'
| property 'browserClient' -> object with constructor 'BrowserClient'
--- property '_runtimeInfo' closes the circle
at JSON.stringify ()
at Object.getBrowserInfo (xxx\testcafe\node_modules\testcafe\src\browser\provider\pool.js:124:26)
at async Promise.all (index 0)
at TestCafeConfiguration._getBrowserInfo (xxx\testcafe\node_modules\testcafe\src\configuration\testcafe-configuration.ts:265:29)
at TestCafeConfiguration.asyncMergeOptions (xxx\testcafe\node_modules\testcafe\src\configuration\testcafe-configuration.ts:110:44)
at LiveModeRunner._applyOptions (xxx\testcafe\node_modules\testcafe\src\runner\index.js:538:9)

Stopping TestCafe live mode...
 ```
From above we can see that BrowserClient and RuntimeInfo are tightly coupled which may result in errors even after fixing #6499

### What is the Expected behavior?
BrowserClient and RuntimeInfo are related to each other using browserId without direct references inside.

**Comment by aafeltowicz** [comment]
Solution for that would be decoupling BrowserClient and RuntimeInfo classes. Patch before I find time to prepare proper PR:
[BrowsersClient-RuntimeInfo_decoupling.txt](https://github.com/DevExpress/testcafe/files/7227656/BrowsersClient-RuntimeInfo_decoupling.txt)
.

**Comment by aleks-pro** [comment]
Hello @aafeltowicz ,

Thank you for the suggestion. We will look into it and update this thread once we have any results.
