### ISSUE TITLE
ERROR Cannot establish one or more browser connections. 1 of 1 browser connections have not been established

### ISSUE THREAD

**Issue by habeeb-badmus-trimplement** [DevExpress/testcafe#6690]
### What is your Scenario?

I schedule a job to run my end-to-end test at interval using jenkins.

### What is the Current behavior?

2021-11-11T05:55:11.856Z testcafe:utils:temp-directory Found temp directories: []
2021-11-11T05:55:11.857Z testcafe:utils:temp-directory Temp directory path:  /tmp/testcafe/chrome-profile-18TYRCEm2UJoj7
2021-11-11T05:55:11.936Z testcafe:bootstrapper tests compilation took 81 ms
2021-11-11T05:55:12.227Z testcafe:browser-tools:open '"/usr/bin/chromium-browser" --remote-debugging-port=38765 --user-data-dir=/tmp/testcafe/chrome-profile-18TYRCEm2UJoj7 --headless --disable-infobars --disable-session-crashed-bubble --no-first-run --new-window --disable-background-networking --disable-ipc-flooding-protection --disable-background-timer-throttling --disable-backgrounding-occluded-windows --autoplay-policy=no-user-gesture-required --no-sandbox --disable-dev-shm-usage "http://172.17.0.3:1337/browser/connect/9S3yY7W" 0<&- >/dev/null 2>&1 &'
2021-11-11T05:55:28.130Z testcafe:browser:connection:9S3yY7W status changed to 'ready'
2021-11-11T05:57:11.942Z testcafe:browser:connection:9S3yY7W status changed to 'closing'
2021-11-11T05:57:11.996Z testcafe:browser:connection:9S3yY7W TypeError: Cannot read property 'config' of undefined
    at BrowserProviderPluginHost.isHeadlessBrowser (/usr/lib/node_modules/testcafe/src/browser/provider/built-in/dedicated/base.js:65:51)
    at BrowserProvider.canUseDefaultWindowActions (/usr/lib/node_modules/testcafe/src/browser/provider/index.ts:263:53)
    at BrowserProvider.closeBrowser (/usr/lib/node_modules/testcafe/src/browser/provider/index.ts:326:44)
    at BrowserConnection._closeBrowser (/usr/lib/node_modules/testcafe/src/browser/connection/index.ts:221:13)
    at BrowserConnection.close (/usr/lib/node_modules/testcafe/src/browser/connection/index.ts:423:9)
    at Function._closeConnection (/usr/lib/node_modules/testcafe/src/runner/browser-set.ts:55:9)
    at async Promise.all (index 0)
    at BrowserSet.dispose (/usr/lib/node_modules/testcafe/src/runner/browser-set.ts:163:9)
    at Function.from (/usr/lib/node_modules/testcafe/src/runner/browser-set.ts:108:13)
    at async Promise.all (index 0)
2021-11-11T05:57:11.997Z testcafe:browser:connection:9S3yY7W status changed to 'closed'
ERROR Cannot establish one or more browser connections.
1 of 1 browser connections have not been established:
- chromium:headless

### What is the Expected behavior?

test should pass.

### What is your public website URL? (or attach your complete example)

http://devexpress.github.io/testcafe/example

### What is your TestCafe test code?

```
import { Selector } from 'testcafe';
fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');
});
```

### Your complete configuration file

not using configuration file

### Your complete test report

```
+ docker run --rm -v /var/jenkins_home/workspace/shop-testcafe-test:/project -w /project --env ENV=dev --env DEBUG=testcafe:* testcafe/testcafe chromium:headless simple-test.js
2021-11-11T05:55:10.615Z testcafe:cli 
    [
      '/usr/bin/node',
      '/usr/lib/node_modules/testcafe/lib/cli',
      '--ports',
      '1337,1338',
      'chromium:headless',
      'simple-test.js'
    ]

2021-11-11T05:55:10.619Z testcafe:cli 
    {
      clientScripts: [],
      ports: [
        1337,
        1338
      ],
      v8Flags: undefined,
      listBrowsers: false,
      browsers: [
        'chromium:headless'
      ],
      src: [
        'simple-test.js'
      ],
      filter: undefined,
      screenshots: {},
      reporter: []
    }

2021-11-11T05:55:10.621Z testcafe:configuration Unable to find the "/project/.testcaferc.js" configuration file. Error details:

Error: ENOENT: no such file or directory, stat '/project/.testcaferc.js'
2021-11-11T05:55:10.621Z testcafe:configuration Unable to find the "/project/.testcaferc.json" configuration file. Error details:

Error: ENOENT: no such file or directory, stat '/project/.testcaferc.json'
2021-11-11T05:55:11.842Z testcafe:runner 
    TestCafeConfiguration {
      _options: {
        developmentMode: Option {
          name: 'developmentMode',
          value: false,
          source: 'Configuration'
        },
        hostname: Option {
          name: 'hostname',
          value: '172.17.0.3',
          source: 'Input'
        },
        port1: Option {
          name: 'port1',
          value: 1337,
          source: 'Input'
        },
        port2: Option {
          name: 'port2',
          value: 1338,
          source: 'Input'
        },
        ssl: Option {
          name: 'ssl',
          value: undefined,
          source: 'Input'
        },
        experimentalDebug: Option {
          name: 'experimentalDebug',
          value: undefined,
          source: 'Input'
        },
        retryTestPages: Option {
          name: 'retryTestPages',
          value: false,
          source: 'Configuration'
        },
        cache: Option {
          name: 'cache',
          value: undefined,
          source: 'Input'
        },
        configFile: Option {
          name: 'configFile',
          value: undefined,
          source: 'Input'
        },
        disableHttp2: Option {
          name: 'disableHttp2',
          value: false,
          source: 'Configuration'
        },
        v8Flags: Option {
          name: 'v8Flags',
          value: undefined,
          source: 'Input'
        },
        proxy: Option {
          name: 'proxy',
          value: undefined,
          source: 'Input'
        },
        proxyBypass: Option {
          name: 'proxyBypass',
          value: undefined,
          source: 'Input'
        },
        src: Option {
          name: 'src',
          value: [Array],
          source: 'Input'
        },
        tsConfigPath: Option {
          name: 'tsConfigPath',
          value: undefined,
          source: 'Input'
        },
        browsers: Option {
          name: 'browsers',
          value: [Array],
          source: 'Input'
        },
        reporter: Option {
          name: 'reporter',
          value: undefined,
          source: 'Input'
        },
        concurrency: Option {
          name: 'concurrency',
          value: 1,
          source: 'Configuration'
        },
        filter: Option {
          name: 'filter',
          value: undefined,
          source: 'Input'
        },
        videoPath: Option {
          name: 'videoPath',
          value: undefined,
          source: 'Input'
        },
        videoOptions: Option {
          name: 'videoOptions',
          value: undefined,
          source: 'Input'
        },
        videoEncodingOptions: Option {
          name: 'videoEncodingOptions',
          value: undefined,
          source: 'Input'
        },
        screenshots: Option {
          name: 'screenshots',
          value: [Object],
          source: 'Input'
        },
        appCommand: Option {
          name: 'appCommand',
          value: undefined,
          source: 'Input'
        },
        appInitDelay: Option {
          name: 'appInitDelay',
          value: 1000,
          source: 'Configuration'
        },
        clientScripts: Option {
          name: 'clientScripts',
          value: undefined,
          source: 'Input'
        },
        compilerOptions: Option {
          name: 'compilerOptions',
          value: [Object],
          source: 'Input'
        },
        skipJsErrors: Option {
          name: 'skipJsErrors',
          value: false,
          source: 'Configuration'
        },
        debugMode: Option {
          name: 'debugMode',
          value: false,
          source: 'Configuration'
        },
        debugOnFail: Option {
          name: 'debugOnFail',
          value: false,
          source: 'Configuration'
        },
        skipUncaughtErrors: Option {
          name: 'skipUncaughtErrors',
          value: false,
          source: 'Configuration'
        },
        stopOnFirstFail: Option {
          name: 'stopOnFirstFail',
          value: false,
          source: 'Configuration'
        },
        takeScreenshotsOnFails: Option {
          name: 'takeScreenshotsOnFails',
          value: false,
          source: 'Configuration'
        },
        disablePageCaching: Option {
          name: 'disablePageCaching',
          value: false,
          source: 'Configuration'
        },
        disablePageReloads: Option {
          name: 'disablePageReloads',
          value: false,
          source: 'Configuration'
        },
        disableScreenshots: Option {
          name: 'disableScreenshots',
          value: false,
          source: 'Configuration'
        },
        disableMultipleWindows: Option {
          name: 'disableMultipleWindows',
          value: false,
          source: 'Configuration'
        },
        selectorTimeout: Option {
          name: 'selectorTimeout',
          value: 10000,
          source: 'Configuration'
        },
        assertionTimeout: Option {
          name: 'assertionTimeout',
          value: 3000,
          source: 'Configuration'
        },
        pageLoadTimeout: Option {
          name: 'pageLoadTimeout',
          value: 3000,
          source: 'Configuration'
        },
        speed: Option {
          name: 'speed',
          value: 1,
          source: 'Configuration'
        },
        proxyless: Option {
          name: 'proxyless',
          value: false,
          source: 'Configuration'
        }
      },
      _defaultPaths: [
        '/project/.testcaferc.js',
        '/project/.testcaferc.json'
      ],
      _filePath: '/project/.testcaferc.js',
      _overriddenOptions: [],
      _isExplicitConfig: false
    }

2021-11-11T05:55:11.856Z testcafe:utils:temp-directory Found temp directories: []
2021-11-11T05:55:11.857Z testcafe:utils:temp-directory Temp directory path:  /tmp/testcafe/chrome-profile-18TYRCEm2UJoj7
2021-11-11T05:55:11.936Z testcafe:bootstrapper tests compilation took 81 ms
2021-11-11T05:55:12.227Z testcafe:browser-tools:open '"/usr/bin/chromium-browser" --remote-debugging-port=38765 --user-data-dir=/tmp/testcafe/chrome-profile-18TYRCEm2UJoj7 --headless --disable-infobars --disable-session-crashed-bubble --no-first-run --new-window --disable-background-networking --disable-ipc-flooding-protection --disable-background-timer-throttling --disable-backgrounding-occluded-windows --autoplay-policy=no-user-gesture-required --no-sandbox --disable-dev-shm-usage "http://172.17.0.3:1337/browser/connect/9S3yY7W" 0<&- >/dev/null 2>&1 &'
2021-11-11T05:55:28.130Z testcafe:browser:connection:9S3yY7W status changed to 'ready'
2021-11-11T05:57:11.942Z testcafe:browser:connection:9S3yY7W status changed to 'closing'
2021-11-11T05:57:11.996Z testcafe:browser:connection:9S3yY7W TypeError: Cannot read property 'config' of undefined
    at BrowserProviderPluginHost.isHeadlessBrowser (/usr/lib/node_modules/testcafe/src/browser/provider/built-in/dedicated/base.js:65:51)
    at BrowserProvider.canUseDefaultWindowActions (/usr/lib/node_modules/testcafe/src/browser/provider/index.ts:263:53)
    at BrowserProvider.closeBrowser (/usr/lib/node_modules/testcafe/src/browser/provider/index.ts:326:44)
    at BrowserConnection._closeBrowser (/usr/lib/node_modules/testcafe/src/browser/connection/index.ts:221:13)
    at BrowserConnection.close (/usr/lib/node_modules/testcafe/src/browser/connection/index.ts:423:9)
    at Function._closeConnection (/usr/lib/node_modules/testcafe/src/runner/browser-set.ts:55:9)
    at async Promise.all (index 0)
    at BrowserSet.dispose (/usr/lib/node_modules/testcafe/src/runner/browser-set.ts:163:9)
    at Function.from (/usr/lib/node_modules/testcafe/src/runner/browser-set.ts:108:13)
    at async Promise.all (index 0)
2021-11-11T05:57:11.997Z testcafe:browser:connection:9S3yY7W status changed to 'closed'
ERROR Cannot establish one or more browser connections.
1 of 1 browser connections have not been established:
- chromium:headless

Hints:
- Increase the value of the "browserInitTimeout" option if it is too low (currently: 2 minutes for local browsers and 6 minutes for remote browsers). This option determines how long TestCafe waits for browsers to be ready.
- The error can also be caused by network issues or remote device failure. Make sure that your network connection is stable and you can reach the remote device.

Type "testcafe -h" for help.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

### Steps to Reproduce

1.  install testCafe version 1.17.0
2. configure jenkins such that it pulls source code from github
3. also configure jenkins run the job with this command `docker run --rm -v ${WORKSPACE}:/project -w /project --env 
ENV=dev --env DEBUG=testcafe:* testcafe/testcafe chromium:headless simple-test.js`
4. configure jenkins to run every 15 minutes

Note: most test will pass, but there will be intermittent failures as shown in the above test report

### TestCafe version

1.17.0

### Node.js version

v12.16.3

### Command-line arguments

docker run --rm -v ${WORKSPACE}:/project -w /project --env  ENV=dev --env DEBUG=testcafe:* testcafe/testcafe chromium:headless simple-test.js

### Platform(s) and version(s)

Ubuntu 16.04.7 LTS

### Other

jenkins is running in docker version Docker version 17.09.0-ce, build afdb6d4

**Comment by pavsenin** [comment]
Hello,
Thank you for your inquire, we already have a request for a similar issue: #6436.
I will close this issue as a duplicate.
