### ISSUE TITLE
there is js errors

### ISSUE THREAD

**Issue by Karrielovely** [DevExpress/testcafe#6709]
JavaScript error details:
      TypeError: this.broadcast is not a function
          at h.<anonymous> (https://ydcdn.nosdn.127.net/dash-online-blue/index.d1b939a990.js:3:2108436)
          at https://ydcdn.nosdn.127.net/dash-online-blue/index.d1b939a990.js:2:3750109

**Comment by Karrielovely** [comment]
here is my scripts,
 Browser: Chrome 96.0.4664.45 / Windows 10

         194 |            .click(this.navi.report)
         195 |    }
         196 |
         197 |    async selectFolder(folderName){
         198 |        await t
       > 199 |            .click(this.table.reportFolder.withExactText(folderName))
         200 |    }
         201 |
         202 |    async selectReport(reportName){
         203 |        await t
         204 |            .click(this.table.reportList.withExactText(reportName))


 this.table.reportFolder = Selector('div.group .folder-1 h4')

source code:
![image](https://user-images.githubusercontent.com/26958126/142613536-5f8309ca-fb8d-4ca1-8471-ac2fe944bc5b.png)
