### ISSUE TITLE
Unable to take screenshots

### ISSUE THREAD

**Issue by mecciau** [DevExpress/testcafe#6808]
### What is your Scenario?

I've created a new testcafe project:

`npm init -y`
`npm install --save-dev testcafe`

also added a new test into `tests` folder.

```
fixture`Google`.page`https://www.google.com`;

test("Take screenshot", async (t) => {
  await t.takeScreenshot();
});
```

### What is the Current behavior?

Running on `chrome` browser
```
testcafe-image-diff  > npx testcafe chrome
 Running tests in:
 - Chrome 96.0.4664.110 / macOS 10.15.7

 Google
 ✓ take screenshot


 1 passed (7s)

 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Error: Unable to locate the page area in the browser window screenshot at
  /testcafe-image-diff/screenshots/2022-01-04_14-56-33/test-1/Chrome_96.0.4664.110_macOS_10.15.7/1.png, because the page area mark with ID
  2539005166 is not found in the screenshot.
      at calculateClipInfo (/testcafe-image-diff/node_modules/testcafe/src/screenshots/crop.js:119:19)
      at Object.cropScreenshot (/testcafe-image-diff/node_modules/testcafe/src/screenshots/crop.js:136:18)
      at /testcafe-image-diff/node_modules/testcafe/src/screenshots/capturer.js:152:40
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Capturer._capture (/testcafe-image-diff/node_modules/testcafe/src/screenshots/capturer.js:133:9)
      at Capturer.captureAction (/testcafe-image-diff/node_modules/testcafe/src/screenshots/capturer.js:186:16)
      at BrowserManipulationQueue._takeScreenshot (/testcafe-image-diff/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:55:20)
      at BrowserManipulationQueue._executeCommand (/testcafe-image-diff/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:72:24)
      at BrowserManipulationQueue.executePendingManipulation
  (/testcafe-image-diff/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:112:24)
  ```

Runing on `chrome:headless`:
```
testcafe-image-diff  > npx testcafe chrome:headless
 Running tests in:
 - Chrome 96.0.4664.110 / macOS 10.15.7

 Handshake
 ✓ take screenshot


 1 passed (7s)

 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Error: Unexpected end of input
      at module.exports.ChunkStream._end (/testcafe-image-diff/node_modules/pngjs/lib/chunkstream.js:100:7)
      at module.exports.ChunkStream._process (/testcafe-image-diff/node_modules/pngjs/lib/chunkstream.js:203:12)
      at module.exports.ChunkStream.end (/testcafe-image-diff/node_modules/pngjs/lib/chunkstream.js:90:10)
      at exports.PNG.PNG.end (/testcafe-image-diff/node_modules/pngjs/lib/png.js:98:16)
      at exports.PNG.PNG.parse (/testcafe-image-diff/node_modules/pngjs/lib/png.js:88:8)
      at Object.readPng (/testcafe-image-diff/node_modules/testcafe/src/utils/promisified-functions.js:25:9)
      at BrowserProviderPluginHost.takeScreenshot
  (/testcafe-image-diff/node_modules/testcafe/src/browser/provider/built-in/dedicated/base.js:90:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at BrowserProvider.takeScreenshot (/testcafe-image-diff/node_modules/testcafe/src/browser/provider/index.ts:404:13 
```

### What is the Expected behavior?

it should save screenshot on both `chrome` and `chrome:headless`, but it only saves on `chrome` with a warning. It should also save thumbnails but it does not do that

### What is your public website URL? (or attach your complete example)

www.google.com

### What is your TestCafe test code?

```
fixture`Google`.page`https://www.google.com`;

test("Take screenshot", async (t) => {
  await t.takeScreenshot();
});
```

### Steps to Reproduce

1. create new testcafe project
2. try to take a screenshot of any url on `chrome` and `chrome:headless`

### TestCafe version

1.18.1

### Node.js version

v17.0.1

### Command-line arguments

npx testcafe chrome:headless

### Browser name(s) and version(s)

chrome, chrome:headless

### Platform(s) and version(s)

macOS 12.1

**Comment by AlexanderMoiseev** [comment]
Hello,

Unfortunately, I was not able to reproduce this behavior.
I see no warnings, and screenshots are working fine for me both in chrome and chrome:headless.
Please try running your example on a freshly installed OS and share the results with us.  If the issues still persist, please send us a full example project.

**Comment by NutanTTN** [comment]
> takeScreenshot();
> });

Hello,
Facing the same issue while running on the Jenkins linux server

**Comment by VasilyStrelyaev** [comment]
Thank you, I reproduced the error. We already have an open issue describing the same behavior: https://github.com/DevExpress/testcafe/issues/6886

Please subscribe to this issue to keep track of our progress.
