### ISSUE TITLE
Drag action should use pointer events in addition to touch events, like modern browsers

### ISSUE THREAD

**Issue by joshhansen** [DevExpress/testcafe#6810]
### What is your Scenario?

I created a numberline widget that responds to pointer events and functions properly on desktop and mobile.
I'd like to test it using testcafe.

### What is the Current behavior?

The testcafe `dragToElement` action does not properly simulate the behavior of a mobile user because it fires touch events only, while mobile browsers seem to trigger touch events AND pointer events on touch.

So as to support both touch and mouse usage, I want to target only the pointer events, not the touch events, with my widget.

However, testcafe's drag action only seems to produce touch events, not pointer events, making the drag gesture emulation inaccurate.

### What is the Expected behavior?

`dragToElement` should fire pointer events as well as touch events.

### What is your public website URL? (or attach your complete example)

http://learnsomething.app

Though the pointer events based widget is not deployed

### What is your TestCafe test code?

The main test file:

```
import landing from './pages/LandingPage.page';
import nav from './pages/Navigable.page'
import numberlinePV from './pages/NumberlineResponseProblemView.page';
import skillIntro from './pages/SkillIntro.page';
import startCourseModal from './pages/StartCourseModal.page';

fixture `Numberline`
	.page('http://localhost:8080')
	.beforeEach(async () => {
		//FIXME When we properly implement login, use testcafe's Role system instead
		await landing.getStarted();

		await startCourseModal.start();
	
		await nav.navigateToSkill('Solving Linear Inequalities');

		await skillIntro.practice();
	})
;

test('clears and submits', async t => {
	const { clearButton: clear, nextOrSubmitButton: next } = numberlinePV;

	await t
		.expect(clear.visible).ok()
		.expect(clear.hasClass('text-button__disabled')).ok()
	;

	await t
		.expect(next.exists).ok()
		.expect(next.visible).ok()
		.expect(next.hasClass('text-button__disabled')).ok()
	;

	await numberlinePV.gtInc(0);

	await t
		.expect(clear.visible).ok()
		.expect(clear.hasClass('text-button')).ok()
		.expect(clear.hasClass('text-button__disabled')).notOk()
		.expect(clear.textContent).contains('Clear')
	;

	await t
		.expect(next.visible).ok()
		.expect(next.hasClass('text-button')).ok()
		.expect(next.hasClass('text-button__disabled')).notOk()
		.expect(next.textContent).contains('Submit')
	;

	await numberlinePV.clear();

	await t
		.expect(clear.visible).ok()
		.expect(clear.hasClass('text-button')).notOk()
		.expect(clear.hasClass('text-button__disabled')).ok()
		.expect(clear.textContent).contains('Clear')
	;

	await t
		.expect(next.visible).ok()
		.expect(next.hasClass('text-button')).notOk()
		.expect(next.hasClass('text-button__disabled')).ok()
		.expect(next.textContent).contains('Submit')
	;

	const value = await numberlinePV.ineqValue();
	const wrongValue = value < 0 ? value + 1 : value - 1;

	await numberlinePV.gtInc(wrongValue);

	await t
		.expect(next.visible).ok()
		.expect(next.hasClass('text-button')).ok()
		.expect(next.hasClass('text-button__disabled')).notOk()
		.expect(next.textContent).contains('Submit')
	;

	await numberlinePV.submit();

	await t
		.expect(next.visible).ok()
		.expect(next.hasClass('text-button')).ok()
		.expect(next.hasClass('text-button__disabled')).notOk()
		.expect(next.textContent).contains('Next')
	;

	await numberlinePV.next();
});
```

The problem actually arises in `NumberlineResponseProblemView.page.ts`, a page constructed around the numberline widget, in the `gtTickIdx` method which is supposed to draw a "greater than" segment on the numberline. The error occurs in the `dragToElement` call, which does not effectively trigger the drag action because it uses touch events rather than the more standard pointer events. This is caught by the following `expect` which finds that the "greater than" segment is not highlighted as expected.

```
import { t, Selector } from 'testcafe';

import { ProblemView } from "./ProblemView.page";

class NumberlineResponseProblemView extends ProblemView {
	async gtTickIdx(tickIdx: number) {
		const tick = Selector('div.tick.central').withAttribute('idx', tickIdx.toString());

		const nextTickIdx = tickIdx + 1;
		const nextLine = Selector('div.line').withAttribute('idx', nextTickIdx.toString());
		const nextTick = Selector('div.tick.central').withAttribute('idx', nextTickIdx.toString());

		await t
			.expect(tick.exists).ok()
			.expect(tick.count).eql(1)
			.expect(tick.visible).ok()
			.expect(tick.getAttribute('idx')).eql(tickIdx.toString())

			.expect(nextTick.exists).ok()
			.expect(nextTick.visible).ok()
			.expect(nextTick.count).eql(1)
			.expect(nextTick.getAttribute('idx')).eql(nextTickIdx.toString())

			// .hover(tick)
			// .expect(tick.getAttribute('highlight')).eql('highlighted')

			.dragToElement(tick, nextTick, {
				offsetX: 1,
				offsetY: 1,
				destinationOffsetX: 1,
				destinationOffsetY: 1,
				speed: 0.5,
			})

			.expect(tick.getAttribute('highlight')).eql('none')

			.expect(nextLine.getAttribute('highlight')).eql('included')
		;
	}

	async gtInc(inc: number) {
		const tickIdx = await Selector('div.number').withExactText(inc.toString()).getAttribute('idx');

		await this.gtTickIdx(parseInt(tickIdx));
	}

	async ineqValue(): Promise<number> {
		const problem = await this.problemContent();

		return problem
			.split(' ')
			.map(x => parseInt(x))
			.filter(x => !isNaN(x))
			[0]
		;
	}
}

export default new NumberlineResponseProblemView();
```

### Your complete configuration file

n/a

### Your complete test report

```
$ yarn test:e2e:ci:linux
 Running tests in:
 - Chrome 94.0.4606.81 / Linux 0.0

 Graph
 ✓ adds and clears a point

 LandingPage
 ✓ all buttons scroll into view

 NumberResponse
 ✓ gets one wrong then right and proceeds

 Numberline
 ✓ clears and submits

 StartCourseModal
 ✓ all buttons fully visible


 5 passed (1m 10s)
 Running tests in:
 - Chrome 94.0.4606.81 / Linux 0.0 (Emulating iPhone 6/7/8)

 Graph
 ✓ adds and clears a point

 LandingPage
 ✓ all buttons scroll into view

 NumberResponse
 ✓ gets one wrong then right and proceeds

 Numberline
 ✖ clears and submits

   1) AssertionError: expected 'none' to deeply equal 'included'
      
      + expected - actual
      
      -none
      +included
      

      Browser: Chrome 94.0.4606.81 / Linux 0.0 (Emulating iPhone 6/7/8)

         32 |    			speed: 0.5,
         33 |			})
         34 |
         35 |			.expect(tick.getAttribute('highlight')).eql('none')
         36 |
       > 37 |			.expect(nextLine.getAttribute('highlight')).eql('included')
         38 |		;
         39 |	}
         40 |
         41 |	async gtInc(inc: number) {
         42 |		const tickIdx = await Selector('div.number').withExactText(inc.toString()).getAttribute('idx');

         at NumberlineResponseProblemView.<anonymous>
      (/home/josh/Projects/learn-something3/client/e2e/pages/NumberlineResponseProblemView.page.ts:37:48)
         at <anonymous> (/home/josh/Projects/learn-something3/client/e2e/pages/NumberlineResponseProblemView.page.ts:8:71)
         at __awaiter (/home/josh/Projects/learn-something3/client/e2e/pages/NumberlineResponseProblemView.page.ts:4:12)
         at NumberlineResponseProblemView.gtTickIdx
      (/home/josh/Projects/learn-something3/client/e2e/pages/NumberlineResponseProblemView.page.ts:16:16)
         at NumberlineResponseProblemView.<anonymous>
      (/home/josh/Projects/learn-something3/client/e2e/pages/NumberlineResponseProblemView.page.ts:44:14)
         at fulfilled (/home/josh/Projects/learn-something3/client/e2e/pages/NumberlineResponseProblemView.page.ts:5:58)


 StartCourseModal
 ✓ all buttons fully visible


 1/5 failed (1m 10s)
ERROR: "test:e2e:chromium:headless:touch" exited with 1.
```

### Steps to Reproduce

```
<!DOCTYPE html>
<html>
    <head>
        <script>
            function pd(e) {
                console.log('pd');
                e.preventDefault();
            }
            function pl(e) {
                console.log('pl');
                e.preventDefault();
            }
            function pu(e) {
                console.log('pu');
                e.preventDefault();
            }
            function ts(e) {
                console.log('ts');
                if (e.cancelable) {
                    e.preventDefault();
                }
            }
            function load() {
                const html = document.querySelector('html');
                html.addEventListener('pointerdown', pd, { passive: false });
                html.addEventListener('pointerleave', pl, { passive: false });
                html.addEventListener('pointerup', pu, { passive: false });
                html.addEventListener('touchstart', ts, { passive: false });
            }
        </script>
        <style>html {
            user-select: none;
            height: 100px;
            overflow-y: hidden;
        }</style>
    </head>
<body onload="load()">
    <span id="start" onpointermove="console.log('pm1');">Drag from here...</span>
    <span id="end" onpointermove="console.log('pm2');">... to here</span>
</body>
</html>
```

1. Make a simple widget that reacts to pointer events, see above
2. See that mobile browsers are able to interact with the widget via touch, and that dragging from the first element to the second produces these pointer events.
3. See that mobile device emulation in TestCafe + Chrome fails to produce a comparable sequence of pointer events via touch, try
```
.dragToElement(start, end)
```
to drag between the two `span`s.

### TestCafe version

1.18.0

### Node.js version

v15.3.0

### Command-line arguments

testcafe "chromium:headless:emulation:device=iPhone 6/7/8" ./e2e/*.test.ts

### Browser name(s) and version(s)

Chromium Version 94.0.4606.81 (Official Build) Fedora Project (64-bit)

### Platform(s) and version(s)

Fedora 35 x86_64

**Comment by miherlosev** [comment]
Hi @joshhansen 

> The testcafe dragToElement action does not properly simulate the behavior of a mobile user because it fires touch events only, while mobile browsers seem to trigger touch events AND pointer events on touch.

Could you please share an example that we can run without any additional setup? See more information about creating an example in the [Create a Minimal Working Example When You Submit an Issue](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue) article.
