### ISSUE TITLE
resizeWindow fails to resize the window on chrome:headless without reporting an error

### ISSUE THREAD

**Issue by ccheraa** [DevExpress/testcafe#6883]
### What is your Scenario?

I want to run some tests for different window sizes, so some tests will start with `.resizeWindow(x, y);`.

### What is the Current behavior?

The test fails, because the expected UI for the specified window size doesn't exist, because the command `.resizeWindow` didn't actually resize the window.

### What is the Expected behavior?

The window should resize correctly, and the test should pass.

### What is your public website URL? (or attach your complete example)

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    div.small {
      display: none;
    }
    @media only screen and (max-width: 600px) {
      div.small {
        display: block;
      }
      div.large {
        display: none;
      }
    }
  </style>
  <title>.resizeWindow</title>
</head>
<body>
  <div class="large">
    <h1>Large screen</h1>
  </div>
  <div class="small">
    <h1>Small screen</h1>
  </div>
</body>
</html>
```

### What is your TestCafe test code?

```typescript
import { Selector } from 'testcafe';

const url = 'http://127.0.0.1:3000/index.html';

fixture`resizeWindow issue test`
  .page`${url}`
  .beforeEach(async t => {
    await t.resizeWindow(1280, 800)
    return t;
  });

test('test for large screen', async t => {
  await t
    .expect(Selector('.large').visible).ok()
    .expect(Selector('.small').visible).notOk();
});
test('test for small screen', async t => {
  await t
    .resizeWindow(480, 800)
    .expect(Selector('.small').visible).ok()
    .expect(Selector('.large').visible).notOk();
});
```

### Your complete configuration file

no configuration file

### Your complete test report

```
yarn run v1.22.17
$ testcafe chrome:headless test
 Running tests in:
 - Chrome 98.0.4758.80 / Linux 0.0

 resizeWindow issue test
 ✓ test for large screen
 ✖ test for small screen

   1) AssertionError: expected false to be truthy

      Browser: Chrome 98.0.4758.80 / Linux 0.0

         15 |    .expect(Selector('.small').visible).notOk();
         16 |});
         17 |test('test for large screen', async t => {
         18 |  await t
         19 |    .resizeWindow(480, 800)
       > 20 |    .expect(Selector('.small').visible).ok()
         21 |    .expect(Selector('.large').visible).notOk();
         22 |});
         23 |

         at <anonymous> (/home/ccheraa/Test/resize-window-issue/test/resize.spec.ts:20:41)
         at <anonymous> (/home/ccheraa/Test/resize-window-issue/test/resize.spec.ts:8:71)
         at __awaiter (/home/ccheraa/Test/resize-window-issue/test/resize.spec.ts:4:12)
         at <anonymous> (/home/ccheraa/Test/resize-window-issue/test/resize.spec.ts:17:41)



 1/2 failed (7s)
error Command failed with exit code 1.
```

### Steps to Reproduce

1. run a local server serving the html file
2. run the test

### TestCafe version

1.18.3

### Node.js version

14.17

### Command-line arguments

chrome:headless test/resize.spec.ts

### Browser name(s) and version(s)

Chrome 98.0.4758.102

### Platform(s) and version(s)

Ubuntu 21.10

**Comment by tmhao2005** [comment]
I also ran into the same issue but it's still intermittent in my case though. Is there any update on this one yet @alexphilin ?

**Comment by Klaster1** [comment]
A simple retry wrapper around `resilzeWindow` helped to stabilize my test suite:
```
/**
 * Workaround for TestCafe intermittently [not resizing the window](https://github.com/DevExpress/testcafe/issues/6883).
 */
export const resizeWindow = async (width: number, height: number, maxAttempts: number = 10) => {
  if (maxAttempts <= 0) return;
  await t.resizeWindow(width, height);
  const rect: { width: number; height: number } = await t.eval(() => ({
    width: window.innerWidth,
    height: window.innerHeight,
  }));
  if (rect.width !== width || rect.height !== height) {
    await resizeWindow(width, height, maxAttempts - 1);
  }
};
```

**Comment by Aleksey28** [comment]
Hi @Klaster1,

Thank you for the workaround.

**Comment by marmoure** [comment]
@mcmeeking
check out the work around provided here

**Comment by Artem-Babich** [comment]
Hi, I just tried to reproduce this issue with TestCafe v2.5.0, and it is not reproducible anymore. Feel free to reopen this issue if you encounter this behavior in v2.5.0 or higher.
