### ISSUE TITLE
Unable to take screenshots on chrome:headless

### ISSUE THREAD

**Issue by agataDeviniti** [DevExpress/testcafe#6886]
### What is your Scenario?

I noticed that screenshot is not taken when running test in chrome or chrome:headless. I receive the following error:
```
 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Error: Unable to locate the page area in the browser window screenshot at
  /Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/log/2022-02-20_20-33-31/test-1/run-1/Chrome_98.0.4758.102_macOS_10.15.7/1.png, because the page
  area mark with ID 2538690424 is not found in the screenshot.
      at calculateClipInfo (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/crop.js:119:19)
      at Object.cropScreenshot (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/crop.js:136:18)
      at /Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/capturer.js:148:40
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Capturer._capture (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/capturer.js:129:9)
      at Capturer.captureAction (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/capturer.js:181:16)
      at BrowserManipulationQueue._takeScreenshot
  (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:54:20)
      at BrowserManipulationQueue.executePendingManipulation
  (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:71:24)
      at TestRun.ServiceMessages.<computed> [as ready-for-browser-manipulation]
  (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/test-run/index.js:1080:18)
      at TestRun.handleServiceMessage (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe-hammerhead/lib/session/index.js:70:20)
```

The problem appears only on Chrome browser. I have checked both Firefox and Safari and it works fine there.
Maybe the problem concerns macOS, but I am not able to confirm this assumption.

Environment:
* Chrome 98.0.4758.102
* macOS 10.15.7
* TestCafe version 1.14.2 (I cannot update due to issue https://github.com/DevExpress/testcafe/issues/6681)

### What is the Current behavior?

The screenshot is not taken when using takeScreenshot() function or when test fails.

I receive following error when running test with takeScreenshot() function:
```
 Running tests in:
 - Chrome 98.0.4758.102 / macOS 10.15.7

 Google
 ✓ Take screenshot


 1 passed (3s)

 Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Error: Unable to locate the page area in the browser window screenshot at
  /Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/log/2022-02-20_20-33-31/test-1/run-1/Chrome_98.0.4758.102_macOS_10.15.7/1.png, because the page
  area mark with ID 2538690424 is not found in the screenshot.
      at calculateClipInfo (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/crop.js:119:19)
      at Object.cropScreenshot (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/crop.js:136:18)
      at /Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/capturer.js:148:40
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Capturer._capture (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/capturer.js:129:9)
      at Capturer.captureAction (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/capturer.js:181:16)
      at BrowserManipulationQueue._takeScreenshot
  (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:54:20)
      at BrowserManipulationQueue.executePendingManipulation
  (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:71:24)
      at TestRun.ServiceMessages.<computed> [as ready-for-browser-manipulation]
  (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/test-run/index.js:1080:18)
      at TestRun.handleServiceMessage (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe-hammerhead/lib/session/index.js:70:20)
```

### What is the Expected behavior?

The screenshot should be taken.

### What is your public website URL? (or attach your complete example)

I can reproduce the problem using the test provided below.

### What is your TestCafe test code?

fixture(`Google`).page(`https://www.google.com`);

test('Take screenshot', async (t) => {
    await t.takeScreenshot();
});

### Steps to Reproduce

1. Run an example test provided above //including takeScreenshot() function// on `chrome` or `chrome:headless`

### TestCafe version

1.14.2

### Node.js version

v17.0.1

### Command-line arguments

testcafe chrome -e -q tests/screenshot.test.ts

### Browser name(s) and version(s)

Chrome 98.0.4758.102

### Platform(s) and version(s)

macOS 10.15.7

**Comment by agataDeviniti** [comment]
As I have mentioned I cannot update testcafe version due to issue https://github.com/DevExpress/testcafe/issues/6681. But.. for testing purpose I have upgraded version to 1.18.3(latest) and the problem still appears. When running an example test on 1.18.3 I receive the following error:
```
 Running tests in:
 - Chrome 98.0.4758.102 / macOS 10.15.7

 Google
 ✓ Take screenshot


 1 passed (3s)

 Warnings (2):
 --
  The "src" and "browsers" options from the configuration file will be ignored.
 --
  Was unable to take a screenshot due to an error.

  RangeError: The value of "sourceStart" is out of range. It must be >= 0. Received -16051032
      at new NodeError (node:internal/errors:371:5)
      at _copy (node:buffer:219:13)
      at Buffer.copy (node:buffer:775:12)
      at Object.copyImagePart
  (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/utils.js:50:23)
      at Object.cropScreenshot
  (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/crop.js:140:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at /Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/capturer.js:152:34
      at Capturer._capture
  (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/capturer.js:133:9)
      at Capturer.captureAction
  (/Users/agatagrzelczak/Deviniti/DEV/Bitbucket/apps-automated-tests/node_modules/testcafe/src/screenshots/capturer.js:186:16)
```

**Comment by AlexanderMoiseev** [comment]
Hi,

I managed to reproduce this behavior. Please stay tuned for our updates.

Note for the team - reproducible with node version 17.0.1.

**Comment by pawanamigo** [comment]
I am able to replicate this as we\ll..Is there any update on this?

Warnings (1):
 --
  Was unable to take a screenshot due to an error.

  Error: Unexpected end of input
      at module.exports.ChunkStream._end
  (C:\GitLab-Runner\builds\YxWiLN1H\0\dolby-io-sdk\spider-man\node_modules\testcafe\node_modules\pngjs\lib\chunkstream.js:100:7)
      at module.exports.ChunkStream._process
  (C:\GitLab-Runner\builds\YxWiLN1H\0\dolby-io-sdk\spider-man\node_modules\testcafe\node_modules\pngjs\lib\chunkstream.js:203:12)
      at module.exports.ChunkStream.end
  (C:\GitLab-Runner\builds\YxWiLN1H\0\dolby-io-sdk\spider-man\node_modules\testcafe\node_modules\pngjs\lib\chunkstream.js:90:10)
      at exports.PNG.PNG.end
  (C:\GitLab-Runner\builds\YxWiLN1H\0\dolby-io-sdk\spider-man\node_modules\testcafe\node_modules\pngjs\lib\png.js:98:16)
      at exports.PNG.PNG.parse
  (C:\GitLab-Runner\builds\YxWiLN1H\0\dolby-io-sdk\spider-man\node_modules\testcafe\node_modules\pngjs\lib\png.js:88:8)
      at Object.readPng
  (C:\GitLab-Runner\builds\YxWiLN1H\0\dolby-io-sdk\spider-man\node_modules\testcafe\src\utils\promisified-functions.js:25:9)
      at BrowserProviderPluginHost.takeScreenshot
  (C:\GitLab-Runner\builds\YxWiLN1H\0\dolby-io-sdk\spider-man\node_modules\testcafe\src\browser\provider\built-in\dedicated\base.js:90:30)
      at BrowserProvider.takeScreenshot
  (C:\GitLab-Runner\builds\YxWiLN1H\0\dolby-io-sdk\spider-man\node_modules\testcafe\src\browser\provider\index.ts:404:13)
      at Capturer._takeScreenshot
  (C:\GitLab-Runner\builds\YxWiLN1H\0\dolby-io-sdk\spider-man\node_modules\testcafe\src\screenshots\capturer.js:118:9)
      at
  C:\GitLab-Runner\builds\YxWiLN1H\0\dolby-io-sdk\spider-man\node_modules\testcafe\src\screenshots\capturer.js:145:13

**Comment by josephgav** [comment]
I am getting similar errors running trying to get snapshots using testcafe v1.19 with firefox:headless in a docker container:
` Was unable to take a screenshot due to an error.

  Error: no such window: Unable to locate window: undefined
      at MarionetteClient._throwMarionetteError
  (/etc/frontend-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js:132:15)
      at MarionetteClient._getResponse
  (/etc/frontend-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js:191:18)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at MarionetteClient._switchToWindow
  (/etc/frontend-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js:136:9)
      at MarionetteClient._getActiveWindowHandle
  (/etc/frontend-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js:148:13)
      at MarionetteClient._ensureActiveWindow
  (/etc/frontend-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js:168:18)
      at MarionetteClient._request
  (/etc/frontend-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js:175:9)
      at MarionetteClient._getScreenshotRawData
  (/etc/frontend-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js:197:16)
      at MarionetteClient.getScreenshotData
  (/etc/frontend-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js:233:27)
      at BrowserProviderPluginHost.takeScreenshot
  (/etc/frontend-tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/base.js:87:32)`

**Comment by josephgav** [comment]
@miherlosev 
I'm running tests using 1.19.0 so in that case I'll make a new issue.
