### ISSUE TITLE
RangeError-maximum call stack size exceeded

### ISSUE THREAD

**Issue by davilo61** [DevExpress/testcafe#6896]
### File a new question on StackOverflow

https://stackoverflow.com/questions/ask?tags=testcafe

**Comment by davilo61** [comment]
TestCafe just abruptly started throwing the following error:
````
RangeError: Maximum call stack size exceeded
    at WriteStream.overriddenWrite (/Users/{user/Desktop/testcafe_local/node_modules/log-update-async-hook/src/index.js:15:27)
    at WriteStream.stream.write (/Users/{user}/Desktop/testcafe_local/node_modules/testcafe/src/notifications/debug-logger.js:19:30)
    at WriteStream.overriddenWrite{users}/Desktop/testcafe_local/node_modules/log-update-async-hook/src/index.js:22:31)`
```
I couldn't find anything recent on the cause of the error on github or SO.  
Mac O/S running Monterrey 12.2.1 TestCafe 1.18.4. Browser - Chrome Version 98.0.4758.102
I deleted and re-added the node_modules with no change. Error still occurs.
