### ISSUE TITLE
v1.19.0 throws error on node 12: throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);

### ISSUE THREAD

**Issue by qualityshepherd** [DevExpress/testcafe#7064]
### What is your Scenario?

I just tried upgrading to v1.19.0 and now when I run my tests, I get an error:

`throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);`

### What is the Current behavior?

The following error:

internal/util.js:279
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function. Received undefined
    at promisify (internal/util.js:279:11)
    at Object.<anonymous> (/Users/brine/Code/janus-ui/e2e/node_modules/testcafe-safe-storage/lib/file.js:18:33)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/brine/Code/janus-ui/e2e/node_modules/testcafe-safe-storage/lib/index.js:30:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/brine/Code/janus-ui/e2e/node_modules/testcafe/lib/dashboard/config-storage.js:3:33) {
  code: 'ERR_INVALID_ARG_TYPE'
}

### What is the Expected behavior?

That the tests run. 

### What is your public website URL? (or attach your complete example)

don't have/need one

### What is your TestCafe test code?

any

### Steps to Reproduce

Run tests... 

### TestCafe version

v1.19.0 (occurs on all builds newer than 1.19.0-alpha.1)

### Node.js version

 v12.22.10

### Command-line arguments

testcafe chrome tests/

### Browser name(s) and version(s)

chrome102

### Platform(s) and version(s)

mac m1

### Other

Does not occur with node v16. I get that _use the latest node_ will be probably be the answer... but sadly, my app is stuck on v12. ¯\_(ツ)_/¯

**Comment by VasilyStrelyaev** [comment]
I have reproduced the described behavior in Node 12. However, the minimal supported Node version is currently 14. The behavior you described is not reproduced with Node 14, so I will close the issue.

**Comment by qualityshepherd** [comment]
Fair...
