### ISSUE TITLE
v1.19.0 throws error on node 14.7.0: throw new ERR_INVALID_ARG_TYPE('original', 'Function', original)

### ISSUE THREAD

**Issue by CarlesGarro** [DevExpress/testcafe#7072]
### What is your Scenario?

I just tried upgrading to v1.19.0 and now when I run my tests, I get an error:

throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);

I can't use the command "testcafe -v" to get a version, it throws the same error. 

Tried on node LTS version and it worked as expected.

### What is the Current behavior?

internal/util.js:279
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function. Received undefined
    at promisify (internal/util.js:279:11)
    at Object.<anonymous> (/Users/carlesgarrocegarra/Documents/repos/FrontTests/node_modules/testcafe-safe-storage/lib/file.js:18:33)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/carlesgarrocegarra/Documents/repos/FrontTests/node_modules/testcafe-safe-storage/lib/index.js:30:19)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/carlesgarrocegarra/Documents/repos/FrontTests/node_modules/testcafe/lib/dashboard/config-storage.js:3:33) {
  code: 'ERR_INVALID_ARG_TYPE'
}

### What is the Expected behavior?

Should be working on the node version 14.7.0, and I'd expect the tests to run/testcafe to work with 14+ node version.

### What is your public website URL? (or attach your complete example)

none, use 14.7.0 node version with testcafe 1.19 and nothing works.

### What is your TestCafe test code?

no need, you cna run testcafe -v on the terminal with that combination and It will throw the error.

### Steps to Reproduce

1. Install node version 14.7.0
2. Install testcafe 1.19
3. Nothing works.

### TestCafe version

1.19

### Node.js version

14.7.0

### Command-line arguments

testcafe chrome tests

**Comment by CarlesGarro** [comment]
okey, that's nice to know, thanks!
