### ISSUE TITLE
Hamerhead proxy breaks syntax when destructuring, parenthesis, and nullish coalescing are used in the same statement

### ISSUE THREAD

**Issue by dantman** [DevExpress/testcafe#7088]
### What is your Scenario?

I have a script where destructuring is used in the same statement as parenthesis and nullish coalescing (??). This works fine normally and even works if I use the browser TestCafe opens to directly visit the site.

But when the site is visited by TestCafe through the hamerhead proxy the proxy I get a `Uncaught SyntaxError: Unexpected token '??' ` error.

### What is the Current behavior?

The following script:

```js
// Variables
const a = undefined;
const b = 'b';
const c = 0;
const get = () => 1;
const obj = {b: 1}

// Normal nullish colascing usage
const d = a ?? b;
// nullish colascing with parentheses
const e = (a && b) ?? c;
// nullish colascing with a function
const f = get() ?? c;
// nullish colascing with a function and parentheses
const g = (a && get()) ?? c;
// nullish colascing with property syntax
const h = obj['b'] ?? c;
// nullish colascing with property syntax and parentheses
const i = (a && obj['b']) ?? c;
// nullish colascing with dynamic property syntax
const j = obj[b] ?? c;
// nullish colascing with dynamic property syntax and parentheses
const k = {a: (b && obj[b]) ?? c};
// nullish colascing with dynamic property syntax, parentheses, and descructuring
const {l} = {l: (b && obj[b]) ?? c};

// Test completed
document.getElementById('result').innerHTML = 'Script completed';

export {}
```

Is converted to the following by hamerhead:
```js
/*hammerhead|script|start*/if (typeof window !== 'undefined' && window){window['hammerhead|process-dom-method'] && window['hammerhead|process-dom-method']();if (window.__get$ && typeof __get$ === 'undefined')var __get$Loc = window.__get$Loc,__set$Loc = window.__set$Loc,__set$ = window.__set$,__get$ = window.__get$,__call$ = window.__call$,__get$Eval = window.__get$Eval,__proc$Script = window.__proc$Script,__proc$Html = window.__proc$Html,__get$PostMessage = window.__get$PostMessage,__get$ProxyUrl = window.__get$ProxyUrl,__rest$Array = window.__rest$Array,__rest$Object = window.__rest$Object,__arrayFrom$ = window.__arrayFrom$;} else {if (typeof __get$ === 'undefined')var __get$Loc = function(l){return l},__set$Loc = function(l,v){return l = v},__set$ = function(o,p,v){return o[p] = v},__get$ = function(o,p){return o[p]},__call$ = function(o,p,a){return o[p].apply(o,a)},__get$Eval = function(e){return e},__proc$Script = function(s){return s},__proc$Html = function(h){return h},__get$PostMessage = function(w,p){return arguments.length===1?w.postMessage:p},__get$ProxyUrl = function(u,d){return u},__rest$Array = function(a,i){return Array.prototype.slice.call(a, i)},__rest$Object = function(o,p){var k=Object.keys(o),n={};for(var i=0;i<k.length;++i)if(p.indexOf(k[i])<0)n[k[i]]=o[k[i]];return n},__arrayFrom$ = function(r){if(!r)return r;return!Array.isArray(r)&&"function"==typeof r[Symbol.iterator]?Array.from(r):r};if (typeof importScripts !== "undefined" && /\[native code]/g.test(importScripts.toString()))importScripts((location.origin || (location.protocol + "//" + location.host)) + "/worker-hammerhead.js");}/*hammerhead|script|processing-header-end*/
// Variables
const a = undefined;
const b = 'b';
const c = 0;
const get = () => 1;
const obj = {b: 1}

// Normal nullish colascing usage
const d = a ?? b;
// nullish colascing with parentheses
const e = (a && b) ?? c;
// nullish colascing with a function
const f = get() ?? c;
// nullish colascing with a function and parentheses
const g = (a && get()) ?? c;
// nullish colascing with property syntax
const h = obj['b'] ?? c;
// nullish colascing with property syntax and parentheses
const i = (a && obj['b']) ?? c;
// nullish colascing with dynamic property syntax
const j =  __get$(obj,b)  ?? c;
// nullish colascing with dynamic property syntax and parentheses
const k = {a: (b &&  __get$(obj,b) ) ?? c};
// nullish colascing with dynamic property syntax, parentheses, and descructuring
 const _hh$temp0={l:b&&__get$(obj,b)??c},l=_hh$temp0.l; 

// Test completed
document.getElementById('result').innerHTML = 'Script completed';

export {}

/*hammerhead|script|end*/
```

### What is the Expected behavior?

When the following code is transformed by hammerhead:
```js
// nullish colascing with dynamic property syntax, parentheses, and descructuring
const {l} = {l: (b && obj[b]) ?? c};
```

Hammerhead should not strip the parenthesis wrapping the expression before the `??`.
```js
// Wrong
 const _hh$temp0={l:b&&__get$(obj,b)??c},l=_hh$temp0.l; 
// Right
 const _hh$temp0={l:(b&&__get$(obj,b))??c},l=_hh$temp0.l; 
```

### What is your public website URL? (or attach your complete example)

https://bl.ocks.org/dantman/raw/a2425f88f6c5cb167061c843bd54f373/15bbc992971611b0a9edaf6063ee7372302d1844/

### What is your TestCafe test code?

```js
import { Selector } from 'testcafe';

fixture`?? Test`
  .page`https://bl.ocks.org/dantman/raw/a2425f88f6c5cb167061c843bd54f373/15bbc992971611b0a9edaf6063ee7372302d1844/`;

test('script should complete', async (t) => {
  await t.expect(Selector('span').withText('Script completed').exists).ok();
});
```

### Your complete configuration file

```json
{
  "userVariables": {
    "baseUrl": "http://localhost:3000"
  },
  "src": "./tests/e2e/testcafe/",
  "compilerOptions": {
    "typescript": {
      "customCompilerModulePath": "../typescript",
      "options": {
        "esModuleInterop": true,
        "resolveJsonModule": true
      }
    }
  },
  "clientScripts": [
    { "module": "@testing-library/dom/dist/@testing-library/dom.umd.js" }
  ]
}
```

### Your complete test report

```
The "src" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 102.0.5005.115 / Windows 10

 ?? Test
 × script should complete

   1) undefinedA JavaScript error occurred on
      "https://bl.ocks.org/dantman/raw/a2425f88f6c5cb167061c843bd54f373/15bbc992971611b0a9edaf6063ee7372302d1844/".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors" configuration
      file property to "true".
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      SyntaxError: Unexpected token '??'

      Browser: Chrome 102.0.5005.115 / Windows 10


   2) AssertionError: expected false to be truthy

      Browser: Chrome 102.0.5005.115 / Windows 10

         2 |
         3 |fixture`?? Test`
         4 |  .page`https://bl.ocks.org/dantman/raw/a2425f88f6c5cb167061c843bd54f373/15bbc992971611b0a9edaf6063ee7372302d1844/`;
         5 |
         6 |test('script should complete', async (t) => {
       > 7 |  await t.expect(Selector('span').withText('Script completed').exists).ok();
         8 |});
         9 |

         at <anonymous> (C:\Users\danie\Workspace\Work\Transactive\seymour-portal\tests\e2e\testcafe\auth\Test.ts:7:72)
         at <anonymous> (C:\Users\danie\Workspace\Work\Transactive\seymour-portal\tests\e2e\testcafe\auth\Test.ts:8:71)
         at __awaiter (C:\Users\danie\Workspace\Work\Transactive\seymour-portal\tests\e2e\testcafe\auth\Test.ts:4:12)
         at <anonymous> (C:\Users\danie\Workspace\Work\Transactive\seymour-portal\tests\e2e\testcafe\auth\Test.ts:6:44)



 1/1 failed (4s)

 Warnings (1):
 --
  The "src" option from the configuration file will be ignored.
```

### Steps to Reproduce

1. Make sure that nullish coalescing (??) is not transpilled away (e.g. run Vite in dev mode)
2. Start a statement with destructuring syntax like `const {foo}`
3. Write a ?? statement where the expression before it is parenthesis with an `&&` operator that will break if the parenthesis is removed

### TestCafe version

1.19.0

### Node.js version

v16.15.1

### Command-line arguments

testcafe chrome test.ts

### Other

The example looks a little contrived because I've stripped away anything unrelated. The real world example is:

```ts
const { data, loading } = useApiQuery(
  codeType ? miscApi.getCodes(codeType) : null,
  {
    staleTime: (codeType && CodeDefaultStaleTimes[codeType]) ?? ONE_HOUR,
    refetchOnLocale: true,
  }
);
```

**Comment by VasilyStrelyaev** [comment]
Thank you for reporting this behavior. I have reproduced it on my side. We already have a similar issue: https://github.com/DevExpress/testcafe/issues/6995. Please subscribe to [#6995](https://github.com/DevExpress/testcafe/issues/6995) to keep track of our progress. I will close this issue as a duplicate.
