### ISSUE TITLE
Intermittent htmlTypeError: Cannot destructure property 'config' of 'this.openedBrowsers[browserId]' as it is undefined after finishing test execution.

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#7127]
### What is your Scenario?

I'm getting htmlTypeError: Cannot destructure property 'config' of 'this.openedBrowsers[browserId]' as it is undefined after finishing test execution error when exit code as 1. Don't have exact repro steps but started getting this error intermittently after using latest TestCafe. Any clue?

TestCafe version: 1.19.0
node version: v14.16.0
        
```
Total Tests: 77
  Total Passed: 77
  Total Failed: 0
  Total Skipped: 0

  Total Failed due to Known Test Failures: 0
  Total Failed due to Open Application Bugs: 0
  (Duration: 16m 13s)
  ----------------------------------------------------------------

  The file was saved at  test-reports/bhr-zimbra9x-testcafe/Report_5_7_2022_22_32_59.htmlTypeError: Cannot destructure property 'config' of 'this.openedBrowsers[browserId]' as it is undefined.
    at BrowserProviderPluginHost.hasCustomActionForBrowser (/home/circleci/zm-x-web-zimbra9/tests/testcafe/node_modules/testcafe/src/browser/provider/built-in/dedicated/chrome/index.js:121:17)
    at BrowserProvider.hasCustomActionForBrowser (/home/circleci/zm-x-web-zimbra9/tests/testcafe/node_modules/testcafe/src/browser/provider/index.ts:428:28)
    at TestRun._adjustScreenshotCommand (/home/circleci/zm-x-web-zimbra9/tests/testcafe/node_modules/testcafe/src/test-run/index.ts:1041:84)
    at TestRun._internalExecuteCommand (/home/circleci/zm-x-web-zimbra9/tests/testcafe/node_modules/testcafe/src/test-run/index.ts:1189:24)
    at TestRun._makeScreenshotOnFail (/home/circleci/zm-x-web-zimbra9/tests/testcafe/node_modules/testcafe/src/test-run/index.ts:1278:38)
    at TestRun._executeTestFn (/home/circleci/zm-x-web-zimbra9/tests/testcafe/node_modules/testcafe/src/test-run/index.ts:604:13)
    at TestRun.start (/home/circleci/zm-x-web-zimbra9/tests/testcafe/node_modules/testcafe/src/test-run/index.ts:668:13)

Exited with code exit status 1

CircleCI received exit code 1
```

### What is the Current behavior?

```
The file was saved at  test-reports/bhr-zimbra9x-testcafe/Report_5_7_2022_22_32_59.htmlTypeError: Cannot destructure property 'config' of 'this.openedBrowsers[browserId]' as it is undefined.
    at BrowserProviderPluginHost.hasCustomActionForBrowser (/home/circleci/zm-x-web-zimbra9/tests/testcafe/node_modules/testcafe/src/browser/provider/built-in/dedicated/chrome/index.js:121:17)
```

### What is the Expected behavior?

No error after completing test execution.

### What is your public website URL? (or attach your complete example)

N/A.

### What is your TestCafe test code?

N/A.

### Screenshots

![image](https://user-images.githubusercontent.com/21263826/177385350-1e85ff83-326c-4bff-880f-f284d5ad470b.png)

### Steps to Reproduce

Just execute tests and see if you are getting the error intermittently after finishing the execution.

### TestCafe version

1.19.0

### Node.js version

v14.16.0

### Command-line arguments

node tests/testcafe/utils/testcafe-run.js -T "C2823647|C2823648"

### Browser name(s) and version(s)

Chrome 103

### Platform(s) and version(s)

Linux 18.04.1

**Comment by PavelMor25** [comment]
Hello @karim-penny,

Please create a separate ticket using this [template.](
https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml)
