### ISSUE TITLE
Not possible to start a portable browser

### ISSUE THREAD

**Issue by ognif** [DevExpress/testcafe#7215]
### What is your Scenario?

I simple want to start a portable chromium browser with the way you have written in your documentation and i always get an error.

### What is the Current behavior?

set portable browser according to your documenation:
`const failedCount = await runner.src([testcase]).browsers({path: 'C:\\devel\\heimlich\\infrasctructure\\chrome.exe', cmd: '--new-window'}).run();`
or
_const failedCount = await runner.src([testcase]).browsers({path: 'C:\\devel\\heimlich\\infrasctructure\\chrome.exe'}).run();_
or
`const failedCount = await runner.src([testcase]).browsers('path:C:\\devel\\heimlich\\infrasctructure\\chrome.exe').run();`
```
0|Worker s | 
0|Worker s | Error: The specified browser name is not valid!
0|Worker s |     at BrowserProviderPluginHost.openBrowser (C:\devel\heimlich\clipcafebot\node_modules\testcafe\src\browser\provider\built-in\path.js:52:19)
0|Worker s |     at BrowserProvider.openBrowser (C:\devel\heimlich\clipcafebot\node_modules\testcafe\src\browser\provider\index.ts:322:9)
0|Worker s |     at BrowserConnection._runBrowser (C:\devel\heimlich\clipcafebot\node_modules\testcafe\src\browser\connection\index.ts:212:13)
0|Worker s |     at BrowserConnection._runBrowser (C:\devel\heimlich\clipcafebot\node_modules\testcafe\src\browser\connection\index.ts:221:32) {
0|Worker s |   code: 'E1038',
0|Worker s |   data: [
0|Worker s |     'path:c:/devel/heimlich/infrasctructure/chrome.exe',
0|Worker s |     'Error: The specified browser name is not valid!\n' +
0|Worker s |       '    at BrowserProviderPluginHost.openBrowser (C:\\devel\\heimlich\\clipcafebot\\node_modules\\testcafe\\src\\browser\\provider\\built-in\\path.js:52:19)\n' +
0|Worker s |       '    at BrowserProvider.openBrowser (C:\\devel\\heimlich\\clipcafebot\\node_modules\\testcafe\\src\\browser\\provider\\index.ts:322:9)\n' +
0|Worker s |       '    at BrowserConnection._runBrowser (C:\\devel\\heimlich\\clipcafebot\\node_modules\\testcafe\\src\\browser\\connection\\index.ts:212:13)'
0|Worker s |   ]
0|Worker s | }
```

### What is the Expected behavior?

That tescafe will start the browser  and do not throw an error in case of a invalid browser.

### What is your public website URL? (or attach your complete example)

local

### What is your TestCafe test code?

`const failedCount = await runner.src([testcase]).browsers({path: 'C:\\devel\\heimlich\\infrasctructure\\chrome.exe', cmd: '--new-window'}).run();`
or
`_const failedCount = await runner.src([testcase]).browsers({path: 'C:\\devel\\heimlich\\infrasctructure\\chrome.exe'}).run();_`
or
`const failedCount = await runner.src([testcase]).browsers('path:C:\\devel\\heimlich\\infrasctructure\\chrome.exe').run();`

### Steps to Reproduce

please look at the code

### TestCafe version

1.20

### Node.js version

16.16

### Command-line arguments

none

### Browser name(s) and version(s)

chromium

### Platform(s) and version(s)

Windows 10 64 bit

**Comment by ognif** [comment]
Tested also with .testcaferc.json and 
```
{
    "browsers": "path:C:\\devel\\heimlich\\infrasctructure\\chrome.exe"
}
```
Same error message
