### ISSUE TITLE
"An asynchronous method that you do not await includes an assertion."

### ISSUE THREAD

**Issue by JESii** [DevExpress/testcafe#7390]
### What is your Scenario?

I've written a test to verify that certain text elements exist on a page. It works most of the time, but gives a very strange error message on occasion: `An asynchronous method that you do not await includes an assertion.`
Here's the utility function:
```
export const testPageContent = async (_t, ...pageTextArray) => {
  console.log('=====> pageTextArray:', pageTextArray);
  const bodyElement = await Selector('body');
  const bodyText = await bodyElement.textContent;
  const bodyTextLowerCase = await bodyText.toLowerCase();
  console.log('typeof bodyTextLowerCase', typeof bodyTextLowerCase);
  // await R.map(async pageText => { // => don't use Ramda, in case that's an issue
  await pageTextArray.map(async pageText => {
    const pageTextLowerCase = pageText.toLowerCase();
    console.log('=====> typeof pageTextLowerCase:', typeof pageTextLowerCase);
    await _t
      .expect(await bodyTextLowerCase)
      .contains(
        await pageTextLowerCase,
        colorErrorMsg(`ERROR[testPageContent]: Unable to locate ${pageText} on the page`)
      );
    // })(pageTextArray); // => don't use Ramda, in case that's an issue
  });
};
```
It's pretty gooped up because of all the console logs and awaits everywhere that I've thrown in.

Here's how it's called:
```
  await testPageContent(t, 'Portfolio Overview', 'Estimated as of');
```
I just want to make sure -- in this case -- that the the body of the page includes `Portfolio Overview` `Estimated as of`.

### What is the Current behavior?

The test is failing with the following output:
```
 yarn run v1.22.19
$ testcafe chrome -s takeOnFails=true --hostname localhost --page-load-timeout=20000 --selector-timeout=20000 --assertion-timeout=20000  -r nunit3 src/tests/pages/coverpage.js
TEST: User can log in and land on CoverPage / CoverPage exists
testing on non-local ( dev ) environment
Current clientName is XXXX
=====> pageTextArray: [ 'Portfolio Overview', 'Estimated as of' ]
typeof bodyTextLowerCase string
=====> typeof pageTextLowerCase: string
=====> typeof pageTextLowerCase: string
<?xml version="1.0" encoding="UTF-8" ?>
<test-run id="2" name="TestCafe Tests" start-time="2022-11-19T21:40:08.186Z" end-time="2022-11-19T21:40:25.742Z">
    <test-suite type="Assembly" name="CoverPage Tests" start-time="2022-11-19T21:40:08.188Z" end-time="2022-11-19T21:40:25.740Z">
        <test-case name="User can log in and land on CoverPage / CoverPage exists" fullname="CoverPage Tests - User can log in and land on CoverPage / CoverPage exists" result="Passed" duration="17.544">
            <failure>
                <message>
                    <![CDATA[]]>
                </message>
                <stack-trace>
                    <![CDATA[
An asynchronous method that you do not await includes an assertion. Inspect that method's execution chain and add the 'await' keyword where necessary.

   114 |  await pageTextArray.map(async pageText => {
   115 |    const pageTextLowerCase = pageText.toLowerCase();
   116 |    console.log('=====> typeof pageTextLowerCase:', typeof pageTextLowerCase);
   117 |    await _t
   118 |      .expect(await bodyElement.textContent)
 > 119 |      .contains(
   120 |        await pageTextLowerCase,
   121 |        colorErrorMsg(`ERROR[testPageContent]: Unable to locate ${pageText} on the page`),
   122 |        {allowUnawaitedPromise: true}
   123 |      );
   124 |    // })(pageTextArray);

   at <anonymous> (/Users/XXX/src/tests/utils/utils.js:119:8)
   at asyncGeneratorStep (/Users/XXX/src/tests/utils/utils.js:5:1328)
   at _next (/Users/XXX/src/tests/utils/utils.js:5:1666)]]>
                </stack-trace>
            </failure>
        </test-case>
    </test-suite>
✨  Done in 33.27s.
```
Notice that it claims that the missing await issue is line 119 -- the 'contains' function. 

### What is the Expected behavior?

It should pass. I even added the `{ allowUnawaitedPromise: true }` option but that didn't help.

### What is your public website URL? (or attach your complete example)

Website is public but client does not allow access by folks outside the organization. The app is a data-heavy financial / investment reporting app like so:
![CleanShot 2022-11-18 at 17 21 45@2x](https://user-images.githubusercontent.com/486/202827283-12059dd3-6530-4a8f-a799-6e8725e8309a.png)
I do not have a test case but will see what I can do...

But really... why should I be getting this error about "not awaiting"? Makes no sense to me...

### What is your TestCafe test code?

Test Case
```
/* eslint-disable no-console */
import {Selector} from 'testcafe';

import {loginToSite, getUrl} from '../utils/loginToSite';
import {logClientName, testPageContent, testPageLoaded} from '../utils/utils';
import {explicitErrorHandler} from '../utils/explicitErrorHandler';

fixture`CoverPage Tests`
  .clientScripts({content: `(${explicitErrorHandler.toString()})()`})
  .page(getUrl());

test('User can log in and land on CoverPage / CoverPage exists', async t => {
  console.log('TEST: User can log in and land on CoverPage / CoverPage exists');
  // log in
  await loginToSite(t);
  await logClientName(t);

  // wait for clients to load
  await testPageLoaded(t, 'coverPage');

  // test if current page is coverpage page
  await testPageLoaded(t, 'coverPage');
  await testPageContent(t, 'Portfolio Overview', 'Estimated as of');
});
```

### Your complete configuration file

```
{
  "skipUncaughtErrors": true,
  "takeOnFail": true,
  "clientScripts": [{"module": "@testing-library/dom/dist/@testing-library/dom.umd.js"}]
}

```

### Your complete test report

```
<?xml version="1.0" encoding="UTF-8" ?>
<test-run id="2" name="TestCafe Tests" start-time="2022-11-19T01:16:03.298Z" end-time="2022-11-19T01:16:55.531Z">
    <test-suite type="Assembly" name="CoverPage Tests" start-time="2022-11-19T01:16:03.300Z" end-time="2022-11-19T01:16:55.529Z">
        <test-case name="User can log in and land on CoverPage / CoverPage exists" fullname="CoverPage Tests - User can log in and land on CoverPage / CoverPage exists" result="Passed" duration="13.718">
            <failure>
                <message>
                    <![CDATA[]]>
                </message>
                <stack-trace>
                    <![CDATA[
An asynchronous method that you do not await includes an assertion. Inspect that method's execution chain and add the 'await' keyword where necessary.

   114 |  await pageTextArray.map(async pageText => {
   115 |    const pageTextLowerCase = pageText.toLowerCase();
   116 |    console.log('=====> typeof pageTextLowerCase:', typeof pageTextLowerCase);
   117 |    await _t
   118 |      .expect(await bodyTextLowerCase)
 > 119 |      .contains(
   120 |        await pageTextLowerCase,
   121 |        colorErrorMsg(`ERROR[testPageContent]: Unable to locate ${pageText} on the page`),
   122 |        {allowUnawaitedPromise: true}
   123 |      );
   124 |    // })(pageTextArray);

   at <anonymous> (/Users/XXX/src/tests/utils/utils.js:119:8)
   at asyncGeneratorStep (/Users/XXX/src/tests/utils/utils.js:5:1328)
   at _next (/Users/XXX/src/tests/utils/utils.js:5:1666)]]>
                </stack-trace>
            </failure>
        </test-case>
        <test-case name="CoverPage displays Overview" fullname="CoverPage Tests - CoverPage displays Overview" result="Passed" duration="8.605">
        </test-case>
        <test-case name="CoverPage displays Asset Allocation" fullname="CoverPage Tests - CoverPage displays Asset Allocation" result="Passed" duration="10.011">
        </test-case>
        <test-case name="CoverPage displays Big Picture Benchmarks Graph" fullname="CoverPage Tests - CoverPage displays Big Picture Benchmarks Graph" result="Passed" duration="7.325">
        </test-case>
        <test-case name="CoverPage displays when switching clients" fullname="CoverPage Tests - CoverPage displays when switching clients" result="Passed" duration="12.553">
        </test-case>
    </test-suite>
✨  Done in 68.41s.
```

### Steps to Reproduce

1.
2.
3.

### TestCafe version

2.0.0

### Node.js version

v14.15.4

### Command-line arguments

testcafe chrome -s takeOnFails=true --hostname localhost --page-load-timeout=20000 --selector-timeout=20000 --assertion-timeout=20000  -r nunit3 src/tests/pages/coverpage.js

### Browser name(s) and version(s)

Chrome Version 107.0.5304.110 (Official Build) (x86_64)

### Platform(s) and version(s)

MacOS 11.6.8

### Other

I'm hoping there's something obvious about the test that will point to a solution.
At this point, my basic question is: what is left to be awaited?
Thanks for a great QA test framework -- I have some great tests working...jon

**Comment by Aleksey28** [comment]
Hi @JESii,

[`Array.prototype.map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) in your case returns an array of promises. You cannot just `await` this array. You need to use [`Promise.all()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all).
