### ISSUE TITLE
Selector becomes invalid without any reason

### ISSUE THREAD

**Issue by ognif** [DevExpress/testcafe#7550]
### What is your Scenario?

I use a function to check if a selector exists. When exists I put the Selector to a variable. 

`````
            let anfrageButtonExists = await Selector(".col-lg-4").nth(k).find(".btn.btn-primary.btn-xs.requestlink").withText("Anfrage stellen").exists;
            if(anfrageButtonExists){
                var anfrageButton = null;
                anfrageButton = Selector(".col-lg-4").nth(k).find(".btn.btn-primary.btn-xs.requestlink").withText("Anfrage stellen");
                console.log("Anfragebutton");
                console.log(anfrageButton);
                if(anfrageButton === null){
                  console.log("Button ist NULL");
                }else{
                  await t.hover(anfrageButton);
                  if(await anfrageButton.hasAttribute("disabled")){   
                      console.log("Button disabled");                     
                      continue;
                  }
                  await t.click(anfrageButton);
                  kartenCount++;
                  console.log(kartenCount);
                }

                 
            }else{
                console.log("Button nicht da");
                continue;
            }
`````

### What is the Current behavior?

After this I process a hover get Attributes and click. 200 times it success and inside the code the Selector is not valid anymore.

At this line, testcafe reports the selector do not exist
`await t.hover(anfrageButton);`

The result from "anfrageButton" is:
````
[Function: __$$clientFunction$$] {
  with: [Function (anonymous)],
  nth: [Function (anonymous)],
  withText: [Function (anonymous)],
  withExactText: [Function (anonymous)],
  withAttribute: [Function (anonymous)],
  filter: [Function (anonymous)],
  filterVisible: [Function (anonymous)],
  filterHidden: [Function (anonymous)],
  find: [Function (anonymous)],
  parent: [Function (anonymous)],
  child: [Function (anonymous)],
  sibling: [Function (anonymous)],
  nextSibling: [Function (anonymous)],
  prevSibling: [Function (anonymous)],
  shadowRoot: [Function (anonymous)],
  getStyleProperty: [Function (anonymous)],
  getAttribute: [Function (anonymous)],
  hasAttribute: [Function (anonymous)],
  getBoundingClientRectProperty: [Function (anonymous)],
  hasClass: [Function (anonymous)],
  addCustomDOMProperties: [Function (anonymous)],
  addCustomMethods: [Function (anonymous)],
  [Symbol(functionBuilder)]: SelectorBuilder {
    callsiteNames: { instantiation: 'Selector', execution: '__$$clientFunction$$' },
    fn: [Function: selectorFn],
    options: {
      dependencies: [Object],
      customDOMProperties: undefined,
      customMethods: undefined,
      boundTestRun: undefined,
      timeout: undefined,
      visibilityCheck: undefined,
      apiFnChain: [Array],
      apiFn: ".withText('Anfrage stellen')",
      apiFnID: 3
    },
    compiledFnCode: '(function(){\n' +
      "                  var __f$=(function(){var selector=__dependencies$['selector'];var filter=__dependencies$['filter'];var filterNodes=__dependencies$['filterNodes'];var textRe=__dependencies$['textRe']; var func = function func() {\n" +
      '/* eslint-disable no-undef */\n' +
      'var nodes = selector();\n' +
      'if (!nodes.length)\n' +
      'return null;\n' +
      'return filterNodes(nodes, filter, document, void 0, textRe);\n' +
      '/* eslint-enable no-undef */\n' +
      '}; return func;})();;\n' +
      '                  return function(){\n' +
      '                      var args           = __dependencies$.boundArgs || arguments;\n' +
      '                      var selectorFilter = __dependencies$.selectorFilter;\n' +
      '\n' +
      '                      var nodes = __f$.apply(this, args);\n' +
      '                      nodes     = selectorFilter.cast(nodes);\n' +
      '\n' +
      '                      if (!nodes.length && !selectorFilter.error)\n' +
      '                          selectorFilter.error = __dependencies$.apiInfo.apiFnID;\n' +
      '\n' +
      '                      return selectorFilter.filter(nodes, __dependencies$.filterOptions, __dependencies$.apiInfo);\n' +
      '                  };\n' +
      '               })();',
    replicator: {
      transforms: [Array],
      transformsMap: [Object: null prototype],
      serializer: [Object]
    },
    callsite: undefined
  }
}
````

The error is:
````
× Test: CAN 1 (screenshots: C:\home\ingof\heimlich_server\laBot\screenshots\2023-03-03_12-58-59\test-1\Chrome_109.0.0.0_Windows_10\errors\1.png)

   1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

         | Selector('.col-lg-4')
         |   .nth(2)
       > |   .find('.btn.btn-primary.btn-xs.requestlink')
         |   .withText('Anfrage stellen')

      Browser: Chrome 109.0.0.0 / Windows 10
      Screenshot: C:\home\ingof\heimlich_server\laBot\screenshots\2023-03-03_12-58-59\test-1\Chrome_109.0.0.0_Windows_10\errors\1.png

          93 |                console.log(anfrageButton);
          94 |                if(anfrageButton === null){
          95 |                  console.log("Button ist NULL");
          96 |                }else{
          97 |                  //await t.hover(anfrageButton);
       >  98 |                  if(await anfrageButton.hasAttribute("disabled")){
          99 |                      console.log("Button disabled");
         100 |                      continue;
         101 |                  }
         102 |                  await t.click(anfrageButton);
         103 |                  kartenCount++;

         at <anonymous> (C:\devel\heimlich\laBot\tests\heimlichanfrage.js:98:42)
         at asyncGeneratorStep (C:\devel\heimlich\laBot\tests\heimlichanfrage.js:3:262)
         at _next (C:\devel\heimlich\laBot\tests\heimlichanfrage.js:3:600)



 1/1 failed (38m 47s)
Heimlich 8091 - No Success. Fails: 1
````

### What is the Expected behavior?

That the Selector will not get invalid.

I tried on Windows VSCode Project and as self running Node Server on Linux Ubuntu Server. Same behavior.

The Screenshot I did from the error looks well, no error.

### What is your public website URL? (or attach your complete example)

No, it is a lokal project. There is an instance available in the Internet. But just to execute, not to see.

### What is your TestCafe test code?

So in first point.

### Your complete configuration file

Default

### Steps to Reproduce

1.
2.
3.

### TestCafe version

2.3.1

### Node.js version

16.17

### Command-line arguments

No Commandline, runner from code

### Browser name(s) and version(s)

Chrome current version

### Platform(s) and version(s)

Windows 10 and also Ubuntu 22.04 Server

**Comment by Aleksey28** [comment]
Hi @ognif,

It isn't easy to reproduce your usage scenario based only on your description. Please follow this guide to create a simple example: [https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue).
