### ISSUE TITLE
View all assertion failures with quarantine mode

### ISSUE THREAD

**Issue by codambro** [DevExpress/testcafe#7636]
### What is your Scenario?

To help reduce false negatives, we use the TestCafe Quarantine Mode to attempt to rerun tests. However, sometimes the test failure on a rerun is for a different reason than the initial failure. Right now, TestCafe only shows the assertion failure for the last attempt.

### What are you suggesting?

It would be helpful to see the assertion failure for all quarantine mode attempts and not just the last one. As this is critical information for debugging the test flakiness.

### Additional context

Sample test:
```
fixture("Fixture");

let count = 1;

test("Test", async t => {
    console.log("Running Test " + count);
    count = count + 1;
    await t.expect(count).eql(0);
});
```

And output:
```
 Fixture
Running Test 1
Running Test 2
Running Test 3
 ✖ Test (screenshots: /Users/codambro/Documents/GitHub/KennaSecurity/qa-automation-ui/results/screenshots/Chrome_111.0.0.0_macOS_10.15.7/Fixture_Test.png)

   1) AssertionError: expected 4 to deeply equal 0
      
      + expected - actual
      
      -4
      +0
      

      Browser: Chrome 111.0.0.0 / macOS 10.15.7
      Screenshot: /Users/codambro/Documents/GitHub/KennaSecurity/qa-automation-ui/results/screenshots/Chrome_111.0.0.0_macOS_10.15.7/Fixture_Test.png

         3 |let count = 1;
         4 |
         5 |test("Test", async t => {
         6 |    console.log("Running Test " + count);
         7 |    count = count + 1;
       > 8 |    await t.expect(count).eql(0);
         9 |});

         at Object.<anonymous> (/Users/codambro/Documents/GitHub/KennaSecurity/qa-automation-ui/tests/quarantineTest.ts:8:27)
         at <anonymous> (/Users/codambro/Documents/GitHub/KennaSecurity/qa-automation-ui/tests/quarantineTest.ts:7:71)
         at __awaiter (/Users/codambro/Documents/GitHub/KennaSecurity/qa-automation-ui/tests/quarantineTest.ts:3:12)
         at <anonymous> (/Users/codambro/Documents/GitHub/KennaSecurity/qa-automation-ui/tests/quarantineTest.ts:5:24)



 1/1 failed (12s)
```

Config:
```
  "quarantineMode": {
    "successThreshold": 1,
    "attemptLimit": 3
  },
```

I'm requesting to see the assertion trace error for all 3 test runs and not just the final one.

**Comment by aleks-pro** [comment]
Hello @codambro ,

Thank you for the feedback. The suggestion makes sense. We will take it into account.

**Comment by miherlosev** [comment]
Closed in favor https://github.com/DevExpress/testcafe/issues/4001
