### ISSUE TITLE
Can't run tests with nativeAutomation set to true.

### ISSUE THREAD

**Issue by Flauxt** [DevExpress/testcafe#7646]
### What is your Scenario?

I want to run a test with nativeAutomation set to true.

### What is the Current behavior?

When I run a test with nativeAutomation set to true i get the following error:

TypeError: client.Fetch.continueResponse is not a function
    at formatter (C:\CCShare\ATLAS\ATLAS\Testcafe\ROAD\Tests\node_modules\testcafe\src\native-automation\request-pipeline\safe-api.ts:39:28)
    at connectionResetGuard (C:\CCShare\ATLAS\ATLAS\Testcafe\ROAD\Tests\node_modules\testcafe\src\native-automation\request-pipeline\safe-api.ts:19:15)
    at safeContinueResponse (C:\CCShare\ATLAS\ATLAS\Testcafe\ROAD\Tests\node_modules\testcafe\src\native-automation\request-pipeline\safe-api.ts:34:11)
    at handler (C:\CCShare\ATLAS\ATLAS\Testcafe\ROAD\Tests\node_modules\testcafe\src\native-automation\request-pipeline\special-handlers.ts:51:39)
    at Chrome.<anonymous> (C:\CCShare\ATLAS\ATLAS\Testcafe\ROAD\Tests\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:352:23)
    at Chrome.emit (node:events:526:28)
    at Chrome.emit (node:domain:475:12)
    at Chrome._handleMessage (C:\CCShare\ATLAS\ATLAS\Testcafe\ROAD\Tests\node_modules\chrome-remote-interface\lib\chrome.js:287:18)
    at WebSocket.<anonymous> (C:\CCShare\ATLAS\ATLAS\Testcafe\ROAD\Tests\node_modules\chrome-remote-interface\lib\chrome.js:240:22)
    at WebSocket.emit (node:events:526:28)

The test starts fine without the nativeAutomation. The reason I want it is because I believe it might solve another issue I'm having when running the test.
I started with TestCafe version 2.5.0 and also tried the 2.5.1-rc.1 version. Same results

### What is the Expected behavior?

I expect the test to run as normal

### What is your public website URL? (or attach your complete example)

I am not allowed to share the URL.

### What is your TestCafe test code?

    await t
        .typeText("input.form-control", "8802178668", { replace: true, paste: true })
        .click("button#radgivning")
        .typeText("textarea.form-control.other-notes", "Something", {
            replace: true,
            paste: true,
        })
        .click("button.btn.btn-primary");
});

### Your complete configuration file

{
    "browsers": ["chrome"],
    "src": [
      "./ROAD.js"
    ],
     "concurrency": 1,
    "quarantineMode": false,
    "debugMode": false,
    "debugOnFail": false,
    "stopOnFirstFail": false,
    "selectorTimeout": 7000,
    "assertionTimeout": 1000,
    "pageLoadTimeout": 1000,
    "speed": 1,
    "disablePageCaching": false,
    "developmentMode": false,
    "skipJsErrors": true,
    "nativeAutomation": true
  }

### Steps to Reproduce

Just run a test with nativeAutomation set to true i guess.

### TestCafe version

2.5.1-rc.1

### Node.js version

16.14.2

### Command-line arguments

npx testcafe

### Browser name(s) and version(s)

chrome

### Platform(s) and version(s)

Windows 10

**Comment by AlexKamaev** [comment]
Thank you for reaching out to us. We would like to help you diagnose the cause of the issue. However, we need a simple sample that we can easily run on our side in order to replicate the issue. I know that you mentioned you couldn't share your project, but perhaps you can send it privately to support@devexpress.com.
