### ISSUE TITLE
Unhandled promise rejection in NativeAutomationRequestHookEventProvider.onResponse with slow async RequestMock.response

### ISSUE THREAD

**Issue by fredrikkarlsson-pervanovo** [DevExpress/testcafe#7683]
### What is your Scenario?

I modify the response of some endpoints with RequestMock by doing the same call with axios, modifying the data and then setting the response body.
It works without errors when running without nativeAutomation.

### What is the Current behavior?

I get the following error in the tests following the test with the slow mocked response:
```
      TypeError: Cannot read properties of undefined (reading 'update')
      at NativeAutomationRequestHookEventProvider.onResponse (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-hooks\event-provider.ts:56:63)
      at NativeAutomationRequestPipeline._handleOtherRequests (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:317:53)
      at Chrome.<anonymous> (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:376:17)
```

### What is the Expected behavior?

No errors, like without native automation

### What is your public website URL? (or attach your complete example)

See next section

### What is your TestCafe test code?

import { fixture, RequestMock, Selector } from "testcafe";

export function wait(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

fixture`EventFactory bug`;

const testMethod = async (t: TestController) => {
  await t.addRequestHooks(
    RequestMock()
      .onRequestTo(new RegExp("getting-started"))
      .respond(async (req, res) => {
        await wait(5_000); //simulate fetching the data with fetch or axios
        res.setBody(JSON.stringify({}));
      })
  );
  await t.navigateTo("https://testcafe.io/");
  await t.expect(Selector("*").withText(/Deploy without fear/i).visible).ok();
};
test("Test", testMethod);
test("Test 2", testMethod);
test("Test 3", testMethod);
test("Test 4", testMethod);

### Your complete configuration file

{
  "browsers": "chrome",
  "nativeAutomation": true,
  "compilerOptions": {
    "typescript": {
      "configPath": "testcafe/testcafe.tsconfig.json"
    }
  },
  "selectorTimeout": 20000,
  "assertionTimeout": 15000,
  "pageLoadTimeout": 10000,
  "src": [
    "testcafe/tests/*.test.ts"
  ],
  "reporter": [
    {
      "name": "list"
    }
  ]
}

### Your complete test report

Testing started at 12:12 ...
"C:\Program Files\nodejs\node.exe" --inspect-brk=52416 node_modules/testcafe/lib/cli/index.js chrome C:/Users/flomm/Documents/Pervanovo/bjelin-web/testcafe/tests/Bug.test.ts -r spec,json:node_modules/testcafe/tmp/testcafe-out-90d8f126-6517-43ab-9f5c-4eb10740e4dc --color
Testing started at 12:12 ...
Debugger listening on ws://127.0.0.1:52416/ed79d1fe-bfc7-42fd-8d1c-fd1818ffa8f4
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
The "src", "browsers", and "reporter" options from the configuration file will be ignored.
 Running tests in:
 - Chrome 112.0.0.0 / Windows 11

 EventFactory bug
 √ Test
 × Test 2

   1) Unhandled promise rejection:
      
      TypeError: Cannot read properties of undefined (reading 'update')
      at NativeAutomationRequestHookEventProvider.onResponse (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-hooks\event-provider.ts:56:63)
      at NativeAutomationRequestPipeline._handleOtherRequests (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:317:53)
      at Chrome.<anonymous> (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:376:17)

      Browser: Chrome 112.0.0.0 / Windows 11

 × Test 3

   1) Unhandled promise rejection:
      
      TypeError: Cannot read properties of undefined (reading 'update')
      at NativeAutomationRequestHookEventProvider.onResponse (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-hooks\event-provider.ts:56:63)
      at NativeAutomationRequestPipeline._handleOtherRequests (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:317:53)
      at Chrome.<anonymous> (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:376:17)

      Browser: Chrome 112.0.0.0 / Windows 11

 × Test 4

   1) Unhandled promise rejection:
      
      TypeError: Cannot read properties of undefined (reading 'update')
      at NativeAutomationRequestHookEventProvider.onResponse (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-hooks\event-provider.ts:56:63)
      at NativeAutomationRequestPipeline._handleOtherRequests (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:317:53)
      at Chrome.<anonymous> (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:376:17)

      Browser: Chrome 112.0.0.0 / Windows 11

 3/4 failed (14s)

 Warnings (1):
 --
  The "src", "browsers", and "reporter" options from the configuration file will be ignored.
Waiting for the debugger to disconnect...

Process finished with exit code 3

Unhandled promise rejection:

TypeError: Cannot read properties of undefined (reading 'update')
at NativeAutomationRequestHookEventProvider.onResponse (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-hooks\event-provider.ts:56:63)
at NativeAutomationRequestPipeline._handleOtherRequests (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:317:53)
at Chrome.<anonymous> (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:376:17)

Browser: Chrome 112.0.0.0 / Windows 11

Unhandled promise rejection:

TypeError: Cannot read properties of undefined (reading 'update')
at NativeAutomationRequestHookEventProvider.onResponse (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-hooks\event-provider.ts:56:63)
at NativeAutomationRequestPipeline._handleOtherRequests (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:317:53)
at Chrome.<anonymous> (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:376:17)

Browser: Chrome 112.0.0.0 / Windows 11

Unhandled promise rejection:

TypeError: Cannot read properties of undefined (reading 'update')
at NativeAutomationRequestHookEventProvider.onResponse (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-hooks\event-provider.ts:56:63)
at NativeAutomationRequestPipeline._handleOtherRequests (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:317:53)
at Chrome.<anonymous> (C:\Users\flomm\Documents\Pervanovo\bjelin-web\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:376:17)

Browser: Chrome 112.0.0.0 / Windows 11

### Steps to Reproduce

1. Run the provided example

### TestCafe version

2.6.0-rc.1

### Node.js version

v16.19.0

### Command-line arguments

testcafe testcafe/tests/Bug.test.ts

### Browser name(s) and version(s)

Chrome 112.0.0.0

### Platform(s) and version(s)

Windows 11

**Comment by AlexKamaev** [comment]
Thank you for sharing your test code. I managed to reproduce the issue.

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe/pull/7692.
