### ISSUE TITLE
Multipart form data with blob/file request body should be logged with native automation enabled

### ISSUE THREAD

**Issue by fredrikkarlsson-pervanovo** [DevExpress/testcafe#7747]
### What is your Scenario?

Be able to log request body when sending multipart form data containing blob/files with native automation enabled

### What is the Current behavior?

The body in the logged request is an empty string when native automation is enabled

### What is the Expected behavior?

The body in the logged request contains the multipart form data, ie. NOT an empty string

### What is your public website URL? (or attach your complete example)

-

### What is your TestCafe test code?

```typescript
import { fixture, RequestLogger, RequestMock, Selector } from "testcafe";

fixture`Bug`;
test("Multipart form data with blob request body should be logged", async t => {
  const page = `
<!DOCTYPE html>
<html lang="en">
<head>
<script>
function doSubmit() {
  var formData = new FormData();
  var blob = new Blob([JSON.stringify({ hello: "world" }, null, 2)], {
    type: "application/json",
  });
  formData.set("blob", blob);
  fetch("/action", {
    body: formData,
    headers: {
        "Content-Type": "multipart/form-data",
    },
    method: "post",
  });
}
</script>
</head>
<body>
<button onclick="doSubmit()">Submit</button>
</body>
</html>`;
  const logger = RequestLogger(/action/, {
    logRequestBody: true,
    stringifyRequestBody: true
  });
  const mock = RequestMock()
    .onRequestTo(/page.html/)
    .respond(page, 200)
    .onRequestTo(/action/)
    .respond("", 200);
  await t.addRequestHooks(mock, logger);
  await t.navigateTo("https://www.testcafe.io/page.html");
  await t.click("button");
  await t
    .expect(logger.count(record => record.request.method === "post"))
    .eql(1);
  const loggedRequest = logger.requests[0].request;
  const payload = loggedRequest.body;
  await t.expect(payload.length > 0).ok();
});
```

### Your complete configuration file

{
  "browsers": "chrome",
  "nativeAutomation": true
}

### Your complete test report

```
The "src" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 113.0.0.0 / Windows 11

 × Bug - Multiform data with blob request body should be logged

   1) AssertionError: expected false to be truthy

      Browser: Chrome 113.0.0.0 / Windows 11

         42 |  await t
         43 |    .expect(logger.count(record => record.request.method === "post"))
         44 |    .eql(1);
         45 |  const loggedRequest = logger.requests[0].request;
         46 |  const payload = loggedRequest.body;
       > 47 |  await t.expect(payload.length > 0).ok();
         48 |});
         49 |

         at <anonymous> (C:\Users\flomm\Documents\Pervanovo\bjelin-web\testcafe\tests\Bug2.test.ts:47:38)
         at fulfilled (C:\Users\flomm\Documents\Pervanovo\bjelin-web\testcafe\tests\Bug2.test.ts:5:58)



 1/1 failed (1s)

 Warnings (1):
 --
  The "src" option from the configuration file will be ignored.
```

### Steps to Reproduce

Run the provided test script

### TestCafe version

2.6.2-rc.1

### Node.js version

v16.19.0

### Command-line arguments

testcafe Bug.test.ts

### Browser name(s) and version(s)

Chrome 113.0.5672.127

### Platform(s) and version(s)

Windows 11

**Comment by Aleksey28** [comment]
Hi @fredrikkarlsson-pervanovo,

I managed to reproduce the issue. We will update this thread once we have news.

**Comment by miherlosev** [comment]
Hi @fredrikkarlsson-pervanovo,

It's a Chrome bug - https://bugs.chromium.org/p/chromium/issues/detail?id=1371396. We are waiting for its resolution.

**Comment by miherlosev** [comment]
I will close this issue since it's a Chrome bug. Please track the bug in the `Chromium` repository and feel free to reopen this issue if the fix won't help you.

**Comment by fredrikkarlsson-pervanovo** [comment]
Is it really the same bug? The link you provided only tells that the files are omitted from the payload, whilst in my case all other fields are also gone.

Updated testcode:
```
import { fixture, RequestLogger, RequestMock } from "testcafe";

fixture`Bug`;
test("Multiform data with blob request body should be logged", async t => {
  const page = `
<!DOCTYPE html>
<html lang="en">
<head>
<script>
function doSubmit() {
  var formData = new FormData();
  var blob = new Blob([JSON.stringify({ hello: "world" }, null, 2)], {
    type: "application/json",
  });
  formData.set("blob", blob);
  formData.set("myField", "A string value");
  fetch("/action", {
    body: formData,
    headers: {
        "Content-Type": "multipart/form-data",
    },
    method: "post",
  });
}
</script>
</head>
<body>
<button onclick="doSubmit()">Submit</button>
</body>
</html>`;
  const logger = RequestLogger(/action/, {
    logRequestBody: true,
    stringifyRequestBody: true
  });
  const mock = RequestMock()
    .onRequestTo(/page.html/)
    .respond(page, 200)
    .onRequestTo(/action/)
    .respond("", 200);
  await t.addRequestHooks(mock, logger);
  await t.navigateTo("https://www.testcafe.io/page.html");
  await t.click("button");
  await t
    .expect(logger.count(record => record.request.method === "post"))
    .eql(1);
  const loggedRequest = logger.requests[0].request;
  const payload = loggedRequest.body;
  await t.expect(payload.length > 0).ok();
});

```

**Comment by miherlosev** [comment]
> Is it really the same bug? The link you provided only tells that the files are omitted from the payload

Yes. We use the [DevTools protocol](%5Bhttps://chromedevtools.github.io/devtools-protocol/%5D(https://chromedevtools.github.io/devtools-protocol/)) protocol to communicate with Google Chrome and retrieve data from the request. For this usage scenario, [Request.postData, Request.postDataEntries](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Request) are empty. This is why, `RequestLogger `doesn't contain the necessary entries.
