### ISSUE TITLE
Getting error while executing test on Vs Code by using Testcafe 

### ISSUE THREAD

**Issue by ekatagrupdev** [DevExpress/testcafe#7795]
### What is your Scenario?

Running test on chrome browser 

### What is the Current behavior?

 Failed to find a DNS-record for the resource at "http://localhost:4250/".

### What is the Expected behavior?

After running test, TestCafe should be open up and  perform the given test Like login page

### What is your public website URL? (or attach your complete example)

http://localhost:4250/

### What is your TestCafe test code?

fixture`Assign/Validation of Assign Dialog`
  .page(config.baseUrl)
  .beforeEach(async t => {
    await t.maximizeWindow();
  })
  .afterEach(async t => {
    await assignToDialog.cancelButton.click();
    await header.logoutWithExpectCopyRight();
  });

test
  .meta('author', 'Volodymyr')
  .meta('id', 'XRAY-1603')
  .meta('priority', '5- High')
  (`[XRAY-1603] Verify that Assign dialog gets displayed by clicking on Assign button`, async t => {
    // #region Arrange
    await login.login('Axe', '');
    await t.click(leftSidebar.libraryBrowserButton);
    await leftSidebar.libraryBrowser.clickNodeByColumnValue(0, 'Unchecked');

    await resultsGrid.getRow(['Filename', 'Assign_UI-Doc1.txt']).click();
    await resultsGrid.getRow(['Filename', 'Assign_UI-Doc1.txt']).getCell('Owner').verify.value('');
    // #endregion

    // #region Act
    await appToolbar.homeTab.assign.click();
    // #endregion

    // #region Assert
    await assignToDialog.verify.visibility(true);
    // #endregion
  });

### Your complete configuration file

Using locally installed version of TestCafe.
2.6.2

npm 9.7.1

### Your complete test report

Running tests in:
 - Chrome 114.0.0.0 / Windows 10

 × Assign/Validation of Assign Dialog - [XRAY-1603] Verify the default value in Assign To dropdown in Assign Dialog (screenshots:
 C:\Git\Testing\TestCafe\report\screenshots\2023-06-13_21-51-11\test-1\Chrome_114.0.0.0_Windows_10\errors\1.png)

   1) - Error in fixture.beforeEach hook -
      Failed to load the page at "http://localhost:4250/".
      Increase the value of the "pageRequestTimeout" variable, enable the "retryTestPages" option, or use quarantine mode to perform       
      additional attempts to execute this test.
      You can find troubleshooting information for this issue at "https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".

      Error details:
      Failed to find a DNS-record for the resource at "http://localhost:4250/".

      Browser: Chrome 114.0.0.0 / Windows 10
      Screenshot: C:\Git\Testing\TestCafe\report\screenshots\2023-06-13_21-51-11\test-1\Chrome_114.0.0.0_Windows_10\errors\1.png

          9 |import login from '../../../page-model/login';
         10 |
         11 |fixture`Assign/Validation of Assign Dialog`
         12 |  .page(config.baseUrl)
         13 |  .beforeEach(async t => {
       > 14 |    await t.maximizeWindow();
         15 |  })
         16 |  .afterEach(async t => {
         17 |    await assignToDialog.cancelButton.click();
         18 |    await header.logoutWithExpectCopyRight();
         19 |  });

         at <anonymous> (C:\Git\Testing\TestCafe\Scripts\tests\qa\assign\assign-to-dialog.test.ts:14:13)
         at <anonymous> (C:\Git\Testing\TestCafe\Scripts\tests\qa\assign\assign-to-dialog.test.ts:8:71)
         at __awaiter (C:\Git\Testing\TestCafe\Scripts\tests\qa\assign\assign-to-dialog.test.ts:4:12)
         at <anonymous> (C:\Git\Testing\TestCafe\Scripts\tests\qa\assign\assign-to-dialog.test.ts:13:25)

 1/1 failed (2s)

 Warnings (1):
 --
  The "src" option from the configuration file will be ignored.

### Steps to Reproduce

1.
2.
3.

### TestCafe version

2.6.2

### Node.js version

v18.16.0

### Command-line arguments

testcafe

### Browser name(s) and version(s)

Chrome

### Platform(s) and version(s)

Windows

**Comment by Aleksey28** [comment]
Hi @Klaster1,

As much as I'd like to help you, unfortunately, there's not much I can do with the current information. You shared only a test - for proper research, I need a reproducible example that I can run without additional effort. Please share the app you are testing.
