### ISSUE TITLE
"write EPIPE" in console after cancelling mid-run

### ISSUE THREAD

**Issue by Klaster1** [DevExpress/testcafe#7799]
### What is your Scenario?

I want to cancel a test run that includes dozens of tests, high concurrency and video recording on failure enabled. If you wait until the suite finishes, there are no errors. NA does not affect the behavior.

### What is the Current behavior?

When cancelling, I get a ton of these errors in console:
```
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.Writable.write (node:internal/streams/writable:337:10)
    at VideoRecorder._addFrame (C:\dev\gmc\modules\frontend\node_modules\testcafe\src\video-recorder\process.js:109:58)
    at VideoRecorder._capture (C:\dev\gmc\modules\frontend\node_modules\testcafe\src\video-recorder\process.js:122:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4047,
  code: 'EPIPE',
  syscall: 'write'
}
```

### What is the Expected behavior?

The run is canceled without errors.

### Your complete configuration file

```
module.exports = {
  src: './e2e/fixtures/',
  screenshots: {
    path: './e2e/screenshots',
    takeOnFails: true,
  },
  selectorTimeout: 5000,
  assertionTimeout: 5000,
  pageLoadTimeout: 5000,
};
```

### Steps to Reproduce

1. Have a large test suite, with dozens of tests.
2. Run the suite with high concurrency and video recording.
3. Cancel mid-run with ctrl+c.

### TestCafe version

3.0.0-rc.1

### Node.js version

18.15.0

### Command-line arguments

npx testcafe chrome:headless .\e2e\fixtures\running-queries-monitoring.ts -c 10 --video e2e\screenshots\videos --video-options failedOnly=true

### Browser name(s) and version(s)

Chrome 114

### Platform(s) and version(s)

Windows 11

**Comment by Klaster1** [comment]
[testcafe-7799.zip](https://github.com/DevExpress/testcafe/files/11755044/testcafe-7799.zip)
Figured it out, it was a global uncaught error listener I have in my tests. The same happens in 2.6.2 with NA off.
```
process.addListener("uncaughtException", (e) => {
	console.warn(e);
});
```
I guess you can close the issue as a false alarm. Or catch the events in question so they don't bubble up to the user code.
