### ISSUE TITLE
WIndow Resize in IE11 is failing

### ISSUE THREAD

**Issue by EthanHastings20** [DevExpress/testcafe#7851]
### What is your Scenario?

'resize the browser window' and 'Maximize the browser window'

### What is the Current behavior?

The test is failing as undefined because of the methods resizewindow() and maximizewindow() are undifined methods

### What is the Expected behavior?

tests will resize window and pass

### What is your public website URL? (or attach your complete example)

https://devexpress.github.io/testcafe/example/

### What is your TestCafe test code?

import Page from './page-model';

fixture `A set of examples that illustrate how to use TestCafe API`
    .page `https://devexpress.github.io/testcafe/example/`;

// Page model
const page = new Page();

// Tests
test('Text typing basics', async t => {
    await t
        .typeText(page.nameInput, 'Peter') // Type name
        .typeText(page.nameInput, 'Paker', { replace: true }) // Replace with last name
        .typeText(page.nameInput, 'r', { caretPos: 2 }) // Correct last name
        .expect(page.nameInput.value).eql('Parker'); // Check result
});

test('Maximize the browser window', async t => {
  await t.maximizeWindow();
});

test('resize the browser window', async t => {
  await t.resizeWindow(640, 1080);
});

### Your complete configuration file

{
    "Internet Explorer@11.0:Windows 10": {
        "build": "TestCafe Demo",
        "network": true,
        "visual": true,
        "resolution": "1024x768"
    }

### Your complete test report

1) Unhandled promise rejection:

      Error: [maximize({"error":"unknown command","message":"Command not found: GET /session/4fc2d5ed-219b-4ff7-a90e-9fd7c68b5c03/window_handles","stacktrace":""})] Error response status: 1
      at exports.newError (/__w/ronin-e2e-test/ronin-e2e-test/node_modules/wd/lib/utils.js:152:13)
      at /__w/ronin-e2e-test/ronin-e2e-test/node_modules/wd/lib/callbacks.js:36:19
      at /__w/ronin-e2e-test/ronin-e2e-test/node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (/__w/ronin-e2e-test/ronin-e2e-test/node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (/__w/ronin-e2e-test/ronin-e2e-test/node_modules/request/request.js:185:22)
      at Request.emit (node:events:520:28)
      at Request.emit (node:domain:475:12)
      at Request.<anonymous> (/__w/ronin-e2e-test/ronin-e2e-test/node_modules/request/request.js:1161:10)
      at Request.emit (node:events:520:28)
      at Request.emit (node:domain:475:12)
      at IncomingMessage.<anonymous> (/__w/ronin-e2e-test/ronin-e2e-test/node_modules/request/request.js:1083:12)
      at Object.onceWrapper (node:events:639:28)
      at IncomingMessage.emit (node:events:532:35)
      at IncomingMessage.emit (node:domain:475:12)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

      Browser: Internet Explorer 11.0 / Windows 10 ( https://automation.lambdatest.com/logs/?sessionID=db7e0641-9a9c-4797-b5db-41fb3048f60b )

### Steps to Reproduce

1. log into LT
2. run tests through LT
3.

### TestCafe version

2.6.1

### Node.js version

18.16.0

### Command-line arguments

testcafe "lambdatest:Internet Explorer@11.0:Windows 10" "test.js"    

### Browser name(s) and version(s)

IE 11

### Platform(s) and version(s)

Windows

**Comment by aleks-pro** [comment]
Hello @EthanHastings20 ,

Please try to reproduce this issue with testcafe of version 2.6.2 We made some fixes in this version for IE11.

NOTE: Since version 3.0.0, we removed support for IE11. You can find more information here: https://testcafe.io/404438/release-notes/framework/2023-6-21-introducing-testcafe-v-3-0-0#removed-internet-explorer-support

**Comment by EthanHastings20** [comment]
I have updated to 2.6.2 and I am still reciving the same error. 

 ✖ resize the browser window

   1) Unhandled promise rejection:
      
      Error: [windowSize({"error":"unknown command","message":"Command not found: GET /session/40546c74-0433-4903-a2ce-d420cd59cb3d/window_handles","stacktrace":""},640,1080)] Error response status: 1
      at exports.newError (/Users/ethanhastings/testcafe-sample/node_modules/wd/lib/utils.js:152:13)
      at /Users/ethanhastings/testcafe-sample/node_modules/wd/lib/callbacks.js:36:19
      at /Users/ethanhastings/testcafe-sample/node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (/Users/ethanhastings/testcafe-sample/node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (/Users/ethanhastings/testcafe-sample/node_modules/wd/node_modules/request/request.js:185:22)
      at Request.emit (node:events:513:28)
      at Request.emit (node:domain:489:12)
      at Request.<anonymous> (/Users/ethanhastings/testcafe-sample/node_modules/wd/node_modules/request/request.js:1161:10)
      at Request.emit (node:events:513:28)
      at Request.emit (node:domain:489:12)

**Comment by aleks-pro** [comment]
Hello @EthanHastings20 ,

Thank you for the update.

We looked into the issue and found out that its cause most likely lies in the [`testcafe-browser-provider-lambdatest`](https://www.npmjs.com/package/testcafe-browser-provider-lambdatest) package. I recommend that you address you question to the Lambda test team since they maintain this package.
