### ISSUE TITLE
Chrome <= 94 throws `TypeError: client.Fetch.continueResponse is not a function`

### ISSUE THREAD

**Issue by htho** [DevExpress/testcafe#7868]
### What is your Scenario?

I run my tests against the oldest browsers we support. For Chrome this is 88. On the build-pipeline it is a headless browser.

I use the portable versions of older browser versions. But the problem also occurs with an installed version. 

### What is the Current behavior?

When run in normal mode TestCafe fails with `TypeError: client.Fetch.continueResponse is not a function` (see below for the complete call stack).

When run in headless mode the name of the fixture is logged, then the program does not continue anymore.

### What is the Expected behavior?

Tests are executed as with more recent versions of TestCafe.

### What is your public website URL? (or attach your complete example)

`about:blank`

### What is your TestCafe test code?

```js
fixture('Getting Started')
    .page('about:blank');

test('My first test', async t => {
    // Test code goes here
});
```

### Your complete test report

Normal Mode:
```
> npx testcafe chromium:.\GoogleChromePortable94\GoogleChromePortable.exe .\test.tc.js
TypeError: client.Fetch.continueResponse is not a function
    at formatter (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\safe-api.ts:41:28)
    at connectionResetGuard (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\safe-api.ts:20:15)
    at safeContinueResponse (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\safe-api.ts:35:11)
    at handleRequestPauseEvent (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\special-handlers.ts:31:35)
    at handler (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\special-handlers.ts:58:15)
    at Chrome.<anonymous> (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:422:23)
    at Chrome.emit (node:events:513:28)
    at Chrome.emit (node:domain:489:12)
    at Chrome._handleMessage (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\chrome-remote-interface\lib\chrome.js:287:18)
    at WebSocket.<anonymous> (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\chrome-remote-interface\lib\chrome.js:240:22)
TypeError: client.Fetch.continueResponse is not a function
    at formatter (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\safe-api.ts:41:28)
    at connectionResetGuard (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\safe-api.ts:20:15)
    at safeContinueResponse (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\safe-api.ts:35:11)
    at handleRequestPauseEvent (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\special-handlers.ts:31:35)
    at handler (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\special-handlers.ts:58:15)
    at Chrome.<anonymous> (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:422:23)
    at Chrome.emit (node:events:513:28)
    at Chrome.emit (node:domain:489:12)
    at Chrome._handleMessage (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\chrome-remote-interface\lib\chrome.js:287:18)
    at WebSocket.<anonymous> (C:\path\to\github.com\htho\testcafe-repro-old-headless-chromium\node_modules\chrome-remote-interface\lib\chrome.js:240:22)
```

Headless Mode (aborted with Control+c after a minute):
```
> npx testcafe chromium:.\GoogleChromePortable94\GoogleChromePortable.exe:headless .\test.tc.js
 Running tests in:
 - Chrome 94.0.4606.81 / Windows 10

 Getting Started
Stopping TestCafe...
Batchvorgang abbrechen (J/N)?
^C
```

### Steps to Reproduce

1. Download and "install" the portable browser to `./GoogleChromePortable94/`
2. `npx testcafe chromium:.\GoogleChromePortable94\GoogleChromePortable.exe .\test.tc.js`

### TestCafe version

3.0.1

### Node.js version

v18.16.1

### Command-line arguments

npx testcafe chromium:.\GoogleChromePortable94\GoogleChromePortable.exe .\test.tc.js

### Browser name(s) and version(s)

Chrome 94

### Platform(s) and version(s)

Windows 10

### Other

Here is a repository with test code and links to the according portable apps:

https://github.com/htho/testcafe-repro-old-headless-chromium

**Comment by miherlosev** [comment]
Hi @htho,

The latest TestCafe version (`3.0.1`) supports the latest browser versions (see [https://testcafe.io/documentation/402828/guides/intermediate-guides/browsers?search#browser-support](https://testcafe.io/documentation/402828/guides/intermediate-guides/browsers?search#browser-support)). The `94` version of Google Chrome is too outdated. However, as a workaround, you can use the `2.x` version.

**Comment by htho** [comment]
Hi,

I really get a bad feeling in my gut reading your reply.
I see how it makes sense to only support the latest browsers from a development point of view.
But for me as someone who needs to support older Browser-Versions as-well, this makes TestCafe unattractive.

Anyway - I found a solution: I [disable native automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode#q-how-do-i-disable-native-automation).

I hope this works as long as Firefox and other Browsers are supported.
