### ISSUE TITLE
headless + nativeAutomation + Role on login on 3rd party website - Error in Role initializer

### ISSUE THREAD

**Issue by BehaminBakhshaie** [DevExpress/testcafe#7884]
### What is your Scenario?

Login with chrome:headless, using nativeAutomation and roles on our website where authentication cookie is set on a 3rd party website. 

### What is the Current behavior?

Error in Role initializer:

 ```
Running tests in:
 - Chrome 114.0.5735.199 / Windows 11

 Bug: Native Automation Bug Test
START: Use registeredUser and navigateTo
 √ Use registeredUser and navigateTo
START: Use premiumUserRole and navigateTo
#submitButton reached
START: Use premiumUserRole and navigateTo
 × Use premiumUserRole and navigateTo

   1) - Error in Role initializer -
      Error: The Chrome 114.0.5735.199 / Windows 11 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault.

      Browser: Chrome 114.0.5735.199 / Windows 11

         10 |  await t.expect(Selector('#submitButton').visible).ok();
         11 |  await t.typeText(Selector('#userNameInput'), 'PublicUser');
         12 |  await t.typeText(Selector('#passwordInput'), 'WeLoveTestCafe');
         13 |
         14 |  console.log('#submitButton reached');
       > 15 |  await t.click(Selector('#submitButton'));
         16 |  console.log('#submitButton clicked');
         17 |});
         18 |
         19 |fixture('Bug: Native Automation Bug Test');
         20 |

         at <anonymous> (C:\Users\beba\workspace\pla-cropmanager-bff\Seges.CropManager.Frontend\ClientApp\e2e\testcafe\tests\nativeAutomationBug.cafe.ts:15:11)
         at fulfilled (C:\Users\beba\workspace\pla-cropmanager-bff\Seges.CropManager.Frontend\ClientApp\e2e\testcafe\tests\nativeAutomationBug.cafe.ts:5:58)



 1/2 failed (2m 12s)
```

### What is the Expected behavior?

That it would log in and test would pass.
You can see expected behavior by simply running it in none headless or set disableNativeAutomation: true.

### What is your public website URL? (or attach your complete example)

https://dev-cropmanager.vfltest.dk/#/

### What is your TestCafe test code?

In this test I am using role on registeredUser and on our 3rd party authentication "premiumUserRole". The test with registeredUser will pass but the test with premiumUserRole will fail:

```
import { Role, Selector } from 'testcafe';

const registeredUser = Role('https://devexpress.github.io/testcafe/example/', async (t) => {});

const premiumUserRole = Role('https://dev-cropmanager.vfltest.dk/#/', async (t) => {
  await t.click(Selector('#e2e-logOnCm'));

  // Wait for the new page to load
  await t.expect(Selector('#submitButton').exists).ok();
  await t.expect(Selector('#submitButton').visible).ok();
  await t.typeText(Selector('#userNameInput'), 'PublicUser');
  await t.typeText(Selector('#passwordInput'), 'WeLoveTestCafe');

  console.log('#submitButton reached');
  await t.click(Selector('#submitButton'));
  console.log('#submitButton clicked');
});

fixture('Bug: Native Automation Bug Test');

test.only('Use registeredUser', async (t) => {
  console.log('START: Use registeredUser');
  await t.useRole(registeredUser); // Works

  await t.expect(true).ok();
});

test.only('Use premiumUserRole', async (t) => {
  console.log('START: Use premiumUserRole');
  await t.useRole(premiumUserRole); // Does not work

  await t.expect(true).ok();
});


```

### Your complete configuration file

```
const baseUrl = process.env.WEBAPP_URL || 'https://localhost.vfltest.dk:8080/'; 

module.exports = {
  src: ['./e2e/testcafe/tests/**/*.cafe.ts'],
  browsers: ['chrome:headless:emulation:width=1920;height=1080'],
  concurrency: 1,
  baseUrl: baseUrl,
  compilerOptions: {
    typescript: {
      configPath: '../ClientApp/e2e/testcafe/tsconfig.cafe.json',
    },
  },
  disableNativeAutomation: false, // will fail if set to false
  stopOnFirstFail: true,
  cache: false,
  disablePageCaching: true,
  disableMultipleWindows: true, // possible fix for nativeAutomationBug
};
```

### Steps to Reproduce

1. copy and run the test
2. This test will pass: Use registeredUser
3. This test will fail: Use premiumUserRole
4. following configurations are important: chrome:headless, disableNativeAutomation: false, (Otherwise it will pass both tests)

### TestCafe version

3.0.1

### Node.js version

v18.16.1

### Command-line arguments

npx testcafe

### Browser name(s) and version(s)

Chrome 114.0.5735.199 

### Platform(s) and version(s)

Windows 11

### Other

Could be related to this issue: [https://github.com/DevExpress/testcafe/issues/7874]( https://github.com/DevExpress/testcafe/issues/7874)

**Comment by Aleksey28** [comment]
Hi @BehaminBakhshaie,

It is fixed in TestCafe [3.1.0-rc.1](https://www.npmjs.com/package/testcafe/v/3.1.0-rc.1). Please run your test with this version, and let us know if the issue still occurs on your side.
