### ISSUE TITLE
Testcafe fails to find selector after performing action on it

### ISSUE THREAD

**Issue by tgrisley** [DevExpress/testcafe#7894]
### What is your Scenario?

Have updated to 3.1.0-rc.1 and running in native automation, when running example below notice that TestCafe fails to find a selector that it has already interacted with and should not be clicking anymore.

### What is the Current behavior?

TestCafe fails to find selector that it has just performed action on.

### What is the Expected behavior?

Expect TestCafe to not fail and move onto next action. 

### What is your public website URL? (or attach your complete example)

stage.economist.com

### What is your TestCafe test code?

// cookie-consent.js //

```
import { RequestMock } from 'testcafe';

// Mock Evidon cookie consent to avoid interacting with the module on each new session
export function mockEvidonCookieConsent() {
  return RequestMock()
    .onRequestTo(/evidon\.com\//)
    .respond('', 200);
}

export function mockSourcepointCookieConsent() {
  return RequestMock()
    .onRequestTo(/cmp-cdn\.p\.aws\.economist\.com\/latest\/cmp\.min\.js/)
    .respond('', 200);
}

```

// example.js //

```
import { ClientFunction, fixture , Selector, t } from 'testcafe';
import { xpathSelector } from './helpers';
import {
  mockEvidonCookieConsent,
  mockSourcepointCookieConsent,
} from './cookie-consent';

fixture `example fixture`
  .page('stage.economist.com')
  .requestHooks([mockEvidonCookieConsent(), mockSourcepointCookieConsent()])
 
const loginLink = Selector('.ds-masthead').find('a').withText('Log in')
const subscribeLink = Selector('header a').withText('Subscribe');
const emailField =  xpathSelector('//*[@type="text"]');
const passwordField = xpathSelector('//*[@type="password"]');

test('example', async t => {
  console.log('it exists')
  await t.click(loginLink)
  console.log('clicked')
  await t.typeText(emailField, 'email@example.com')
  await t.typeText(passwordField, 'password')
  console.log('password entered')
});

test('example 2', async t => {
  console.log('it exists')
  await t.click(loginLink)
  console.log('clicked')
  await t.typeText(emailField, 'email@example.com')
  console.log('email entered')
  await t.typeText(passwordField, 'password')
  console.log('password entered')
});

test('example 3', async t => {
  console.log('it exists')
  await t.click(loginLink)
  console.log('clicked')
  await t.typeText(emailField, 'email@example.com')
  console.log('email entered')
  await t.typeText(passwordField, 'password')
  console.log('password entered')
});

test('example 3', async t => {
  console.log('it exists')
  await t.click(subscribeLink);
  console.log('clicked')
  const getURL = await ClientFunction(() => window.location.href)();
  await t.expect(getURL).contains('subscribe');
});
```

helpers.js

```
import { Selector } from 'testcafe';

/**
 * Retrieves all elements that match a given xpath.
 * @param {string} xpath - xpath to search with
 * @return {Object} found elements
 */
const getElementsByXPath = Selector(xpath => {
  const iterator = document.evaluate(
    xpath,
    document,
    null,
    XPathResult.UNORDERED_NODE_ITERATOR_TYPE,
    null,
  );

  const items = [];
  let item = iterator.iterateNext();

  while (item) {
    items.push(item);
    item = iterator.iterateNext();
  }

  return items;
});


/**
 * Create a selector based on a xpath. Testcafe does not natively support xpath
 * selectors, hence this function.
 * @param {string} xpath - xpath to search with
 * @returns {Selector} returns a selector
 */
export const xpathSelector = xpath => {
  return Selector(getElementsByXPath(xpath));
};
```

### Your complete test report

```
example fixture
it exists
 ✖ example

   1) The specified selector does not match any element in the DOM tree.
      
       > | Selector('.ds-masthead')
         |   .find('a')
         |   .withText('Log in')

      Browser: Chrome 114.0.0.0 / Ventura 13

         14 |const emailField =  xpathSelector('//*[@type="text"]');
         15 |const passwordField = xpathSelector('//*[@type="password"]');
         16 |
         17 |test('example', async t => {
         18 |  console.log('it exists')
       > 19 |  await t.click(loginLink)
         20 |  console.log('clicked')
         21 |  await t.typeText(emailField, 'email@example.com')
         22 |  await t.typeText(passwordField, 'password')
         23 |  console.log('password entered')
         24 |});

         at <anonymous> (/Users/tomgrisley/Desktop/example/example.js:19:11)
         at asyncGeneratorStep (/Users/tomgrisley/Desktop/example/example.js:3:150)
         at _next (/Users/tomgrisley/Desktop/example/example.js:3:488)
         at <anonymous> (/Users/tomgrisley/Desktop/example/example.js:3:653)
         at <anonymous> (/Users/tomgrisley/Desktop/example/example.js:3:394)
         at <anonymous> (/Users/tomgrisley/Desktop/example/example.js:17:5)
```

### Screenshots

<img width="609" alt="Screenshot 2023-07-20 at 23 31 01" src="https://github.com/DevExpress/testcafe/assets/126177701/0152fc37-3d2f-4428-a7a6-ab418d382af7">

<img width="1225" alt="Screenshot 2023-07-20 at 23 29 50" src="https://github.com/DevExpress/testcafe/assets/126177701/57af4a58-1f48-451d-a04f-6d2ba3bc8390">

### Steps to Reproduce

1. testcafe chrome example.js --skip-js-errors
2. notice that it clicks on login link on homepage and takes user to login page
3. notice that testcafe fails as it cannot find login link on homepage, even though it has just performed this action so shouldn't need to check it?

### TestCafe version

3.1.0-rc.1

### Command-line arguments

testcafe chrome example.js --skip-js-errors

### Browser name(s) and version(s)

Chrome 114

### Platform(s) and version(s)

macOS 13.3

**Comment by tgrisley** [comment]
Seems like a workaround is to add an an assert to check the element exists before clicking it. 

I shouldn't have to do this though if TestCafe is actually already clicking the element?

**Comment by AlexKamaev** [comment]
I managed to reproduce the issue. Thank you for sharing the example. We'll research the issue and update the thread once we have news.

**Comment by miherlosev** [comment]
Hi @tgrisley,

```js
export function mockSourcepointCookieConsent() {
return RequestMock()
.onRequestTo(/cmp-cdn\.p\.aws\.economist\.com\/latest\/cmp\.min\.js/)
.respond('', 200);
}
```

This code responds to a request with an HTML page but it should respond with script content.
To fix this, you need to change the code piece as follows:

```js
.respond('', 200, {
'content-type': 'text/javascript',
});
```

Also, empty content causes script errors that break the correct JavaScript execution on the tested website.
![](https://github.com/DevExpress/testcafe/assets/4133518/32f35902-8a03-4a07-a87d-85def16c2f47)
Please find the correct script content for a dummy request and use it. If this doesn't help, please feel free to reopen this issue.
