### ISSUE TITLE
React "TestCafe" tests are failing with "TypeError: Illegal invocation" when working with tinyMCE

### ISSUE THREAD

**Issue by alonzrihan** [DevExpress/testcafe#7941]
### What is your Scenario?

Testing a component that includes the "tinymce-react" editor

### What is the Current behavior?

When running test on a component which includes the tinymce editor, the test starts to run as expected but when there is a reload/rerender of the page the test fails after a few seconds with the following message:

JavaScript error details:
TypeError: Illegal invocation
at r._removeInternalProperties (hammerhead.js:16:7987)
at r.dispose (hammerhead.js:16:8216)
at t.eval (hammerhead.js:16:7750)
at e.emit (hammerhead.js:4:8361)
at t._emitEvent (hammerhead.js:15:5580)
at t.handleEvent (hammerhead.js:15:8023)
at t._removeNodeCore (http://10.1.28.12:50238/hammerhead.js:10:31534)
at HTMLDivElement.removeChild (http://10.1.28.12:50238/hammerhead.js:11:2482)
at Po ([path to tinymce package]/tinymce/themes/silver/theme.min.js:5:15425)
at Vd ([path to tinymce package]/tinymce/themes/silver/theme.min.js:5:63038)

When adding the flag skipJsErrors = true to the test cafe config the tests are running as expected but we don't want to use it, for obvious reasons.

It is important to note that this issue happens on every page that includes the tinyMCE component, even without using it.

### What is the Expected behavior?

continue the test as expected without crashing

### What is your public website URL? (or attach your complete example)

can't share any urls

### What is your TestCafe test code?

can't share any code

### Steps to Reproduce

1. Create a component with TinyMCE editor (tinymce-react)
2. Run a simple test and during said test reload the entire page 

### TestCafe version

2.6.2

### Node.js version

16.16.0

### Command-line arguments

none

**Comment by alonzrihan** [comment]
looks like the new [native automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode) fix the issue but causes another issues with <input> elements
