### ISSUE TITLE
Suddenly TestCafe cant find chrome path

### ISSUE THREAD

**Issue by ejerskov** [DevExpress/testcafe#7979]
### What is your Scenario?

I've been running a TestCafe project on a Microsoft DevOps pipeline for a couple of years. Suddenly it fails saying it cant find the chrome path.

### What is the Current behavior?

I get this error:

```
D:\a\1\s\node_modules\testcafe\lib\browser\provider\pool.js:94
##[error]Cmd.exe exited with code '1'.
            throw new runtime_1.GeneralError(types_1.RUNTIME_ERRORS.cannotFindBrowser, alias);
                  ^

GeneralError: Cannot find the browser. "chrome" is neither a known browser alias, nor a path to an executable file.
    at Object.getBrowserInfo (D:\a\1\s\node_modules\testcafe\lib\browser\provider\pool.js:94:19)
    at async Promise.all (index 0)
    at async TestCafeConfiguration._getBrowserInfo (D:\a\1\s\node_modules\testcafe\lib\configuration\testcafe-configuration.js:205:29)
    at async TestCafeConfiguration.asyncMergeOptions (D:\a\1\s\node_modules\testcafe\lib\configuration\testcafe-configuration.js:66:44)
    at async TestCafeConfiguration.init (D:\a\1\s\node_modules\testcafe\lib\configuration\testcafe-configuration.js:60:9)
    at async getConfiguration (D:\a\1\s\node_modules\testcafe\lib\index.js:32:9)
    at async createTestCafe (D:\a\1\s\node_modules\testcafe\lib\index.js:47:27) {
  code: 'E1005',
  data: [ 'chrome' ]
```

Chrome seems to be missing from the browser list on the devops agent - how can I fix this?

```
> testcafe --list-browsers

firefox
edge
ie
```

### What is the Expected behavior?

Im expecting it to run as usual and use the correct path.

### What is your public website URL? (or attach your complete example)

-

### What is your TestCafe test code?

-

### Steps to Reproduce

1.
2.
3.

### TestCafe version

3.2.0

### Command-line arguments

-

**Comment by miherlosev** [comment]
Hi @ejerskov,
This is the issue of the runner image - [https://github.com/actions/runner-images/issues/8114](https://github.com/actions/runner-images/issues/8114).
Track it to be aware of our progress.
