### ISSUE TITLE
ERR_REQUIRE_ESM error when starting testcafe tests

### ISSUE THREAD

**Issue by kicr1** [DevExpress/testcafe#8020]
### What is your Scenario?

When running tests we see the following error:
```
ERROR Error [ERR_REQUIRE_ESM]: require() of ES Module /home/vsts/work/1/s/testcafe-tests/node_modules/get-func-name/index.js from /home/vsts/work/1/s/testcafe-tests/node_modules/chai/lib/chai/utils/inspect.js not supported.
Instead change the require of index.js in /home/vsts/work/1/s/testcafe-tests/node_modules/chai/lib/chai/utils/inspect.js to a dynamic import() which is available in all CommonJS modules.
```

This happens on start-up of the tests. The issue has started happening from today.

### What is the Current behavior?

Testcafe tests fail to start with ERR_REQUIRE_ESM error.

### What is the Expected behavior?

Testcafe tests should run without error.

### What is your public website URL? (or attach your complete example)

N/A

### What is your TestCafe test code?

Can't share codebase

### Your complete configuration file

Can't share config file

### Your complete test report

```
ERROR Error [ERR_REQUIRE_ESM]: require() of ES Module /home/vsts/work/1/s/testcafe-tests/node_modules/get-func-name/index.js from /home/vsts/work/1/s/testcafe-tests/node_modules/chai/lib/chai/utils/inspect.js not supported.
Instead change the require of index.js in /home/vsts/work/1/s/testcafe-tests/node_modules/chai/lib/chai/utils/inspect.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/chai/lib/chai/utils/inspect.js:4:15)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/chai/lib/chai/utils/objDisplay.js:11:15)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/chai/lib/chai/utils/getMessage.js:13:18)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/chai/lib/chai/utils/index.js:34:22)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/chai/lib/chai.js:25:12)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/chai/index.js:1:18)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/assertions/get-fn.js:6:16)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/assertions/executor.js:11:34)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/test-run/index.js:69:36)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/runner/test-run-controller.js:32:36)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/runner/browser-job.js:8:47)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/runner/task/index.js:9:39)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.<anonymous> (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/runner/index.js:13:32)
    at Module._compile (/home/vsts/work/1/s/testcafe-tests/node_modules/source-map-support/source-map-support.js:568:25)
    at lazy (/home/vsts/work/1/s/testcafe-tests/node_modules/import-lazy/index.js:2:51)
    at Object.construct (/home/vsts/work/1/s/testcafe-tests/node_modules/import-lazy/index.js:18:11)
    at TestCafe._createRunner (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/testcafe.js:82:27)
    at TestCafe.createRunner (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/testcafe.js:106:21)
    at runTests (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/cli/cli.js:83:75)
    at async cli (/home/vsts/work/1/s/testcafe-tests/node_modules/testcafe/lib/cli/cli.js:136:13)

```

### Steps to Reproduce

1. Run npm i
2. Run npm run test script
3. Error occurs 

### TestCafe version

3.2.0

### Node.js version

18.17.1

### Command-line arguments

export NODE_ENV=XXXX&& testcafe 'chrome:headless' ./tests --base-url "http://localhost:4080/xxxx" --fixture-meta XXXX=true --reporter spec,nunit3:report.xml -e

**Comment by kicr1** [comment]
I think this can be closed now. An update was made to the get-func-name package which seems to have resolved the issue.
