### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by volosincu** [DevExpress/testcafe#8104]
### What is your Scenario?

**NPM dependencies** package.json 

```
 "@reduxjs/toolkit": "^2.0.1",
    "axios-hooks": "^5.0.2",
    "clsx": "^1.1.1",
    "mui-image": "^1.0.7",
    "npm-force-resolutions": "^0.0.10",
    "prop-types": "^15.7.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-redux": "^8.1.2",
    "react-world-flags": "^1.5.1",
    "redux": "^4.2.1",
    "redux-immutable-state-invariant": "^2.1.0",
    "redux-thunk": "^2.4.2"
```

Webpack config 
```
 new ModuleFederationPlugin({
        name: 'myApp', 
        remotes: {
          mfeCommon: microFrontendRemoteUrl,
        },
        shared: {
          react: {
            singleton: true,
            requiredVersion: deps.react,
            eager: true,
          },
          'react-dom': {
            singleton: true,
            requiredVersion: deps['react-dom'],
            eager: true,
          },
        },
      }),
```

```
import MenuComponent from './menu/MenuComponent';
import { createRoot } from 'react-dom/client';
const Shell = React.lazy(() => import('mfeCommon/Shell'));
const ShellContextProvider = React.lazy(() =>
  import('mfeCommon/ShellContextProvider')
);
const Header = React.lazy(() =>
  import('mfeCommon/Header')
);

function MfeStudio() {
  const [shellData, setShellData] = React.useState({
    applicationSettings: {},
  } as IShellData);

  return (
    <Suspense fallback={<></>}>
      <ShellContextProvider
        value={{
          shellData,
          setShellData,
        }}
      >
        <Shell>
          <Header />
          <MenuComponent />
        </Shell>
      </ShellContextProvider>
    </Suspense>
  );
}
```

```
remoteApp/Shell  RangeError: Maximum call stack size exceeded
    at PropertyAccessorsInstrumentation._propertyGetter (hammerhead.js:20827:66)
    at get maxSize [as maxSize] (vendors-node_modules_axios-hooks_es_index_js.js:1060:17)
    at PropertyAccessorsInstrumentation._propertyGetter (hammerhead.js:20839:22)
    at get maxSize [as maxSize] (vendors-node_modules_axios-hooks_es_index_js.js:1060:17)
    at PropertyAccessorsInstrumentation._propertyGetter (hammerhead.js:20839:22)
    at get maxSize [as maxSize] (vendors-node_modules_axios-hooks_es_index_js.js:1060:17)
    at PropertyAccessorsInstrumentation._propertyGetter (hammerhead.js:20839:22)
    at get maxSize [as maxSize] (vendors-node_modules_axios-hooks_es_index_js.js:1060:17)
    at PropertyAccessorsInstrumentation._propertyGetter (hammerhead.js:20839:22)
    at get maxSize [as maxSize] (vendors-node_modules_axios-hooks_es_index_js.js:1060:17)
```

```
	Uncaught ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (vendors-node_modules_axios-hooks_es_index_js.js:16:42)
    at getter (remote.js:96:27)
    at useCacheTimestamps (src_Events_EventHandlers_ts-src_components_Icons_IconsHelper_tsx-src_components_Menu_menu_hoo-0ffb7f.js:1255:14)
    at Header (src_components_Header_Header_tsx-webpack_sharing_consume_default_clsx_clsx.js:1518:76)
    at renderWithHooks (bundle.app.js:16261:18)
    at updateFunctionComponent (bundle.app.js:19539:20)
    at mountLazyComponent (bundle.app.js:19910:17)
    at beginWork (bundle.app.js:21544:16)
    at HTMLUnknownElement.callCallback (bundle.app.js:4120:14)
    at HTMLUnknownElement.dispatchEvent (hammerhead.js:40262:56)
```

![TestCafe-webpack-err__2023-12-14 095946](https://github.com/DevExpress/testcafe/assets/737332/3204002e-43c9-48bd-bffc-5aed9ba15464)

### What is the Current behavior?

**Scenario**

The tests flows break with following errors 

When rendering the 2 components from the remote microfrontend the error below appears.
It happens only in the TestCafe browser window. Not sure why but I reckon that hooks from the components loaded with dynamic import in React.lazy break cause __WEBPACK_DEFAULT_EXPORT__ is missing ( the same code works if not in TestCafe context)

### What is the Expected behavior?

To render the 2 components from the remote microfrontend.

### What is the public URL of the test page? (attach your complete example)

https://localhost:80/

### What is your TestCafe test code?

```
fixture`Smoke Test`.page("https://localhost:80/");

test("crawl homepage test", async (t) => {
  await t.setNativeDialogHandler(() => true);


  try {
   await t
        .typeText("#username", username)
        .typeText("#password", password)
        .click(Selector("#login"));

      await t
        .expect(
          await Selector("#create-asset", { timeout: 30000 }).visible
        )
        .eql(true);
```

### Your complete configuration file
```

module.exports = {
  selectorTimeout: 30000,
  pageLoadTimeout: 10000,
  ajaxRequestTimeout: 60000,
  pageRequestTimeout: 25000,
  browsers: "chrome",
  skipJsErrors: true,
  disableNativeAutomation: false,
  hostname: "localhost",
  //concurrency: 2,
  videoPath: "./output/report-video",
  videoOptions: {
    singleFile: false,
    failedOnly: true,
    pathPattern:
      "${FIXTURE}/${TEST}/${USERAGENT}/${DATE}_${TIME}/${FILE_INDEX}.mp4",
  },
  screenshots: {
    path: "./output/report-images",
    takeOnFails: true,
    fullPage: true,
    failedOnly: true,
    pathPattern:
      "${FIXTURE}/${TEST}/${USERAGENT}/${DATE}_${TIME}/${FILE_INDEX}.png",
  },
  reporter: [
    {
      name: "custom",
      output: "output-custom/report.txt",
    },
    {
      name: "html",
      output: "output/report.html",
    },
  ],
  hooks: {},
};

```

### Steps to Reproduce

1. create a microfrontend React architecture with ModuleFederationPlugin
2. use es6 dynamic import  to load remote component in React.lazy
3. add an axios hook in one of the remove components

### TestCafe version

3.4.0

### Node.js version

18.10

### Command-line arguments

npx testcafe ./test_examples/test_smoke.js --config-file .testcafenight.js

### Browser name(s) and version(s)

Chrome 120

### Platform(s) and version(s)

Windows 11

**Comment by PavelMor25** [comment]
Hello @volosincu,

Could you please pack all necessary files into a public repository?

**Comment by Bayheck** [comment]
Hello,

Thank you for creating an example repo.

I did not encounter any issues when running your test in Native Automation mode. Starting from version 3.0, TestCafe runs tests with the [Native Automation](%5Bhttps://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode%5D(https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode)) option enabled by default. If you can reproduce the issue using native automation mode, please create a separate ticket using this [template](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml)
