### ISSUE TITLE
maximise window issue with scrolling to buttons

### ISSUE THREAD

**Issue by KatlegoMthunzi** [DevExpress/testcafe#8164]
### What is your Scenario?

set my window size to full screen via CLI (or mid script with the maximizeWindow() method). The button(s) in question appear much lower in the page and are necessary to proceed to the next page

### What is the Current behavior?

When script is running, testcafe has a problem scrolling to my selectors for buttons and clicking them. it throws an error stating: The action target (<My Selector element>) is located outside the the layout viewport.

### What is the Expected behavior?

Click the visible and existing selector and continue with the script

### What is the public URL of the test page? (attach your complete example)

N/A, Private repo

### What is your TestCafe test code?

import { Selector, t } from "testcafe";

class Step2{
    
    constructor() {

            this.SignatoryName = Selector("#Name")

            this.SignatorySurname= Selector('#Surname')
            this.SignatoryCell = Selector('#Cell')
    
            this.SignatoryEmail = Selector('#Email')

            this.SignatoryRole = Selector('#RoleId')

            this.SaveSignatory = Selector('button').withText('Save')

            this.Proceedbtn = Selector('#btnUpdateSchedule')

            this.warningToast = Selector('div > div.toast-title')
            this.signOptionDD = Selector('#RoleId')
            this.completeDDOption = Selector('option').withText('Complete')

    }

    async Fill_in_Signatory(name, surname) {
        
        await t
            .expect(this.SignatoryCell.exists).ok({timeout: 30000 })
            .typeText(this.SignatoryName, name)
            .typeText(this.SignatorySurname, surname)
            .typeText(this.SignatoryCell, '0726051545')
            .typeText(this.SignatoryEmail, 'katlego.mthunzi+01@mrisoftware.com')
            .scroll(this.SaveSignatory)
            .click(this.SaveSignatory)

    }

    async Fill_in_Signatory_Complete(name, surname) {
        

        
        await t
        .expect(this.signOptionDD.exists).ok({timeout: 30000 })
        // console.log(await this.SaveSignatory.innerText)

            await t
            .typeText(this.SignatoryName, name)
            .typeText(this.SignatorySurname, surname)
            .typeText(this.SignatoryCell, '0726051545')
            .typeText(this.SignatoryEmail, 'katlego.mthunzi+01@mrisoftware.com')
            .click(this.signOptionDD)
            .click(this.completeDDOption)
            .scroll(this.SaveSignatory)
            .click(this.SaveSignatory)

    }

    async Fill_in_Signatory_Incorrect() {
        
        await t
            .expect(this.SignatoryCell.exists).ok({timeout: 30000 })
            .typeText(this.SignatoryName, 'Testing')
            .typeText(this.SignatorySurname, 'Tester')
            .typeText(this.SignatoryCell, '0726051545')
            .click(this.SaveSignatory)
            .expect(this.warningToast.visible).ok()
            .selectText(this.SignatoryName)
            .pressKey('delete')
            .selectText(this.SignatorySurname)
            .pressKey('delete')
            .selectText(this.SignatoryCell)
            .pressKey('delete')

            await t
            .expect(this.SignatoryCell.exists).ok({timeout: 30000 })   
            .typeText(this.SignatoryName, 'Testing')
            .typeText(this.SignatorySurname, 'Tester')
            .typeText(this.SignatoryEmail, 'katlego.mthunzi+01@mrisoftware.com')
            .click(this.SaveSignatory)
            .expect(this.warningToast.visible).ok()
            .selectText(this.SignatoryName)
            .pressKey('delete')
            .selectText(this.SignatorySurname)
            .pressKey('delete')
            .selectText(this.SignatoryEmail)
            .pressKey('delete')

            await t
            .expect(this.SignatoryCell.exists).ok({timeout: 30000 })
            .typeText(this.SignatoryEmail, 'katlego.mthunzi+01@mrisoftware.com')
            .typeText(this.SignatorySurname, 'Tester')
            .typeText(this.SignatoryCell, '0726051545')
            .click(this.SaveSignatory)
            .expect(this.warningToast.visible).ok()
            .selectText(this.SignatoryEmail)
            .pressKey('delete')
            .selectText(this.SignatorySurname)
            .pressKey('delete')
            .selectText(this.SignatoryEmail)
            .pressKey('delete')

            await t
            .expect(this.SignatoryCell.exists).ok({timeout: 30000 })
            .typeText(this.SignatoryEmail, 'katlego.mthunzi+01@mrisoftware.com')
            .typeText(this.SignatoryName, 'Tester')
            .typeText(this.SignatoryCell, '0726051545')
            .click(this.SaveSignatory)
            .expect(this.warningToast.visible).ok()
            .typeText(this.SignatorySurname, 'Tester')
            .click(this.SaveSignatory)
            .expect(this.warningToast.visible).ok()

    }

    async Proceed() {
        await t
        .scrollIntoView(this.Proceedbtn)
        .click(this.Proceedbtn)
    }
         
    
    }
                
    export default new Step2()

import LoginPage from "./PageObjects/LoginPage";
import HomePage from "./PageObjects/HomePage";
import CreateDocPage from "./PageObjects/CreateDocPage";
import Step1 from "./PageObjects/CreateDocSteps/Step1";
import Step2 from "./PageObjects/CreateDocSteps/Step2";
import Step3 from "./PageObjects/CreateDocSteps/Step3";
import Step4 from "./PageObjects/CreateDocSteps/Step4";
import SettingsPage from "./PageObjects/SettingsPages/SettingsPage";
import CreateFolderPage from "./PageObjects/CreateFolderPage";
import DeletePage from "./PageObjects/DeletePage";
import RestorePage from "./PageObjects/RestorePage";
import MoveItemsPage from "./PageObjects/MoveItemsPage";
import CompletedDocPage from "./PageObjects/CompletedDocPage";

const dotenv = require('dotenv');

dotenv.config()

fixture('Create and Delete Leases and Folders')
    .page(process.env.BASE_ESIGN_URL)
    .beforeEach(async t => {

        await LoginPage.signInUser(process.env.automationuser1, process.env.password1, t)

    });

    
    test('Month to Month Lease Agreement : eSign Access', async t => {
     
    
        var docOption = 'esign' //ignore
    
        await HomePage.clickCreateEdocbtn() //ignore
    
        await t.expect(CreateDocPage.returntoEdocsbtn.exists).ok() //ignore
    
        await CreateDocPage.ResidentialLeasePack("lease", "Month to Month Lease Agreement", docOption) // ignore
        
        await  Step1.NameNewDocProcceed() //ignore
        

    
        **await Step2.Fill_in_Signatory_Complete('Testing', 'Tester')
        await Step2.Fill_in_Signatory_Complete('Landlord', 'Testy')
        await Step2.Proceed()**
    
        await Step3.MonthtoMonthRequiredFieldsEsign()
    
        await Step4.CompleteDoc(docOption)

        await CompletedDocPage.checkSignatoryStatusAwaiting()

        await CompletedDocPage.editSignatoryDetails()

        await CompletedDocPage.resendLink()

        await CompletedDocPage.checkDocumentActivity()

        await CompletedDocPage.downloadDoc()

        

    
    
    });

### Your complete test report

 × Month to Month Lease Agreement : eSign Access

   1) The action target (<button id="btnUpdateSchedule" type="button" class="btn btn-primary pull-right" data-loading-text="<i
      class='fa fa-spinner fa-spin'>">Proceed...</button>) is located outside the the layout viewport.

      Browser: Chrome 123.0.0.0 / Windows 10

         120 |
         121 |    }
         122 |
         123 |    async Proceed() {
         124 |        await t
       > 125 |        .scrollIntoView(this.Proceedbtn)
         126 |        .click(this.Proceedbtn)
         127 |    }
         128 |
         129 |
         130 |    }

         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:125:10)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at Step2.Proceed [as Proceed]
      (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:126:32)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:48:21)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:14:63)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:14:63)

 × Month to Month Lease Agreement : Manual/Word Access

   1) The action target (<button id="btnUpdateSchedule" type="button" class="btn btn-primary pull-right" data-loading-text="<i
      class='fa fa-spinner fa-spin'>">Proceed...</button>) is located outside the the layout viewport.

      Browser: Chrome 123.0.0.0 / Windows 10

         120 |
         121 |    }
         122 |
         123 |    async Proceed() {
         124 |        await t
       > 125 |        .scrollIntoView(this.Proceedbtn)
         126 |        .click(this.Proceedbtn)
         127 |    }
         128 |
         129 |
         130 |    }

         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:125:10)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at Step2.Proceed [as Proceed]
      (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:126:32)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:89:17)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:14:63)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:14:63)

 √ Month to Month Lease Agreement : Basic Access
 × Rental Application Form : Multi-use Document - Specific Signatory

   1) The action target (<a id="Other" href="javascript:void(0)" data-toggle="collapse" data-target="#div_1_4">...</a>) is invisible.      
      It descends from an element that has the 'display: none' property (<div id="div_1" class="collapse p-2">...</div>).

      Browser: Chrome 123.0.0.0 / Windows 10

         33 |
         34 |        switch (folder) {
         35 |            case "other":
         36 |
         37 |                await t
       > 38 |                    .click(this.Res_Other)
         39 |                await this.selectLeaseFromOpenFolder(docName, option)
         40 |                break;
         41 |            case "mandate":
         42 |                await t
         43 |                    .click(this.Res_Mandate)

         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocPage.js:38:22)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocPage.js:1:40)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocPage.js:1:40)

 × Natural Person Lease Agreement (CPA) : Check wiki links

   1) The action target (<button id="btnUpdateSchedule" type="button" class="btn btn-primary pull-right" data-loading-text="<i
      class='fa fa-spinner fa-spin'>">Proceed...</button>) is located outside the the layout viewport.

      Browser: Chrome 123.0.0.0 / Windows 10

         120 |
         121 |    }
         122 |
         123 |    async Proceed() {
         124 |        await t
       > 125 |        .scrollIntoView(this.Proceedbtn)
         126 |        .click(this.Proceedbtn)
         127 |    }
         128 |
         129 |
         130 |    }

         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:125:10)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at Step2.Proceed [as Proceed]
      (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:126:32)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:175:17)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:14:63)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:14:63)

 √ Buffer test - ignore
 × Month to Month Lease Agreement : Landlord Signing Option - Complete

   1) The action target (<button id="btnUpdateSchedule" type="button" class="btn btn-primary pull-right" data-loading-text="<i
      class='fa fa-spinner fa-spin'>">Proceed...</button>) is located outside the the layout viewport.

      Browser: Chrome 123.0.0.0 / Windows 10

         120 |
         121 |    }
         122 |
         123 |    async Proceed() {
         124 |        await t
       > 125 |        .scrollIntoView(this.Proceedbtn)
         126 |        .click(this.Proceedbtn)
         127 |    }
         128 |
         129 |
         130 |    }

         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:125:10)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:1:40)
         at Step2.Proceed [as Proceed]
      (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\CreateDocSteps\Step2.js:126:32)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:209:17)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:14:63)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:14:63)

 √ Change Doc Header to custom header
 √ Create a new Folder
 × Move Documents to folder

   1) AssertionError: expected '4' to deeply equal '2'

      + expected - actual

      -4
      +2

      Browser: Chrome 123.0.0.0 / Windows 10

         100 |
         101 |
         102 |    async verifyExpectedDocCounts(allDocsCount = '0', awaitingSignCount = '0', signedDocsCount = '0', templateDocsCount =    
      '0') {
         103 |        await t
         104 |            .expect(this.allDocsCount.exists).ok({timeout: 10000})
       > 105 |            .expect(this.allDocsCount.innerText).eql(allDocsCount)
         106 |            .expect(this.awaitingSignCount.innerText).eql(awaitingSignCount)
         107 |            .expect(this.signedDocsCount.innerText).eql(signedDocsCount)
         108 |            .expect(this.templateDocsCount.innerText).eql(templateDocsCount)
         109 |
         110 |    }

         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\HomePage.js:105:50)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\HomePage.js:1:40)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\HomePage.js:1:40)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\HomePage.js:1:40)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\HomePage.js:1:40)
         at HomePage.verifyExpectedDocCounts [as verifyExpectedDocCounts]
      (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\PageObjects\HomePage.js:108:77)
         at <anonymous> (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:268:20)
         at asyncGeneratorStep (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:14:63)
         at _next (C:\Users\Katlego.Mthunzi\TPN_Cypress_Proj\tests\eSign\CreateAndDeleteLeaseAndfFolder.js:14:63)

### Steps to Reproduce

1. Set window to full screen before any code runs
2. Set some Selector pointing to a button that isn't visible when landing on the page(need to scroll to see button)
3.Error occurs when script tries to click button

### TestCafe version

3.5.0

### Node.js version

20.4.0

### Command-line arguments

testcafe \"chrome --start-fullscreen\" --reporter spec,html:results\\eSign\\report.html --video results\\eSign\\videos \"./tests/eSign/C*.js\" -e 

### Browser name(s) and version(s)

Chrome 123.0.0.0 / Windows 10

### Platform(s) and version(s)

Windows

**Comment by Bayheck** [comment]
Hello,

I tried to reproduce the issue in the usage scenario you described, but I did not manage to get the error.

Could you please share a [Minimal Working Example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue) with a working URL so that the team can research the issue and help you?
