### ISSUE TITLE
Importing a markdown file into my React application causes TestCafe to throw

### ISSUE THREAD

**Issue by mathampson** [DevExpress/testcafe#8168]
### What is your Scenario?

I am importing `.md` Markdown files into my React application. These are interpreted by the `ReactMarkdown` package for display. (Background: I'm doing this so non-technical staff can edit parts of the site content - i.e. a _very_ basic CMS.)

### What is the Current behavior?

In my most simplified test case simply importing the .md file (not using it, not importing or invoking ReactMarkdown) causes TestCafe to throw an "Unexpected token" error at the first character of the file (`#`)

### What is the Expected behavior?

Importing a .md file should not, in itself, throw an error.

### What is the public URL of the test page? (attach your complete example)

This is the publicly available production build:
https://leyden.health.elsevier.com

### What is your TestCafe test code?

This happens on load, so the test code is no more than:
```fixture('Test component').page('http://localhost:3000');```

### Your complete configuration file

```
module.exports = {
    screenshots: {
        takeOnFails: true,
        path: './testcafe/reports/screenshots/',
        pathPattern: '${DATE}_${TIME}_test-${TEST_INDEX}.png',
    },
    skipJsErrors: true,
};
```

### Your complete test report

ERROR Cannot prepare tests due to the following error:

SyntaxError: C:\Repos\health-leyden\documentation-a
pp\src\_markdown\data-viz\bar-chart.md: Unexpected token (1:0)

> 1 | ### Pattern summary
    | ^
  2 |
  3 | Also called bar graph or column chart, the ba
r chart is useful for comparing categorical data wi
th a shared baseline. Bars can be orientated in eit
her a vertical or horizontal direction depending on space available or desired fidelity.
  4 |
    at Object.<anonymous> (C:\Repos\health-leyden\documentation-app\src\_constants\nav-data.js:3:1)   
    at Object.<anonymous> (C:\Repos\health-leyden\testcafe\main.tc.js:1:1)

### Steps to Reproduce

1. import an .md file into your React project, e.g.: `import barChartMarkdown from '../_markdown/data-viz/bar-chart.md';`
2. load page in a TestCafe test

### TestCafe version

^3.5.0

### Node.js version

18.8.0

### Command-line arguments

testcafe chrome ./testcafe/main.tc.js -r json:./testcafe/reports/chrome-report.json

### Platform(s) and version(s)

Windows 11

### Other

I've done my best with Google, looking for Testcafe/Markdown, or some way to tell Testcafe how to treat these files. I apologise if there's a known configuration for this (I've also read through the Testcafe config options in the docs, trying dev mode & disabling js errors)

**Comment by mathampson** [comment]
Apologies - I have realized it's not loading the .md from my web application, bu from a data file from which I was getting the routes to test - from within testcafe itself. It probably still shouldn't error just by importing the file, but its easily worked around for me and anyone else experiencing it.
