### ISSUE TITLE
Testcafe fails while establishing connection with chrome browser

### ISSUE THREAD

**Issue by AlekseyKravtsov17** [DevExpress/testcafe#8305]
### What is your Scenario?

We have a set of tests which executes every 30 mins 24/7

### What is the Current behavior?

We have around 50 executions per day, but starting from yesterday, about 20-30% of these executions started failing with the following error:
The "concurrency" option from the configuration file will be ignored.
ERROR Unable to open the "chrome:headless" browser due to the following error:

Error: WebSocket connection closed
    at /home/runner/work/monorepo/monorepo/src/js/tests/node_modules/chrome-remote-interface/lib/chrome.js:94:35
    at Chrome._handleConnectionClose (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/chrome-remote-interface/lib/chrome.js:256:13)
    at WebSocket.<anonymous> (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/chrome-remote-interface/lib/chrome.js:2[43](https://github.com/GuideToIceland/monorepo/actions/runs/11402912259/job/31728874759#step:7:47):22)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at WebSocket.emitClose (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/ws/lib/websocket.js:2[46](https://github.com/GuideToIceland/monorepo/actions/runs/11402912259/job/31728874759#step:7:50):10)
    at Socket.socketOnClose (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/ws/lib/websocket.js:1148:15)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at TCP.<anonymous> (node:net:339:12)

Type "testcafe -h" for help.
Error: Process completed with exit code 1.

We didn't change anything in code related to the testcafe configuration. Tests are running in GH hosted agents with concurrency 2-3. browserInitTimeout is already huge, no issue with app under test.

We already tried to change browsers value to the following, but it didn't change anything:
`browsers: "chrome:headless --disable-search-engine-choice-screen",`

Here is the testcafe debug log for such failure:

> 2024-10-18T11:41:45.966Z testcafe:cli 
    [
      '/opt/hostedtoolcache/node/18.20.4/x64/bin/node',
      '/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/gherkin-testcafe/main.js',
      '--param-type-registry-file',
      './guide-to-common/features/steps/transformers.js',
      '--concurrency',
      '2',
      '--src',
      './guide-to-common/features/Booking.feature',
      './guide-to-common/features/CarSearch.feature',
      './guide-to-common/features/CarSearchResult.feature',
      './guide-to-common/features/Cart.feature',
      './guide-to-common/features/FlightSearch.feature',
      './guide-to-common/features/FlightSearchResult.feature',
      './guide-to-common/features/HotelSearchResult.feature',
      './guide-to-common/features/HotelsSearch.feature',
      './guide-to-common/features/Payments.feature',
      './guide-to-common/features/ProductDetails.feature',
      './guide-to-common/features/SearchResult.feature',
      './guide-to-common/features/StaysBooking.feature',
      './guide-to-common/features/TripBooking.feature',
      './guide-to-common/features/TripSearch.feature',
      './guide-to-common/features/steps',
      './guide-to-common/features/steps/booking.js',
      './guide-to-common/features/steps/carSearchResult.js',
      './guide-to-common/features/steps/cart.js',
      './guide-to-common/features/steps/filter.js',
      './guide-to-common/features/steps/flightSearchResult.js',
      './guide-to-common/features/steps/footer.js',
      './guide-to-common/features/steps/footerPages.js',
      './guide-to-common/features/steps/funnelNavigation.js',
      './guide-to-common/features/steps/header.js',
      './guide-to-common/features/steps/links.js',
      './guide-to-common/features/steps/localization.js',
      './guide-to-common/features/steps/menu.js',
      './guide-to-common/features/steps/payments.js',
      './guide-to-common/features/steps/productPage.js',
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:350:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:128:17) {
  code: 104,
  killed: false,
  signal: null,
  cmd: '/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe-browser-tools/bin/linux/glibc-64/find-window mCY9Z3X'
}
2024-10-18T11:42:16.125Z testcafe:browser:provider UnableToOpenDisplayError: The /home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe-browser-tools/bin/linux/glibc-64/find-window process cannot open the display.
    at runFindWindowBinary (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe-browser-tools/src/api/find-window.js:33:19)
    at Object.default_1 (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe-browser-tools/src/api/find-window.js:43:15)
    at BrowserProvider._ensureBrowserWindowDescriptor (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe/src/browser/provider/index.ts:186:36)
    at BrowserProviderPluginHost.closeLocalBrowser (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe/src/browser/provider/plugin-host.js:59:9)
    at BrowserProviderPluginHost.closeBrowser (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe/src/browser/provider/built-in/dedicated/chrome/index.js:121:[13](https://github.com/GuideToIceland/monorepo/actions/runs/11403027385/job/31729211112?pr=34204#step:5:14))
    at BrowserProvider.closeBrowser (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe/src/browser/provider/index.ts:342:13)
    at BrowserConnection._closeBrowser (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe/src/browser/connection/index.ts:304:13)
    at BrowserConnection.close (/home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe/src/browser/connection/index.ts:513:9)
2024-10-18T11:42:[16](https://github.com/GuideToIceland/monorepo/actions/runs/11403027385/job/31729211112?pr=34204#step:5:17).130Z testcafe:reporter begin dispatchToPlugin method: reportWarnings
[
  {
    message: 'Could not find the "chrome:headless --disable-search-engine-choice-screen" window. TestCafe is unable to resize the window or take screenshots.\n' +
      '\n' +
      'The following error occurred while TestCafe was searching for the window descriptor:\n' +
      '\n' +
      'The /home/runner/work/monorepo/monorepo/src/js/tests/node_modules/testcafe-browser-tools/bin/linux/glibc-64/find-window process cannot open the display.',
    testRunId: undefined,
    actionId: null
  }
]
2024-10-18T11:42:16.130Z testcafe:reporter end dispatchToPlugin method: reportWarnings
2024-10-18T11:42:16.188Z testcafe:browser:provider:chrome browser closed mCY9Z3X
2024-10-18T11:42:16.188Z testcafe:browser:connection:mCY9Z3X status changed to 'closed'
2024-10-18T11:42:16.2[17](https://github.com/GuideToIceland/monorepo/actions/runs/11403027385/job/31729211112?pr=34204#step:5:18)Z testcafe:browser:provider:chrome browser closed -QjC8mz
2024-10-[18](https://github.com/GuideToIceland/monorepo/actions/runs/11403027385/job/31729211112?pr=34204#step:5:19)T11:42:16.217Z testcafe:browser:connection:-QjC8mz status changed to 'closed'

### What is the Expected behavior?

Should work as well as other successful executions

### What is the public URL of the test page? (attach your complete example)

N/A

### What is your TestCafe test code?

N/A

### Your complete configuration file

module.exports = {
screenshots: {
path: "./artifacts/screenshots",
takeOnFails: false,
pathPattern: "${DATE}${TIME}/${TEST}/${FILE_INDEX}${QUARANTINE_ATTEMPT}.png",
thumbnails: false
},
disableMultipleWindows: true,
browsers: "chrome:headless --disable-search-engine-choice-screen",
concurrency: 2,
skipJsErrors: true,
browserInitTimeout: 120000,
pageLoadTimeout: 60000,
pageRequestTimeout: 65000,
selectorTimeout: 20000,
testExecutionTimeout: 900000,
quarantineMode: false,
disableNativeAutomation: false,
testResults,
}

### Steps to Reproduce

N/A

### TestCafe version

3.6.0

### Node.js version

Tried with both v18 and v20

### Command-line arguments

yarn testcafe

**Comment by AlekseyKravtsov17** [comment]
After updating to chrome 130 all new executions fails with the same error:

The "concurrency" and "quarantineMode" options from the configuration file will be ignored.
ERROR Unable to open the "chrome:headless" browser due to the following error:

Error: WebSocket connection closed
    at tests\node_modules\chrome-remote-interface\lib\chrome.js:94:35
    at Chrome._handleConnectionClose (tests\node_modules\chrome-remote-interface\lib\chrome.js:256:13)
    at WebSocket.<anonymous> (tests\node_modules\chrome-remote-interface\lib\chrome.js:243:22)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at WebSocket.emitClose (tests\node_modules\ws\lib\websocket.js:246:10)
    at Receiver.receiverOnFinish (tests\node_modules\ws\lib\websocket.js:1058:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.emit (node:domain:488:12)
    at finish (node:internal/streams/writable:953:10)

**Comment by RafaelBeltranClip** [comment]
@AlekseyKravtsov17,
I've been following issue #8300, and there is a fix for it in the latest release candidate (3.7.0). However, after testing it, I encountered a new issue: I am unable to log in, as I can't interact with the page elements. The elements are detected, but I'm unable to write into or click on them. Could you please take a look?

**Comment by gforepsly** [comment]
I see some thumbs up for this issue under the first topic meant for this bug:
https://github.com/DevExpress/testcafe/issues/8240

I will link it for the reference - We have the same issue, so I'm using Edge for now as a workaround. But this is very nasty and a complete blockage for us.

**Comment by Bayheck** [comment]
Hello [@AlekseyKravtsov17](https://github.com/AlekseyKravtsov17),

We have released testcafe 3.7.0-rc.1, which addresses this issue.

Please take a look and let us know your results.

I will close this issue as a duplicate of [https://github.com/DevExpress/testcafe/issues/8300](https://github.com/DevExpress/testcafe/issues/8300).

**Comment by vasilyevi** [comment]
3.7.0-rc.1 does not work for me at all, it jsut failed on github actions timeout. Seems tests are just stuck

**Comment by AlekseyKravtsov17** [comment]
> 3.7.0-rc.1 does not work for me at all, it jsut failed on github actions timeout. Seems tests are just stuck

Same for me

**Comment by gforepsly** [comment]
> 3.7.0-rc.1 does not work for me at all, it jsut failed on github actions timeout. Seems tests are just stuck

Same for me.

> > 3.7.0-rc.1 does not work for me at all, it jsut failed on github actions timeout. Seems tests are just stuck
> 
> Same for me

Same for me.

Explanation:
https://github.com/DevExpress/testcafe/issues/8307

I've noticed the spec reporter hangs when it needs to throw an error. It's quite easily reproduced on v3.7.0-rc.1

**Comment by Bayheck** [comment]
Hello [@AlekseyKravtsov17](https://github.com/AlekseyKravtsov17),

I believe you have encountered this issue: [https://github.com/DevExpress/testcafe/issues/8300.](https://github.com/DevExpress/testcafe/issues/8300.)

Please stay tuned - we are already working on it.
