### ISSUE TITLE
Testcafe can't work fine with the latest chrome [Version 130.0.6723.70 (Official Build) (64-bit)]

### ISSUE THREAD

**Issue by goodnightql** [DevExpress/testcafe#8318]
### What is your Scenario?

Execute test cases using testcafe
testcafe chrome  test.js

### What is the Current behavior?

The console throws error as fallowing
ERROR Unable to open the "chrome:" browser due to the following error:

Error: WebSocket connection closed
    at D:\DDVTest\node_modules\chrome-remote-interface\lib\chrome.js:94:35
    at Chrome._handleConnectionClose (D:\DDVTest\node_modules\chrome-remote-interface\lib\chrome.js:256:13)
    at WebSocket.<anonymous> (D:\DDVTest\node_modules\chrome-remote-interface\lib\chrome.js:243:22)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at WebSocket.emitClose (D:\DDVTest\node_modules\chrome-remote-interface\node_modules\ws\lib\websocket.js:246:10)
    at Receiver.receiverOnFinish (D:\DDVTest\node_modules\chrome-remote-interface\node_modules\ws\lib\websocket.js:1058:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.emit (node:domain:488:12)
    at finish (node:internal/streams/writable:953:10)

### What is the Expected behavior?

run testcases fine

### What is the public URL of the test page? (attach your complete example)

a private testurl 
ip+port+testpage.html

### What is your TestCafe test code?

fixture('DDVUITest PerspectiveViewer').page("www.baidu.com").before( ctx=>{  
})
.beforeEach(async t=>{
    
})
.afterEach(t=>{
})
.afterEach(t=>{
})
.after(ctx=>{

}).skipJsErrors();

test("test", t=>{
    console.log("test")
})

### Steps to Reproduce

testcafe chrome test.js

### TestCafe version

3.1.0

### Node.js version

20.17.0

### Command-line arguments

testcafe chrome test.js

### Browser name(s) and version(s)

chrome  Version 130.0.6723.70 (Official Build) (64-bit)

### Platform(s) and version(s)

windows 11

**Comment by Bayheck** [comment]
Hello, the issue was fixed at [https://github.com/DevExpress/testcafe/issues/8300](https://github.com/DevExpress/testcafe/issues/8300).

We are working on a TestCafe release with the fix right now, but we cannot give you any ETA.

In the meantime, you can try using TestCafe 3.7.0-rc.2 as a temporary solution.

I will be closing this issue as a duplicate.

**Comment by goodnightql** [comment]
After I upgraded testcafe to 3.7.0-rc.2, a new problem occurred. I found that I could not draw annotations in live mode, but I could draw them in remote mode. See attachments.

https://github.com/user-attachments/assets/abf7c611-3745-4aab-9b8d-72c1938d4627



https://github.com/user-attachments/assets/5a1edafa-e761-4cb8-89af-857ebfbe96e5
